### ISSUE TITLE
Make sure users see progress when installing on Docker

### ISSUE THREAD

**Issue by imikushin** [vmware-tanzu/community-edition#1064]
I'm currently installing TCE deploying on Docker. I've been staring at this screen for a while now:

Deploying Tanzu Community Edition on Docker
Deployment of the Tanzu Community Edition management cluster to Docker is in progress.
Logs
```
...
ℹ [0713 18:21:54.31093]: logger.go:128] Ensuring node image (projects.registry.vmware.com/tce/kind/node:v1.20.4_vmware.1) ...
ℹ [0713 18:21:54.53879]: logger.go:128] Pulling image: projects.registry.vmware.com/tce/kind/node:v1.20.4_vmware.1 ...
```

Looks like pulling image `projects.registry.vmware.com/tce/kind/node:v1.20.4_vmware.1` can take a while since it's a **big** image. 

**Question**: Can we let the user know about the progress of this image being pulled? Something like what `docker pull` command shows:
```
❯ docker pull projects.registry.vmware.com/tce/kind/node:v1.20.4_vmware.1
v1.20.4_vmware.1: Pulling from tce/kind/node
67b8b51191f1: Already exists
5bee746ea8f9: Already exists
014d36ded12e: Already exists
034b978a08c2: Already exists
4471c5eeb3f8: Already exists
f6b16ac98fac: Already exists
5652b0c7f142: Already exists
90ea08f2d4de: Already exists
17b65f20d5af: Already exists
b5f1c5b23fff: Already exists
ce6451c87514: Already exists
7f21b81ad0f9: Downloading [========================================>          ]  492.4MB/606.4MB
```

**Comment by stmcginnis** [comment]
We are looking to make this whole experience better with https://github.com/vmware-tanzu/community-edition/issues/2730

Going to close this specific issue in favor of that overall proposal. Please watch that issue and/or leave comments on the proposed plan. Thanks!
