### ISSUE TITLE
Add octant as a tanzu CLI plugin for TCE

### ISSUE THREAD

**Issue by qnetter** [vmware-tanzu/community-edition#1139]
## Feature Request

(_below re-written by @joshrosso_)

To provide TCE users with a dashboard allowing them to view workloads in cluster, TCE will introduce [octant](https://github.com/vmware-tanzu/octant) as a tanzu CLI plugin. We'll expose `octant` as a subcommand `dashboard`. In short, users of `tanzu` CLI will be able to run the following to launch octant against their current kube context.

```
tanzu dashboard
```

**Comment by cmoulliard** [comment]
> As a near-term solution, we'll [document installation and usage of Octant](https://github.com/vmware-tanzu/community-edition/issues/1139).

Is it done (= documented) ?
