### ISSUE TITLE
`make generate-package-metadata` does not work against main channel

### ISSUE THREAD

**Issue by danniel1205** [vmware-tanzu/community-edition#1149]
## Bug Report

- Realized the structure changes in addons/repos/main.yaml
- The new structure change broke the `make generate-package-metadata`
- The new structure change in addons/repos/main.yaml is inconsistent with the output from `make create-channel`

## Expected Behavior

Expect the all make commands to be working and the repo yamls have the consistent structure.

## Steps to Reproduce the Bug

- Run `make generate-package-metadata OCI_REGISTRY=<your registry> CHANNEL=main REPO_TAG=0.4.1`. You will see errors.
- Run `make create-channel NAME=foobar`, you will see the newly generated yaml has different structure from addons/repos/main.yaml

## Environment Details

* Build version (`tanzu version`):  latest main
* Operating System (client):

**Comment by seemiller** [comment]
The `generate-package-metadata` task was deprecated and removed.
