### ISSUE TITLE
Diagrams difficult to read in small browser windows

### ISSUE THREAD

**Issue by stmcginnis** [vmware-tanzu/community-edition#1155]
## Feedback

User feedback on https://quirky-franklin-8969be.netlify.app/docs/latest/designs/standalone-clusters/#standalone-workload-cluster-sc-creation that the diagrams there are difficult to read when they have their browser set to half of their screen width.

## Suggested Changes

May be a good idea to enable a way to click images to pop them out into their own view to maximize their size.

**Comment by jpmcb** [comment]
This was tackled when introducing the `image-zoom` library 🚀 

https://github.com/vmware-tanzu/community-edition/issues/2003
