### ISSUE TITLE
Allow installation on ESXI free

### ISSUE THREAD

**Issue by displacedbuck** [vmware-tanzu/community-edition#1239]
## Feature Request

Since tce is a community edition it would be nice if it could be installed on ESXI free and not require vCenter.

## Additional context

Lots of homelab environments are configured using free(ish) software and/or single host environments.  ESXI free works well in a single host environment.  

Since ESXI has a free version and tce will be free, it would be nice for them to work together.

**Comment by dhaanpaa-lab0** [comment]
just was wondering where are the providers at so that we can see an example of what is involved for adding support for another installation type?

**Comment by stmcginnis** [comment]
Here is the source for the CAPV provider for vSphere: https://github.com/kubernetes-sigs/cluster-api-provider-vsphere

There are also docs on implementing providers in the cluster-api project here: https://cluster-api.sigs.k8s.io/developer/providers/implementers-guide/overview.html

I think there may be some challenges with trying to communicate directly to ESXi, but I haven't actually dug into it myself to see what those hard parts might be. If someone has the time and interesting, that would be great to hear how things go.
