### ISSUE TITLE
Documentation Search Feature

### ISSUE THREAD

**Issue by stevetilkens** [vmware-tanzu/community-edition#1243]
## Feature Request

Add search capabilities to the TCE documentation site.

**Comment by garrying** [comment]
My notes on getting search working for `https://tanzucommunityedition.io/docs/`:
- Most of the frontend/Hugo templating is already accounted for through a few values in `config.yaml`. Mainly the `docs_search_*` properties.
- I've opened a support ticket with Algolia DocSearch via https://docsearch.algolia.com/ to create the index and search `api_key`. Waiting to hear back from them.
  - I'm not aware of an existing Algolia index/account we could use—happy to use that if one is around!
- Preview of how it will look (from a local branch): https://silly-mirzakhani-c505f9.netlify.app/docs/latest/
  - Note: Results are pointing to the `.io` domain, and the index was generated manually. There's also a minor update to fix the input font.

I'll make a PR if no one is looking into this!

**Comment by kcoriordan** [comment]
Looks great. A PR would be great, as far as I know, no one else is looking into this.

**Comment by jpmcb** [comment]
Thanks for looking into this @garrying - one other thing of note; it would be great if we could bump to the new alpha of `docsearch.js` v3. The [v2.6 version of docsearch.js](https://www.npmjs.com/package/docsearch.js) that we have declared in the `doc/site/themes/template/layouts/_default/baseof.html` hasn't had a published release for over 2 years and has a few transient security vulnerabilities.

If we introduce this feature, we should use v3 of docsearch.js
