### ISSUE TITLE
Ability to install a particular version of Kubernetes cluster for Docker Standalone Cluster

### ISSUE THREAD

**Issue by karuppiah7890** [vmware-tanzu/community-edition#1264]
## Feature Request

Ability to install a particular version of Kubernetes cluster for Docker Standalone Cluster

## Describe alternatives you've considered

I couldn't find any alternatives

## Additional context

This came up because we are now noticing an issue in K8s 1.21.2 version which is causing issues in Docker E2E tests for standalone and management + workload clusters. Context - https://github.com/vmware-tanzu/tce/issues/1136#issuecomment-896026435

I noticed configuring Kubernetes Version was not possible in Docker Standalone Cluster, haven't tried with AWS/vSphere/Azure

Currently Tanzu Framework's `cluster` plugin has this feature by having a `--tkr` option

```bash
$ tanzu cluster version
v1.4.0-pre-alpha-2

$ tanzu version
version: v1.4.0-pre-alpha-2
buildDate: 2021-08-10
sha: 5a42a2b

$ tanzu cluster create -h
Create a cluster

Usage:
  tanzu cluster create CLUSTER_NAME [flags]

Flags:
  -d, --dry-run       Does not create cluster, but show the deployment YAML instead
  -f, --file string   Configuration file from which to create a cluster
  -h, --help          help for create
      --tkr string    TanzuKubernetesRelease(TKr) to be used for creating the workload cluster. If TKr name prefix is provided, the latest compatible TKr matching the TKr name prefix would be used

Global Flags:
      --log-file string   Log file path
  -v, --verbose int32     Number for the log level verbosity(0-9)
```

Looking at the code, given a TKr name, it fetches matching TKrs, then it sets the `options.KubernetesVersion` which in turn gets used to set the `KUBERNETES_VERSION`

https://github.com/vmware-tanzu/tanzu-framework/blob/main/pkg/v1/tkg/constants/config_variables.go#L141

https://github.com/vmware-tanzu/tanzu-framework/blob/main/pkg/v1/tkg/client/cluster.go#L453-L461

I tried to use the `KUBERNETES_VERSION` environment variable but that didn't work with Docker K8s cluster

```bash
$ guest_cluster_name="guest-cluster-${RANDOM}"
$ KUBERNETES_VERSION="v1.20.8+vmware.1" CLUSTER_PLAN=dev CLUSTER_NAME="$guest_cluster_name" tanzu standalone-cluster create ${guest_cluster_name} -i docker -v 10
```

It still used 1.21.2 version and installed the cluster on top of Docker

**Comment by jpmcb** [comment]
Closing - there is a new [standalone-cluster proposal](https://github.com/vmware-tanzu/community-edition/issues/2266) that uses a different model with a much liter weight methodology. Please look at the proposal, try it out, and give your feedback there!

Since the current standalone-cluster plugin is being deprecated in a future release, we will not be accepting new features.
