### ISSUE TITLE
TCE should automatically install the community-edition package repository when clusters bootstrap

### ISSUE THREAD

**Issue by joshrosso** [vmware-tanzu/community-edition#1308]
## Feature Request

Today, users must run a command with `tanzu package` to install the community edition repository.

We should **instead** install the community-edition repository by default when workload clusters are created. This is desirable for both managed clusters and standalone clusters.

## Describe alternatives you've considered

None, current state is manual installation which is a less-than-desirable UX.

## Additional context

The following issues/PRs have some relation to this one.

* https://github.com/vmware-tanzu/tanzu-framework/issues/327
    * Please note, this is the issue the work should be done against. Once complete and merged in tanzu-framework, we should circle back to this issue to ensure the change is included in the TCE distribution. 
* https://github.com/vmware-tanzu/tce/issues/1258
    * https://github.com/vmware-tanzu/tanzu-framework/pull/377

**Comment by joshrosso** [comment]
@qnetter to follow-up with PM to determine if we should try to do this in v0.11.0

**Comment by qnetter** [comment]
This is a thinking-out-loud bit but: maybe we want a better approach based on stable or leading-edge repo... The easiest for us, of course, is just to tell them to set it by CLI or UI...

**Comment by stealthybox** [comment]
I would guess we would want this exposed as a repo list in the cluster config file.
The cluster installer would default the value.

For installer improvements, may want a list selector UI component to be added to the installer UI to parameterize the config for the user.

The main reason that I think of this is for the case where people want to support air-gapped repos or mirrors + user or community-maintained repos.

**Comment by qnetter** [comment]
This should go to @vkorbes now…

Sent with a Spark<https://sparkmailapp.com/source?from=signature>
On Mar 3, 2022, 1:23 PM -0800, leigh capili ***@***.***>, wrote:

I would guess we would want this exposed as a repo list in the cluster config file.
The cluster installer would default the value.

For installer improvements, may want a list selector UI component to be added to the installer UI to parameterize the config for the user.

The main reason that I think of this is for the case where people want to support air-gapped repos or mirrors + user or community-maintained repos.

**Comment by stealthybox** [comment]
The unmanaged-cluster CLI should probably also default to the latest patch release of the package repo version matching the release (unless we are willing to cut a binary release every time we update the package repo -- this would also work).

**Comment by joshrosso** [comment]
@stealthybox, philosophically, yes. However, at this moment, due to constrains with being coupled to TKG, producing a TKR that is viable for `unmanaged` clusters requires leg work to make happen.

You can find examples of these details here: https://github.com/vmware-tanzu/community-edition/issues/3354

Once/if decoupling work completes, we'll move to this approach.
