### ISSUE TITLE
AWS cluster creation UI text needs correction for ACCESS KEY ID and SECRET ACCESS KEY

### ISSUE THREAD

**Issue by RusiH** [vmware-tanzu/community-edition#1346]
## Bug Report

When using the UI to create a standalone cluster in AWS, when the One Time Credentials option is selected it states that the ACCESS KEY ID (OPTIONAL) and SECRET ACCESS KEY (OPTIONAL) are optional.  These values are not optional for the One Time Credentials option.

## Expected Behavior

The (OPTIONAL) text should be removed from ACCESS KEY ID and SECRET ACCESS KEY.

## Steps to Reproduce the Bug

Install 0.7.0 RC4 and run the command 'tanzu standalone-cluster create --ui'. --> Amazon EC2 Deploy --> Start Fresh --> One Time Credentials

## Environment Details

* Build version (`tanzu version`):
version: v1.4.0-pre-alpha-2
buildDate: 2021-08-18
sha: ab30672

* Operating System (client):
Mac OS

**Comment by stmcginnis** [comment]
Hey @miclettej - looks like we never linked this to a `tanzu-framework` issue to track it. Do you know if this is still an issue? I _think_ it has been addressed, but I haven't checked lately.

**Comment by miclettej** [comment]
Hi @stmcginnis yes we fixed this one some time back. Let me see if I can find the original TF issue.

**Comment by miclettej** [comment]
I think we did it as 

> Hey @miclettej - looks like we never linked this to a `tanzu-framework` issue to track it. Do you know if this is still an issue? I _think_ it has been addressed, but I haven't checked lately.

Hi @stmcginnis I thought we had addressed this but after reading back through comments there is some uncertainty as to whether or not we should make those fields optional. I checked git history and current state of the UI; no changes have been made for making these fields required. Is this still a valid request? I recall that the user experience around use of temporary creds needs a re-think, but I'm not certain what the approach should be.

**Comment by stmcginnis** [comment]
Thanks for checking @miclettej! I'm not really sure either. I'm tempted to say that we've gotten better documentation around this, and it hasn't been an ongoing issue, so it probably could be closed. But let's wait a bit more and see if anyone else chimes in with any other feedback.

**Comment by joshrosso** [comment]
This is still an issue on v0.10.0, but perhaps it got fixed in a later release, we'll keep track of this to ensure there's some resolution.

![image](https://user-images.githubusercontent.com/6200057/151247892-743acf04-4824-4549-a152-44115da845b5.png)

**Comment by joshrosso** [comment]
We're going to close this issue to see if it ends up causing confusion in the future. For now it feels like there's not a clear path forward.
