### ISSUE TITLE
Management Cluster deploy from WIndows bootstrap to vSphere fails with Error: unable to ensure prerequisite ... certificate signed by unknown authority (WITH WORKAROUND) 

### ISSUE THREAD

**Issue by cantbewong** [vmware-tanzu/community-edition#1398]
## Bug Report
Attempting to deploy a management cluster to vSphere from a Windows bootstrap machine fails with this output: 
```
tanzu management-cluster create --ui
Downloading TKG compatibility file from 'projects-stg.registry.vmware.com/tkg/v1.4.0-zshippable/tkg-compatibility'
Error: unable to ensure prerequisites: unable to ensure tkg BOM file: failed to download TKG compatibility file from the registry: failed to list TKG compatibility image tags: Get "https://projects-stg.registry.vmware.com/v2/": x509: certificate signed by unknown authority
←[1mUsage:←[0m
```
## Expected Behavior
management cluster gets deployed
Note: when that if the link cited in the error message is opened in a browser on the same machine, the certificate is indicated as valid - so unclear why the install process has an unsigned authority issue..

## Steps to Reproduce the Bug
Install Docker Desktop, kubectl, TCE (install.bat)
run tanzu management-cluster create --ui

All as decribed in docs

## Environment Details
tce v0.7.0 (for Windows)
Windows Version	10.0.19043 Build 19043
 I believe this can happen with either hyperV or WSL enabled

**Comment by joshrosso** [comment]
With our bump in Framework via #2985, this should be fixed. I've assigned myself to do the validation.

**Comment by joshrosso** [comment]
Verified with our current release (0.9.1) the X509 validation fails:

![image](https://user-images.githubusercontent.com/6200057/154382950-232b8fb9-3c23-45d2-8924-d5b870feb0dc.png)

Rebuilt off df11daf9e2dbe1fa26fccb60886f16b6a04334e9 using:

```
$ make build-tce-cli-plugins ENVS=windows-amd64
```

Unfortunately, it still fails.

![image](https://user-images.githubusercontent.com/6200057/154384486-d59ab4ea-fc2a-4afc-a0e1-baee8e879a6d.png)

Note that unmanaged cluster pulls a TKR and does **not** have this issue.

**Comment by joshrosso** [comment]
I've opened

* https://github.com/vmware-tanzu/tanzu-framework/issues/1710

in framework to track this issue.

**Comment by joshrosso** [comment]
This won't make it in `v0.11.0`, bumping to `v0.12.0`.

**Comment by cmoulliard** [comment]
FYI: When we try to create a pod using harbor registry installed on TCE and even if the certificate is well present here `/etc/docker/certs.d/harbor.<IP>.nip.io/ca.crt`, then we got such an error during pod creation. Do we have to pass the `ca.crt` to TCE or t use the trick discussed within this issue ? 
```
Failed to pull image "harbor.65.108.148.216.nip.io/toto/httpd:2.4.52-alpine": 
rpc error: code = Unknown desc = failed to pull and unpack image "harbor.65.108.148.216.nip.io/toto/httpd:2.4.52-alpine":
failed to resolve reference "harbor.65.108.148.216.nip.io/toto/httpd:2.4.52-alpine":
failed to do request: Head "https://harbor.65.108.148.216.nip.io/v2/toto/httpd/manifests/2.4.52-alpine":
x509: certificate signed by unknown authority
```

**Comment by joshrosso** [comment]
Further diagnosis has occurred on the framework side and there is a plan to get this in, but it won't happen for v0.12.0.

Pushing it back to v0.13.0 to assess then.

**Comment by thefluffysysop** [comment]
Another workaround, is to add this env var:  `set TKG_CUSTOM_IMAGE_REPOSITORY_SKIP_TLS_VERIFY=true`

This is.. sorta.. documented here: https://github.com/vmware-tanzu/tanzu-framework/blob/b9218aded61ff9628850cd9a42f702b1a7f0ed79/docs/cli/tkgctl/airgapped-deployment.md

Perhaps this should be added to install.bat as a workaround?
