### ISSUE TITLE
We should document getting Docker for RHEL8 and derivatives

### ISSUE THREAD

**Issue by qnetter** [vmware-tanzu/community-edition#1399]
## Feedback

RHEL8 ships with the podman family and does not include docker.  We should help users find docker (and maybe support podman some day).

## Suggested Changes

Link to https://linuxconfig.org/how-to-install-docker-in-rhel-8

## Environment Details

* Build version (`tanzu version`): 0.7.0 (and previous)  
* Operating System (client): N/A

**Comment by dvonthenen** [comment]
I agree with the last statement @joshrosso made and I'm closing this.

The official docker documentation found here (https://docs.docker.com/engine/install/) provides install instructions for the following platforms in their "Install per Distro" section":
- Install on CentOS
- Install on Debian
- Install on Fedora
- Install on RHEL
- Install on SLES
- Install on Ubuntu
- Install binaries (Generic Linux install)
