### ISSUE TITLE
Need a supported load balancer for workloads for TCE on vSphere (and Docker?)

### ISSUE THREAD

**Issue by qnetter** [vmware-tanzu/community-edition#1437]
## Feature Request

Since we deferred the option of using NSX ALB for user workloads until after MVP for both inward-facing (no commitment to help support the community use) and outward-facing reasons (too complex for developers, too resource-intensive for small clusters) reasons, we should include a blessed approach to L4 load balancing, preferably in the MVP if possible. 

## Describe alternatives you've considered

The Contour team has already demonstrated interoperability with MetalLB. However, there have been complaints about stagnation and lack of support in the MetalLB community since its founder left the project over a year ago. Kube-vip and haproxy are also options that are known to be used by members of the upstream k8s-on-VMware user group.

Alex Xu reports that if we opt for MetalLB, the Contour team would package and help test, and if either of the others, we should package but they would help test, all in time for 0.8.0.

**Comment by joshrosso** [comment]
@qnetter any update on this? Something we still want to get in the roadmap or potentially prioritize?

**Comment by qnetter** [comment]
I think we do want to do this, and there is momentum internally and externally toward kube-vip.
