### ISSUE TITLE
Document TCE Release Engineering docs in GitHub Repo

### ISSUE THREAD

**Issue by karuppiah7890** [vmware-tanzu/community-edition#1440]
## Feature Request

We already have documents on `Design for TCE Test Automation Framework` and also reports and/ logs `TCE Build-Deploy-Test Automation Log` and more documents, which are all in Google Docs or in the form of images in Miro boards

If the document is complete, with all the data that we need as of now, I recommend we move it to TCE GitHub Repo. Even if it's a long living document which will have changes when processes change, we can then start maintaining it in the GitHub repo

Benefits are
- It will be in the open and anyone will be able to access it
- We will be able to refer to the docs in our PRs and issues, and it won't be an internal link. We can't use internal links / links with auth in PRs and issues

cc @vmware-tanzu/tce-releng 

## Describe alternatives you've considered

None

## Additional context

Related: #1356

**Comment by joshrosso** [comment]
Seems docs have been added. if not, please feel free to reopen this issue!
