### ISSUE TITLE
When tanzu cli is used on Microsoft Windows, unhandled characters are displayed in output

### ISSUE THREAD

**Issue by cantbewong** [vmware-tanzu/community-edition#1490]
## Bug Report

When tanzu cli is used on Microsoft Windows, unhandled (virtuual terminal formatting?) characters are displayed in output
Example:
```
C:\ISOs\tce\tce-windows-amd64-v0.7.0-rc.1.tar\tce-windows-amd64-v0.7.0-rc.1\tce-windows-amd64-v0.7.0-rc.1>tanzu --help
←[1mTanzu CLI←[0m

←[1mUsage:←[0m
  tanzu [command]

←[1mAvailable command groups:←[0m

  ←[1mRun←[0m
    cluster                 Kubernetes cluster operations
    kubernetes-release      Kubernetes release operations
    management-cluster      Kubernetes management cluster operations
    package                 Tanzu package management
    standalone-cluster      Create clusters without a dedicated management cluster

  ←[1mSystem←[0m
    completion              Output shell completion code
    config                  Configuration for the CLI
    init                    Initialize the CLI
    login                   Login to the platform
    plugin                  Manage CLI plugins
    update                  Update the CLI
    version                 Version information


←[1mFlags:←[0m
  -h, --help   help for tanzu

Use "tanzu [command] --help" for more information about a command.

Not logged in
```

Observed by dessign partner rogram participant.

## Expected Behavior

I suspect these are virtual terminal formating characters that do something useful or attractive in a standard Linux shell. They should either be removed on the Windows version of the CLI, or perhaps converted to something that works
See: https://docs.microsoft.com/en-us/windows/console/console-virtual-terminal-sequences?redirectedfrom=MSDN

## Steps to Reproduce the Bug
Install CLI on Windows 10. run tanzu --help
Other Tanzu CLI commands exhibit similar behavior. Result ranges from just looking ugly to making output really difficult to read.

## Environment Details
0.7.0
Build version (tanzu version): version: v1.4.0-pre-alpha-2
buildDate: 2021-08-19
sha: 75cfa0e

Operating System (client): WindowsOS Name: Microsoft Windows 10 Enterprise
OS Version: 10.0.19043 N/A Build 19043

**Comment by joshrosso** [comment]
Based on upstream progress, I don't see this being included in our `v0.10.0` release. Moving it out for tracking in `v0.11.0`.

**Comment by joshrosso** [comment]
Putting this in the icebox, no current plans to pickup this work for a future milestone.

**Comment by danfein** [comment]
I was doing some tests of different terminals on windows to see about the mangling of text decorations, and found that while the command prompt and powershell in admin mode don't handle text decorations, a number of other tools do.

Displays text correctly
* non-admin powershell
* cygwin
* git bash
* terminal in vscode

Does not display text correctly
* admin mode powershell
* command prompt (admin / non admin)

After seeing the command prompt I was going to write a similar issue on the tanzu-framework repo to disable text-decoration by default on windows, but after seeing a few other terminals display things correctly, I am looking into which are most commonly used to determine how likely it is that folks are going to run into the experience Steve is calling attention to.
