### ISSUE TITLE
Provide documented workaround for changing `kapp-controller` version

### ISSUE THREAD

**Issue by joshrosso** [vmware-tanzu/community-edition#1491]
## Feature Request

Internally (at VMware), a request to swap out `kapp-controller` for a different version was mentioned.

Today, we do not have this ability until we have this ability until we solve for https://github.com/vmware-tanzu/tanzu-framework/issues/60 as kapp-controller is referenced in the bom.

For a workaround, we need someone to document the steps to:

**management-clusters**

* pause the reconciled (workload) kapp-controller from the management cluster
* re-deploy an updated kapp-controller in the workload cluster

**standalone clusters**

* swap the kapp-controller

## Describe alternatives you've considered

None

## Additional context

None

**Comment by vrabbi** [comment]
is there a plan on documenting this or making this configurable at least in workload clusters? i want to deploy TAP on TCE but currently TAP requires kapp controller 0.25 so its not possible OOTB

**Comment by joshrosso** [comment]
> is there a plan on documenting this

This ticket details exactly that. Essentially we need someone to take @jorgemoralespou's [steps](https://github.com/vmware-tanzu/community-edition/issues/1491#issuecomment-916167601) and add them to docs.

We are actively working on a plan to make the lower-level core components customizable. But I don't have a timeline yet.

**Comment by vrabbi** [comment]
It also seems it will need a different approach possibly on standalone as there isnt a secret with that convention in a standalone cluster
