### ISSUE TITLE
tanzu standalone-cluster completion bash --help missing tanzu part of command

### ISSUE THREAD

**Issue by cormachogan** [vmware-tanzu/community-edition#1587]
## Bug Report

Running the following command for help displays incorrect commands:

```
% tanzu standalone-cluster completion bash --help

Generate the autocompletion script for the bash shell.

This script depends on the 'bash-completion' package.
If it is not installed already, you can install it via your OS's package manager.

To load completions in your current shell session:
$ source <(standalone-cluster completion bash)

To load completions for every new session, execute once:
Linux:
  $ standalone-cluster completion bash > /etc/bash_completion.d/standalone-cluster
MacOS:
  $ standalone-cluster completion bash > /usr/local/etc/bash_completion.d/standalone-cluster

You will need to start a new shell for this setup to take effect.

Usage:
  tanzu standalone-cluster completion bash

Flags:
  -h, --help              help for bash
      --no-descriptions   disable completion descriptions

Global Flags:
  -v, --verbose int32   Number for the log level verbosity(0-9)
```

## Expected Behavior

Notice that many of the commands are missing `tanzu` and are simply displayed as standalone-cluster. I believe these commands should be `tanzu standalone-cluster`, not just standalone cluster.

## Steps to Reproduce the Bug

Run the command:

`tanzu standalone-cluster completion bash --help`

## Environment Details

* Build version (`tanzu version`): 
   version: v1.4.0-pre-alpha-2
   buildDate: 2021-08-19
   sha: 75cfa0e
* Operating System (client):
   macOS Big Sur v11.5.2.
   Docker desktop 3.6.0 / Docker Engine 20.10.8

**Comment by jpmcb** [comment]
Closing - standalone-clusters are being deprecated in v0.11.0 in support of transitioning to unmanaged-clusters

Ref: https://github.com/vmware-tanzu/community-edition/issues/2266
