### ISSUE TITLE
When workload cluster deployed with Avi, kubeconfig get throws error - can't assign requested address

### ISSUE THREAD

**Issue by cormachogan** [vmware-tanzu/community-edition#1614]
## Bug Report

When a TKG workload cluster is deployed on vSphere using kube-vip but without Identity Management (no pinniped), users are shown a reasonable error when they attempt to retrieve the kubeconfig information:

```
$ tanzu cluster kubeconfig get tkg-workload-1
Error: failed to get pinniped-info from management cluster: failed to get pinniped-info from the cluster
Usage:
  tanzu cluster kubeconfig get CLUSTER_NAME [flags]
```

When a TKG workload cluster is deployed on vSphere using NSX ALB (Avi) but again without Identity Management , users are shown a very odd error when they attempt to retrieve the kubeconfig information:

```
% tanzu cluster kubeconfig get workload
Error: failed to get cluster-info from cluster: failed to get cluster-info from the end-point: Get "https://:0/api/v1/namespaces/kube-public/configmaps/cluster-info": dial tcp :0: connect: can't assign requested address
Usage:
  tanzu cluster kubeconfig get CLUSTER_NAME [flags]
```

Adding --admin to the command works in both cases, so it is just the error that is different.

```
% tanzu cluster kubeconfig get workload --admin
Credentials of cluster 'workload' have been saved
```

## Expected Behavior

I would expect that there is a common error in both cases. While even the Pinniped error itself is not ideal - see  #847 - the error thrown when the NSX ALB is present is very poor, can lead to customers spinning there wheels determining what the issue is, and can lead to a poor UX overall. This needs to show the same error as the case without NSX ALB at the very least.

## Steps to Reproduce the Bug

Deploy TKG management cluster on vSphere with NSX ALB, and then deploy workload cluster on same vSphere cluster using same NSX ALB. 

## Environment Details

* Build version (`tanzu version`):  
   version: v1.4.0-pre-alpha-2
   buildDate: 2021-08-19
   sha: 75cfa0e
* Operating System (client):
macOS (Big Sur) 11.5.2, deploying to vSphere 7.0U2c (build 18356314)

**Comment by jpmcb** [comment]
Hi Cormac - this is something that `tanzu-framework` will need to prioritize. I've created the following issue:

- [ ] https://github.com/vmware-tanzu/tanzu-framework/issues/837
