### ISSUE TITLE
[DOCS] Some suggestion to improve Velero package experience

### ISSUE THREAD

**Issue by cormachogan** [vmware-tanzu/community-edition#1678]
## Feedback

I just ran through the docs for the Velero package - https://quirky-franklin-8969be.netlify.app/docs/latest/package-readme-velero-1.5.2/#usage-example - and found a few things which may make the on-boarding easier.

## Suggested Changes

1. probably already in hand, but would be good to move the images (including the example nginx image) out of the docker registry. Using a busybox (or similar) example instead on nginx which hosted on gcr.io would avoid the docker rate limiting issue

2. when downloading the velero client, the link goes to the latest version of the velero client. However, if this is used as the client, when the `velero version` command is run, it reports a mismatch between client and server, and recommendsupgrading the server. Can we provide  link to the client that matches the server, and some guidance which states that the client version should match the server version? See symptoms below:

```
% tanzu package installed list
/ Retrieving installed packages...
  NAME    PACKAGE-NAME                       PACKAGE-VERSION  STATUS
  velero  velero.community.tanzu.vmware.com  1.5.2            Reconcile succeeded

% velero version
Client:
	Version: v1.6.3
	Git commit: 5fe3a50bfddc2becb4c0bd5e2d3d4053a23e95d2
Server:
	Version:
# WARNING: the client version does not match the server version. Please update server
```

3. When the client and server match, the server derails are not reported. See below:

```
% velero version
Client:
	Version: v1.5.2
	Git commit: e115e5a191b1fdb5d379b62a35916115e77124a4
Server:
	Version:
%
```

## Environment Details

* Build version (`tanzu version`):   v1.4.0-pre-alpha-2
* Operating System (client): macOS (big sur) v11.5.2

**Comment by joshrosso** [comment]
cc @vmware-tanzu/pkg-velero-owners any status on this? Is it still something we want to improve or possible already have?

**Comment by blackpiglet** [comment]
I will look into this.
I'm working on update Velero Carvel package version. v1.7.1 is already added. 
Planning to add v1.8.0 after Chinese Spring festival, after that, I suppose the version mismatch should be resolved.
For the example image issue, we need to discuss to reach agreement on it in Velero team. Currently, we are facing the same issue on Velero BYOT test in vSphere environment too.
