### ISSUE TITLE
Update knative-serving package to latest

### ISSUE THREAD

**Issue by seemiller** [vmware-tanzu/community-edition#1727]
## Feature Request

Knative is currently shipping `0.25.0`
TCE is still on `0.22.0`

## Describe alternatives you've considered

Stay on the old version

**Comment by joshrosso** [comment]
@seemiller how does this look for the `0.10.0` package repo?

We can move it to `0.11.0` assuming the change did not make it in.

**Comment by seemiller** [comment]
The latest `0.9.2` package repository has knative-serving `0.26.0` and `1.0.0`.

**Comment by joshrosso** [comment]
@seemiller which PR did this work? Can we attach it to this issue?
