### ISSUE TITLE
Update Gatekeeper package to latest version

### ISSUE THREAD

**Issue by seemiller** [vmware-tanzu/community-edition#1729]
## Feature Request

Gatekeeper is currently shipping `3.6.0`
TCE is still on `3.2.3`

## Describe alternatives you've considered

Stay on the old version

**Comment by pksheldon4** [comment]
I have an implementation for this. Working through the process as this is my first contribution.

**Comment by seemiller** [comment]
@pksheldon4 Let me know if you need any help with the process on your contribution.

**Comment by seemiller** [comment]
@pksheldon4 Looks like Gatekeeper has released a 3.7.0. If you're still working on an implementation would you want to update it to that? I'm hoping to get this updated for our 0.10.0 release. Still happy to help out with your PR if you need it!

**Comment by pksheldon4** [comment]
> @pksheldon4 Looks like Gatekeeper has released a 3.7.0. If you're still working on an implementation would you want to update it to that? I'm hoping to get this updated for our 0.10.0 release. Still happy to help out with your PR if you need it!
Thanks, upgrading should be easy enough to do.  I tried to fill out a CLA at https://cla.vmware.com/  but it doesn't seem to have an option. I need to find some dedicated time to pair with someone who's done this before.

**Comment by pksheldon4** [comment]
I was trying to navigate the CLA for a vmware employee but the PR had me sign one. Not sure if that's the correct process.

**Comment by joshrosso** [comment]
@seemiller looks like we got the newer gatekeeper in. Can we close this out?

**Comment by seemiller** [comment]
Can confirm that `3.7.0` is in the `0.9.2` package repository.

```
tanzu package available list gatekeeper.community.tanzu.vmware.com
/ Retrieving package versions for gatekeeper.community.tanzu.vmware.com...
  NAME                                   VERSION  RELEASED-AT
  gatekeeper.community.tanzu.vmware.com  1.0.0
  gatekeeper.community.tanzu.vmware.com  3.7.0
```
