### ISSUE TITLE
[DOCS] Expand on our Package Management documentation to cover other failure scenarios

### ISSUE THREAD

**Issue by joshrosso** [vmware-tanzu/community-edition#1740]
## Description

From @jorgemoralespou in slack:

> On the troubleshooting, it’s relevant to say how to get the -o yaml version of the package if it fails, and document other common errors, (e.g. formatting in data-values file, namespaces collision problems, …) and other issues we know people regularly hit

It'd be great to expand on all failure scenarios and troubleshooting steps we know of. If someone is able to take this one, I'm sure the TCE engineering team (or community) can help with many of the details.

## Location

`Packages > Package Management`

* Not impossible the location of this document has moved.

## Additional Context

None

**Comment by stmcginnis** [comment]
@seemiller do you know if we have any common failure scenarios with package management that would be good to document?

I know we've had times where users were caught offguard by the need to wait for background sync to happen when adding a package repo, but other than specific package issues, I'm not aware of other common things we could address.

This is a really good idea, but I wonder if it would be better to close this and just open specific issues for specific cases that we need to cover.
