### ISSUE TITLE
NSX ALB with Contour/Envoy Ingress fails Health Monitor System-TCP

### ISSUE THREAD

**Issue by cormachogan** [vmware-tanzu/community-edition#1752]
## Bug Report

Standing up the monitoring stack of packages - Cert-Manager + Contour/Envoy Ingress + Prometheus + Grafana on TKG. via TCE v0.7.0. Deploying TKG to vSphere on-prem (7.0U2c) + NSX ALB (Avi) v2.0.1.5

During the Contour/Envoy Ingress deployment, the status of the service was shown as down in the NSX ALB (Avi) UI. On further investigation, it seemed that the reason was due to the Avi Health Monitor failing, specifically HM System-TCP which is the health monitor associated with the pool created for this service. It reports a `Connection Refused`. I have captured a screenshot of the error below:

![NSX-ALB Ingress Down](https://user-images.githubusercontent.com/18258500/133425127-9de05294-7b81-4dba-bd3c-400246203439.png)

## Expected Behavior

I'm not 100% sure what the correct health monitoring behaviour should be - should HM System-TCP work for the Contour/Envoy Ingress? Or is this an inappropriate health monitor test for Contour/Envoy Ingress?

I have noticed that System-TCP seems to work fine as the HM for a number of other pools that have been created, e.g. control plane, Pinniped, Dex, Nginx LB, Grafana. However these are not Ingresses, so perhaps Ingresses need a different health monitor? (just guessing I'm afraid)

Either way, it needs to be addressed to allow the Avi Health Monitor to pass the Contour/Envoy Ingress service as healthy.

## Steps to Reproduce the Bug

Deploy TCE (v0.7.0) TKG onto vSphere 7.0U2c. Deploy Contour package with service type set to Load Balancer. Monitor NSX ALB events. 

## Work around

I was able to workaround the issue by editing the Health Monitor in the pools associated with the Contour/Envoy Ingress. I changed the Health Monitor from HM System-TCP to HM System-Ping. This enabled the service to come online successfully, and did not seem to impact dependent applications, such as Prometheus. See screenshot highlighting change below:

![Pool - HM System-Ping](https://user-images.githubusercontent.com/18258500/133426527-ba4bfab4-1940-4472-bb0b-29a916e16c53.png)

## Environment Details

* Build version (`tanzu version`):  
version: v1.4.0-pre-alpha-2
buildDate: 2021-08-19
sha: 75cfa0e
* Operating System (client):
macOS (Big Sur) v11.5.2.
vSphere 7.0U2c
NSX ALB (Avi Vantage) v2.0.1.5.

**Comment by jpmcb** [comment]
@XudongLiuHarold - thanks for looking into this - any updates on this?

**Comment by youngnick** [comment]
Contour is discussing opening ports without requiring ingress config again on projectcontour/contour#4643.
