### ISSUE TITLE
Group Search Attribute Filter is not Optional in LDAP UI, though marked as Optional

### ISSUE THREAD

**Issue by cormachogan** [vmware-tanzu/community-edition#1774]
## Bug Report

Testing varying LDAPS configuration. UI states that **Group Search Attribute Filter** is  _Optional_. However Verify LDAP Configuration fails with a filter compile error if no field is populated in the Filter.

![Filter Compile Error](https://user-images.githubusercontent.com/18258500/133589618-f0f62642-18ab-45c8-8b22-7ad1e0b99aee.png)

By adding Filter: (objectClass=group), the Verify LDAP Configuration operation succeeds.

## Expected Behavior

If the field is indeed optional, there should be no filter compiler error thrown when an LDAP verification is run.
If the field is not optional, we need to remove the (OPTIONAL) label from it.

## Steps to Reproduce the Bug

Run a Verify LDAP Configuration with the **Group Search Attribute Filter** blank. This will show the issue.

## Environment Details

* Build version (`tanzu version`):
TCE v0.8.0-rc2
version: v0.2.1
buildDate: 2021-09-13
sha: ceaa474
* Operating System (client):
macOS (big sur) v11.5.2
MS Active Directory on Windows 2012 R2.

**Comment by jpmcb** [comment]
I've created a tracker issue for this in `tanzu-framework`

- [] https://github.com/vmware-tanzu/tanzu-framework/issues/843

We can keep an eye on that there to get this resolved!
