### ISSUE TITLE
[DOCS] Add pointers to next steps after deployment is complete in quick start guide

### ISSUE THREAD

**Issue by stmcginnis** [vmware-tanzu/community-edition#1780]
## Description

In our quick start guides, we're pretty good about covering the deployment lifecycle of clusters to get them up and running, and to get them removed when done. It would be good if we had some pointers to content, or some basic next steps, to help guide someone on what to do next once they've gotten a cluster deployed.

User feedback:

> The Getting Started does not go into details of deploying an application to the newly created clusters, which makes the guide feel like it ends rather abruptly.

## Location

All quick start guides.

**Comment by kcoriordan** [comment]
I think this will be covered by TAP when that is available?
I think right now, the closest thing we have in the docs right now are the Guides so I can add a link to them?
