### ISSUE TITLE
[DOCS] Suggestions to the Architecture section 

### ISSUE THREAD

**Issue by davidmirror-ops** [vmware-tanzu/community-edition#1784]
## Description

In the **Package Management** section there's a typo in the diagram:

![image](https://user-images.githubusercontent.com/82604841/133647226-07efca17-4a6c-4a9e-9972-e5cffe5b4a72.png)

The following text is missing a "d":

*Within the cluster, a PackageInstall resource is **create** and it instructs...*

In the end, after reading the Architecture section, it's still not clear what do I need to run TCE? what's mandatory and what's optional?

Additionally, I see some advantages for standalone clusters listed but it's not clear what do users lose if they choose not to run a Management cluster?

## Location

https://quirky-franklin-8969be.netlify.app/docs/latest/architecture/

**Comment by joshrosso** [comment]
Thanks a bunch for opening this issue, sorry it took so long to respond :).

We're going to track this in https://github.com/vmware-tanzu/community-edition/issues/2425 since it's got more follow-up.
