### ISSUE TITLE
[DOCS] IDENTITY_MANAGEMENT_TYPE is a required field for workload clusters, not just management clusters

### ISSUE THREAD

**Issue by cormachogan** [vmware-tanzu/community-edition#1795]
## Description

The configuration variable IDENTITY_MANAGEMENT_TYPE is a requirement in the workload/guest cluster manifest if you want to use an identity manager and allow non-admin users to have access to the workload cluster.

In our docs, this is not highlighted. In fact, our docs have the following note:

`Note: Set these variables only for the management cluster. You do not need to set them for your workload clusters.`

I believe this may have been the case for earlier versions of Pinniped/Dex, but in TCE and TKG 1.4, this environment variable needs to be include in the manifest of the workload cluster to enable the workload cluster to use identity management.

## Location

https://docs.vmware.com/en/VMware-Tanzu-Kubernetes-Grid/1.4/vmware-tanzu-kubernetes-grid-14/GUID-cluster-lifecycle-enable-identity-management.html#idp

## Additional Context

Please check out #https://github.com/vmware-tanzu/community-edition/issues/1794 which is a feature request to handle this mis-configuration better. The issue also has the error included.

**Comment by joshrosso** [comment]
@kcoriordan I believe we got some amount of identity management in. Feel free to close this issue if so.

**Comment by stmcginnis** [comment]
I believe this is covered now in https://tanzucommunityedition.io/docs/v0.12/vsphere-ldap-config/#identity_management_type-variable-in-manifest - please reopen if that is still missing something.
