### ISSUE TITLE
imgpkg push can optionally add a unique tag

### ISSUE THREAD

**Issue by seemiller** [vmware-tanzu/community-edition#1809]
## Feature Request

This issue provides a link to a feature request in `carvel-imgpkg`.

The imgpkg feature request would add the capability of push commands to optionally add a unique tag.

## Additional Context

This is a tracker issue for:

* https://github.com/vmware-tanzu/carvel-imgpkg/issues/248

All work should be done against that issue. Once it is available in a release. TCE should include this dependency. This this issue may be referenced and closed.

**Comment by joshrosso** [comment]
@seemiller with this issue resolved upstream, can we close this issue?
