### ISSUE TITLE
Grafana package should support all ingress controllers, by using the `Ingress` resource rather than `HTTPProxy`

### ISSUE THREAD

**Issue by jorgemoralespou** [vmware-tanzu/community-edition#1813]
## Bug Report

In this PR: https://github.com/vmware-tanzu/community-edition/pull/567 an ingress of type HTTPProxy was added. These ingress types only work with contour. It should be clearly defined in the documentation. Alternative, a regular Ingress can be created, or it can be a choice to the user whether to create an Ingress or HTTPProxy.

I know contour is our default package, but it's not required, and if it is, should be clearly stated in the docs.

**Comment by joshrosso** [comment]
I think a decision around this has grown stale. I'm putting it in the icebox for now since even the ownership of this package over-time is still being decided.
