### ISSUE TITLE
Kickstart UI should say `Amazon Web Services` or `AWS` rather than `Amazon EC2`

### ISSUE THREAD

**Issue by joshrosso** [vmware-tanzu/community-edition#1821]
## Feedback

This is a tracker issue to resolve this in https://github.com/vmware-tanzu/tanzu-framework/issues/655.

All work should be done in [tanzu-framework](https://github.com/vmware-tanzu/tanzu-framework). Once the work is done and included in a release, a pull request bumping our dependency should be opened in this repository.

## Suggested Changes

n/a

## Environment Details

n/a

**Comment by dvonthenen** [comment]
this has been fixed and will be available in the upcoming release
