### ISSUE TITLE
Packages with ingress should have a note to use `kubectl port-forward` for ad-hoc UI on CAPD

### ISSUE THREAD

**Issue by rajaskakodkar** [vmware-tanzu/community-edition#1836]
## Feedback
For contour-based ingress on CAPD it is much easier to use NodePort service and then use `kubectl port-forward` to access UI as in the case of Harbor.  https://github.com/vmware-tanzu/community-edition/issues/886#issuecomment-922797361
We can also use `kubectl port-forward` to access ad-hoc UI without an ingress on CAPD as in the case of Prometheus.
https://github.com/vmware-tanzu/community-edition/tree/main/addons/packages/prometheus/2.27.0#configuration
Note on the usage of `kubectl port-forward` on CAPD should be added for any package with ingress.

## Suggested Changes
Add a note similar to
```
Note: Ingress for Prometheus server is disabled by default, and can be enabled using the ingress.enabled configuration field.

If you choose to enable the Contour-based Ingress, Contour must also be installed on the target cluster. Additionally, enabling the Ingress requires either Cert Manager or your own user-provided TLS certificate (ingress.tlsCertificate.tls.crt and ingress.tlsCertificate.tls.key) to configure TLS settings for the Ingress. For ad-hoc Prometheus UI access without an Ingress, use kubectl port-forward.

```
 https://github.com/vmware-tanzu/community-edition/tree/main/addons/packages/prometheus/2.27.0#configuration seen in prometheus, grafana for other applicable packages such as harbor, knative and so on.

I am not sure which other packages are applicable apart from harbor and knative.

## Environment Details

* Build version (`tanzu version`): v0.2.1 TCE v0.8.0-rc.2
* Operating System (client): Darwin

**Comment by jpmcb** [comment]
Thanks for opening this issue! I think this would be a great issue for the community to tackle. Anyone, please feel free to open a PR against the package readmes with this information or ask questions in this issue!

**Comment by chetak123** [comment]
Can I take up this issue please ?

**Comment by rajaskakodkar** [comment]
@chetak123 Please go ahead, I am assigning this one to you.
