### ISSUE TITLE
Enable TCE deployments to support Kind port mappings to enable host/cluster communication

### ISSUE THREAD

**Issue by cormachogan** [vmware-tanzu/community-edition#1956]
## Feature Request

I recently deployed a number of community packages with TCE standalone (on Docker), including Prometheus and Grafana. Unfortunately, because of the way Docker runs on macOS (and Windows IIRC), it uses on internal VM and an internal docker network which are not accessible from the desktop host. Thus we cannot use any Load Balancer functionality in TCE standalone and are relying on port-forward from kubectl to get access to the applications.

This is not a great user experience for users of TCE.

## Describe alternatives you've considered

It seems that Kind has the ability to configure "Extra Port Mappings" which would enable getting traffic into the kind cluster - https://kind.sigs.k8s.io/docs/user/configuration/#extra-port-mappings. The request here is to enable this configuration option in TCE standalone (maybe through an advanced configuration/values file to the cluster), which would enable host access to the TCE standalone cluster. This would avoid having to resort to kubectl port-forwards.

This would make TCE much more attractive, and enable users to use it in much the same way as they would use TCE on vSphere, and TCE on AWS with their respective infrastructure based load balancers. 

It would also give some feature parity to standalone Kind clusters.

**Comment by Alfaj0r** [comment]
Ah, this is totally my issue! 
I'm very much a beginner, and have been stuck at this problem for days. 
Can you expand on "Right now I'm simply hard coding an extraPortMapping to the kind cluster" @stevesloka ? :) 

Professional context: I need this MacOS + Docker deployment to be a proper demo, so that I can get buy-in to use up a couple of precious on-prem vSphere hosts to further evaluate TCE... as a gateway to all Tanzu products.

**Comment by stevesloka** [comment]
Hey @Alfaj0r, I'm referencing this guide (https://projectcontour.io/guides/kind/) which maps a port from your local machine to a port in the cluster. Envoy then listens on a hostport and that gets mapped to your local machine via Kind. 

Please let me know if you have any other questions!

**Comment by jorgemoralespou** [comment]
@jpmcb I think this issue is solved with your recent changes.
