### ISSUE TITLE
Document how to create and test a package locally

### ISSUE THREAD

**Issue by jorgemoralespou** [vmware-tanzu/community-edition#197]
## Feedback

An extension author might want to develop his own extension and test it before submitting a PR to the repository for the extension to be considered. Since this process is possible, it should be documented.

## Suggested Changes

A doc page should be created detailing the process:
- Create the source extension directory
- Add the extension.yaml and the extension's descriptor 
- Bundle your extension
- Push the extension into a registry
- Add your extension to the extension list at $XDG_DATA_HOME/tanzu-repository/metadata/latest/metadata.yaml
- Drop the extension locally in the directory $XDG_DATA_HOME/tanzu-repository/extensions/latest/<extension name>
  - Just copy any of the existing extensions on that directory, rename the directory and fix the extension.yaml file and the extensions's bundle registry reference

PS: I'm happy to contribute this in a PR with example snippets for all the steps

## Details

**TCE build version:** `v0.1.0`

**Comment by seemiller** [comment]
@jorgemoralespou Given the current state of TCE documentation, would you consider this is closed?
