### ISSUE TITLE
Make harbor package more configurable

### ISSUE THREAD

**Issue by jorgemoralespou** [vmware-tanzu/community-edition#1994]
## Feature Request

Currently harbor package does not provide flexibility in it's configuration like the Helm chart does. One can't provide a secretName to configure the TLS cert, or can't provide an Issuer/ClusterIssuer name for generating the certs that uses to communicate internally, or uses an HTTPproxy that requires the users to have contour installed.

An example of helm configuration:

```
helm install -n demo-harbor \
    https://github.com/goharbor/harbor-helm/tarball/1.0.1 \
    --set expose.ingress.hosts.core=harbor.demo.example.com \
    --set expose.ingress.annotations.'kubernetes\.io/ingress\.class'=contour \
    --set expose.ingress.annotations.'certmanager\.k8s\.io/cluster-issuer'=letsencrypt-prod \
    --set externalURL=https://harbor.demo.example.com \
    --set expose.tls.secretName=demo-harbor-harbor-ingress-cert \
    --set notary.enabled=false
```

cc/ @GrahamDumpleton

**Comment by kacole2** [comment]
+1 to this as it would be an incredible feature. Without the use of Let's Encrypt, we are stuck with having to follow [ytt templates](https://docs.vmware.com/en/VMware-Tanzu-Kubernetes-Grid/1.3/vmware-tanzu-kubernetes-grid-13/GUID-cluster-lifecycle-secrets.html) to inject self-signed certs.

**Comment by heww** [comment]
I think the harbor package may support configuring the TLS secret name by this PR https://github.com/vmware-tanzu/community-edition/pull/2563

**Comment by zyyw** [comment]
As @heww mentioned, tlsCertificateSecretName is supported in PR 2563, I think we can close this issue now.
