### ISSUE TITLE
Document best practices for migration to a commercial edition

### ISSUE THREAD

**Issue by qnetter** [vmware-tanzu/community-edition#2058]
## Description

We need to give people guidelines on how to migrate workloads from TCE to a commercial edition. Initially this will probably involve setting up a separate cluster, pointing at the same registry (or other source) that holds the user's apps and other tools, and using Velero based migration to redeploy the workloads.

After some time, we may develop an in-place strategy, which would then need to be documented. But that is out of scope for now.

## Location

This would be new doc.

**Comment by stmcginnis** [comment]
cc @vkorbes - not sure if we actually have a process for this or if we're relying on a lift-and-shift migration if someone wants to move to a commercially supported version. Wondering if we can close this issue until we have that in place.
