### ISSUE TITLE
knative install instructions do not work

### ISSUE THREAD

**Issue by seemiller** [vmware-tanzu/community-edition#2070]
## Bug Report

The Knative-serving installation instructions have the following command to install Contour:

```
tanzu package install contour --package-name contour.community.tanzu.vmware.com --namespace contour-external --version 1.17.1
```

The `--namespace` argument is incorrect and should be removed.

## Expected Behavior

The installation instructions should be correct.

## Steps to Reproduce the Bug

Follow the instructions, get an error:

```
Error: namespaces "contour-external" not found
```

## Environment Details

* Build version (`tanzu version`): 
* Deployment (Managed/Standalone cluster): 
* Infrastructure Provider (Docker/AWS/Azure/vSphere): 
* Operating System (client):

**Comment by vrabbi** [comment]
Add --create-namespace flag to the command
