### ISSUE TITLE
`tanzu diagnostics collect` not respecting `KUBECONFIG` environment variable for standalone clusters

### ISSUE THREAD

**Issue by karuppiah7890** [vmware-tanzu/community-edition#2077]
## Bug Report

`tanzu diagnostics collect` can diagnose standalone clusters only if the kube config is at `${HOME}/.kube/config`. It cannot diagnose standalone clusters whose kube config is present in a different location and is passed through `KUBECONFIG` environment variable

## Expected Behavior

`tanzu diagnostics collect` to respect `KUBECONFIG` environment variable

## Steps to Reproduce the Bug

Showing the issue with a simple kind cluster -

```bash
$ KUBECONFIG=kind.kubeconfig kind create cluster --name test

$ KUBECONFIG=kind.kubeconfig kubectl config rename-context kind-test test-admin@test

$ KUBECONFIG=kind.kubeconfig tanzu diagnostics collect --bootstrap-cluster-skip --management-cluster-skip --workload-cluster-name test
```

Note: The context rename is required due to #2076 

Output looks like this -

```bash
~ $ KUBECONFIG=kind.kubeconfig kind create cluster --name test
Creating cluster "test" ...
 ✓ Ensuring node image (kindest/node:v1.21.1) 🖼 
 ✓ Preparing nodes 📦  
 ✓ Writing configuration 📜 
 ✓ Starting control-plane 🕹️ 
 ✓ Installing CNI 🔌 
 ✓ Installing StorageClass 💾 
Set kubectl context to "kind-test"
You can now use your cluster with:

kubectl cluster-info --context kind-test

Not sure what to do next? 😅  Check out https://kind.sigs.k8s.io/docs/user/quick-start/
~ $ KUBECONFIG=kind.kubeconfig kubectl config rename-context kind-test test-admin@test
Context "kind-test" renamed to "test-admin@test".

~ $ KUBECONFIG=kind.kubeconfig tanzu diagnostics collect --bootstrap-cluster-skip --management-cluster-skip --workload-cluster-name test
2021/10/01 16:47:53 bootstrap cluster: skip=true: diagnostics will not be collected
2021/10/01 16:47:53 management cluster: skip=true: diagnostics will not be collected
2021/10/01 16:47:53 Info: Retrieving workload cluster credentials
2021/10/01 16:47:53 Info: Retrieving workload cluster: cluster=test; context=test-admin@test; kubeconfig=/Users/karuppiahn/.kube/config;
2021/10/01 16:47:53 Info: Capturing pod logs: cluster=test
2021/10/01 16:47:53 Warn: skipping workload cluster diagnostics: exec failed: Traceback (most recent call last):
  scripts/workload_cluster.star:98:9: in <toplevel>
  scripts/workload_cluster.star:88:30: in diagnose
  scripts/workload_cluster.star:27:24: in diagnose_workload_cluster
  scripts/lib.star:29:17: in capture_k8s_objects
  <builtin>: in kube_get
Error: could not initialize search client: context "test-admin@test" does not exist
~ $ 
```

Note how workload cluster diagnostics is not collected

## Additional information and context

There is code to pickup the `KUBECONFIG` here -

https://github.com/vmware-tanzu/community-edition/blob/77e7bdb6b7b6f650bee811caff086ff0c6701ecf/cli/cmd/plugin/diagnostics/pkg/support.go#L26-L32

and there is code to pickup the value and use it in the workload cluster star lark script too present here

https://github.com/vmware-tanzu/community-edition/blob/77e7bdb6b7b6f650bee811caff086ff0c6701ecf/cli/cmd/plugin/diagnostics/scripts/workload_cluster.star

But it is not working because of this code -

https://github.com/vmware-tanzu/community-edition/blob/77e7bdb6b7b6f650bee811caff086ff0c6701ecf/cli/cmd/plugin/diagnostics/scripts/workload_cluster.star#L52-L72

The script always has `standalone` value as `True` because `workload_cluster_standalone` argument is not sent to the star lark script in the golang code -

https://github.com/vmware-tanzu/community-edition/blob/77e7bdb6b7b6f650bee811caff086ff0c6701ecf/cli/cmd/plugin/diagnostics/pkg/collect_cmd.go#L189-L204

Since `standalone` value is always `False`, the `if not standalone` body is what is always executed in the workload cluster star lark script

https://github.com/vmware-tanzu/community-edition/blob/77e7bdb6b7b6f650bee811caff086ff0c6701ecf/cli/cmd/plugin/diagnostics/scripts/workload_cluster.star#L60-L67

But for standalone clusters, there's a separate block of code to pickup the workload cluster kube config and context

https://github.com/vmware-tanzu/community-edition/blob/77e7bdb6b7b6f650bee811caff086ff0c6701ecf/cli/cmd/plugin/diagnostics/scripts/workload_cluster.star#L67-L72

Due to the bug, the kube config used for standalone clusters is always `${HOME}/.kube/config` which is defined here

https://github.com/vmware-tanzu/community-edition/blob/77e7bdb6b7b6f650bee811caff086ff0c6701ecf/cli/cmd/plugin/diagnostics/scripts/workload_cluster.star#L56

## Environment Details

* Build version (`tanzu version`): 77e7bdb
* Deployment (Managed/Standalone cluster): Standalone Cluster
* Infrastructure Provider (Docker/AWS/Azure/vSphere): Docker
* Operating System (client): MacOS

**Comment by vladimirvivien** [comment]
This is a great bug writeup @karuppiah7890 👍 
Working on a fix for v0.10.0.
