### ISSUE TITLE
[Docs] Blog tags not working

### ISSUE THREAD

**Issue by jpmcb** [vmware-tanzu/community-edition#2106]
## Description
For blogs, the `tags` don't appear to be working.

For this blog, the authors have a tag:

Clicking that link takes us to `https://tanzucommunityedition.io/tags/nigel-brown-roger-klorese` which is the tag url which leads to 404.

## Location

`https://tanzucommunityedition.io/tags/nigel-brown-roger-klorese` 404s

## Additional Context

It doesn't seem we've enabled or fleshed out `tags` for our hugo site. This is something we should consider enabling or disabling for the site.

**Comment by jonasrosland** [comment]
Temporarily fixed in https://github.com/vmware-tanzu/community-edition/pull/2110
