### ISSUE TITLE
The `tanzu management-cluster create` command fails with "invalid provider name" error

### ISSUE THREAD

**Issue by alexbrand** [vmware-tanzu/community-edition#2128]
## Bug Report

The `tanzu management-cluster create` command fails with an "invalid provider name" error:

```
➜  tce-darwin-amd64-v0.9.1 tanzu management-cluster create

Downloading TKG compatibility file from 'projects.registry.vmware.com/tkg/framework-zshippable/tkg-compatibility'
Downloading the TKG Bill of Materials (BOM) file from 'projects.registry.vmware.com/tkg/tkg-bom:v1.4.0'
Downloading the TKr Bill of Materials (BOM) file from 'projects.registry.vmware.com/tkg/tkr-bom:v1.21.2_vmware.1-tkg.1'
ERROR 2021/10/04 12:24:07 svType != tvType; key=release, st=map[string]interface {}, tt=<nil>, sv=map[version:], tv=<nil>

Validating the pre-requisites...
Error: unable to parse provider name: invalid provider name "". Provider name should be in the form name[:version] and name cannot be empty
Usage:
  tanzu management-cluster create [flags]
```

## Expected Behavior

The `tanzu` CLI should create a management cluster OR tell me how to move past this error message/specify a provider. There does not seem to be a `--provider` flag, which makes me think I need to use the config file?

I wonder: should the command fail with a pretty error message if `--file` OR `--ui` is not provided?

## Steps to Reproduce the Bug

1. Download tce v0.9.1
2. Install tce
3. Run `tanzu management-cluster create`

**Comment by joshrosso** [comment]
@alexbrand yes, you do need a config file.

If you run `tanzu management-cluster create --ui` it'll walk you through creating one.

I agree this UX/response is not great, let's make it more clear.

**Comment by dvonthenen** [comment]
closing this out as it shoudnt be the case anymore
