### ISSUE TITLE
Installation of Chocolatey package appears to hang on `tanzu init`

### ISSUE THREAD

**Issue by nrb** [vmware-tanzu/community-edition#2132]
## Bug Report

When installing the Chocolatey package, the process stops at `- Moved CLI plugins to C:\Users\Administrator\AppData\Local\tanzu-cli`. A "successful," yet failed validation can [be found at this gist](https://gist.github.com/choco-bot/0a7b61c368e651654060108da0e421fc).

The next step here is to run `tanzu init`, which uses an ASCII spinner. This is not well-support in the Windows Console Host, where Chocolately must run from to do installs.

This appears to be blocking Chocolatey's validation process, and therefore blocking publishing of the package.

## Expected Behavior

The chocolatey package would run the installation to completion.

## Steps to Reproduce the Bug

From a Windows machine, using an admin Powershell command prompt:

```
cd <TCE checkout>\hack\choco
choco pack
choco install -dv -s . tanzu-community-edition
```

## Screenshots or additional information and context

[Recording of the pause when tanzu init is invoked](https://kubernetes.slack.com/files/U7S597E00/F02GDPYSAMU/screen_recording_2021-10-04_at_2.25.26_pm.mov)
## Environment Details

* Build version (`tanzu version`): v0.2.1
* Operating System (client): Windows 10

Possibly related to https://github.com/vmware-tanzu/tanzu-framework/issues/43

**Comment by seemiller** [comment]
@nrb believes that this issue has been resolved via another PR
