### ISSUE TITLE
Incorrect image links in Envoy and Grafana logs

### ISSUE THREAD

**Issue by jonasrosland** [vmware-tanzu/community-edition#2142]
## Description

I see multiple errors in our logs where images aren't linked correctly:
```
Resource not found | Requests
-- | --
/docs/latest/img/envoy-listings.png | 34
/docs/latest/img/envoy-db1.png | 31
/docs/site/content/docs/img/envoy-listings.png | 31
/docs/latest/img/envoy-db3.png | 30
/docs/latest/docs/img/envoy-db2.png | 30
/docs/latest/docs/img/grafana-data-source.png | 29
/docs/latest/docs/img/grafana-landing-page.png | 29
/docs/latest/img/grafana-manage-dashboards.png | 29
/docs/site/content/docs/img/envoy-db1.png | 28
/docs/site/content/docs/img/envoy-db2.png | 28

```

## Location

Looks like they are located in docs/site/content/docs/latest/vsphere-monitoring-stack.md

**Comment by stmcginnis** [comment]
Hey @jonasrosland - can you point to where you are seeing these errors? Those images appear to be showing up fine in the rendered site: https://tanzucommunityedition.io/docs/latest/vsphere-monitoring-stack/#validating-contour-functionality
