### ISSUE TITLE
Formatting of right nav overlaps table

### ISSUE THREAD

**Issue by mikegehard** [vmware-tanzu/community-edition#2151]
**On Page:** [](/docs/latest/package-readme-contour-1.18.1/)

Right sidebar overlaps with table on a 13" laptop screen.

![image](https://user-images.githubusercontent.com/128210/136025973-86b1b226-3583-40b0-9e5d-1a167e52549c.png)

**Comment by stmcginnis** [comment]
Thanks @mikegehard! We'll take a look at this.

Kind of unrelated, but wanted to check on the bug creation workflow. When creating a new issue, it *should* be prompting you for which type of issue you want to file and apply a set of tags based on your selection. Are you not seeing that when you go to file a new Issue? I've noticed there hasn't been any tags on the issues you've filed and just want to understand what's causing that.

Thanks for all the issues by the way - great to get these documented so they can get addressed!

**Comment by mikegehard** [comment]
A lot of these are coming from the link in the docs to file an issue...

See https://github.com/vmware-tanzu/community-edition/pull/2148#issuecomment-934475399
