### ISSUE TITLE
Missing toleration and short on CPU resources

### ISSUE THREAD

**Issue by vxav** [vmware-tanzu/community-edition#2158]
## Feedback

I created a management cluster to vSphere in dev mode using an ubuntu bootstrapper and it failed at the very end during the move of the management components.

The issue seems twofolds: 
- **Tolerations**: tkr-controller-manager-xxx-yyy in namespace tkr-system had no toleration to node-role.kubernetes.io/master:NoSchedule
Fix: added the toleration to the deployment
- **CPU**: The VM deployed from template (Ubuntu 20.04 and Kubernetes v1.21.2+vmware.1) has 2vCPU by default, the node had 1970m provisioned (out of 2000 then) and tkr-controller-manager-xxx-yyy requires 100m.
Fix: added 1vCPU to the virtual appliance

## Environment Details

* Build version (`tanzu version`): version: v0.2.1 buildDate: 2021-09-29
* Operating System (client): ubuntu-20.04.2

**Comment by jpmcb** [comment]
Hi @vxav - thanks for opening this issue! Wondering if we can get a bit more info:

- Can you provide a bit more information about your deployment and the command you used to deploy?
- Can you provide the logs and error message you got when running this deployment?

Thanks much!

**Comment by vxav** [comment]
Sure. 
Can you provide a bit more information about your deployment and the command you used to deploy?
- I run the bootstrap cluster in an ubuntu VM without X, so I use: _tanzu management-cluster create --ui --browser none --bind 192.168.1.20:8080 &_
- Can you provide the logs and error message you got when running this deployment?

`‼ [1005 20:06:17.29306]: init.go:705] Failure while deploying management cluster, Here are some steps to investigate the cause: 

‼ [1005 20:06:17.29323]: init.go:706] Debug: 

‼ [1005 20:06:17.29384]: init.go:707] kubectl get po,deploy,cluster,kubeadmcontrolplane,machine,machinedeployment -A --kubeconfig /home/ubuntu/.kube-tkg/tmp/config_8qEpSXFC 

‼ [1005 20:06:17.29404]: init.go:708] kubectl logs deployment.apps/<deployment-name> -n <deployment-namespace> manager --kubeconfig /home/ubuntu/.kube-tkg/tmp/config_8qEpSXFC 

‼ [1005 20:06:17.29475]: init.go:711] To clean up the resources created by the management cluster: 

‼ [1005 20:06:17.29488]: init.go:712] tanzu management-cluster delete 

✘ [1005 20:06:17.29504]: init.go:86] unable to set up management cluster, : unable to wait for cluster getting ready for move: worker nodes are still being created for MachineDeployment 'vtce-md-0', DesiredReplicas=1 Replicas=1 ReadyReplicas=0 UpdatedReplicas=1 `

When I mentioned the steps to fix the deployment it was on the management cluster, not the bootstrapped one.

In vSphere I have a *-control-plane-* VM that seems ok and an *-md-* that is stuck on "[FAILED] Failed to start Wait for Network to be Configured".

So far I haven't managed to successfully deploy the management cluster to vSphere.

I'll keep the environment as is if needed, let me know what files (logs or else) would be useful.

**Comment by vrabbi** [comment]
Can you share the santized version of the cluster config file which was auto generated in ~/.config/tanzu/tkg/clusterconfigs/
This is the file with all values you entered in the UI so sanitize whatever values shouldnt be shared

**Comment by AlvinRamoutar** [comment]
Experiencing the same thing here - identical error on all platforms below.

Bootstrap platforms:
- Windows 10 x64
- Windows Server 2019 Standard
- Ubuntu Server 20.04.3
- Ubuntu (WSL v2, 20.04.3)

Target:
- vSphere (vCenter Server 7.0.2.00500)

Attached logs are the result of bootstrapping from Windows 10 x64.
`tanzu management-cluster create --ui -b "127.0.0.1:8088"`
[ui_logs.txt](https://github.com/vmware-tanzu/community-edition/files/7334081/ui_logs.txt)
[esdi3jwf2d_sanitized.yaml.txt](https://github.com/vmware-tanzu/community-edition/files/7334084/esdi3jwf2d_sanitized.yaml.txt)

**Comment by AlvinRamoutar** [comment]
Should note that I've tried for both release 0.9.0 and 0.9.1
