### ISSUE TITLE
ClusterApi Provider Google (CAPG) Support

### ISSUE THREAD

**Issue by vrabbi** [vmware-tanzu/community-edition#2165]
## Feature Request
add CAPG as an infrastructure provider in Tanzu

## Describe alternatives you've considered
Deploy upstream CAPG with clusterctl

## Additional context
GCP is one of the 3 main Hyper Scaler Clouds and has a CAPI provider as well which is now maintained (was stale for a while).
this would be awesome to support as we are seeing GCP usage growing rapidly recently and CAPG via TCE would offer a great solution!

**Comment by dims** [comment]
@vrabbi https://github.com/kubernetes-sigs/cluster-api-provider-gcp/ is still not very healthy yet, we are trying to ... could use help there first before we can bring it here.

**Comment by vrabbi** [comment]
@dims i will try and see what i can do in the upstream CAPG. My bandwith is not that hogh right now but will see what i can do.

**Comment by qnetter** [comment]
We were discussing it today, in fact. I'll have updates soon.
