### ISSUE TITLE
clusterconfig filename does not match management cluster name

### ISSUE THREAD

**Issue by djschny** [vmware-tanzu/community-edition#2172]
## Bug Report

The [documentation says](~/.config/tanzu/tkg/clusterconfigs/<MGMT-CLUSTER-NAME>.yaml) the management cluster configuration file should be found as follows:

> ~/.config/tanzu/tkg/clusterconfigs/<MGMT-CLUSTER-NAME>.yaml where <MGMT-CLUSTER-NAME> is either the name you specified in the installer interface or else the randomly generated name if you didn’t specify a name.

However even though a cluster name was provided and verified in the config file and other places, the name of the file is a randomly generated name.

## Expected Behavior

The configuration file name to match the name of the management cluster.

## Steps to Reproduce the Bug

Create a management cluster using the Installer UI and give it a name.

## Screenshots or additional information and context

```
$ tanzu management-cluster get
  NAME             NAMESPACE   STATUS   CONTROLPLANE  WORKERS  KUBERNETES        ROLES       
  my-mgmt-cluster  tkg-system  running  1/1           1/1      v1.21.2+vmware.1  management  


Details:

NAME                                                                READY  SEVERITY  REASON  SINCE  MESSAGE
/my-mgmt-cluster                                                    True                     51m           
├─ClusterInfrastructure - DockerCluster/my-mgmt-cluster             True                     52m           
├─ControlPlane - KubeadmControlPlane/my-mgmt-cluster-control-plane  True                     51m           
│ └─Machine/my-mgmt-cluster-control-plane-g8jfp                     True                     51m           
└─Workers                                                                                                  
  └─MachineDeployment/my-mgmt-cluster-md-0                                                                 
    └─Machine/my-mgmt-cluster-md-0-5bbb796786-rkl69                 True                     51m           


Providers:

  NAMESPACE                          NAME                   TYPE                    PROVIDERNAME  VERSION  WATCHNAMESPACE  
  capd-system                        infrastructure-docker  InfrastructureProvider  docker        v0.3.23                  
  capi-kubeadm-bootstrap-system      bootstrap-kubeadm      BootstrapProvider       kubeadm       v0.3.23                  
  capi-kubeadm-control-plane-system  control-plane-kubeadm  ControlPlaneProvider    kubeadm       v0.3.23                  
  capi-system                        cluster-api            CoreProvider            cluster-api   v0.3.23                  
$ ls ~/.config/tanzu/tkg/clusterconfigs
a6zgiz6zta.yaml
```

## Environment Details

* Build version (`tanzu version`): `v0.9.1`
* Deployment (Managed/Standalone cluster): `Managed`
* Infrastructure Provider (Docker/AWS/Azure/vSphere): `Docker`
* Operating System (client): `Ubuntu`

**Comment by berndtj** [comment]
This issue is still present, and the docs do not match the current state of random clusterconfig file names.  To me this is a problem of cluster config discoverability and another, even better solution, would be to store the clusterconfig on the management cluster, so that it can be accessed by anyone that has a valid kubeconfig to the management cluster.
