### ISSUE TITLE
Provide a quick path for impatient people who just want to see something happen.

### ISSUE THREAD

**Issue by GrahamDumpleton** [vmware-tanzu/community-edition#2182]
## Description

The `README` file in GitHub gives instructions for installing the `tanzu` CLI but then stops. Impatient people are left hanging thinking what now.

Add a section after CLI installation in the `README` which says something like the following.

"""
Full details for creating clusters can be found in the documentation, but if you are the impatient type who just wants to see something work, then to create a standalone cluster running within your local docker environment, run:

```
tanzu standalone-cluster create -i docker <STANDALONE-CLUSTER-NAME>
```

Once the creation of the cluster has completed run:

```
kubectl config use-context <STANDALONE-CLUSTER-NAME>-admin@<STANDALONE-CLUSTER-NAME>
```

You can then interact with the TCE cluster using kubectl.

```
kubectl get pods -A
```
"""

It would also be useful to have at the start of the instructions for managed clusters a note indicating that if only want to test things, you may be better to use a standalone cluster and link to the page for standalone clusters. This is because impatient people will not read the architecture documentation and likely just drill down on TOC for Getting Started and click on the first entry which is Managed Clusters, not understanding that the better choice just to get something working is the Standalone Clusters page.

## Location

* https://github.com/vmware-tanzu/community-edition/blob/main/README.md
* https://tanzucommunityedition.io/docs/latest/getting-started/

## Additional Context

People like instant gratification and don't want to spend ages reading docs to get something working.

**Comment by joshrosso** [comment]
I'm a little worried about this because we get **so many** issues when folks deploy to docker without checking out the docs. Especially mac users that may not have adjusted their system resources.

Thanks said, we'd happily review a PR with these suggestions made and see if we can find a happy-medium without letting our README get too dense.
