### ISSUE TITLE
Add a search box to docs site.

### ISSUE THREAD

**Issue by GrahamDumpleton** [vmware-tanzu/community-edition#2186]
## Description

Can't seem to find a search box on the docs site. This would be useful when trying to find stuff in the docs.

One could obviously go to Google and search as:

```
site:tanzucommunityedition.io cert-manager
```

if one knows one can do that.

If the docs site itself cannot include its own search functionality, at least have a search box which goes to Google and does a search with the qualifier of `site:tanzucommunityedition.io`.

## Location

* https://tanzucommunityedition.io/docs/latest/

## Additional Context

Impatient people don't want to read docs and just want to search for the specific thing they think they need.

**Comment by jorgemoralespou** [comment]
Projectcontour does have this ability https://projectcontour.io/docs/v1.18.2/
