### ISSUE TITLE
The "--verbose" option doesn't do anything for "tanzu package" commands.

### ISSUE THREAD

**Issue by GrahamDumpleton** [vmware-tanzu/community-edition#2187]
## Feature Request

When a package install fails or times out one will be looking for more useful information as to why it failed to install. For many the first option would be to look to see if the command has an option to enable more verbose logging. When one looks at the help for the `tanzu` command one finds:

```
Global Flags:
      --log-file string   Log file path
      --verbose int32     Number for the log level verbosity(0-9)
```

which on face value gives the expectation that more output would be produced to explain what the command is doing and thus hopefully why it failed. Unfortunately this is not the case and using ``--verbose 9`` does not change the output of `tanzu package install` and `tanzu package installed delete` commands at all.

## Describe alternatives you've considered

The docs at:

* https://tanzucommunityedition.io/docs/latest/package-management/#troubleshooting-packages

do give troubleshooting tips, although running `kubectl describe` on the mentioned objects doesn't necessarily help.

Even though information in ``packageinstall`` and ``app`` resources is not always useful, maybe if nothing else can be shown for `--verbose` option due to how the CLI works, when `--verbose` is used with `tanzu package install` at least include a message (filled out with actual resource names for the deployment), something like:

"""
For additional information if installation issues arise run:

kubectl describe packageinstall.packaging.carvel.dev/${PKG} -n ${NS}
kubectl describe app.kappctrl.k14s.io/${PKG} -n ${NS}
"""

What you can do in the way of guiding information in `--verbose` information when `tanzu package installed delete` fails am not sure since those resources may not exist any longer, although in the case of a timeout they may have been left around.

Maybe in the case of a failure in delete and `--verbose` is used, output a list of the resources that couldn't be deleted as a pointer for where to start looking. This would include packaging resources, but also the service accounts, roles and rolebindings that were left behind and not deleted. In case of failure maybe `tanzu package installed delete` should always do that anyway since if it fails and leaves stuff behind you need to know things were not cleaned up and that you may have to run the delete again or manually clean stuff up somehow. The docs maybe should even include stuff about how to clean up things properly when delete fails, whether that be run it again, or manually delete resources.

## Additional context

Impatient people don't want to have to search for how to debug things and want easy ways to find more detail information on what the problem may be.

**Comment by joshrosso** [comment]
Thanks! Let's plan to address this in framework per @jorgemoralespou's links above and then we can bump our dependencies in a PR an close this issue.
