### ISSUE TITLE
Support deploying K8S OVA in vSphere using Content Library

### ISSUE THREAD

**Issue by lamw** [vmware-tanzu/community-edition#2189]
## Feature Request

Today, the workflow for a vSphere-based deployment still has many moving parts. Users must download the set of K8s OVA and import them vCenter Server. After that, they must convert the image to a vSphere Template before TCE can detect and deploy Management and/or Workload Clusters from. 

It would really simplify the user experience if the K8s OVA were available as an [externally hosted Content Library](https://williamlam.com/2018/07/creating-a-vsphere-content-library-directly-on-amazon-s3.html) like S3 or any HTTP(s) endpoint and then have TCE be able to also search for OVA within Content Library and simply deploy from it. In addition to automatically sync'ing all current and future K8s OVA, there's no additional step to convert image to vSphere Template 

## Describe alternatives you've considered

N/A

## Additional context

For Air-gapped or offline env, customers can also create their own Content Library either backed by a local vSphere Datastore or setup a similar externally hosted Content Library that resides within a user env

**Comment by joshrosso** [comment]
Raised this internally on several occasions. Going to put into `icebox` for now as I don't want to keep giving bad expectations to the community.
