### ISSUE TITLE
Update Pinniped to a recent non 0.4.x release

### ISSUE THREAD

**Issue by vrabbi** [vmware-tanzu/community-edition#2197]
## Feature Request
Update the Pinniped Version in TCE to use one of the newer releases of Pinniped. this would allow getting rid of Dex as there is now direct LDAP and even specific AD support which would allow for CLI base login which is great.
Also this would give a much better experience when running from a jump box without a browser as you dont need an additional terminal to paste the URL returned and its also exposed in a cleaner more understandable way.
this would also allow for OIDC providers that support the password grant auth flow (AzureAD for example) to support a CLI based login and not require a UI interaction.

## Describe alternatives you've considered
I currently deploy pinniped manually on my clusters as i need a good experience for jump boxes which currently problematic.
I use a custom api group similar to the way TMC does in order to not interfere with the pinniped deployed by TCE and the one deployed via TMC.
needing to have 3 pinnipeds seems like overkill and really not the best UX.
 

## Additional context
Getting rid of Dex would be great as its simply one less component to need to debug.
and if anyone needs Dex, they can configure Dex as the OIDC provider for identity management so no functionality is lost.

**Comment by jpmcb** [comment]
New Pinniped package has been merged, just waiting to release a new package repository with those changes and then will close this!
