### ISSUE TITLE
error when retrieving non-admin workload cluster kubeconfig

### ISSUE THREAD

**Issue by djschny** [vmware-tanzu/community-edition#2199]
## Bug Report

When retrieving a non-admin workload cluster kubeconfig an error is thrown:

```
$ tanzu cluster kubeconfig get my-workload-1
Error: failed to get pinniped-info from management cluster: failed to get pinniped-info from the cluster
Usage:
  tanzu cluster kubeconfig get CLUSTER_NAME [flags]

Examples:
  
    # Get workload cluster kubeconfig
    tanzu cluster kubeconfig get CLUSTER_NAME

    # Get workload cluster admin kubeconfig
    tanzu cluster kubeconfig get CLUSTER_NAME --admin

Flags:
      --admin                Get admin kubeconfig of the workload cluster
      --export-file string   File path to export a standalone kubeconfig for workload cluster
  -h, --help                 help for get
  -n, --namespace string     The namespace where the workload cluster was created. Assumes 'default' if not specified.

Global Flags:
      --log-file string   Log file path
  -v, --verbose int32     Number for the log level verbosity(0-9)

Error: exit status 1

✖  exit status 1
```

## Expected Behavior

Expect the command to run successful.

## Steps to Reproduce the Bug

* Create management cluster
* Create workload cluster
* Retrieve workload cluster kubeconfig without `--admin`

## Environment Details

* Build version (`tanzu version`): `v0.9.1`
* Deployment (Managed/Standalone cluster): `Managed`
* Infrastructure Provider (Docker/AWS/Azure/vSphere): `Docker`
* Operating System (client): `Ubuntu`

**Comment by vrabbi** [comment]
Did you configure identity management on tbe mgmt cluster?
Did you set the identity_managenent_typr property on tge workload cluster config file?

**Comment by joshrosso** [comment]
I've opened up the following issue in tanzu-framework:

* https://github.com/vmware-tanzu/tanzu-framework/issues/833

Work should occur against that issue and this issue should be referenced and closed via a PR that bumps our tanzu-framework dependency.

**Comment by djschny** [comment]
> Fair point! I think our takeaway here is the CLI should be able to detect that identity management is not turned on and let the use know this / point to docs.
> 
> Rather than expose that it couldn't communicate with some underlying component.
> 
> Seem sensible @djschny ?

Correct. It is exposing an internal implementation detail to the user as opposed to explaining what the problem is. So something like:

`Identify management is not setup and required to retrieve a non-admin kubeconfig. Add `--admin` to retrieve the admin config or see the following for how to configure identity management. <url_here>`

It should provide a much better experience and is the kind of things that people expect out of an opinionated platform or distribution compared to vanilla kubernetes. I hope that makes sense.
