### ISSUE TITLE
Docker installation: "Failed to invoke API on cluster : Get "https://172.18.0.3:6443/version?timeout=32s": dial tcp 172.18.0.3:6443: connectex"

### ISSUE THREAD

**Issue by HercegAndras** [vmware-tanzu/community-edition#2200]
Trying to install the TCE 0.91 to Docker (WSL2@W10 21H1, 19043.1237, w Docker Desktop latest v4.1.0)
After the step "Install providers on bootstrap cluster" I got the following error:

✘ [1007 22:55:26.54614]: init.go:108] unable to set up standalone cluster, : unable to get standalone cluster client: unable to get client: Failed to invoke API on cluster : Get "https://172.18.0.3:6443/version?timeout=32s": dial tcp 172.18.0.3:6443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because host has failed to respond.

What I have tried, but no change:

- different W10 PC
- reinstall the docker desktop
- tried with "MGMT and WKL cluster" and "Standalone" cluster installation options as well
- setting the memory limit to higher of the docker desktop

if you have WA, please let me know, thanks.

**Comment by joshrosso** [comment]
@HercegAndras deploying *to* a Docker Desktop / WSL instance is currently quite complicated. For example, it requires compiling a custom kernel to support antrea (our CNI).

You might [find our Windows guides useful](https://tanzucommunityedition.io/docs/latest/ref-windows-capd/), but I generally advise against bootstrapping to Windows hosts at this point.

**Comment by Tuto-Tanzu-Fr** [comment]
Hello it's still 05/11/2021 and it's not possible to use TCE with DockerDesktop on windows 10 I've the same error.

cluster: unable to get management cluster client: unable to get client: Failed to invoke API on cluster : Get "https://172.18.0.3:6443/version?timeout=32s":

Pls can you help ?

**Comment by kcoriordan** [comment]
@thesteve0 - a note was added here:
![image](https://user-images.githubusercontent.com/80768390/150821406-e8ff7883-a9ab-47a0-957a-0036ab670d1e.png)
