### ISSUE TITLE
ERROR thrown when creating default Docker management cluster

### ISSUE THREAD

**Issue by djschny** [vmware-tanzu/community-edition#2205]
## Bug Report

When creating a management cluster the following error is thrown but it appears to continue anyway and succeed:

```
ERROR 2021/10/08 17:24:44 svType != tvType; key=release, st=map[string]interface {}, tt=<nil>, sv=map[version:], tv=<nil>
```

## Expected Behavior

To not see the error message or if it is an actual problem for the error to be something that makes sense to the user.

## Steps to Reproduce the Bug

* `tanzu management-cluster create --ui --bind 0.0.0.0:8888 --browser none`
* Click ``DEPLOY`` from the Docker box
* Click ``NEXT`` when the installer validated it can connect to Docker
* Name the cluster ``my-mgmt-cluster`` and then click ``NEXT``
* Leave the network settings as default and click ``NEXT``
* Click ``REVIEW CONFIGURATION``
* Click ``DEPLOY MANAGEMENT CLUSTER``

## Screenshots or additional information and context

```
$ tanzu management-cluster create --ui --bind 0.0.0.0:8888 --browser none
Downloading TKG compatibility file from 'projects.registry.vmware.com/tkg/framework-zshippable/tkg-compatibility'
Downloading the TKG Bill of Materials (BOM) file from 'projects.registry.vmware.com/tkg/tkg-bom:v1.4.0'
Downloading the TKr Bill of Materials (BOM) file from 'projects.registry.vmware.com/tkg/tkr-bom:v1.21.2_vmware.1-tkg.1'
ERROR 2021/10/08 17:24:44 svType != tvType; key=release, st=map[string]interface {}, tt=<nil>, sv=map[version:], tv=<nil>

Validating the pre-requisites...
Serving kickstart UI at http://[::]:8888
Identity Provider not configured. Some authentication features won't work.
Validating configuration...
Using infrastructure provider docker:v0.3.23
Generating cluster configuration...
Setting up bootstrapper...
Bootstrapper created. Kubeconfig: /home/ubuntu/.kube-tkg/tmp/config_Kv6g8RKI
Installing providers on bootstrapper...
Fetching providers
Installing cert-manager Version="v1.1.0"
Waiting for cert-manager to be available...
Installing Provider="cluster-api" Version="v0.3.23" TargetNamespace="capi-system"
Installing Provider="bootstrap-kubeadm" Version="v0.3.23" TargetNamespace="capi-kubeadm-bootstrap-system"
Installing Provider="control-plane-kubeadm" Version="v0.3.23" TargetNamespace="capi-kubeadm-control-plane-system"
Installing Provider="infrastructure-docker" Version="v0.3.23" TargetNamespace="capd-system"
Start creating management cluster...
Saving management cluster kubeconfig into /home/ubuntu/.kube/config
Installing providers on management cluster...
Fetching providers
Installing cert-manager Version="v1.1.0"
Waiting for cert-manager to be available...
Installing Provider="cluster-api" Version="v0.3.23" TargetNamespace="capi-system"
Installing Provider="bootstrap-kubeadm" Version="v0.3.23" TargetNamespace="capi-kubeadm-bootstrap-system"
Installing Provider="control-plane-kubeadm" Version="v0.3.23" TargetNamespace="capi-kubeadm-control-plane-system"
Installing Provider="infrastructure-docker" Version="v0.3.23" TargetNamespace="capd-system"
Waiting for the management cluster to get ready for move...
Waiting for addons installation...
Moving all Cluster API objects from bootstrap cluster to management cluster...
Performing move...
Discovering Cluster API objects
Moving Cluster API objects Clusters=1
Creating objects in the target cluster
Deleting objects from the source cluster
Waiting for additional components to be up and running...
Waiting for packages to be up and running...
Context set for management cluster my-mgmt-cluster as 'my-mgmt-cluster-admin@my-mgmt-cluster'.

Management cluster created!


You can now create your first workload cluster by running the following:

  tanzu cluster create [name] -f [file]
```

## Environment Details

* Build version (`tanzu version`): `v0.9.1`
* Deployment (Managed/Standalone cluster): `Managed`
* Infrastructure Provider (Docker/AWS/Azure/vSphere): `Docker`
* Operating System (client): `Ubuntu`

**Comment by joshrosso** [comment]
Based on upstream progress (which I own :) ), this won't make it in for v0.10.0, moving it to the next release.

**Comment by joshrosso** [comment]
@stmcginnis could you please verify this for us.

Knowing that v0.11.0 will pin to framework v0.11.1, could you:

1. Build the management-cluster plugin from **framework** using the v0.11.1 tag
2. Verify the management-cluster plugin is of the correct version
3. Try what's describe above and see if this error still shows up?

**Comment by stmcginnis** [comment]
Tested with the current v0.10.0 release just to see. This error is not there, but the v0.10.0 release does contain the similar error of:

```
WARNING: key is not a string: %!s(int=1)WARNING: key is not a string: %!s(int=1)Validating configuration...
```

That is fixed in https://github.com/vmware-tanzu/tanzu-framework/issues/1521

Built and installed with tanzu-framework v0.11.1. Same error as above since https://github.com/vmware-tanzu/tanzu-framework/issues/1521 wasn't included in a release until the tanzu-framework v0.16.0 release.

So original error is no longer there, but the one error has been replaced by two equally confusing warnings.

**Comment by joshrosso** [comment]
kk.

even if we made a change in framework today, it wouldn't show up in the next release. Moving this item out.

**Comment by stmcginnis** [comment]
Tested this again with our latest release:

```
❯ rm -fr ~/.config/tanzu

❯ tanzu mc create foo -i docker -p dev
Downloading TKG compatibility file from 'projects.registry.vmware.com/tkg/framework-zshippable/tkg-compatibility'
Downloading the TKG Bill of Materials (BOM) file from 'projects.registry.vmware.com/tkg/tkg-bom:v1.5.1-tf-v0.11.2'
Downloading the TKr Bill of Materials (BOM) file from 'projects.registry.vmware.com/tkg/tkr-bom:v1.22.5_vmware.1-tkg.3-tf-v0.11.2'

Validating the pre-requisites...
Identity Provider not configured. Some authentication features won't work.
WARNING: key is not a string: %!s(int=1)WARNING: key is not a string: %!s(int=1)
Setting up management cluster...
```

It did not show the error descibed. There is the `WARNING: key is not a string` warning string that we are waiting on https://github.com/vmware-tanzu/tanzu-framework/issues/1521 to make it into one of our builds, but not the more concerning `ERROR 2021/10/08 17:24:44 svType != tvType` message.

@djschny if/when you get a chance, could you try again with our [latest release](https://github.com/vmware-tanzu/community-edition/releases/tag/v0.11.0) and verify things look OK now?

**Comment by stmcginnis** [comment]
This appears to be fixed, so going to close it out. If you do still see the issue then feel free to reopen.
