### ISSUE TITLE
"Deploy Standalone Cluster" Button Does Nothing If Cluster Name Already Exists

### ISSUE THREAD

**Issue by DennisFaucher** [vmware-tanzu/community-edition#2210]
## Bug Report

Kicked off a new cluster creation, tce-blog, which failed when my Mac went to sleep. Tried to create again, but this time "Deploy Standalone Cluster" button did nothing. 

## Expected Behavior
An error like "Cluster name already exists" would be helpful

An error like "Cluster name already exists" would be helpful
## Steps to Reproduce the Bug
Create a cluster with failure, try to create a cluster with the same name again

## Environment Details

* Build version (`tanzu version`): 
version: v0.2.1
buildDate: 2021-09-29
sha: ceaa474
* Deployment (Managed/Standalone cluster): Standalone
* Infrastructure Provider (Docker/AWS/Azure/vSphere): vSphere
* Operating System (client): MacOS 10.15.7

**Comment by joshrosso** [comment]
With our plans to deprecate this plugin and introduce the new standalone model, I'm going to close this issue out since it's a UX annoyance and not a blocker.
