### ISSUE TITLE
Define ownership of the Velero package

### ISSUE THREAD

**Issue by jpmcb** [vmware-tanzu/community-edition#2215]
## Maintainer Request

We need to define who is owning the Velero package. Right now, in the `metadata.yaml` fiile:

```yaml
  maintainers:
    - name: Carlisia Thompson
```

https://github.com/vmware-tanzu/community-edition/blob/main/addons/packages/velero/metadata.yaml#L10-L11

We can also take this opportunity to update the `pkg-velero-owners` github team to the correct people: https://github.com/orgs/vmware-tanzu/teams/pkg-velero-owners 

cc @nrb @carlisia

**Comment by nrb** [comment]
Let me see if I can add folks into `@vmware-tanzu/pkg-velero-owners`.

**Comment by blackpiglet** [comment]
The maintainer is already updated to me 

``` yaml
  maintainers:
    - name: Xun Jiang
```
https://github.com/vmware-tanzu/community-edition/blob/main/addons/packages/velero/metadata.yaml#L10-L11

I'm also added into https://github.com/orgs/vmware-tanzu/teams/pkg-velero-owners

**Comment by nrb** [comment]
@blackpiglet Yeah, it can! Thanks for reminding us.
