### ISSUE TITLE
Can it be deployed offline like KubeSphere？

### ISSUE THREAD

**Issue by yinggoga** [vmware-tanzu/community-edition#2218]
Can it be deployed offline like KubeSphere？

**Comment by stmcginnis** [comment]
Hi @yinggoga, thanks for asking. The short answer is yes, it should be able to be. But the longer, and perhaps slightly disappointing answer, is that we don't have any of that documented right now. There are several steps that need to be taken to set up an airgapped environment to be able to deploy offline, but we haven't gotten to validating and documenting all of those steps yet.

So while possible, until we get those steps written down, it will be a challenge to figure out what all needs to be done.

**Comment by joshrosso** [comment]
Regarding docs around internet restricted environment:

https://github.com/vmware-tanzu/community-edition/issues/862
