### ISSUE TITLE
doc: add doc for vsphere version

### ISSUE THREAD

**Issue by kcoriordan** [vmware-tanzu/community-edition#2237]
## Description

Need to call out that any vsphere edition that supports vSphere DRS is the actual requirement here:~
https://tanzucommunityedition.io/docs/latest/vsphere/

change:
```
 A vSphere 7, vSphere 6.7u3, VMware Cloud on AWS, or Azure VMware Solution account with:
 ] **vSphere 6.7**: an Enterprise Plus license
 ] **vSphere 7** 
```

to

```
 A vSphere 7, vSphere 6.7u3, VMware Cloud on AWS, or Azure VMware Solution account with
any vSphere edition that supports vSphere DRS
```

**Comment by lamw** [comment]
@kcoriordan After some additional commentary in Slack, I decided to run a few more experiments to confirm my understanding and it looks like `vSphere DRS` is NOT required. You can find the summarized findings on my blog https://williamlam.com/2021/10/minimum-vsphere-edition-features-for-tanzu-community-edition-tce.html 

I think stating that vCenter and vSphere Essential and Standard can be used can be helpful to give them an idea of the low barrier to entry from a licensing/feature standpoint but really ultimately, TCE for vSphere just requires vCenter Server that is managing the ESXi host. If a user has that setup in their env which can also include the default 60 day eval, then they can use TCE

Hope this helps
