### ISSUE TITLE
Bump kapp-controller to 0.27

### ISSUE THREAD

**Issue by jorgemoralespou** [vmware-tanzu/community-edition#2240]
## Feature Request
Bump kapp-controller to 0.27 to benefit from the speed improvements in reconciliation introduced in this version.
Keep in mind that 0.26 changed default syncPeriods of both PackageRepositories and PackageInstalls, so evaluate what the most appropriate value for TCE/TKG is (or make it configurable).

## Describe alternatives you've considered
Doing my own, and replacing the one in TCE :-( 

## Additional context
Related issue in tanzu-framework https://github.com/vmware-tanzu/tanzu-framework/issues/872

**Comment by joshrosso** [comment]
closing this in favor of ticket tracking 0.30 :+1: 

* https://github.com/vmware-tanzu/community-edition/projects/15
