### ISSUE TITLE
Add a link to the headless installation page to the main doc ToC links

### ISSUE THREAD

**Issue by kcalmond** [vmware-tanzu/community-edition#2251]
## Description

The headless install process is documented, but not findable via browsing the doc structure in the tanzucommunityedition.io site. 

## Location

Make [Tanzu Community Edition Headless Installation](https://tanzucommunityedition.io/docs/latest/headless-install/) browsable from here: https://tanzucommunityedition.io    

## Additional Context

I found the doc on headless by searching inside the repo for "headless".  You can also find it using an advanced query: https://www.google.com/search?as_q=headless&as_sitesearch=tanzucommunityedition.io

**Comment by joshrosso** [comment]
@stmcginnis curious, do these instructions still work?

Excuse my ignorance, but I'm wondering how moving the config file over for, say AWS, would work since it assumes the same AWS CLI profile would be available on the bootstrapping node?

I'm open to keeping this doc around, but I _think_ it'd need some reconsideration/updating?

**Comment by stmcginnis** [comment]
> I'm wondering how moving the config file over for, say AWS, would work since it assumes the same AWS CLI profile would be available on the bootstrapping node

For the case of creating on one machine, copying over, then running on the other machine I think you are right that this may not be entirely accurate anymore. As far as the other options, those should still work.

I think it may still be worth getting this added to the TOC. I think @kcoriordan was asking about it not long ago too. But it might be good to add a note about the need for having the AWS profile defined. I don't believe the other target platforms have the same limitation as AWS though.
