### ISSUE TITLE
Filter invalid machine types to prevent invalid selection in UI

### ISSUE THREAD

**Issue by afewell** [vmware-tanzu/community-edition#2259]
## Feature Request

Currently when installing mgmt cluster on AWS, the UI dropdown list for control plane and worker node machine types includes invalid selections including types that may be below minimum requirements or with invalid hardware such as arm processors. 

I am not sure if this is also a problem on Azure or vSphere. 

The dropdown list should ideally be filtered to ensure only valid machine types are displayed. 

Thanks!

**Comment by stmcginnis** [comment]
We can use this issue to track picking up this from tanzu-framework: https://github.com/vmware-tanzu/tanzu-framework/issues/861

**Comment by seemiller** [comment]
Closing - This issue can be handled via https://github.com/vmware-tanzu/community-edition/issues/2134
