### ISSUE TITLE
Add instructions for pushing packages + repo to a custom docker repo for dev testing

### ISSUE THREAD

**Issue by jayunit100** [vmware-tanzu/community-edition#2271]
## Description

cc @perithompson brought this up.'
'
We'd like instructions for pushing packages and repositories somewhere that can make the dev workflow for
adding/testing new packages a little more obvious....

## Location

I suppose this should live in the blog maybe since it would be useful to a broad audience  https://github.com/vmware-tanzu/community-edition/tree/main/docs/site/content/posts ?

Or maybe it could live in the formal docs, or both

**Comment by kcoriordan** [comment]
@perithompson

There is some content for adding/testing new packages in PR:
https://github.com/vmware-tanzu/community-edition/pull/2604

What other content did you have in mind?
Probably best to build on the formal docs content

**Comment by kcoriordan** [comment]
@jayunit100
There is some content here:
[Create a Package and a Package Repository](https://tanzucommunityedition.io/docs/latest/package-creation-step-by-step)


[Create a Package and Package Repository Example](https://tanzucommunityedition.io/docs/latest/packages-create-example)


Does this content cover what you had in mind?

**Comment by seemiller** [comment]
I would agree with Kay, I think that those docs probably have the information that you are looking for.

**Comment by kcoriordan** [comment]
@jayunit100 are you ok to close this issue based on above content?

**Comment by stmcginnis** [comment]
Per comments from Kay and Nick, I believe this need is covered now. Please feel free to reopen with any specific items missing. Thanks!
