### ISSUE TITLE
Add `provider/*` labels (e.g. `aws`, `vsphere`, etc) to this repository's issues

### ISSUE THREAD

**Issue by randomvariable** [vmware-tanzu/community-edition#2299]
## Feedback

As an upstream Cluster API provider maintainer who also happens to work for VMware, it might be helpful to have provider/aws, provider/vsphere etc... labels to gather feedback for upstream, see common concerns etc...

## Suggested Changes

Add labels as above.

## Environment Details

* Build version (`tanzu version`):
* Operating System (client):

**Comment by randomvariable** [comment]
I should add that not every issue is necessarily going to be upstream in Cluster API...

**Comment by stmcginnis** [comment]
@joshrosso I think we need your input on this one.

FWIW, I like it. I know we were trying to keep our labels super simple, but I can see this adding value.

**Comment by joshrosso** [comment]
`kind/`, `area/`, `proposal/` and `triage/` have meaning to the TCE engineering team.
As long as:

* Those prefixes are not added to or modified.
* This new label has a prefer, seems `provider/` is suggested.
* There is a consistent color used for all `provider/`, then I am :+1: .

@stmcginnis assigning this to you for v0.10.0.

**Comment by joshrosso** [comment]
Please note that labeling with `provider/` will be best effort.

**Comment by stmcginnis** [comment]
Added `provider/*` labels and updated our [Triaging, Prioritizing, and Labeling](https://github.com/vmware-tanzu/community-edition/issues/1829) instructions to note their usage.
