### ISSUE TITLE
Support for custom machine images in TCE

### ISSUE THREAD

**Issue by dims** [vmware-tanzu/community-edition#2303]
Context:
https://docs.vmware.com/en/VMware-Tanzu-Kubernetes-Grid/1.4/vmware-tanzu-kubernetes-grid-14/GUID-build-images-index.html

Do we support a custom image (with possibly upstream kubernetes bits using image-builder) in TCE? Is it just a matter of documentation?

**Comment by stmcginnis** [comment]
@nrb - is this related to the work you are currently doing?

**Comment by dvonthenen** [comment]
looks like this problem is 2 fold....
1) we should document in TCE docs how to do custom images for management clusters
2) provide more tooling to make this beyond easier for TCE users (the super ideal state would be BYOI self-service - ie provide inputs and hit a button)

**Comment by nrb** [comment]
This will be tackled as part of #2717

**Comment by RussellHamker** [comment]
Now that there is an OVA provided by VMware for Ubuntu and Photon, is it possible to get access to the git repository for the code of the OVA? I ask as this would allow others to assist in making it better and allow users to clone it and make their own version of it.

**Comment by stmcginnis** [comment]
@vuil do you know where this should go or who can comment on it? I believe this would need to be something handled in `tanzu-framework`. It might even be something we can support today, but I don't have much visibility into that OVA creation process.
