### ISSUE TITLE
vSphere Install Doc does not include UI install step 9 - Register TMC

### ISSUE THREAD

**Issue by thefluffysysop** [vmware-tanzu/community-edition#2312]
## Description

When initiating a TCE install against vSphere using the UI, the UI will list a  'step 9'  "Register TMC" (Tanzu Mission Control)

![image](https://user-images.githubusercontent.com/29251599/138355396-d54caa56-5469-4027-a691-2789704c6500.png)

This step is not documented, the documentation stops at 'step 8'

## Location

https://tanzucommunityedition.io/docs/latest/vsphere-install-mgmt/

## Additional Context

Is this step supposed to be included in TCE at all?  Currently, Tanzu Mission Control is only available as a paid IAAS service. A free 'starter' tier is in the works, but not yet available.  This step is either incorrectly included in the UI wizard, or requires some context on the documentation page.  In the case of the latter, a dedicated reference page on how to add TCE clusters to TMC-Starter would be useful later.

**Comment by qnetter** [comment]
The "Register MC" step will not work until a compatible version of Tanzu Mission Control is released. That's expected pretty soon, but as of now it does not work. We should document and note it.

**Comment by kcoriordan** [comment]
I thought Register TMC step was removed from the UI - or it should be:
https://github.com/vmware-tanzu/tanzu-framework/issues/812

**Comment by stmcginnis** [comment]
Kay is correct, the section has now been removed from the UI. So I think we can close this issue.
