### ISSUE TITLE
Kickstart UI not booting up on creating management cluster UI

### ISSUE THREAD

**Issue by PradeepLoganathan** [vmware-tanzu/community-edition#2318]
## Bug Report

TCE Management UI not starting up. 

## Expected Behavior

I should be able to see the management UI and create K8s cluster locally or in the cloud 

## Steps to Reproduce the Bug

1. Use this command to start the management UI  ``tanzu management-cluster create --ui
2. I get the "Serving kickstart  UI at http://127.0.0.1:8000" messagge
3. Navigating to the above URL shows a blank page.
4. Browser console displays this message "Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/plain". Strict MIME type checking is enforced for module scripts per HTML spec."
5
## Environment Details

* Build version (`tanzu version`): version: v0.2.1
* Deployment (Managed/Standalone cluster):  Standalone cluster
* Infrastructure Provider (Docker/AWS/Azure/vSphere): Docker
* Operating System (client): Windows 11 Build 220000.282

## Diagnostics and log bundle

C:\>tanzu diagnostics collect
2021/10/22 10:07:59 Collecting bootstrap cluster diagnostics
2021/10/22 10:07:59 Error: kind program binary not found
2021/10/22 10:07:59 Error: One or more required program(s) missing
2021/10/22 10:07:59 Warn: skipping management cluster diagnostics: management cluster: name not set
2021/10/22 10:07:59 Warn: skipping workload cluster diagnostics: workload cluster: name not set

**Comment by stmcginnis** [comment]
Any update on this @PradeepLoganathan? It looks like @miclettej's suggestion might be it, but would be great to get confirmation that your issue has been resolved. Thanks!

**Comment by PradeepLoganathan** [comment]
Hello @stmcginnis Yes, the registry fix worked great. The UI is now visible and i am able to create clusters on Azure and AWS.
