### ISSUE TITLE
Please add the kuberentes version included to release notes

### ISSUE THREAD

**Issue by thesteve0** [vmware-tanzu/community-edition#2329]
Greetings:
It is basically impossible to find out which version of Kube is bundled in the current TCE unless you have already created a server. 
The install instructions require kubectl be pre-installed. Best practice would be to match your kubectl to your server version (though it is possible to be a version off in either direction)

I think this could solved by adding the K8 version to the release notes in github.
Thanks

**Comment by kcoriordan** [comment]
fyi: We list the supported versions here: https://tanzucommunityedition.io/docs/latest/support-matrix/#supported-kubernetes-versions

**Comment by stmcginnis** [comment]
@dvonthenen - any way we can automate pulling this in to be included in the release notes?

**Comment by dvonthenen** [comment]
yep! I think we can download the BOM and dynamically parse then place on the draft release before publishing

**Comment by thesteve0** [comment]
Was this fixed?
