### ISSUE TITLE
Addons imgpkgBundle.images need to be rebuilt on addon changes

### ISSUE THREAD

**Issue by jorgemoralespou** [vmware-tanzu/community-edition#233]
## Feedback
When updating an addon (contents, etc....) the imgpkgBundle.image needs to be rebuilt to have the latests contents.

Currently, it's pointing to projects.registry.vmware.com/tce/EXTENSION_NAME-extension-templates:dev, and if the image is not rebuilt, you won't get the new addon contents. Probably there needs to be defined some versioning on addon definition changes, but since we're moving to Package definitions, I'll leave it sleep until then.

## Details

**TCE build version:** `v0.1.0`

**Comment by joshrosso** [comment]
Let's reopen if it's verified to not be completed.
