### ISSUE TITLE
Document vSphere Storage Requirements for Users

### ISSUE THREAD

**Issue by timmycarr** [vmware-tanzu/community-edition#2359]
## Description

As a user of TCE on vSphere we see TCE clusters are created with a default storageclass, but we need to have documentation to include what's needed on the vSphere side from an administration perspective to allow TCE to consume vSphere storage. Some of these details are already written up here: https://docs.vmware.com/en/VMware-Tanzu-Kubernetes-Grid/1.4/vmware-tanzu-kubernetes-grid-14/GUID-tanzu-k8s-clusters-storage.html

**Comment by stmcginnis** [comment]
Making sure you've seen this @kcoriordan

**Comment by kcoriordan** [comment]
plan on adding this content this week

**Comment by kcoriordan** [comment]
@timmycarr  -fyi - PR https://github.com/vmware-tanzu/community-edition/pull/2685
let me know if you have any comments
