### ISSUE TITLE
Create a method for copying TCE CLI installation & current config (created cluster state, credentials etc) from one node to another

### ISSUE THREAD

**Issue by kcalmond** [vmware-tanzu/community-edition#2379]
## Feature Request

Create a method for copying TCE CLI installation config (created cluster state, credentials etc) from one node (CLI client) to another.  Discussed on 10/27 office hrs call. Confirmed capabilities supporting this type of portability are not available yet. 

## Describe alternatives you've considered

n/a

## Additional context

The use case here is to provide a way to copy your TCE CLI context to a different client/node if needed. (Maybe you lose the initial TCE client node for some reason, without backup or snapshot to recover from)

**Comment by dvonthenen** [comment]
yea, this is a great idea especially considering that TCE and TKG aren't binary compatible
