### ISSUE TITLE
Install.bat falsely reports an error

### ISSUE THREAD

**Issue by thesteve0** [vmware-tanzu/community-edition#2381]
## Bug Report

When doing install.bat on windows powershell, the output for a successful install shows:

```
PS C:\Users\steve\Downloads\tce-windows-amd64-v0.9.1> .\install.bat
        1 file(s) copied.
The system cannot find the path specified.
        1 file(s) copied.
        1 file(s) copied.
        1 file(s) copied.
        1 file(s) copied.
        1 file(s) copied.
        1 file(s) copied.
        1 file(s) copied.
        1 file(s) copied.
        1 file(s) copied.
        1 file(s) copied.
✔  successfully initialized CLI
"Installation complete!"
```

The line "The system cannot find the path specified." appears to the user as error. It is not an error, it is just a notification that it can't find a path and is going to create it. 

## Expected Behavior

Change the current line to:

"The system cannot find the path xxxx/xxxx. Now creating the path"

## Steps to Reproduce the Bug

run install.bat on windows

## Environment Details

tce-windows-amd64-v0.9.1
 Tanzu version: v0.2.1
buildDate: 2021-09-29
sha: ceaa474
* Operating System (client): Windows 10 powershell

**Comment by dvonthenen** [comment]
yea, looks like we need to just eat this error and move on. I'm pretty sure this error is from testing a path and checking for it's existence (thus giving the error)
