### ISSUE TITLE
[Docs] [](/docs/latest/cli-installation/)

### ISSUE THREAD

**Issue by kremerpatrick** [vmware-tanzu/community-edition#2382]
## Description

Chocolatey installation command is incorrect at https://tanzucommunityedition.io/docs/latest/cli-installation/

The docs say to use `choco install tanzu-community-edition --version=v0.9.1`

However, the correct command is `choco install tanzu-community-edition --version=0.9.1`  (the letter `v` needs to be dropped).

## Location

docs/latest/cli-installation/

**Comment by kcoriordan** [comment]
@nrb can we close this ?

**Comment by kremerpatrick** [comment]
The Windows instructions now say 'choco install tanzu-community-edition', but the comment after the command is still wrong 'Using an explicit version is required for now.'

**Comment by nrb** [comment]
Yeah, we should update it since the package was approved. I'll put a PR in.

**Comment by nrb** [comment]
Nevermind - PR #2812 fixed it.
