### ISSUE TITLE
Mgmt Cluster UI Bootstrapper reporting LDAP lookup error

### ISSUE THREAD

**Issue by DanPhonovation** [vmware-tanzu/community-edition#2383]
In attempting to bootstrap a mgmt cluster and utilizing the identity mgmt provider configurator (against Active Directory), I am using this config:

```
LDAP_BIND_DN: CN=tanzuldap,OU=Service Accounts,OU=MyOrg,DC=MyDomain,DC=local
LDAP_BIND_PASSWORD: <encoded:VomittezASOFIHO=>
LDAP_GROUP_SEARCH_BASE_DN: DC=MyDomain,DC=local
LDAP_GROUP_SEARCH_FILTER: (objectClass=group)
LDAP_GROUP_SEARCH_GROUP_ATTRIBUTE: ""
LDAP_GROUP_SEARCH_NAME_ATTRIBUTE: cn
LDAP_GROUP_SEARCH_USER_ATTRIBUTE: ""
LDAP_HOST: SRV-VDEV-DC01.mydomain.local:636
LDAP_ROOT_CA_DATA_B64: <omit>
LDAP_USER_SEARCH_BASE_DN: DC=MyDomain,DC=local
LDAP_USER_SEARCH_FILTER: (objectClass=person)
LDAP_USER_SEARCH_NAME_ATTRIBUTE: sAMAccountName
LDAP_USER_SEARCH_USERNAME: sAMAccountName

```

When clicking the "Verify configuration" button: 
1) Binding succeeds
2) but fails upon looking up a specific user (any user, including the bind user itself).  

The same search executed manually (from the same machine as tanzu-cli) works:

```
ldapsearch -x -b 'DC=MyDomain,DC=local' -H ldaps://SRV-VDEV-DC01.mydomain.local:636 -D "CN=tanzuldap,OU=Service Accounts,OU=MyOrg,DC=MyDomain,DC=local" -W (objectclass=person)
```
Output
```
... ldap stuff
# search result
search: 1
result: 0 Success
```

**Comment by joshrosso** [comment]
@vmware-tanzu/pinniped-owners, seems to be something related to auth, not sure if ya'll can help here or if anything obvious sticks out.

**Comment by margocrawf** [comment]
What version of Pinniped is this running?
The user search filter looks like it's too broad, it should probably be `"&(objectClass=inetOrgPerson)(sAMAccountName={})"` or something.

**Comment by enj** [comment]
@vmware-tanzu/tkg-iam-owners should be able to help.

**Comment by benjaminapetersen** [comment]
Cool, we'll take a look at this.

**Comment by arcticjoe** [comment]
hi Dan, did you by any chance managed to get this sorted?
We are seeing the same issue when trying to deploy Tanzu 1.5.
When trying to validate LDAP settings, user search test only works when entering the Full Name, despite Login Attribute field being set to either userPricipleName or SamAccountName.
We cannot get group search to work no matter what we try.
LDAP works perfectly fine for other LDAP utilizing applications.

**Comment by sabbey37** [comment]
I imagine this is the same issue as the one called out here: https://github.com/vmware-tanzu/tanzu-framework/issues/1269.  Quoting from that issue:

> Pinniped/TKG IAM utilize whatever the user provides in this configuration. The LDAP search is hardcoded on the Kickstart UI side to utilize the filter + CN for user search (https://github.com/vmware-tanzu/tanzu-framework/blob/main/pkg/v1/tkg/ldap/client.go#L111) and the filter + OU for Group Search (https://github.com/vmware-tanzu/tanzu-framework/blob/main/pkg/v1/tkg/ldap/client.go#L180).
> 
> The issue lies in the LDAP verification performed by the Kickstart UI, which does not utilize Pinniped/TKG IAM tooling at all, it just performs a normal HTTP call.

Also tagging @miclettej and @raymondz1 who worked on this issue and added additional tooltip text to `Verify LDAP Configuration`
