### ISSUE TITLE
Support skip x509 check when deploy to vsphere

### ISSUE THREAD

**Issue by hangyan** [vmware-tanzu/community-edition#2395]
## Feature Request

When using ui to deploy tce in vsphere, after i input the username/password info and connect, an error mesage show up

```bash
Failed to connect to the specified vCenter Server. Post "https://<ip>/sdk": x509: certificate signed by unknown authority
```

I would like an option in UI to skip check for x509 cert in this situtaion

**Comment by jpmcb** [comment]
I've created an issue in tanzu-framework since the ui code is all upstream from there

- [ ] https://github.com/vmware-tanzu/tanzu-framework/issues/1028

We can track that issue here and we will bump the version of tanzu framework we ship to capture those changes

**Comment by miclettej** [comment]
[Code](https://github.com/vmware-tanzu/tanzu-framework/commit/7b637c3dd4f8ac077b91a1ad5d1409f2296c554f) has been merged to main. We have added a checkbox to the UI that is unchecked by default. When checked, user is electing to bypass SSL Thumbprint verification during authentication with their vCenter and all subsequent operations for creating clusters. 

https://user-images.githubusercontent.com/13439013/140963165-7eebdc01-15f6-4ed9-908a-a90d85865137.png

**Comment by miclettej** [comment]
@hangyan or @jpmcb the ability to skip x509 check was merged in Nov. Please feel free to close this issue as I am unable to do so. Thanks!

**Comment by jpmcb** [comment]
We haven't bumped our version of tanzu framework yet to capture those changes so we will keep this open. This was incorrectly labeled stale and we're working on modifying the stale or to ignore issues like this one that correlate to long running tanzu framework changes

**Comment by miclettej** [comment]
> We haven't bumped our version of tanzu framework yet to capture those changes so we will keep this open. This was incorrectly labeled stale and we're working on modifying the stale bot to ignore issues like this one that correlate to long running tanzu framework changes

Ah got it, thanks!

**Comment by jpmcb** [comment]
We've bumped to `v0.16.0` of tanzu-framework and this should be apart of the v0.11.0 release of TCE. Ref PR: https://github.com/vmware-tanzu/community-edition/pull/3149

**Comment by joshrosso** [comment]
Now that we've moved back to v0.11.1, is it still fixed?

Assigned to @jpmcb to validate.

**Comment by jpmcb** [comment]
Built off of `main` and I see the skip verify option:

<img width="1060" alt="Screen Shot 2022-03-07 at 5 27 00 PM" src="https://user-images.githubusercontent.com/23109390/157141369-f506ef99-9aa1-4948-9e0b-0ea203e3d310.png">

```
❯ make version
BUILD_VERSION: v0.11.0-fake.3
CONFIG_VERSION: v0.11.0
FRAMEWORK_BUILD_VERSION: v0.11.1
XDG_DATA_HOME: /home/jmcb/.local/share

```
