### ISSUE TITLE
Documentation site should include context-aware footer

### ISSUE THREAD

**Issue by joshrosso** [vmware-tanzu/community-edition#2400]
## Description

Today, the footer, even when on the docs page, takes you to the docs page.

![image](https://user-images.githubusercontent.com/6200057/139472627-467d728c-2e5b-4cca-b9f2-8dbdde8259c0.png)

This should be context aware and provide a different footer when already in docs.

## Location

https://tanzucommunityedition.io/docs/latest/

## Additional Context

None

**Comment by garrying** [comment]
A possible option is to have the footer on `/docs` point to `/community`. A mockup with copy reflected from community:
![Screen Shot 2021-11-11 at 2 09 43 PM](https://user-images.githubusercontent.com/227587/141355471-640e01fc-7b2c-4607-a444-2ecb35745734.png)

`/resources` could maybe be another option.
