### ISSUE TITLE
Document internal NLB requirement for AWS deployments in a limited-internet environment

### ISSUE THREAD

**Issue by xyloman** [vmware-tanzu/community-edition#2419]
## Bug Report

Attempting to perform management-cluster with CLI `tanzu management-cluster create --ui`  Results in the following error in pod `deployment.apps/capa-controller-manager -n capa-system manager`. 

```
E1101 20:27:48.232928       1 controller.go:257] controller-runtime/controller "msg"="Reconciler error" "error"="failed to create classic load balancer: \u0026{tce-cluster-01-apiserver  Internet-facing [] [] [sg-0272373de31f992cf] [0xc000829f20] 0xc000829f50 {10m0s false} map[Name:tce-cluster-01-apiserver sigs.k8s.io/cluster-api-provider-aws/cluster/tce-cluster-01:owned sigs.k8s.io/cluster-api-provider-aws/role:apiserver]}: ValidationError: Either AvailabilityZones or SubnetIds must be specified\n\tstatus code: 400, request id: b875eec8-c495-49b6-a616-35da63101313" "controller"="awscluster" "name"="tce-cluster-01" "namespace"="tkg-system"
```

We are attempting to reuse existing hardware that does not have an internet gateway or NAT.  Both facilities are provided through an existing transit gateway provided to the subnet. 

We have attempted to follow the advice documented here for [tagging resources](https://tanzucommunityedition.io/docs/latest/ref-aws/#tag-aws-resources).

## Expected Behavior

All load balancers created for standalone and management clusters will need to be internal.

## Steps to Reproduce the Bug

Use existing AWS hardware with tags described [here](https://tanzucommunityedition.io/docs/latest/ref-aws/#tag-aws-resources) with subnets with out internet gateway or nat gateway.  Instead, make use of a transit gateway.  Truely not sure if that is necessary. 

## Screenshots or additional information and context

```
E1101 20:27:48.232928       1 controller.go:257] controller-runtime/controller "msg"="Reconciler error" "error"="failed to create classic load balancer: \u0026{tce-cluster-01-apiserver  Internet-facing [] [] [sg-0272373de31f992cf] [0xc000829f20] 0xc000829f50 {10m0s false} map[Name:tce-cluster-01-apiserver sigs.k8s.io/cluster-api-provider-aws/cluster/tce-cluster-01:owned sigs.k8s.io/cluster-api-provider-aws/role:apiserver]}: ValidationError: Either AvailabilityZones or SubnetIds must be specified\n\tstatus code: 400, request id: b875eec8-c495-49b6-a616-35da63101313" "controller"="awscluster" "name"="tce-cluster-01" "namespace"="tkg-system"
```

## Environment Details

* Build version (`tanzu version`): v0.2.1
* Deployment (Managed/Standalone cluster): management and standalone
* Infrastructure Provider (Docker/AWS/Azure/vSphere):  AWS
* Operating System (client): Ubuntu 20.10

## Diagnostics and log bundle

N/A

**Comment by xyloman** [comment]
I have also reached out on this [slack](https://kubernetes.slack.com/archives/C02GY94A8KT/p1635543420296400)

**Comment by dvonthenen** [comment]
hey @xyloman was this resolved in slack? if you still need help, please drop a line here and we will get someone to help you

**Comment by xyloman** [comment]
@dvonthenen I think I was able to figure this out by leveraging the TKG documentation to configure the overlay to use an internal NLB.  If the content can be pulled from the TKG documentation and added to Community Edition that would help someone next time for sure.

**Comment by dvonthenen** [comment]
adding @kcoriordan to take a look at this

**Comment by stmcginnis** [comment]
@xyloman if you happen to still have the link that helped you, if you could paste that here that could really help anyone in the future that runs into the same situation if they search around and come across this issue. If it's not readily available for you anymore, no worries.

cc @kcoriordan

**Comment by xyloman** [comment]
@stmcginnis took me a bit of time to find this in my notes but here is the link that was the key for me: https://docs.vmware.com/en/VMware-Tanzu-Kubernetes-Grid/1.3/vmware-tanzu-kubernetes-grid-13/GUID-mgmt-clusters-airgapped-environments.html#step-5-initialize-tanzu-kubernetes-grid-9

**Comment by stmcginnis** [comment]
Thanks a ton for taking the time to look that up @xyloman - really appreciate that!

**Comment by kcoriordan** [comment]
thanks @xyloman, I'll work on getting this into TCE doc

**Comment by kcoriordan** [comment]
related to: #https://github.com/vmware-tanzu/community-edition/issues/862

**Comment by joshrosso** [comment]
This would be nice to have, but not a blocker for v0.11.0. Moving out to v0.12.0. It can still be completed asap.

**Comment by kcoriordan** [comment]
Starting work on this, but will not get a PR in for v0.12.0 timeframe, moving to v0.13.0
