### ISSUE TITLE
Propose to add VictoriaMetrics into Tanzu Packages

### ISSUE THREAD

**Issue by denisgolius** [vmware-tanzu/community-edition#2424]
## Feature Request
Could you please add https://github.com/VictoriaMetrics/operator into [Tanzu Packages](https://tanzucommunityedition.io/docs/latest/package-management/) ?

## Additional context

It can be installed from [Helm](https://github.com/VictoriaMetrics/helm-charts/blob/master/charts/victoria-metrics-operator/README.md)

**Comment by denisgolius** [comment]
Hi @stmcginnis!
Do you need any help for adding VictoriaMetrics to Tanzu Packages?

**Comment by nrb** [comment]
@denisgolius The core team won't be taking this on right now, but we'll leave the issue open in case someone (or you) wants to create one.

cc @qnetter for PM consideration

**Comment by denisgolius** [comment]
> @denisgolius The core team won't be taking this on right now, but we'll leave the issue open in case someone (or you) wants to create one.
> 
> cc @qnetter for PM consideration

Ok, I will try🙂
