### ISSUE TITLE
Type in package management diagram

### ISSUE THREAD

**Issue by mmelyp** [vmware-tanzu/community-edition#2425]
## Description

Is  "Package**Res**pository" or  "PackageRepository" ? I think it is a typo in the diagram. ;)

![image](https://user-images.githubusercontent.com/9610041/139835999-b09f013c-0c76-42e0-a66c-c35ce204abe7.png)

**Comment by stmcginnis** [comment]
Good catch @mmelyp!

@joshrosso do you still have the original diagram? If so, can you push up an update?

Might be nice if we can use a markdown native graphic so anyone can update it, but probably overkill for now.

**Comment by joshrosso** [comment]
> Might be nice if we can use a markdown native graphic so anyone can update it, but probably overkill for now.

Personally, not too crazy about mandating a diagramming tool. This diagram lives in our Miro project "TCE Architectures"; anyone on the team can make this correction. Or if someone external wants to recreate the diagram, that's great too.

I'll add it to v0.11.0 as something from the core engineering team to tackle, but if someone wants to jump ahead and resubmit a new diagram, that works too.
