### ISSUE TITLE
bump 1.2.3 Antrea-data-values 

### ISSUE THREAD

**Issue by jayunit100** [vmware-tanzu/community-edition#2431]
## Bug Report

We need to make sure we generally enable all, and new, 1.2.3+ features in the `antrea-data-values` secret.

@edwardbadboy  thinks we can do something  like this:
```
#@ if ANTREA_FULL_CONFIG:

#@ else:
#@ def antrea_agent_conf():
```
inside of the  https://github.com/vmware-tanzu/community-edition/edit/main/addons/packages/antrea/1.2.3/bundle/config/overlay/antrea_overlay.yaml file. 

I think in general this should definetly work.  IS there any major downside to it  ? If not would like to craft a PR. 

## Expected Behavior

antrea 1.2.3 features should be easy to turn on in tce, and for example GRE tunnels aren't supported currently.

cc @edwardbadboy

**Comment by edwardbadboy** [comment]
ANTREA_FULL_CONFIG can be used in some corner cases where user want to toggle some config options but the options are not exposed as data values.

**Comment by dvonthenen** [comment]
cc: @vmware-tanzu/antrea-owners
