### ISSUE TITLE
Outdated / out of sync `go.mod` and `go.sum` files

### ISSUE THREAD

**Issue by karuppiah7890** [vmware-tanzu/community-edition#2453]
Creating this issue based on the conversations in #2167 (https://github.com/vmware-tanzu/community-edition/pull/2167#issuecomment-935675031) and the data in #2444 and few other similar PRs where we noticed that `go.mod` and `go.sum` files were outdated / out of sync.

Maybe to solve the problem of outdated `go.mod` and `go.sum` and ensuring we do not have such outdated Golang module files, we can update the `lint` target in our `Makefile` like this -

```
lint: verify-modules golangci-lint

.PHONY: modules
modules: ## Runs go mod to ensure proper vendoring.
	go mod tidy

.PHONY: verify-modules
verify-modules: modules
	@if !(git diff --quiet HEAD -- go.sum go.mod); then \
		echo "go module files are out of date"; exit 1; \
	fi

golangci-lint: ## Run Go code linting
ifeq ($(origin GOLANGCI_LINT),undefined)
	@echo "Error! GOLANGCI_LINT env var not set"
else
	$(GOLANGCI_LINT) run -v --timeout=5m
endif
```

This is similar to the Golang module files check that CAPZ repo does - 

https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/ace988dec38dcdf27176a1d6f081cc64274fffb9/Makefile#L610-L614

https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/ace988dec38dcdf27176a1d6f081cc64274fffb9/Makefile#L286-L288

**Comment by stmcginnis** [comment]
+1

The `tanzu-framework` repo had something similar to the verify-modules target (though I don't see it now). I think it would be good to add that check so we don't ignore these being out of date.
