### ISSUE TITLE
`tanzu standalone-cluster create` not respecting the default timeout of 30 minutes

### ISSUE THREAD

**Issue by karuppiah7890** [vmware-tanzu/community-edition#2458]
## Bug Report

`tanzu standalone-cluster create` is not respecting the default timeout of 30 minutes for cluster creation. This can be noticed in the below pipelines where cluster creation was running for more than 30 minutes -

https://github.com/vmware-tanzu/community-edition/runs/4041246743?check_suite_focus=true#step:4:2012 - 106m46.458s

https://github.com/vmware-tanzu/community-edition/runs/4052404432?check_suite_focus=true#step:4:2564 - 170m43.967s . Diagnostics data - https://github.com/vmware-tanzu/community-edition/issues/2460#issuecomment-961803821

https://github.com/vmware-tanzu/community-edition/runs/4062644983?check_suite_focus=true#step:4:1752 - 66m37.879s - Diagnostics data - https://github.com/vmware-tanzu/community-edition/issues/2460#issuecomment-961808339

https://github.com/vmware-tanzu/community-edition/runs/4086937447?check_suite_focus=true#step:4:1966 - 93m18.091s

https://github.com/vmware-tanzu/community-edition/runs/4099592800?check_suite_focus=true - more than a few hrs. Not sure about the exact time since it's a single job and some of the time was taken up by `make release`, not sure exactly how much. Since GitHub Actions default Job timeout is 6 hrs, it was cancelled automatically, or else it might have run for more time I think. Diagnostics data - https://github.com/vmware-tanzu/community-edition/issues/2460#issuecomment-961806186

https://github.com/vmware-tanzu/community-edition/runs/4111906685?check_suite_focus=true - more than a few hrs. Not sure about the exact time since it's a single job and some of the time was taken up by `make release`, not sure exactly how much. Since GitHub Actions default Job timeout is 6 hrs, it was cancelled automatically, or else it might have run for more time I think. Diagnostics data - https://github.com/vmware-tanzu/community-edition/issues/2460#issuecomment-961807157

The default timeout is mentioned in the logs like this 

```
timeout duration of at least 15 minutes is required, using default timeout 30m0s
```

Related - #1201

## Expected Behavior

`tanzu standalone-cluster create` to automatically stop once the timeout of 30 minutes was up

## Steps to Reproduce the Bug

Not sure

## Screenshots or additional information and context

I don't have any additional information as of now

## Environment Details

* Build version (`tanzu version`): The latest commit - https://github.com/vmware-tanzu/community-edition/commit/c92900f0f2c90ca281f502086ea29254ae89e8c3 referenced in the latest nightly pipeline and many other commits referenced in the other failed pipelines
* Deployment (Managed/Standalone cluster): Standalone cluster
* Infrastructure Provider (Docker/AWS/Azure/vSphere): vSphere
* Operating System (client): Linux

## Diagnostics and log bundle

I don't have access to the diagnostics bundle for all clusters as we are yet to implement this for the pipelines. But some of the bootstrap clusters are hanging around in the self hosted runner ( due to #2457 ), so I'll upload whatever diagnostics data I find for the clusters related to the above failed pipelines

**Comment by stmcginnis** [comment]
Would be good to see if this behavior changes now that https://github.com/vmware-tanzu/community-edition/pull/2465 has merged.

**Comment by karuppiah7890** [comment]
Ah yeah. That was probably it. I'll keep an eye on the pipelines and also see if I can test it out myself by simulating a long running standalone cluster creation

**Comment by karuppiah7890** [comment]
I think it's fixed now, looking at the following pipeline -

https://github.com/vmware-tanzu/community-edition/runs/4189501402?check_suite_focus=true#step:5:1353 - ~38m
