### ISSUE TITLE
Add `kpack` as an installable package

### ISSUE THREAD

**Issue by kartiklunkad26** [vmware-tanzu/community-edition#2462]
### Problem

As more teams move towards containers, they frequently encounter additional dev ops complexity due to packaging source code alongside dependencies their apps need.  On the developer side, the test, code, build loop is made more complicated by needing to build dockerfiles and manage the resulting images in a registry.  On the dev ops side, keeping fleets of these images from many different teams patched to minimize exposure to security vulnerabilities causes overhead in the form of manual process or investment in/maintenance of complicated CI pipelines.  

### kpack

kpack is a VMware OSS project that consists of a collection of Resources that extend Kubernetes to produce images using Cloud Native Buildpacks that conform to OCI standards.  kpack executes builds directly on the user’s Kubernetes clusters utilizing unprivileged resources.  The project aims to help developers by reducing the complexity in generating an image from source code and removing the burden to update their images as the underlying build dependencies go out of date.  The project also serves dev ops by providing a central mechanism to automate updating of container images to help reduce the time it takes to patch CVEs or move a fleet of images to a new set of dependencies.

### Feature Ask
The ask is to make kpack available as a Tanzu package as part of Tanzu Community Edition.

## Describe alternatives you've considered

The alternatives currently are
1. installing kpack independently through kubectl directly on top of an existing TCE cluster. This is not a great experience overall.  
2. Utilizing a BYO docker image experience 
3. Providing users with a supply chain that utilizes Kaniko to produce images from dockerfiles

**Comment by kartiklunkad26** [comment]
@tomkennedy513 shared an update on this issue! 

"we made the changes in our repo to allow kpack to be shipped as a package, i am working on the pipeline side of things now"

**Comment by joshrosso** [comment]
Thanks for this proposal, overall we're excited get this together, I'd like a few things to be discussed/added to the proposal.

* Where do you plan to host the source configuration for the [carvel] package(s) representing kpack?

**Comment by tomkennedy513** [comment]
The source configuration lives inside of a private github repo that is shared with our commercial configs, but we publish the configs to a public repository (`projects.registry.vmware.com/buildservice/kpack/bundle`). Long term the Tanzu Build Service team will maintain this package

**Comment by joshrosso** [comment]
> The source configuration lives inside of a private github repo that is shared with our commercial configs

If hosting the source configuration in the open is a requirement for including this package, how would ya'll like to approach this? Options we're aware of are:

* Create your own repository
* Add and maintain the source configuration in this community-edition repo.

**Comment by tomkennedy513** [comment]
I think ideally we would decouple the oss config out of the commercial one so im leaning towards the first idea so that we don't have to support multiple sources of truth for the source config

**Comment by joshrosso** [comment]
Sounds great! I think we've got most everything figured out then.

Once the package source is open source, we can open up a PR in TCE's repo to point at this bundle.

Since you already have your bundle stored in `projects.registry.vmware.com`, we're in pretty good shape!

**Comment by tomkennedy513** [comment]
since the bundle is open source, would it be possible for us to use vendir to pull the source config into the tce repo? That would simplify the process for us since procuring oss repos takes a while and would provide the same outcome

**Comment by joshrosso** [comment]
> since the bundle is open source, would it be possible for us to use vendir to pull the source config into the tce repo

By the bundle being open source, do you mean it's available to be unpacked from `projects.registry.vmware.com/buildservice/kpack/bundle`? Or is the bundle source config available in a git repo somewhere?

**Comment by tomkennedy513** [comment]
Right now just the bundle is open source. I think we would be ok moving the package source. What would the process look like for creating our imgpkg bundle if the source lives in tce?

**Comment by joshrosso** [comment]
> I think we would be ok moving the package source. What would the process look like for creating our imgpkg bundle if the source lives in tce?

As discussed, the source configuration would live in the TCE repo. In any downstream repositories that pull in kpack, you would `vendir` the package in and add any overlays/modifications that should *not* be available in TCE.

**Comment by joshrosso** [comment]
In summary, we're approving this proposal 👍. The conceptual flow would be:

![image](https://user-images.githubusercontent.com/6200057/146395517-72833e04-c1e6-4892-8c1d-11d6738720cb.png)

**Comment by jorgemoralespou** [comment]
@joshrosso is there any defined SLAs to updating/fixing the packages that are not maintained by TCE owners but rather contributors?

**Comment by joshrosso** [comment]
Not yet. @seemiller is on point to wrap-up our package maintainer documentation which will feature these expectations going forward. Thinking in the realm of January/Feb.

**Comment by jorgemoralespou** [comment]
@joshrosso My fear with all these new packages being added to TCE main GH repo and code-base is that they are maintained in a proper and timely manner. If somehow the flow you depicted above is not respected, there's a high chance that eventually things will be out of synch. Kpack has a public code repo (https://github.com/pivotal/kpack) that it's the source of truth for the code (maybe not for the config). I would think that this is typically the best place to have these packages located, and just have TCE referencing them, which would probably prevent future forgetness for kpack maintainers to update TCE code repo.

**Comment by tomkennedy513** [comment]
@jorgemoralespou I'm personally not worried about forgetting the TCE repo because we use kpack in a commercial product and if we switch to vendoring in the package from TCE, we will have to update the TCE package to be able to leverage it commercially. We have tossed around the idea of adding this package config to kpack, but at the moment we aren't ready to introduce the carvel tooling as the standard in kpack just yet.

**Comment by joshrosso** [comment]
Having the upstream project host the packaging is an ideal state. However, this sentiment:

> but at the moment we aren't ready to introduce the carvel tooling as the standard in kpack just yet

Is shared amongst most projects we've talked to. And it's understandable consider carvel is a new-comer and not widely adopted.

**Comment by tomkennedy513** [comment]
Linking my wip branch here https://github.com/tomkennedy513/community-edition/tree/add-kpack

**Comment by kcoriordan** [comment]
@tomkennedy513, the readme looks great, adding some minor review comments here as per request in [Slack](https://app.slack.com/client/T09NY5SBT/threads)



Add a section for Supported Providers at the top, for example:
https://tanzucommunityedition.io/docs/latest/package-readme-cert-manager-1.3.3/


**step 1**
change 'Logged in' to 'Log in'
add an introductory comma after 'For dockerhub'

**step 2**
add an introductory comma after 'Later in this tutorial

**step 4**

I think Builder should be lower case

format this as inline code: to your-name/builder or gcr.io/your-project/builder


**step 5**
broken link: kpack secret documentation

**step 6**
format this as inline code: your-name/app or gcr.io/your-project/app

broken link: Note: To use a private git repo follow the instructions in secrets

change 'tail the logs for image' to 'tail the logs for the image'

**step 8**
change 'are able to' to 'can'

**global**
need a consistent way to refer to steps when cross referencing  - I think step 1, step 2 works best
Kubernetes should be initial capital throughout
remove 'please' throughout as per styleguide
