### ISSUE TITLE
Support for the K8s descheduler

### ISSUE THREAD

**Issue by dprotaso** [vmware-tanzu/community-edition#2464]
## Feature Request

There's a upstream Kubernetes tool called the descheduler available at https://github.com/kubernetes-sigs/descheduler. There are many application strategies for various workloads that it would be benefit if TCE could package, ship and support such a component.

## Describe alternatives you've considered

N/A

## Additional context

In Knative upstream there's a [feature request](https://github.com/knative/serving/issues/6176) to limit the lifetime of a pod. Doing this has two effects

1. Forces clients to be built in a resilient way
2. Improves the security posture as a compromised pod can only cause damage for only it's lifetime

The descheduler has a strategy to accomplish what we need via it's [PodLifeTime eviction](https://github.com/kubernetes-sigs/descheduler#podlifetime).

**Comment by timothysc** [comment]
@dprotaso - TCE has limited badwidth, but can probably assist with the packaging.  

cc @joshrosso

**Comment by joshrosso** [comment]
Including the `descheduler` as a package in TCE would definitely be interesting!

For now we don't have any timelines to include it, but we'd welcome contributions.
