### ISSUE TITLE
Label PRs with PR size

### ISSUE THREAD

**Issue by karuppiah7890** [vmware-tanzu/community-edition#2468]
Many OSS projects use bots to label PRs with labels like `small`, `large`, or `XS`, `S`, `L`, `XL` etc so that project maintainers know the size of the PRs when looking at the list of PRs in the PRs page and then they can choose to review small and big PRs depending on how much time they have to review PRs at the time based on PR size and priority (area of PR etc)

**Comment by jpmcb** [comment]
I'd be ok with this although I am generally cautious of adding too many labels and our labeling workflow growing too much. But we could easily automate this with a bot that fires on PR

**Comment by karuppiah7890** [comment]
Makes sense 👍 I'm not sure how we currently review PRs and if this makes sense and helps as part of the PR review process of folks. If this does not enable or fit into our existing PR review process, I think we can close it

**Comment by joshrosso** [comment]
Let's definitely revisit this if we find there's a need for the metadata (could be in the future when the project grows)
