### ISSUE TITLE
Outdated modules of multus-cni test

### ISSUE THREAD

**Issue by chenliu1993** [vmware-tanzu/community-edition#2469]
## Bug Report

Multus-cni's test go module still refers to some outdated modules. We better remove the outdated modules and use the latest ones.

## Expected Behavior

Remove outdated modules

## Steps to Reproduce the Bug

- `go mod tidy` will generate a diff for the modules related file

## Environment Details

* Build version (`tanzu version`):  
version: v1.4.0
buildDate: 2021-08-30
sha: c9929b8f
* Deployment (Managed/Standalone cluster): 
* Infrastructure Provider (Docker/AWS/Azure/vSphere): 
* Operating System (client):

**Comment by karuppiah7890** [comment]
Related - #2453
