### ISSUE TITLE
Reorganize and add consistency for installation docs

### ISSUE THREAD

**Issue by qnetter** [vmware-tanzu/community-edition#2487]
## Description

1. If the installation step is reliably the same across all platforms, then we should consider breaking it out of the per-platform, section and putting it at the same level as, and immediately following, "Plan Your Installation."

2. Also, We should offer both the package-manager and manual options for Windows and Mac, as we do for Linux.

I welcome feedback to the contrary, but a couple of less tech-savvy folks pointed out the inconsistency.

## Location

https://tanzucommunityedition.io/docs/latest/cli-installation/

**Comment by jpmcb** [comment]
> If the installation step is reliably the same across all platforms

Right now, it is not reliably the same. For example, on Windows, we recommend installation through the Chocolatey package manager. On Mac, we recommend Homebrew. Similarly, Mac and Windows need Docker Desktop running while Linux requires the Docker engine to be running (subtle, but important differences).

**Comment by qnetter** [comment]
I mean all infrastructures. We already have separate Linux, Mac, and Windows tabs on the page.

**Comment by stmcginnis** [comment]
There are differences between AWS, Azure, vSphere, and Docker too. I don't think there actually is enough commonality between these to combine them in a reasonable way.

**Comment by qnetter** [comment]
@stmcginnis  We currently link to exactly the same installation page in all four workflows...  Take a look.

**Comment by jpmcb** [comment]
> I mean all infrastructures. We already have separate Linux, Mac, and Windows tabs on the page.

Ah I see, so you're talking more about the infrastructure providers, not necessarily the local binary installation methods. 

Once you have the binaries, there isn't really a difference in the _local install_ and users can move on to the next step for their specific infrastructure (which do vary quite widely). So for example, with AWS, I go to the install page you linked (which instructs me how to install the bits onto my local machine) and then I proceed to the ["Prepare to Deploy a Cluster to AWS"](https://tanzucommunityedition.io/docs/latest/aws/) which gives infrastructure specific instructions.

So if I understand correctly, you want to add a section below the installation tabs you linked that moves the "Prepare" instructions for each infrastructure provider to that page in their own tabs?

**Comment by qnetter** [comment]
I'm focused on the things on the single page, the first in each infra's doc section, that is about installation of the CLI (on all three operating systems) by both the GH-download and package-manager methods. That is, this page: https://tanzucommunityedition.io/docs/latest/cli-installation/

**Comment by qnetter** [comment]
No, the opposite - I want to move the CLI installation page up to the same level as "Prepare" and the Installation header, not replicate it in each infra.

**Comment by stmcginnis** [comment]
> I want to move the CLI installation page up to the same level as "Prepare"

Ah, makes much more sense now. Yes, I agree, and I've commented on that before as well.

**Comment by kcoriordan** [comment]
OK - I'll that change in, it has been requested a few times
