### ISSUE TITLE
Harbor 2.3.3 missing from projects.registry.vmware.com/tce/main:0.9.1 as shown in Docs

### ISSUE THREAD

**Issue by kacole2** [vmware-tanzu/community-edition#2493]
The docs call out the installation and use of Harbor 2.3.3, however, there is no ability to install 2.3.3 since the docs call out installing the repository of `projects.registry.vmware.com/tce/main:0.9.1`. I'm assuming Harbor 2.3.3 is not in `projects.registry.vmware.com/tce/main:0.9.1`. So how does one install it?

## Bug Report

The [package management docs](https://tanzucommunityedition.io/docs/latest/package-management/) specify using `projects.registry.vmware.com/tce/main:0.9.1` as the repo to install. However, that repo does not have Harbor 2.3.3 and only has Harbor 2.2.3 available. 

```
kendrickc@kendrickc-a01 harbor % tanzu package available list harbor.community.tanzu.vmware.com
- Retrieving package versions for harbor.community.tanzu.vmware.com...
  NAME                               VERSION  RELEASED-AT
  harbor.community.tanzu.vmware.com  2.2.3    2021-07-07T18:00:00Z
```

## Expected Behavior

Harbor version 2.3.3 should be available. 

## Steps to Reproduce the Bug

Follow the docs. 
```
$ tanzu package repository add tce-repo \
  --url projects.registry.vmware.com/tce/main:0.9.1 \
  --namespace tanzu-package-repo-global
tanzu package available list harbor.community.tanzu.vmware.com
```

## Screenshots or additional information and context
n/a

## Environment Details

* Build version (`tanzu version`): v0.2.1
* Deployment (Managed/Standalone cluster): Managed
* Infrastructure Provider (Docker/AWS/Azure/vSphere): AWS 
* Operating System (client): Mac OS

## Diagnostics and log bundle
n/a

**Comment by stmcginnis** [comment]
This may be due to lack of versioning in our docs so far. The last official release did not include harbor 2.3.3, but has since been added in https://github.com/vmware-tanzu/community-edition/pull/2413

This will be available with the next release (currently planning for early December, though that may change). But ultimately the "fix" for this is to make sure we have release-versioned docs.

**Comment by kacole2** [comment]
Got it. Yes, it is a bit confusing. Having parity of what's in the docs vs what's available would be good. closing this.
