### ISSUE TITLE
Support for "external" (pluggable) cluster API providers 

### ISSUE THREAD

**Issue by dims** [vmware-tanzu/community-edition#2513]
There are several CAPI providers in the community already and there are many downstream/third-party/custom CAPI providers as well. Since most of the upstream tooling/utilities do support these, we need to find a way to document these scenarios and make pluggable as needed in TCE.

Let's take an example of the CAPG provider in the community for which a feature request has already been added:
https://github.com/vmware-tanzu/community-edition/issues/2165

There should be a way for folks to use TCE with GCP easily, it's quite possible that there are things in TCE that needs to be extensible to support these external CAPI providers. These may include changes here in this repository as well as the tanzu-framework. 

Ideally one should be able to add a external CAPI provider without any changes in TCE, but we may be far away from the ideal state. So could we please use the need for CAPG as a way to experiment how to support this scenario and document the steps needed right now (while we are working through it) and use this experience to remove the rough edges over time to get to the ideal state mentioned above over time.

**Comment by joshrosso** [comment]
Created a issue in framework to enable this functionality.

It is tracked at:

* https://github.com/vmware-tanzu/tanzu-framework/issues/1277

Once this issue is resolved, we should update our dependency of framework and then close **this** issue.

**Comment by anusha94** [comment]
Linking the feature request for BringYourOwnHost Provider here - https://github.com/vmware-tanzu/community-edition/issues/2721

**Comment by thesteve0** [comment]
Might be an interesting test case
https://metal.equinix.com/developers/guides/kubernetes-cluster-api/
