### ISSUE TITLE
Installation on OSX has excessive warnings

### ISSUE THREAD

**Issue by rosskukulinski** [vmware-tanzu/community-edition#2540]
## Feedback

When installing on OSX (`./install.sh`) from the v0.2.1 download, I was presented with a number of these OSX prompts:

![tce-tanzucli-prompts](https://user-images.githubusercontent.com/2746479/141862396-81a80f9c-3a2a-41aa-9df2-444306d91cd1.png)

This prompt popped up for each of the following:

* `tanzu`
* `tanzu-plugin-builder`
* `tanzu-plugin-cluster`
* `tanzu-plugin-conformance`
* `tanzu-plugin-diagnostics`
* `tanzu-plugin-kubernetes-release`
* `tanzu-plugin-local`
* `tanzu-plugin-management-cluster`
* `tanzu-plugin-package`
* `tanzu-plugin-pinniped-auth`
* `tanzu-plugin-standalone-cluster`

This is not a great installation UX and might confuse new users.  I think it would be _reasonable_ for the user to experience one of these, but not for every plugin we're installing.

## Environment Details

* Build version (`tanzu version`): v0.2.1
* Operating System (client): OSX 11.6.1 (Big Sur)

**Comment by stmcginnis** [comment]
Hey @rosskukulinski, were you doing a local build or using one of the official releases? The release binaries are signed, so you should not get these prompts when using that. Local builds will get the error though as they don't go through a signing process, so macOS will throw up this prompt.

**Comment by rosskukulinski** [comment]
Hi @stmcginnis - I downloaded directly from https://tanzucommunityedition.io/download/https://tanzucommunityedition.io/download/.  Specifically, https://github.com/vmware-tanzu/community-edition/releases/download/v0.9.1/tce-darwin-amd64-v0.9.1.tar.gz

**Comment by qnetter** [comment]
@rosskukulinski what do you have System Preferences->General->Allow apps downloaded from: set to?

**Comment by rosskukulinski** [comment]
![Screen Shot 2021-11-15 at 2 56 09 PM](https://user-images.githubusercontent.com/2746479/141865741-3340c843-5126-45a1-9eaf-8dcac53e0d87.png)

**Comment by navidshaikh** [comment]
@rosskukulinski : v0.9.1 patch was specifically released to fix a signing issue (found in the TCE v0.9.0 release). Can you please try running `./uninstall.sh` and then `./install.sh` ?

**Comment by dvonthenen** [comment]
Closing this for now. If the problem still exists in v0.9.1, please reopen the issue.
