### ISSUE TITLE
Error Running configure-tce.sh OSX 

### ISSUE THREAD

**Issue by ryanjbaxter** [vmware-tanzu/community-edition#2543]
I am getting an error running `configure-tce.sh` on OSX after installing the CLI via homebrew.  

I run 
`/usr/local/Cellar/tanzu-community-edition/v0.9.1/libexec/configure-tce.sh`
And got the following error
```
MY_DIR: /usr/local/Cellar/tanzu-community-edition/v0.9.1/libexec
/Users/ryanjbaxter/Library/Application Support
Removing old plugin cache from /Users/ryanjbaxter/.cache/tanzu/catalog.yaml
Making a backup of your Kubernetes config files into /tmp
⠋   initializingError: could not decode config file: no kind "ClientConfig" is registered for version "config.tanzu.vmware.com/v1alpha1" in scheme "pkg/runtime/scheme.go:101"
✖  could not decode config file: no kind "ClientConfig" is registered for version "config.tanzu.vmware.com/v1alpha1" in scheme "pkg/runtime/scheme.go:101"
```

I have tried running `rm -fr ~/.config/tanzu` and rerunning the script but also get the same error.

I have also tried running
```
docker rm -f $(docker ps -a -q)
docker rmi -f $(docker images -q -a)
docker volume prune -f
rm -rf ~/.cache/tanzu* ~/.local/share/tanzu* ~/.local/share/tce* ~/.config/tanzu ~/.kube
```
And running the script and it still failed with the same error.

**Comment by jpmcb** [comment]
Hi Ryan - thanks for opening this issue.

You wouldn't happen to have also had a commercial version of tanzu around before your install of TCE?

If so, you will need to clean up some additional files and caches. There is a provided `uninstall.sh` script that should clean up all the resources. For homebrew, it should be located in the homebrew directory for TCE: `"{libexec}/uninstall.sh"`

This will likely mean you also need to `brew uninstall` and then re install it with `brew install`

**Comment by ryanjbaxter** [comment]
@jpmcb I don't ever recall installing the commercial version, is there a way I can tell if I did or not?  I wouldn't even know where to find the uninstall script if I did.

**Comment by ryanjbaxter** [comment]
@dvonthenen Yes I do

**Comment by joshrosso** [comment]
Haven't heard back. Please feel free to reach out in slack or another github issue!
