### ISSUE TITLE
Fix vSphere management + workload cluster E2E test failure

### ISSUE THREAD

**Issue by karuppiah7890** [vmware-tanzu/community-edition#2545]
This pipeline - https://github.com/vmware-tanzu/community-edition/runs/4218748039?check_suite_focus=true#step:4:1453

There seems to be a BOM file download issue

```bash
+ tanzu management-cluster create test-management-cluster-19886 --file /home/ubuntu/actions-runner/_work/community-edition/community-edition/test/vsphere/cluster-config.yaml -v 10
compatibility file (/home/ubuntu/.config/tanzu/tkg/compatibility/tkg-compatibility.yaml) already exists, skipping download
The old bom folder /home/ubuntu/.config/tanzu/tkg/bom is backed up to /home/ubuntu/.config/tanzu/tkg/bom-20211116001718-vagbn5m0
Error: unable to ensure prerequisites: unable to ensure tkg BOM file: failed to download default bom files from the registry: unable to get the default BOM file ImagePath and Image Tag from the TKG Compatibility file: unable to find the supported TKG BOM version for the management plugin version "v0.10.0" in the TKG Compatibility file "/home/ubuntu/.config/tanzu/tkg/compatibility/tkg-compatibility.yaml"
...
```

Other pipelines worked fine though, like Azure management + workload cluster E2E tests and AWS management + workload cluster E2E tests. For example, see this - https://github.com/vmware-tanzu/community-edition/commit/dccd271d08c092c69415d8e2dbcfa8cafe017c69 which uses Tanzu Framework `v0.10.0` in it's commit, the tests for it - https://github.com/vmware-tanzu/community-edition/runs/4217019212?check_suite_focus=true (there is an issue in it , but not BOM file download issue!), https://github.com/vmware-tanzu/community-edition/runs/4217019249?check_suite_focus=true (fully passes)

- [ ] #2562 
- [ ] Upload latest OVAs to vCenter manually or using automation (#1305)

**Comment by karuppiah7890** [comment]
Another failure - https://github.com/vmware-tanzu/community-edition/runs/4232097279?check_suite_focus=true#step:4:1398

**Comment by karuppiah7890** [comment]
Okay, so this is due to #2562 . The reason for the failure is because the `tkg-compatibility` image is already pulled and the yaml file already exists in the self hosted vSphere runner, causing the new download to not happen

**Comment by karuppiah7890** [comment]
We may also need to upload OVAs to vCenter for the latest management-cluster plugin version, based on https://kubernetes.slack.com/archives/C02GY94A8KT/p1637150411055100 and based on #1305

**Comment by karuppiah7890** [comment]
Again happened - https://github.com/vmware-tanzu/community-edition/runs/4245355555?check_suite_focus=true#step:4:1399 

```bash
+ tanzu management-cluster create test-management-cluster-15847 --file /home/ubuntu/actions-runner/_work/community-edition/community-edition/test/vsphere/cluster-config.yaml -v 10
compatibility file (/home/ubuntu/.config/tanzu/tkg/compatibility/tkg-compatibility.yaml) already exists, skipping download
The old bom folder /home/ubuntu/.config/tanzu/tkg/bom is backed up to /home/ubuntu/.config/tanzu/tkg/bom-20211118001348-7b0v1j7j
Error: unable to ensure prerequisites: unable to ensure tkg BOM file: failed to download default bom files from the registry: unable to get the default BOM file ImagePath and Image Tag from the TKG Compatibility file: unable to find the supported TKG BOM version for the management plugin version "v0.10.0" in the TKG Compatibility file "/home/ubuntu/.config/tanzu/tkg/compatibility/tkg-compatibility.yaml"
```

**Comment by karuppiah7890** [comment]
We need to upload OVA file for fixing the latest failure - https://github.com/vmware-tanzu/community-edition/runs/4258550852?check_suite_focus=true#step:4:1431

```bash
WARNING: key is not a string: %!s(int=1)WARNING: key is not a string: %!s(int=1)Error: configuration validation failed: vSphere template kubernetes version validation failed: unable to get or validate VM Template for given Tanzu Kubernetes release: unable to find VM Template associated with TanzuKubernetesRelease v1.21.5+vmware.1-tkg.1-tf-v0.10.0. Please upload at least one VM Template from versions [v1.21.5+vmware.1-tkg.1-15708800623024541119,v1.21.5+vmware.1-tkg.1-12483545147728596280] to continue
```

**Comment by karuppiah7890** [comment]
I just uploaded the OVA to the VM folder and tried to run a test in my fork - https://github.com/karuppiah7890/community-edition/actions/runs/1525797955 and it passed. Just now I triggered https://github.com/vmware-tanzu/community-edition/runs/4381640883?check_suite_focus=true and if it passes, I'll retrigger all the pipelines

**Comment by karuppiah7890** [comment]
Closing this as it's fixed now 😄

**Comment by stealthybox** [comment]
I also have this same issue on the `v0.10.1-rc3` pre-release after upgrading from `v0.9.1`:
```
tanzu management-cluster get
Error: unable to ensure prerequisites: unable to ensure tkg BOM file: failed to download default bom files from the registry: unable to get the default BOM file ImagePath and Image Tag from the TKG Compatibility file: unable to find the supported TKG BOM version for the management plugin version "v0.10.1" in the TKG Compatibility file "/home/stealthybox/.config/tanzu/tkg/compatibility/tkg-compatibility.yaml"
```

Workaround is to delete the `~/.config/tanzu/tkg/compatibility/tkg-compatibility.yaml`, then the new BOM's will be automatically downloaded:
```
rm ~/.config/tanzu/tkg/compatibility/tkg-compatibility.yaml
tanzu management-cluster get
Downloading TKG compatibility file from 'projects-stg.registry.vmware.com/tkg/framework-zshippable/tkg-compatibility'
Downloading the TKG Bill of Materials (BOM) file from 'projects-stg.registry.vmware.com/tkg/tkg-bom:v1.5.0-tf-v0.10.1'
Downloading the TKr Bill of Materials (BOM) file from 'projects-stg.registry.vmware.com/tkg/tkr-bom:v1.21.5_vmware.1-tkg.1-tf-v0.10.1'
the old providers folder /home/stealthybox/.config/tanzu/tkg/providers is backed up to /home/stealthybox/.config/tanzu/tkg/providers-20220209031442-j8kqvr2d
  NAME             NAMESPACE   STATUS   CONTROLPLANE  WORKERS  KUBERNETES        ROLES
<truncated>
````
