### ISSUE TITLE
Bump Antrea 1.4 into TCE 

### ISSUE THREAD

**Issue by jayunit100** [vmware-tanzu/community-edition#2569]
## Feature Request

We'd like to bump 1.4 into TCE, but along the way we'd like to:
- [ ] define a policy around upstream antrea images that's easy to track
- [ ] make sure we are using upstream antrea in all packages
- [ ] Add some core antrea commiters as owners in the metadata.yml file
- [ ] increase test coverage for antrea CNI in GH actions as much as possible via , at the least, kind clusters that use the latest sem-var of antrea in the packages directory , i.e.
  - 0.11.3
  - 0.13.3
  - 1.2.3 <-- i.e. we'd like to test this in CI as the default, and ignore the others.

As of now, we *link* from tanzu-framework back to TCE by referencing a SHA / package, but, it seems like we should be able to test TCE independently.

**Comment by jayunit100** [comment]
@edwardbadboy @hangyan

**Comment by dvonthenen** [comment]
cc: @vmware-tanzu/antrea-owners
