### ISSUE TITLE
Fix `standalone-cluster` plugin version for `v0.10.0` release(s)

### ISSUE THREAD

**Issue by karuppiah7890** [vmware-tanzu/community-edition#2572]
We currently have `v0.9.1` as the version for `standalone-cluster` plugin for `v0.10.0-rc.1`

```bash
~ $ tanzu standalone-cluster version
v0.9.1
```

We should ideally have `v0.10.0-rc.1` as the version because we recently had one change to `standalone-cluster` plugin - https://github.com/vmware-tanzu/community-edition/commit/093715a8f323cb913234d1851b3cd652c6a85224 , which calls for a version bump, probably the last bump and then we will not touch it and deprecate it soon as the warnings mention

https://github.com/vmware-tanzu/community-edition/blob/e7ad596df377129fbbc4648300112b71929d7dd5/cli/cmd/plugin/standalone-cluster/main.go#L27-L30

**Comment by stmcginnis** [comment]
@dvonthenen did we actually build the standalone-cluster plugin with these new changes? I know we had talked about not touching it since it is going away.

**Comment by jpmcb** [comment]
Yes, it did make it into the RC build; I didn't realize there were any changes - good catch @karuppiah7890 thanks for being on top of that. So, yes, technically, this constitutes as a new feature, so the version for standalone should be bumped to `v0.10.0` in the upcoming release.

Reminder, that the deprecation notice should remain.

I'm also going to go through our backlog / issues and close issues related to standalone cluster feature adds with a deprecation notice.

**Comment by karuppiah7890** [comment]
@aman556 found it out actually 😄
