### ISSUE TITLE
Add version check as part of release gate

### ISSUE THREAD

**Issue by karuppiah7890** [vmware-tanzu/community-edition#2573]
This came up in this conversation https://github.com/vmware-tanzu/community-edition/pull/2304#discussion_r745273350 . Also, to avoid issues similar to #2572 , it's best to add a version check to ensure that the versions of all the commands are correct. All commands includes - TCE plugins, TF plugins (because we build this too from scratch) and `tanzu` command

Having the version check will help us ensure that the users see the right version and can use that to report errors, which will help us while debugging

**Comment by joshrosso** [comment]
Putting this in icebox only because we don't know what release this is targeted for or if it'll be out of band of an "official" release. Feel free to update the milestone if you want to bind yourself to a specific TCE release.

Thanks!
