### ISSUE TITLE
Azure management cluster E2E tests failing - due to non acceptance of VM image license

### ISSUE THREAD

**Issue by karuppiah7890** [vmware-tanzu/community-edition#2574]
## Bug Report

Azure management cluster E2E test seems to be failing since Tanzu Framework bump

https://github.com/vmware-tanzu/community-edition/actions/workflows/e2e-azure-management-and-workload-cluster.yaml

https://github.com/vmware-tanzu/community-edition/runs/4217019212?check_suite_focus=true#step:5:2026

```bash
Error: unable to set up management cluster: unable to wait for cluster and get the cluster kubeconfig: error waiting for cluster to be provisioned (this may take a few minutes): timed out waiting for cluster creation to complete: cluster control plane is still being initialized: ScalingUp
```

https://github.com/vmware-tanzu/community-edition/runs/4217728775?check_suite_focus=true#step:5:2022

```bash
 Error: unable to set up management cluster: unable to wait for cluster and get the cluster kubeconfig: error waiting for cluster to be provisioned (this may take a few minutes): timed out waiting for cluster creation to complete: cluster control plane is still being initialized: ScalingUp
```

https://github.com/vmware-tanzu/community-edition/runs/4231869877?check_suite_focus=true#step:5:2034

```bash
Error: unable to set up management cluster: unable to wait for cluster and get the cluster kubeconfig: error waiting for cluster to be provisioned (this may take a few minutes): timed out waiting for cluster creation to complete: cluster control plane is still being initialized: WaitingForBootstrapData @ Machine/test-mc-9299-control-plane-kjf5z
```

## Expected Behavior

Azure management cluster E2E tests to pass

## Steps to Reproduce the Bug

Run Azure management cluster using TCE `v0.10.0-rc.1` or from any commit since https://github.com/vmware-tanzu/community-edition/commit/dccd271d08c092c69415d8e2dbcfa8cafe017c69

## Screenshots or additional information and context

--

## Environment Details

* Build version (`tanzu version`): https://github.com/vmware-tanzu/community-edition/commit/dccd271d08c092c69415d8e2dbcfa8cafe017c69 or beyond
* Deployment (Managed/Standalone cluster): Manged cluster
* Infrastructure Provider (Docker/AWS/Azure/vSphere): Azure
* Operating System (client): Linux

## Diagnostics and log bundle

Unfortunately I don't have them 😞

**Comment by arpithahg** [comment]
Attaching the tanzu diagnostics run logs when hit the same issue in local run 
[bootstrap.tkg-kind-c6bme0l94819us7vnong.diagnostics.tar.gz](https://github.com/vmware-tanzu/community-edition/files/7569455/bootstrap.tkg-kind-c6bme0l94819us7vnong.diagnostics.tar.gz)

**Comment by arpithahg** [comment]
Attaching the kind logs that is collected on the same cluster to get the capz controller logs
[kind-logs-azure-managment-cluster.tar.gz](https://github.com/vmware-tanzu/community-edition/files/7569992/kind-logs-azure-managment-cluster.tar.gz)
r

**Comment by karuppiah7890** [comment]
We found out that the issue was that the Azure VM image license was not accepted, causing the issue. 

```
2021-11-19T09:07:47.8166081Z stderr F E1119 09:07:47.816382       1 controller.go:257] controller-runtime/controller "msg"="Reconciler error" "error"="failed to create AzureMachineService: failed to create virtual machine: failed to create VM mgmt10-control-plane-mqhdc in resource group az10: compute.VirtualMachinesClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code=\"ResourcePurchaseValidationFailed\" Message=\"User failed validation to purchase resources. Error message: 'You have not accepted the legal terms on this subscription: '3acb4fa4-4486-4bb9-9168-9c9cab47ddb3' for this plan. Before the subscription can be used, you need to accept the legal terms of the image. To read and accept legal terms, use the Azure CLI commands described at https://go.microsoft.com/fwlink/?linkid=2110637 or the PowerShell commands available at https://go.microsoft.com/fwlink/?linkid=862451. Alternatively, deploying via the Azure portal provides a UI experience for reading and accepting the legal terms. Offer details: publisher='vmware-inc' offer = 'tkg-capi', sku = 'k8s-1dot21dot5-ubuntu-2004', Correlation Id: '54d67095-0e6d-4ed4-afdc-c2cac8a81ac1'.'\"" "controller"="azuremachine" "name"="mgmt10-control-plane-mqhdc" "namespace"="tkg-system"
```

This is due to E2E test script hard coding the VM image ID here 

https://github.com/vmware-tanzu/community-edition/blob/438ba11825108fc5281d10d2c198c9085c6e641b/test/azure/deploy-management-and-workload-cluster.sh#L53

Causing the E2E test automation to accept VM image license for an older VM image but not for the latest VM image referred in the latest TKr BOM file - `tkr-bom-v1.21.5+vmware.1-tkg.1-tf-v0.10.0.yaml` from `projects-stg.registry.vmware.com/tkg/tkr-bom:v1.21.5_vmware.1-tkg.1-tf-v0.10.0`. Azure Standalone cluster E2E tests don't have an issue though, since they still use an older version of tanzu-framework and the same old TKr BOM files and Azure VM images which is the same one referred to in the Azure standalone cluster E2E test script

https://github.com/vmware-tanzu/community-edition/blob/438ba11825108fc5281d10d2c198c9085c6e641b/test/azure/deploy-standalone-cluster.sh#L52

I'll raise a PR to fix this. For now I have manually accepted the VM image license by using the TCE E2E test pipeline's Azure subscription. I did this from my local using a temp secret created for the `tce-pipeline` Azure application which I deleted later. I used the same set of commands to accept the Azure VM image license as mentioned in the E2E test script code. I did this to re-run the existing jobs. The latest jobs would work fine once the PR is merged, and VM image licenses would always be accepted automatically in the E2E test though just once is fine

I'll also create an issue to fix the hard coding of the Azure VM image. The solution would be something around finding the TKr BOM that's going to be used by the `tanzu` command and then use it to accept the Azure VM image license. Finding the TKr BOM that's going to be used can be tricky though 😅
