### ISSUE TITLE
Automate publishing OVA images to VMware Customer Connect

### ISSUE THREAD

**Issue by karuppiah7890** [vmware-tanzu/community-edition#2575]
This is based on the conversation from https://kubernetes.slack.com/archives/C02GY94A8KT/p1637150411055100 where we realized that users can't try out RC versions (like `v0.10.0-rc.1`) on vSpere as OVA images haven't been uploaded to VMware Customer Connect, for example like this https://customerconnect.vmware.com/downloads/get-download?downloadGroup=TCE-090

It would be best to automate this part of the pipeline - as part of releases - especially stable (GA) releases and also think about rc or non-GA releases (alpha, beta etc) and think about how we want to automate that and also publish OVA images for those versions to VMware Customer Connect

Related - #1305

**Comment by karuppiah7890** [comment]
cc @navidshaikh

**Comment by joshrosso** [comment]
Putting this in icebox only because we don't know what release this is targeted for or if it'll be out of band of an "official" release. Feel free to update the milestone if you want to bind yourself to a specific TCE release.

Thanks!
