### ISSUE TITLE
Need kickstart UI for new "standalone" plugin

### ISSUE THREAD

**Issue by qnetter** [vmware-tanzu/community-edition#2584]
From community created by [qnetter](https://github.com/qnetter): vmware-tanzu-private/community#2  

From tanzu-framework created by [qnetter](https://github.com/qnetter): vmware-tanzu/tanzu-framework#1200  

(This is used to request new product features)

**Describe the feature request**

The "standalone-cluster" implementation in TCE is being deprecated in v0.10.0, and will be replaced with a new "standalone" plugin that works for local clusters only, runs locally on the system where the installer is run, and is much faster and resource-efficient. 

To graduate to beta, this implementation needs a kickstart UI.

Initially, only a Docker provider will be available, but I expect the plugin to grow to include `podman` and `containerd` providers. We also expect to add support for Workstation and Fusion, but it is not clear yet if we will need a UI here or if they will call the `standalone` functionality directly from their UI.

**Describe alternatives you've considered**

For consistent experience with both management-cluster and the current standalone-cluster, this is needed.

**Affected product area (please put an X in all that apply)**

- [ ] APIs
- [ ] Addons
- [x] CLI
- [ ] Docs
- [ ] IAM
- [ ] Installation
- [ ] Plugin
- [ ] Security
- [ ] Test and Release
- [x] User Experience

**Additional context**

Code, doc, etc. can be found [here](https://github.com/vmware-tanzu/community-edition/tree/standalone-overhaul/cli/cmd/plugin/standalone-cluster).

**Comment by qnetter** [comment]
> This issue should actually probably land in `community-edition`
> 
> With the new standalone cluster plugin, we actually aren't importing `tanzu-framework` (since we are going with a much liter, no-lifecycle model). If we do indeed want a UI, we would need to either import `tanzu-framework` or port over the UI code from `tanzu-framework`
> 
> Although, this does raise an interesting question @miclettej - is it possible for the UI bits be separated from `tanzu-framework` so that it can be consumed as a dependency _outside of using_ `tanzu-framework`? Some sort of UI library that others can consume that isn't time to framework (and therefore tied to arbitrary versions of container runtime, the client go library, etc.)

Should I move it?

**Comment by qnetter** [comment]
@qnetter I think you can move it. If any work items specific to tanzu-framework come out of this we can cross-link them

**Comment by qnetter** [comment]
Hi @jpmcb and @dvonthenen  separating out the UI bits would be ideal. The UI's Angular webapp bits have to be served (currently done by a Go HTTP server in the management-cluster plugin) and need to be able to access whatever REST/API layer is made available to it. All of this is baked into the management-cluster plugin now as you've seen. 

We may have an opportunity here to come up with a fresh design that allows for the flexibility that you're suggesting. I am currently working on building a UI "shell" application in Angular/Webpack 5 that allows us to dynamically plug in other webapps. Imagine we have the frame of our current UI (the shell application which functions as the UI platform) and then we can plug different provider workflows in (developed as individual Angular/React apps) for different flavors of a distribution. Where I will need help is in how we design packaging and supporting backend APIs to also be plugged in. I don't have experience with Carvel yet, but I imagine that we can package and install UI workflows which include their respective UI plugin AND supporting backend.

Maybe that idea is taking things a bit too far but I'd love to brainstorm on how we can do exactly what you are suggesting.

**Comment by qnetter** [comment]
> This issue should actually probably land in `community-edition`
> 
> With the new standalone cluster plugin, we actually aren't importing `tanzu-framework` (since we are going with a much liter, no-lifecycle model). If we do indeed want a UI, we would need to either import `tanzu-framework` or port over the UI code from `tanzu-framework`
> 
> Although, this does raise an interesting question @miclettej - is it possible for the UI bits be separated from `tanzu-framework` so that it can be consumed as a dependency _outside of using_ `tanzu-framework`? Some sort of UI library that others can consume that isn't time to framework (and therefore tied to arbitrary versions of container runtime, the client go library, etc.)

Agreed this issue should probably be filed in the TCE repo. 

From my point of view, the new standalone is inherently for a developer role. What would the UI do exactly... have a textbox for a cluster name? then a button for deploy/start? this seems like it isn't necessary.

If this is for some end-user role with many options, then you need a UI/wizard to guide someone to deploy something that might be difficult to configure. That is definitely not the new standalone plugin.

Side note: I would be entirely in favor of decoupling the UI from business logic!

**Comment by qnetter** [comment]
This issue should actually probably land in `community-edition`

With the new standalone cluster plugin, we actually aren't importing `tanzu-framework` (since we are going with a much liter, no-lifecycle model). If we do indeed want a UI, we would need to either import `tanzu-framework` or port over the UI code from `tanzu-framework`

Although, this does raise an interesting question @miclettej - is it possible for the UI bits be separated from `tanzu-framework` so that it can be consumed as a dependency _outside of using_ `tanzu-framework`? Some sort of UI library that others can consume that isn't time to framework (and therefore tied to arbitrary versions of container runtime, the client go library, etc.)

**Comment by qnetter** [comment]
@jpmcb can you label this correctly as a feature request? Thanks.

**Comment by jorgemoralespou** [comment]
@dvonthenen I would think that even developers might need a UI, for 2 reasons:
- What standalone might make configurable via the standalone config and maybe the specific provider
- Eventually allowing the users (developers) to create clusters with a set of packages and potentially configure these from the UI.

What I don't see is how we can make the UI consistent with the managed clusters UI, as for community edition might/should be easier to augment/iterate on this specific UI more rapidly.
