### ISSUE TITLE
`tanzu diagnostics collect` not collecting `capz-system` namespace pod logs for debugging Azure cluster

### ISSUE THREAD

**Issue by karuppiah7890** [vmware-tanzu/community-edition#2585]
## Bug Report

While debugging #2574 , we noticed that the `tanzu diagnostics collect` command is not collecting `capz-system` namespace pod (containers) logs, for example - https://github.com/vmware-tanzu/community-edition/issues/2574#issuecomment-973933505

Related - #1781 

## Expected Behavior

`tanzu diagnostics collect` to collect `capz-system` namespace pod logs for helping debug Azure cluster creation issues

## Steps to Reproduce the Bug

Run a Azure management cluster or standalone cluster, and simulate an issue, run `tanzu diagnostics collect` and check the tar ball

## Screenshots or additional information and context

This was noticed in #1781 too, but at that time (pre `v0.10.0-rc.1`) `kind export logs` command helped collect `capz-system` namespace pod container logs. With a recent change to remove the dependency on `kind` command #2445 , we are now having issues collecting pod container logs from `capz-system` after the merge and release of #2445

## Environment Details

* Build version (`tanzu version`): `v0.10.0-rc.1`
* Deployment (Managed/Standalone cluster): Management cluster
* Infrastructure Provider (Docker/AWS/Azure/vSphere): Azure
* Operating System (client): MacOS

## Diagnostics and log bundle

https://github.com/vmware-tanzu/community-edition/files/7569455/bootstrap.tkg-kind-c6bme0l94819us7vnong.diagnostics.tar.gz

**Comment by karuppiah7890** [comment]
cc @vladimirvivien

**Comment by vladimirvivien** [comment]
@karuppiah7890 thanks for pointing this out. Will handle to make code freeze.
