### ISSUE TITLE
Check - Validate availability of artifact referred in TKr BOM

### ISSUE THREAD

**Issue by karuppiah7890** [vmware-tanzu/community-edition#2599]
Currently we don't have any validation for availability of artifacts referred in TKr BOM files. This validation is simply to check the availability of all the different kinds of artifacts in the TKr BOM files in respective locations, ideally publicly, so that users can use TCE with no issues like
- Container image not found
- Not able to obtain OVA image from VMware Customer Connect (Related - #2598 , #2575 )
- AWS / Azure VM image not found

Generally such issues are noticed only during the process of creating the cluster - midway, say, as part of E2E tests, and when users use TCE, they also see such errors very late in the process

The goal is to shift left and do checks earlier, so this could be a standalone check, decoupled from the E2E tests, which can check and validate the TKr BOM

Thanks to @navidshaikh for this great idea!

I think we could have sub tasks for this
- [x] #2598

**Comment by jpmcb** [comment]
> so this could be a standalone check, decoupled from the E2E tests, which can check and validate the TKr BOM

I think this is a great idea! Would make releasing much smoother with the confidence images and other artifacts are available and ready to go

**Comment by navidshaikh** [comment]
This is still relevent.
