### ISSUE TITLE
Survey respondent suggests updating installing a package section and describing cert-manager

### ISSUE THREAD

**Issue by pnbrown** [vmware-tanzu/community-edition#2613]
## Description

"I did the standalone guide:
https://tanzucommunityedition.io/docs/latest/getting-started-standalone/

Under the section 'Installing a Package' the sentence ""Make sure your kubectl context is set to either the workload cluster or standalone cluster."" Was confusing to me. I don't grasp the concept of bootstrap, management, workload, standalone clusters yet - what kind of cluster do I have at that point?

Also, a sentence what the package 'cert-manager' does would be nice. It seems like its an arbitarty example to show how packages are handled but this could be an improvement if explicitly mentioned."

## Location

https://tanzucommunityedition.io/docs/latest/getting-started-standalone/

**Comment by kcoriordan** [comment]
OK - good points, I'll action these

**Comment by joshrosso** [comment]
merged with https://github.com/vmware-tanzu/community-edition/pull/2628

Please feel free to reopen if this PR did not cover the change!
