### ISSUE TITLE
Provide User feedback that ARM (`darwin` and `linux`) is not supported for bootstrapping

### ISSUE THREAD

**Issue by edinel** [vmware-tanzu/community-edition#2616]
## Description

It should be clear in the docs that Apple Silicon is not supported yet with TCE.  A good friend of mine was unable to get started because Apple Silicon is not supported and the way he discovered that was, eventually, figuring out somewhat cryptic error messages when he tried to install.

**Comment by dvonthenen** [comment]
Yep, we currently don't support arm64. We have an issue being tracked here: https://github.com/vmware-tanzu/community-edition/issues/2171

All the downloadable packages on the release page do include the CPU architecture as part of the filename. Currently, we only support amd64 on all platforms.

**Comment by pdehlke** [comment]
`brew install vmware-tanzu/tanzu/tanzu-community-edition` works on both amd64 and arm64. It's still not at all unheard of to have amd64 binaries installed on M1 machines, and run just fine via rosetta. To be clear: tanzu _runs_, but does not meaningfully _work_ on Apple Silicon, and there is nothing in the documentation, the error messages, or the output from the software that tells the user that, should they try to build a docker/tanzu cluster on Apple Silicon, it will fail miserably  and obscurely.

The UX here is pretty miserable: the user is left to figure out for themselves that tanzu has pulled arm64 images from projects.registry.vmware.com :(

**Comment by dvonthenen** [comment]
Yea, the TCE build does produce arm64 binaries, but we don't include them in the release yet because of missing certain arm64 images/etc. Will need to revisit this since we updated to a later version of Tanzu Framework. If we still don't have support for arm64, will see about producing an error earlier.

Something @edinel might be able to help with... Since TCE and TKG are tied at the hip because the resources (BOM, images, and etc) used in TCE are the same, is Tanzu Framework going to fully support arm64?

**Comment by joshrosso** [comment]
In summary, it is the process of bootstrapping clusters that is not compatible with ARM (both linux and darwin), as such, we should provide the appropriate warnings to users from a docs and CLI-level. Here is our proposed approach.:

0. Update our docs/pre-reqs to mention that **bootstrapping** on an ARM-based machine does not work
1. Continue to allow install of TCE using amd64 binaries (many apps do this and work transparently via rosetta II)
2. When creating clusters, do an architecture check, and provide a warning that it likely won't work on arm

**Comment by joshrosso** [comment]
@stmcginnis we should add this pre-flight check to unmanaged-cluster. Then we can open an issue in framework for the other plugins.

**Comment by stmcginnis** [comment]
> we should add this pre-flight check to unmanaged-cluster

Already included in the preflight checks here:

https://github.com/vmware-tanzu/community-edition/blob/standalone-overhaul/cli/cmd/plugin/unmanaged-cluster/cluster/kind.go#L207

With a unit test explicitly testing for arm64 here:

https://github.com/vmware-tanzu/community-edition/blob/standalone-overhaul/cli/cmd/plugin/unmanaged-cluster/cluster/kind_test.go#L47

**Comment by joshrosso** [comment]
Great! Will open up an issue in framework for the management-cluster plugin.

**Comment by jpmcb** [comment]
Circling back on this:

- [x] Docs updated with support matrix for arm:

![image](https://user-images.githubusercontent.com/23109390/155564416-f68d0719-c7d3-4e54-8ce2-265dc7151a9a.png)

- [x] Preflight checks exist for `unmanaged` cluster and will display an error if user is trying to bootstrap from an arm based machine
- [x] Opened issue in tanzu framework: https://github.com/vmware-tanzu/tanzu-framework/issues/1732

**Comment by joshrosso** [comment]
Re-opening this as:

* https://github.com/vmware-tanzu/tanzu-framework/issues/1732

is not complete. This should act as a tracking issue until that work is complete and can be integrated into TCE.
