### ISSUE TITLE
Expose envoy's service loadBalancerIP as config option for Contour package

### ISSUE THREAD

**Issue by doddatpivotal** [vmware-tanzu/community-edition#2622]
## Feature Request

Customer would like predictably for the ingress IPs of their clusters.  They do not have a dynamic DNS service and thus takes 2 days to make DNS changes.  When they spin up clusters and spin them down using TKGm + AVI on vSphere, they have noticed that the IP address assigned to the envoy service is randomly assigned from the VIP pool managed by AVI.

Kubernetes allows that a desired loadBalancerIP be set on a service of type loadbalancer.  And AVI does honor this request if the IP is available.  However the Standard Contour package does not provide this as a configuration item in the data values file.  This results in having to apply a custom overlay to the package which is not currently supported and adds operational toil.

Requesting that envoy's service loadBalancerIP be added as a configurable item in the contour package.

**Comment by joshrosso** [comment]
@vmware-tanzu/pkg-contour-owners making sure you saw this as a potential new feature and prioritize it!

**Comment by skriss** [comment]
This should be very straight-forward to implement, just need to add a `values.yaml` option and then add logic to https://github.com/vmware-tanzu/community-edition/blob/main/addons/packages/contour/1.19.1/bundle/config/overlays/update-envoy-service.yaml to set `spec.loadBalancerIP` if the value was configured.

@doddatpivotal, any interest in contributing a patch here?

**Comment by doddatpivotal** [comment]
@skriss Yes.  I would like to do that. I'll give it a shot.

**Comment by doddatpivotal** [comment]
@skriss Happy to get feedback on the implementation and if I correctly followed the contribution guidance.
