### ISSUE TITLE
Autogenerated package PR removed some doc content from toc

### ISSUE THREAD

**Issue by kcoriordan** [vmware-tanzu/community-edition#2641]
## Bug Report

I added a Create Packages topic in https://github.com/vmware-tanzu/community-edition/pull/2604
looks like it was backed out in auto generated PR https://github.com/vmware-tanzu/community-edition/pull/2634
`docs/site/data/docs/latest-toc.yml`
line 86

## Environment Details

* Build version (`tanzu version`): 
* Deployment (Managed/Standalone cluster): 
* Infrastructure Provider (Docker/AWS/Azure/vSphere): 
* Operating System (client):

**Comment by stmcginnis** [comment]
I wonder if the README sync needs to have an explicit rebase of the source.

**Comment by kcoriordan** [comment]
this needs to be re-added now that https://github.com/vmware-tanzu/community-edition/pull/2868 is merged

**Comment by joshrosso** [comment]
sorry! closed by mistake
