### ISSUE TITLE
The readme.md should tell the user that install also adds the tanzu cli

### ISSUE THREAD

**Issue by thesteve0** [vmware-tanzu/community-edition#2665]
## Description

When you do any of the different install methods, including manual, not only is TCE is installed but so is the Tanzu CLI. 
This is important to note to the user because it is only if they click the getting started guide, then scroll through all the instructions and happen to notice the light grey instructions which state the CLI is also installed. 

Some users will probably install, go to look at some examples, and not be sure where the tanzu cli came from. 

All that is needed is adding the line, right above the packages heading that says:

```## At the end of the installation you now have both Tanzu Community Edition and the Tanzu CLI installed on your computer```

## Location

(https://github.com/vmware-tanzu/community-edition/blob/main/README.md)

**Comment by dvonthenen** [comment]
I think we just need to clarify some things. *Tanzu* Community Edition is the Tanzu CLI plus some plugins from this repo.

**Comment by kcoriordan** [comment]
It's mentioned in the docs in a few places. Maybe something like this at the end of a successful install might help

>Tanzu Community Edition (including the Tanzu CLI ) is now installed. 

It's mentioned here in P**lanning Your Install** in step 1
https://tanzucommunityedition.io/docs/latest/installation-planning/

It's also mentioned here **Install Tanzu Community Edition**  in the first sentence:
https://tanzucommunityedition.io/docs/latest/cli-installation/

It's also mentioned here in the first paragraph of **Architecture**
https://tanzucommunityedition.io/docs/latest/architecture/

**Comment by dvonthenen** [comment]
This was mentioned in the PR and I'm just copying it over here... 

> you do bring up a good point though... if there are sections of documentation where it sounds like they are two different things, we should probably fix those.
>
> Yea, there really isn't a TCE binary... TCE is a distribution or packaging of the Tanzu CLI.

**Comment by kcoriordan** [comment]
@thesteve0 - can we close this - as mentioned above it's already called out in doc in a few places?

**Comment by stmcginnis** [comment]
Closing this out per Kay's comment. Please feel free to reopen if there are other specific things that need to be addressed?
