### ISSUE TITLE
Introduce proposal process to Tanzu Community Edition

### ISSUE THREAD

**Issue by joshrosso** [vmware-tanzu/community-edition#2686]
## Abstract

The Tanzu Community Edition project needs a proposal process that can foster:

* Visibility into proposed changes to the project
* Feedback from maintainers, community members, and end-users
* Reaching decisions on proposed changes in a timely manner

## Proposal

Detailed proposal available in a design doc:

* [PR](https://github.com/vmware-tanzu/community-edition/pull/2687)
* [Rendered View](https://github.com/vmware-tanzu/community-edition/blob/proposal-process/docs/designs/2686-proposal-process.md)

## Alternatives Considered

None.

**Comment by joshrosso** [comment]
cc @dims, let's get some of your experience and doc you started in the end prospect.

Let's also use the proposal process against this proposal around proposal process.

**Comment by dims** [comment]
@joshrosso LOL yes, will file a PR in the next 2 days.

**Comment by joshrosso** [comment]
@qnetter FYI, want to make sure you're tracking this proposal on proposals.

**Comment by joshrosso** [comment]
> @joshrosso LOL yes, will file a PR in the next 2 days.

thanks! we've got a pr open now, feel free to add/commit directly too it or add comments for things we need to consider.

**Comment by joshrosso** [comment]
For review with maintainers tomorrow, we got the following suggested design doc template from @dims:

https://gist.github.com/dims/b9cd0c191c785292a8efad34030faf48

Let's review an see if we want to:

* Use it wholesale.
* Take parts out of it to incorporate in our existing template.

**Comment by dims** [comment]
@joshrosso +1 from me. i left some notes in https://github.com/vmware-tanzu/community-edition/pull/2687#issuecomment-993854194 for the maintainers...
