### ISSUE TITLE
[Docs] [AWS prep](/docs/latest/aws/) clarification suggestions

### ISSUE THREAD

**Issue by ciberkleid** [vmware-tanzu/community-edition#2690]
## Description

Wanted to share a few thoughts as I went through the AWS management cluster setup.

Step 1:
Current wording of step 1 is: `Create an access key and access key secret for your active AWS account.`
I think it would be good to say that you can also create a new user, and to specify the permissions the new user would need.

Step 2:
It seems the profile is required for the UI, and the config file generated by the UI contains the profile name.
I surmise that once that config file is available, if the profile save does not exist, then it uses the env vars?
Would be good if the docs were more explicit and perhaps commented on order of precedence if both are populated when the command line is used.

Also the wording here is `Configure AWS credentials`. Maybe more clear to say `Set your credentials locally` or `Set the access key and access key secret locally`, to relate it to the previous step.

Also, docs say: Run `AWS configure`. That should be lowercase, and potentially using the same black box syntax as other commands might be more clear.

Step 3:
Step 2 said to set `AWS_REGION`, and step 3 mentions `AWS_DEFAULT_REGION`, which is a little confusing.

Step 4:
Perhaps this can just be part of step 3, and could explicitly say that the command in step 3 automatically registers the key pair in your account.
Also, should say that `Network & Security > Key Pairs` is under the EC2 Service in AWS.

Step 5:
This is the same as step 2b, except here it is required instead of optional.
Should probably just be required in step 2.

## Location

https://tanzucommunityedition.io/docs/latest/aws/#before-you-begin

**Comment by kcoriordan** [comment]
Thanks for feedback @ciberkleid - I'll get a doc PR ready for review

**Comment by kcoriordan** [comment]
working on this today @ciberkleid

**Comment by joshrosso** [comment]
Looks like work stalled. Feel free to still do asap, but moving to v0.12.0 because it won't block this release.

**Comment by joshrosso** [comment]
moving this one to icebox as it keeps falling behind with due to other priorities. Also, help wanted!
