### ISSUE TITLE
Add `app` CLI plugin to TCE

### ISSUE THREAD

**Issue by heyjcollins** [vmware-tanzu/community-edition#2696]
## Feature Request
This is more of a request to discuss and align on a plan rather than a feature, but this seems like the most suitable issue type to start/track the convo.

The apps plugin for the Tanzu CLI is a dev-focused plugin which enables application developers and/or operators to manage the lifecycle of workloads. We'd like to make it accessible to anyone who's interested in OSS Tanzu.

OSSing the apps plugin on it's own doesn't have enough  community and the investments required to manage its well-being.

## Describe alternatives you've considered

We've considered Tanzu-Framework and decided against it because the apps plugin is most applicable to a TCE-enabled cluster and this is especially/increasingly true as more components of the Tanzu Application Platform go from private to public.

For now, not sure what more to add except that I look forward to working this issue with you!

**Comment by joshrosso** [comment]
:wave: Thanks @heyjcollins, we've added this proposal to our review queue so it now should get attention so we can move it along.

Reading the original issue, the concrete thing being proposed isn't super clear to me, reading between the lines, are you proposing:

* Adding the tanzu app CLI plugin into the `vmware-tanzu/community-edition` repository?

Regarding this point:

> OSSing the apps plugin on it's own doesn't have enough community and the investments required to manage its well-being.

While it's technically possible (and OK) to include this plugin in the community-edition repo, it's not required for the plugin to be included in our distribution. Having  your own repository would enable your own tagging/issues/prioritization/etc. We'd then reference your CLI plugin in our builds, which would include it to TCE users.

I wanted to make sure you're aware of the significant benefits of hosting this code **outside** the community-edition repo as we advance this proposal.

**Comment by kartiklunkad26** [comment]
I believe @heyjcollins also mentioned something to a similar effect - 

`We intend to maintain ownership of the plugin and ideally we’d manage the lifecycle of it independently from TCE.`

So the two approaches here are: 
1. Host the Tanzu Apps CLI plugin into the `vmware-tanzu/community-edition` repository, while still having the Tanzu Apps CLI plugin team maintaining it's lifecycle
2. Host the Tanzu Apps CLI plugin as a separate public repository that can be referenced in the TCE builds, and eventually be available to TCE users.

**Comment by joshrosso** [comment]
When weighing the two approach, we highly recommend **2**. It gives you the flexibility and decoupling to maintain this project independent of the community-edition distribution. Even if there isn't an existing community that justifies its use outside of the community-edition, or tanzu, context, this still enables day-to-day development operations to happen in a way that works best for you.

Pragmatically, due to teams not wanting to start net-new VMware open source projects, people contribute their code to this repository.

**Comment by qnetter** [comment]
Seconded. :)

**Comment by kartiklunkad26** [comment]
@joshrosso @qnetter We've decided to create a separate repository for Tanzu Apps Plugin CLI (2nd approach). cc: @heyjcollins

**Comment by joshrosso** [comment]
Sounds good.

Including the CLI plugin is a little more involved than including packages like `kpack`. Is there a timeframe ya'll have for when the TAP CLI plugin should be included by *default* ?

**Comment by kartiklunkad26** [comment]
@joshrosso please hold on the timeframe. We will provide that timeframe. Will batch this with the Cartographer package based on @scothis's input.

**Comment by joshrosso** [comment]
Makes sense all!

Please note our [proposal process is documented here](https://github.com/vmware-tanzu/community-edition/tree/main/docs/designs). We try to keep the process light-weight and **not not** always require a design doc, although we may suggest one. If you feel a full design doc is justified, you are welcome to create one, however, adding details to this issue might suffice.

We'd need some form of proposal to really understand what we're going to include in TCE and how we want to include it.

**Comment by kartiklunkad26** [comment]
@joshrosso Hey Josh! The Apps CLI Plugin team is in the final stages of making their repository public. Post that they will look to have the Apps CLI Plugin releases in that repository. 

The experience we want is for the Apps CLI Plugin to be installed as part of the TCE Installation. How do you recommend we proceed forward about the collaboration? 

This will very much depend on Cartographer (and FluxCD Source Controller) before this CLI is useful. Wanted to start the conversation though. 

cc: @atmandhol @heyjcollins

**Comment by joshrosso** [comment]
Hey all!

Largely what is needed here is for us to have a place we can pull the binary from. An OCI asset or direct binary could work.

We just need to verify:

Will the binary that gets produced be signed by VMware?

**Comment by joshrosso** [comment]
We had a discussion internally and the TAP OSS/TAP team are working through the signing bits.

TCE will pick up that **signed** binary to ship in our distribution.

**Comment by joshrosso** [comment]
Who from the TAP team owns bringing this plugin in @kartiklunkad26?

From our end, @dvonthenen owns the work item of ensuring it gets bundled in a release.

Note that having this plugin available for us to include must be done by `3/18`.

**Comment by heyjcollins** [comment]
Hey @joshrosso  - @atmandhol and I own bringing the plugin in.

**Comment by joshrosso** [comment]
@heyjcollins, thanks. I've removed @rashedkvm as an owner and added you.

@kartiklunkad26, FYI for this switch.

> I don't see the package listed [here](https://github.com/vmware-tanzu/community-edition#packages) so wondering if cartographer is part of TCE or will be shortly?

That's because it will **not** be added to the TCE package repository until `v0.11.0`. Do you need a `v0.11.0` repo, containing Cartographer, available before the release? If so, @seemiller can generate you a `v0.11.0-pre` repo to use.

**Comment by heyjcollins** [comment]
I’d have to defer to Atman as to whether we need a catographer pre repo.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by joshrosso** [comment]
@heyjcollins and @atmandhol, we went ahead and pushed this pre-release repo.

Details: https://github.com/vmware-tanzu/community-edition/issues/3350#issuecomment-1061247728

**Comment by kartiklunkad26** [comment]
@heyjcollins Cartographer is already merged in, and will be available by the time Tanzu Apps CLI Plugin is there in TCE too.

**Comment by cmoulliard** [comment]
To support fully the Workload CRD (= using Tanzu apps), it will also be needed to package part of TCE the Service Binding Operator, Service Toolkit in order to allow to set up a Service claim - see [here](https://github.com/vmware-tanzu/cartographer/blob/main/pkg/apis/v1alpha1/workload.go#L143-L145)

**Comment by kartiklunkad26** [comment]
Some of those capabilities will not be supported in the initial release of Tanzu Apps CLI Plugin.

**Comment by heyjcollins** [comment]
@kartiklunkad26 @joshrosso - 
It's very unlikely we're going to make the March 18th target for including the apps plugin in the next TCE release.
Delivering a signed `apps` Tanzu CLI binary for TCE distribution is a top priority for my team however we're currently blocked by the provision on a "caymonization" repo (the provisioning request ticket has been submitted and we're in a holding pattern 'till the repo is provided).
Once the cayman repo has been provided, we'll be unblocked to complete the remaining work, but even if we get clear of the blocker today, it's not likely we'll be able to complete the remaining work under the deadline.

**Comment by dvonthenen** [comment]
Please ping me directly if you have any questions about the signing process.

**Comment by kartiklunkad26** [comment]
@heyjcollins @jorgemoralespou had a couple of questions: 
1. What will happen if the user does not have Cartographer or App Toolkit packages installed, and tries to use the tanzu apps CLI plugin? How will it handle the failure to not have the Workload object CR in the cluster? 

2. Is this plugin context-aware today? 

cc: @atmandhol @rashedkvm

**Comment by rashedkvm** [comment]
> What will happen if the user does not have Cartographer or App Toolkit packages installed, and tries to use the tanzu apps CLI plugin? How will it handle the failure to not have the Workload object CR in the cluster?

API Error name:tanzu apps  error:no matches for kind "Workload" in version "carto.run/v1alpha1"

> Is this plugin context-aware today?

Apps plugin is installed as standalone and not context-aware yet

**Comment by rashedkvm** [comment]
> I would expect there to be some control on the plugin side so that a nice message could be displayed to the user saying something like "You don't have TAP/AppToolkit installed on your cluster. Please proceed to install it before using this plugin" or similar.

I agree with your thoughts @jorgemoralespou. We should be friendly to the users. It is a simple fix to update the message for such a condition. I would love to get feedback from UX folks @danfein regarding the message text.

cc: @heyjcollins @atmandhol

**Comment by joshrosso** [comment]
@dvonthenen with rc2, can we close this out?

**Comment by dvonthenen** [comment]
yup, we can!!
