### ISSUE TITLE
[Docs] [](/docs/latest/workload-clusters/) Workload cluster setup instructions polishing

### ISSUE THREAD

**Issue by ciberkleid** [vmware-tanzu/community-edition#2698]
## Description

1. Duplicate links:
As shown below, the docs contain links to the workload cluster templates for each IaaS, and the links in the paragraph and the bullets are the same. Feels like duplicated info that could be condensed.

Page: https://tanzucommunityedition.io/docs/latest/workload-clusters

Excerpt:
```
To deploy a workload cluster, you create a configuration file. You then run the tanzu cluster create command, specifying the configuration file in the --file option. To see an example of a workload cluster configuration file template, see AWS Workload Cluster Template, Azure Workload Cluster Template, or vSphere Workload Cluster Template.

For specific configuration parameters, see:

AWS Workload Cluster Template
vSphere Workload Cluster Template
Microsoft Azure Workload Cluster Template
```

2. What config file to key off of:
Also, right after the reader is referred to these templates, they are instructed not to use them at all:
```
Copy the configuration file: When you deploy a workload cluster, most of the configuration for the cluster is the same as the configuration of the management cluster. The easiest way to obtain an initial configuration file for a workload cluster is to make a copy of the management cluster configuration file and to update it.
```

3. Clarify wording:
The section below talks about deploying workload clusters to namespaces in the management cluster. While this makes sense, there is an implicit assumption that the reader understands this refers to cluster.cluster.x-k8s.io CRD that will precipitate the provisioning of an actual workload cluster via ClusterAPI. If the reader is not clear on this, they may be confused by the phrasing of "deploying clusters to namespaces".

```
Create namespaces: To help you to organize and manage your development projects, you can optionally divide the management cluster into Kubernetes namespaces. You can then use Tanzu CLI to deploy workload clusters to specific namespaces in your management cluster. For example, you might want to create different types of workload clusters in dedicated namespaces. If you do not create additional namespaces, Tanzu Community Edition creates all workload clusters in the default namespace. Complete the following steps:
```

4. Typo:
On this page it says `kubectl create -foo`, which I think is supposed to be `kubectl create ns foo`
Right after that it says `kubectl get namespaces --show-labels` but doesn't mention what to look for in the labels (aka why not just `kubectl get namespaces` - what are the docs calling our attention to in the labels?)

Step 8—"Optional: Deploy a workload cluster in a specific namespace"— is interesting because it says that you must set env var NAMESPACE to install the cluster to the desired namespace. Does that mean that targeting the desired namespace in kube context is not enough, meaning that tanzu CLI will not pick up that information from the context?

Also:
I can see the value of copying the management cluster config file, but in the simplest form, it seems unnecessary since the only mandatory setting (CLUSTER_NAME) is superseded by a command line argument. If that is the only thing that is changing, you could just use the management cluster config file. Or if you want to change the namespace as well, the following would suffice:
`NAMESPACE=foo tanzu cluster create foo-workload-cluster --file /Users/somebody/.config/tanzu/tkg/clusterconfigs/abc1234567.yaml` (using the management cluster config file, not a copy of it).
This can also be used with --dry-run to generate declarative configs per cluster.
I'm not advocating that this is advisable over creating a values yaml file per workload cluster, just that the section could start with an example of the simplest command and then explain why/when it is advisable to actually have a values file per cluster.

Lastly - not sure about the importance of the following two but perhaps worth mentioning:
I wonder if there's value in relating the results of `tanzu get cluster xxx` to `kubectl get cluster xxx` or `kubectl get cluster,KubeadmControlPlane,AWSCluster` and any other resources created.
Also, a screenshot perhaps of EC2 instances in AWS console?

## Location

https://tanzucommunityedition.io/docs/latest/workload-clusters

**Comment by kcoriordan** [comment]
@ciberkleid thanks for feedback, I'll get get the updated doc in a PR for review

**Comment by kcoriordan** [comment]
@ciberkleid 
**1** - removed duplication
**2** - the templates are there as a reference
3 **- what change do you suggest here ?**
**4**- fixed the typo and expanded description

**step 8** - yes that is my understanding

**Also**
An experienced user might see the value of just using the management cluster config file to create the workload cluster with out taking a copy, but I think it would be confusing for a new user, it's better to break out the config files. This is the approach that is used in the [Getting Started guide ](https://tanzucommunityedition.io/docs/latest/getting-started/) step 17 and also in the TKG documentation.

**Comment by kcoriordan** [comment]
@ciberkleid - can you take a look here at the updated topic, and let me know if you have any other suggestions
https://deploy-preview-2782--quirky-franklin-8969be.netlify.app/docs/latest/workload-clusters/

**Comment by ciberkleid** [comment]
1 - looks good
2 - I guess I would move that reference info to the place where it is needed further down where it says `Make a copy of the management cluster configuration file and save it with a new name`. As is the docs says `Copy the configuration file:` in one place, then again `Make a copy of the management cluster configuration file` lower down. I would remove one of the instructions to copy the file, and probably put the references to which file to copy with the instruction.
3 - How about this:
```
Create namespaces: To help you to organize and manage your development projects, you can optionally divide the management cluster into Kubernetes namespaces. You can then use Tanzu CLI to deploy **workload cluster configurations** to specific namespaces in your management cluster. For example, you might want to create different types of **workload cluster configurations** in dedicated namespaces. If you do not create additional namespaces, Tanzu Community Edition creates all **workload cluster management resources** in the default namespace. 
```
and
```
Optional: Deploy a workload cluster in a specific namespace. If you have created namespaces, you can deploy **workload cluster configurations** to those namespaces by specifying the NAMESPACE variable. If you do not specify the NAMESPACE variable, Tanzu Community Edition places **cluster management resources** in the default namespace. 
```
Just an option... I'm sure one can argue for or against this change very easily :)
4. I think the fix here is just to add "ns " to the original command, not necessarily to remove foo. I am not sure what the file is in this command: `kubectl create -f <NAMESPACE-FILE>`. (I mean, I can guess it means create a declarative Namespace resource file, but the first time I read it I searched the rest of the page to see where the instructions ere for creating the file). I think it leaves more work to the reader than necessary. Using foo is probably simpler, just instead of `-foo` it should be `ns foo` or `ns dev-workload-clusters` or something like that. I think I would also say `For more information on Kubernetes namespaces,...` if that link is included.

Hope that helps!! Appreciate you hearing my input :)

**Comment by kcoriordan** [comment]
2. Ya makes sense. done
3  I'll leave as is, I don't really see a distinction between saying  'deploy workload clusters' versus 'deploy workload cluster configurations'. 
4. done

Let me know if you any other comments.
thanks
