### ISSUE TITLE
Rename new standalone to unmanged-cluster

### ISSUE THREAD

**Issue by qnetter** [vmware-tanzu/community-edition#2704]
## Feature Request

For consistency's sake as well as the ability to have both the new and the old features installed simultaneously, please nename the new plugin in code and doc.

**Comment by joshrosso** [comment]
Per the conversation in [the proposal](https://github.com/vmware-tanzu/community-edition/issues/2266), we're moving forward with the name `unmanaged-cluster`. We should do this re-naming as part of our `0.10.0` release.
