### ISSUE TITLE
Add deprecation notice to standalone-cluster plugin

### ISSUE THREAD

**Issue by qnetter** [vmware-tanzu/community-edition#2705]
## Feature Request

Add a notice at plugin invocation that standalone-cluster is deprecated in this release, pointing to the doc for static-cluster (if #2704 is implemented too)

## Describe alternatives you've considered

If we don't crack the release open, it could judst silently disappear in 0.11, but this would be better.

**Comment by qnetter** [comment]
Deprecation message should read. something like:

NOTICE: the standalone-cluster plugin and feature are deprecated in this release, and will be remove in v0.11.0. Please see <URL> for the replacement static-cluster feature and how to install it in this release.

**Comment by jpmcb** [comment]
This was done as part of https://github.com/vmware-tanzu/community-edition/pull/2504

```
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Warning - Standalone clusters will be deprecated in a future release of Tanzu Community Edition
                                  Use at your own Risk
                   Checkout the proposal for the standalone cluster replacement:
                   https://github.com/vmware-tanzu/community-edition/issues/2266
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
```

Is that good enough? Or do we want to change that before it goes out? Just let me know @qnetter!

**Comment by qnetter** [comment]
Let's be explicit that it is deprecated in this release (0.10) and will be removed and replaced with the new one in 0.11.

**Comment by joshrosso** [comment]
Given how much we've gone back and forth with thing, i wonder if **not** coding exactly when it will be replaced would be sensible? How about something like:

```
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Warning - Standalone clusters are deprecated and will be removed in a future release
                                  Use at your own Risk
                   Visit the following proposal to learn about the planned replacement:
                   https://github.com/vmware-tanzu/community-edition/issues/2266
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
```

**Comment by qnetter** [comment]
Let’s go with “near-future” - I want  to create a sense of urgency.

Sent from my iPhone

On Dec 10, 2021, at 10:23 AM, joshrosso ***@***.***> wrote:

﻿

Given how much we've gone back and forth with thing, i wonder if not coding exactly when it will be replaced would be sensible? How about something like:

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Warning - Standalone clusters are deprecated and will be removed in a future release
                                  Use at your own Risk
                   Visit the following proposal to learn about the planned replacement:
                   https://github.com/vmware-tanzu/community-edition/issues/2266
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!


—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fvmware-tanzu%2Fcommunity-edition%2Fissues%2F2705%23issuecomment-991195130&data=04%7C01%7Crklorese%40vmware.com%7Ca0b87b8740a249b6235b08d9bc0a32fa%7Cb39138ca3cee4b4aa4d6cd83d9dd62f0%7C0%7C0%7C637747574263972758%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=lZR%2Ft2bat1x2OO9q3ChP%2BuICTBlvhQNKp9qp6kvXb1U%3D&reserved=0>, or unsubscribe<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FACZWVL5JON3JFCLJTOIGG2LUQJAS7ANCNFSM5JXZOOCA&data=04%7C01%7Crklorese%40vmware.com%7Ca0b87b8740a249b6235b08d9bc0a32fa%7Cb39138ca3cee4b4aa4d6cd83d9dd62f0%7C0%7C0%7C637747574263982712%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=dFbRwKdkcSz06HEjWtoMpZueSEh35xApCy1dZ%2FBjZ5M%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Crklorese%40vmware.com%7Ca0b87b8740a249b6235b08d9bc0a32fa%7Cb39138ca3cee4b4aa4d6cd83d9dd62f0%7C0%7C0%7C637747574263982712%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=LUmtIgOq75GMDJfoeHZTxJnCb2iZxm9ioJytJqXhD%2Fc%3D&reserved=0> or Android<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Crklorese%40vmware.com%7Ca0b87b8740a249b6235b08d9bc0a32fa%7Cb39138ca3cee4b4aa4d6cd83d9dd62f0%7C0%7C0%7C637747574263992666%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=H1tLlMPRWcxVvw91cm%2BpkNGzRteiiw31xs%2F6%2FrV6%2FxU%3D&reserved=0>.

**Comment by jpmcb** [comment]
Cool! So, something like?
```
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Warning - Standalone clusters are deprecated as of 0.10.0 and will be removed in a near-future release
                                        Use at your own Risk
                         Visit the following proposal to learn about the planned replacement:
                         https://github.com/vmware-tanzu/community-edition/issues/2266
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
```

**Comment by qnetter** [comment]
Exactly.

**Comment by stmcginnis** [comment]
This has been addressed.
