### ISSUE TITLE
What should I do next？

### ISSUE THREAD

**Issue by xiaoxiangxzhang** [vmware-tanzu/community-edition#2706]
I want to create Local Docker Clusters according to https://tanzucommunityedition.io/docs/latest/getting-started/
after I carry out this  command
tanzu management-cluster create --ui
display 
Failure while deploying management cluster, Here are some steps to investigate the cause:

Debug:
    kubectl get po,deploy,cluster,kubeadmcontrolplane,machine,machinedeployment -A --kubeconfig /home/test/.kube-tkg/tmp/config_6SDG31q1
    kubectl logs deployment.apps/<deployment-name> -n <deployment-namespace> manager --kubeconfig /home/test/.kube-tkg/tmp/config_6SDG31q1

To clean up the resources created by the management cluster:
          tanzu management-cluster delete
unable to set up management cluster, : unable to wait for cluster and get the cluster kubeconfig: error waiting for cluster to be provisioned (this may take a few minutes): timed out waiting for cluster creation to complete: [cluster control plane is still being initialized, cluster infrastructure is still being provisioned]

I don't what to do next?

**Comment by stmcginnis** [comment]
Hi @xiaoxiangxzhang. There are a few issues with Docker support right now to be aware of. Here are some things to check.

## Cgroup support

We currently only support cgroups v1, but newer versions of Docker Desktop and newer Linux distros are starting to ship with cgroups v2 enabled. To check, you can run the following from the command line:

```sh
$ docker system info | grep Cgroup
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
```

The "Cgroup Version" listed should match the above and show a value of "1". If it says "2", then you would need to revert back to v1. I don't have docs handy on how to do that, but we can track that down if needed.

## Memory and CPU

Another common issue is not enough resources being available that causes problems spinning up the necessary containers. We recommend at least 4-6G of RAM and 2 CPU cores (though more is obviously better).

```sh
$ docker system info | grep -i -E 'cpu|memory'
 CPUs: 4
 Total Memory: 5.807GiB
```

If using Docker Desktop, you would need to go Preferences > Resources to allocate more resources and restart the Docker Engine for the changes to take effect.

## CAPD logs

If it's neither of the above, it's possible something else is causing a problem and we need to take a look at the CAPD (cluster API provider Docker) logs to see what is failing.

This section in the docs walks through connecting to the container to stream the logs:

https://tanzucommunityedition.io/docs/latest/tsg-bootstrap/#troubleshooting-manually

Look for any lines that start with `E` to see actual errors. There will be other failure messages in the logs, but if they don't start with `E` then they are just "normal" reconciliation failure messages. The relevant messages for figuring out what is having an issue will be the lines starting with the `E` to indicate actual errors.

## Alternatives

If all else fails, or if you would like to try where we are going with Docker clusters, there is this proposal:

https://github.com/vmware-tanzu/community-edition/issues/2266

That is only for the standalone cluster model though, not the management and workload clusters model you are following now. But depending on your needs, that maybe could work for you.
