### ISSUE TITLE
Report metrics on all infrastructure providers for managed and standalone

### ISSUE THREAD

**Issue by jpmcb** [vmware-tanzu/community-edition#2709]
## Feature Request

Today, we report metrics for standalone cluster creation and deletion times via the [`tce.pr.standalone-cluster.create-time`](https://github.com/vmware-tanzu/community-edition/blob/main/.github/workflows/check-main.yaml#L91) and the [`tce.pr.standalone-cluster.delete-time`](https://github.com/vmware-tanzu/community-edition/blob/main/.github/workflows/check-main.yaml#L127) which run off the main branch after a merge. We cannot run these jobs in the actions off of forks (inside PRs) since they require the wavefront API secret.

These metrics are also documented in the [`METRICS.md`](https://github.com/vmware-tanzu/community-edition/blob/main/METRICS.md) document.

But we also have github actions for running clusters on AWS, Azure, vSphere, etc. We should report metrics for all infrastructures for both standalone and managed.

Reporting metrics to wavefront is super simple. Example from the `check-main` job:
```bash
GIT_SHA=$(git rev-parse HEAD)
TCE_VERSION=$(git describe --tags --abbrev=0)
echo "tce.pr.standalone-cluster.create-time ${{ needs.create-cluster.outputs.create-cluster-time }} source=<tce.github.${{ github.event.number }}> sha=${GIT_SHA} version=${TCE_VERSION}" | curl \
  --header "Authorization: Bearer ${{ secrets.VMW_WAVEFRONT_API_TOKEN }}" \
  --data @- \
  https://vmware.wavefront.com/report
```
This is [doing "direct ingestion"](https://docs.wavefront.com/direct_ingestion.html) which enables us to not have to run a wavefront ingestion engine, but rather, simply push the metrics to `wavefront.com/report` _directly_ with an API key. _**Note:**_ `VMW_WAVEFRONT_API_TOKEN` is one of our repository secrets _and should be kept secret._

This would also require building panels for these in the WaveFront dashboard.

And finally, this would also require that the `METRICS.md` document be updated with the current metrics we use.

## Describe alternatives you've considered

N/A - reporting metrics requires little computing overhead and we should take advantage of monitoring for feature regression.

**Comment by dvonthenen** [comment]
cc: @vmware-tanzu/tce-releng

**Comment by jpmcb** [comment]
Hi @vmware-tanzu/tce-releng - let me know if there's anything here I can help with!

**Comment by joshrosso** [comment]
This would be cool, but moving to v0.12.0

**Comment by joshrosso** [comment]
Assigning this to @karuppiah7890 to assess.

@karuppiah7890 feel free to let us know if this is feasible for the `v0.12.0` timeframe. It is more of a "nice to have".
