### ISSUE TITLE
Make TCE WaveFront dashboard public

### ISSUE THREAD

**Issue by jpmcb** [vmware-tanzu/community-edition#2710]
## Feature Request

Today, we report cluster creation and deletion times to an internal WaveFront dashboard, a VMware observability platform.

We should make the dashboard public for the community to see.

## Describe alternatives you've considered

There are other public observability tools, like Grafana, but WaveFront is more than capable of visualizing public data. And we should report this data into the public so users and contributors can evaluate the feature times of TCE clusters.

## Additional context

This would mostly require some internal implementation to get VMware to provision a public dashboard.

**Comment by dvonthenen** [comment]
cc: @vmware-tanzu/tce-releng

**Comment by jpmcb** [comment]
@vmware-tanzu/tce-releng Happy to provide any support here or help dig into this!

**Comment by joshrosso** [comment]
Would be cool, but moving this out to v0.12.0.

**Comment by joshrosso** [comment]
Moving this over to @karuppiah7890 for v0.12.0. Feel free to let us know whether this is feasible. If not, we can move it out to a further milestone. This one is much more of a "nice to have"
