### ISSUE TITLE
Ability to SSH into hosts/nodes

### ISSUE THREAD

**Issue by alexnaris** [vmware-tanzu/community-edition#2711]
## Description

Tanzu Community Edition is missing documentation on how to ssh into hosts/nodes

## Location

Administration

**Comment by stmcginnis** [comment]
Good call!

@kcoriordan - I think there are some TKG docs on this already? I'm guessing it will be easy to port over the the TCE docs. At least I hope so. ;)

**Comment by alexnaris** [comment]
Hello again!  All the documentation I have seen has to do with Tanzu grid and vsphere cli.. 

Tanzi Community Edition does rely on ssh key being present and used during installation.  

```
Download and import the OVF image and covert it to a template.
Create a ssh key pair and provide the public key part of the SSH key pair to Tanzu Installer.
```

That leads me to think that sshing to a host would as simple as specifying the correct username along with the keys used during the installation.  However, so far I have not been successful... probably because I am not able to guess the username.

**Comment by kcoriordan** [comment]
I'll something into doc PR for this.

**Comment by alexnaris** [comment]
thank you.  Using "capv" as the user allows SSH'ing into nodes
