### ISSUE TITLE
A mistake at the usage example of Load Balancer Operator 

### ISSUE THREAD

**Issue by ChunPingWang** [vmware-tanzu/community-edition#2714]
I followed the document of the Load Balancer Operator which is the ako-operator/1.5.0 to do a workshop with the customer and hit an issue. 
The URL of the image at harbor-repo.vmware.com/dockerhub-proxy-cache/library/nginx doesn't correct.

Please check this page.
https://github.com/vmware-tanzu/community-edition/tree/main/addons/packages/ako-operator/1.5.0/README.md

**Comment by kcoriordan** [comment]
@seemiller 
@HanFa
@XudongLiuHarold 

do you have the correct url?

**Comment by XudongLiuHarold** [comment]
/assign @HanFa 

Could you please take a look at this?

**Comment by HanFa** [comment]
Yes, taking a look now

**Comment by HanFa** [comment]
Hi @ChunPingWang I am able to pull down and run `harbor-repo.vmware.com/dockerhub-proxy-cache/library/nginx ` at my local kind cluster. Could you double check the cluster connectivity on your side?
