### ISSUE TITLE
Add Cluster API Provider "Bring Your Own Host" into the TCE Fold

### ISSUE THREAD

**Issue by Vijayakumar0328** [vmware-tanzu/community-edition#2721]
## Feature Request

This is more of the feature request to align **[Cluster-api-provider-BringYourOwnHost](https://github.com/vmware-tanzu/cluster-api-provider-bringyourownhost) into TCE.** 

**Intention is to enable users/community to use TCE on Bare Metal infrastructures​**

BYOH is a Cluster API v1beta1 Infrastructure Provider for already-provisioned hosts running Linux

We will add more details here as we proceed.

**Comment by joshrosso** [comment]
@Vijayakumar0328 sounds great! 

Looking forward to seeing a proposal on how we can approach this. Let us know how we can help.

**Comment by joshrosso** [comment]
This was never followed-up on.
