### ISSUE TITLE
Add a Supported Providers section to all packages

### ISSUE THREAD

**Issue by qnetter** [vmware-tanzu/community-edition#2725]
## Description

Some packages list the CAPI providers supported (and not). Please add one for consistency to all pages, even if all providers are checked.

## Location

Packages section in left nav

**Comment by joshrosso** [comment]
Moving this out to `v0.11.0`.

**Comment by kcoriordan** [comment]
These are the ones missing the Supported Provider table, if you provide the details here I can get a PR in for this
Fluent Bit ¶ @seemiller 
gate keeper @seemiller 
Grafana @seemiller 
Knative Serving @seemiller 
Multus CNI @seemiller 
Prometheus @seemiller 
Whereabouts @zhanggbj

**Comment by seemiller** [comment]
Fluent Bit, Gatekeeper, Grafana, Knative-serving, Prometheus should work with all providers

Multus CNI - not confident, but I think it works on AWS, Azure and vSphere - not sure about Docker
