### ISSUE TITLE
Improve visibility into management and workload cluster creation

### ISSUE THREAD

**Issue by stmcginnis** [vmware-tanzu/community-edition#2730]
# Abstract

Our current bootstrapping process emits a lot of output, but it's very hard to follow what is happening. Even if you understand the overall process of deployment, parsing the output can be confusing, and it's not very clear where in the deployment process we are.

When deployment takes awhile, it's hard to tell if things are locked up or if there's something happening under the covers that we are waiting to complete.

When the deployment does fail, it's not always clear what caused the failure. We only give generic troubleshooting steps that may not even be relevant to the failure they are encountering.

**Current Issues:**

Current cluster bootstrap process is very noisy, with a lot of output that is not meaningful to the user and can be potentially confusing:

![image](https://user-images.githubusercontent.com/3922475/146276861-ef6e47fa-e6a7-4697-a3ff-0c34de30b569.png)

There are a few problems with this output:

1. There is no formatting (or a mix of formatting)
2. High level steps are not clear from low level steps being taken
3. It's hard to tell what is relevant to pay attention to, versus what can be ignored
4. Not clear what step is being done and how far along in the process it is
5. When things go wrong, not clear what the cause of the failure is
6. Not clear what the user needs to do to resolve the problem
7. Not clear if there is cleanup that needs to be done before trying again

## Issue Tracking

The following list tracks the issues required to resolve in order to achieve this capability. Please see the next section to understand the larger proposal.

### Tanzu Framework

- https://github.com/vmware-tanzu/tanzu-framework/issues/1524
- https://github.com/vmware-tanzu/tanzu-framework/issues/1662
- https://github.com/vmware-tanzu/tanzu-framework/issues/1663

### Community Edition

- TBD

### Other

- TBD

## Proposal

- [Pull Request](https://github.com/vmware-tanzu/community-edition/pull/2769)
- [Rendered View](https://github.com/vmware-tanzu/community-edition/blob/3a2ca013945b7aa0eb48a5fe0c74ced737b0b64c/docs/designs/2730-visibility.md)

**Comment by stmcginnis** [comment]
cc @garrying

**Comment by joshrosso** [comment]
Thanks for bootstrapping this @stmcginnis. Looking forward to the design doc. Here are some ideas that come to mind, worth considering:

1. 💯 to your common on capx-manager holding the key to failures. The logs from these would surely be too noisy to print at default verbosity, however, I think always writing those logs to a bootstrap log file and outputting to the user its available during bootstrap would be extremely high value.
    ```txt
    Creating management cluster in ${INFRASTURCTURE_PROVIDER}
        View bootstrap logs at: ${HOME}/.config/tanzu/tkg/bootstrap-logs/${CLUSTER_NAME}.log
    ```
    1. At a higher-verbosity, we just tail those logs to `stdout` as well.
1. This proposal should break down the bootstrap visibility for management and workload clusters. I forsee these two looking quite different. In other words, i care about different things, like for my workload cluster, I want to understand what TKR was selected, CNI, etc -- not too dissimilar from our *new* standalone model.

**Comment by garrying** [comment]
This is great @stmcginnis! The high-level changes resonates with me. Happy to help start the design doc.

**Comment by joshrosso** [comment]
[RFC open](https://groups.google.com/g/tanzu-community-edition/c/EC0qddRdJzI), initially targeting closure on `02/04/2022`.

**Comment by DennisFaucher** [comment]
What about something similar to what Linux distros use for installation? A simple screen with one line the describes the current activity and the progress speedometer of that activity. The activity can be expanded to show detail if needed. Does not need to be a GUI, can be ascii/curses/whatever-based
![fedora_progress](https://user-images.githubusercontent.com/9034190/151992037-6e989db9-19c7-4051-aa59-c62f7f183c76.png)

**Comment by stmcginnis** [comment]
Great idea @DennisFaucher. That's a slightly different approach from what is being proposed here, but I could see that as a great follow on. If we make the updates proposed in the design doc, the UI could read those and update the output like the example you show. Then there could be a "Details" expander or something that would give the full output.

What do you think @miclettej ?

**Comment by joshrosso** [comment]
> Great idea @DennisFaucher. That's a slightly different approach from what is being proposed here, but I could see that as a great follow on. If we make the updates proposed in the design doc, the UI could read those and update the output like the example you show. Then there could be a "Details" expander or something that would give the full output.
> 
> What do you think @miclettej ?

I agree that it's a great suggestion :tada: , but something we should consider for larger UI work and keep this proposal scoped to giving bootstrap log visibility.

For our future consideration, how do a progress UI like this differ from the kickstart UI?

![image](https://user-images.githubusercontent.com/6200057/151994999-e453e12c-a120-48c3-abbf-6e59c03ee9f5.png)

**Comment by miclettej** [comment]
To Josh's point, we have something like this in the UI but may need to adjust the granularity of steps or filtering of logs. What we know from customers is that they like to know what stage of the deployment they are on, and what is remaining to complete. The step progress on the left was added in response to customer feedback. We can adjust appearance or granularity of steps/messaging to the customer. I think it may be important to continue to show some indication of steps that are completed and not yet completed.

**Comment by DennisFaucher** [comment]
So long team and thanks for all the fish. TCE was great.
