### ISSUE TITLE
Define guidelines for package contribution and maintenance 

### ISSUE THREAD

**Issue by joshrosso** [vmware-tanzu/community-edition#2736]
# Package Maintainership

* See Also:
    * [Pull Request](https://github.com/vmware-tanzu/community-edition/pull/2737)
    * [Rendered View](https://github.com/vmware-tanzu/community-edition/blob/package-maintainer-proposal/docs/designs/2736-package-maintainership.md)

## Summary

A key feature of Tanzu Community Edition (TCE) is packages. Packages extend and enhance the functionality provided by TCE. There are numerous guides and walk-throughs for creating packages. However, there are no guidelines for maintaining a package. There are also no guides for how a package can be considered for inclusion into the TCE package repository. This proposal is to create and host the documentation to outline what it means to create, own and maintain a package.

## Motivation

Carvel packages are relatively new to the Kubernetes ecosystem. Being new, there is not a lot of existing documentation or experience with packages. It is relatively easy and straightforward to create a package. But what constitutes a _minimum viable package_ that could be distributed by TCE? Should a package be documented? Tested? Who handles the support? When will new versions of a package be released?

We need to provide process and documentation for the community to use and reference regarding packages and their association with TCE. Created a package and want TCE to include it, is it tested? Or licensed? End users who wish to submit a package to TCE should know that it needs to be supported. What happens if a CVE is discovered in a base image used by that package?

There are numerous situations, scenarios and questions that we need to have addressed so that the community knows how to successfully create, submit and maintain package within the TCE ecosystem. 

### Goals

With the implementation of this proposal, we will provide the following:

* Definition of roles/personas involved
* Process to create minimum viable package for TCE
* Process to submit a package for inclusion in TCE
* Establish expectations for package maintenance
* Create a documentation site to host package maintainer docs.

The end goal is that a community member should be able to review a documentation site and have all the information necessary to create, submit and maintain a package. A mockup of such a site is as follows:

<img width="1338" alt="Screen Shot 2022-01-21 at 3 46 43 PM" src="https://user-images.githubusercontent.com/5900/150611803-ca227a9a-34cb-4ca4-b787-e2ff0990dea7.png">

### Non-Goals/Future Work

* Implementing any proposed CI, tests, checks, linters
* Implementing any automation around established processes

### Documentation

Documentation needs to be written that covers various aspects of packages within the TCE ecosystem. A rough outline of sections to be covered follows.

* Roles

  Defining the roles in the packaging processes. The four roles that have been identified at this point are:

  * Owner 
  * Creator
  * Maintainer
  * End User

* Package Creation Process

  There are numerous guides covering the topic of how to create a package. A package creator is free to develop a package as they see fit. However, to be considered for inclusion in TCE, a set of requirements will need to be met. These requirements will define a minimum viable package and show how to create a package.  

    * High level overview of the creation process
    * Carvel Tools
    * OCI Registry
    * Directory structure
    * Package documentation and usage/examples
    * Metadata
    * Unit tests
    * End-to-End tests
    * Licensing
    * Base image restrictions

* Request for Inclusion in TCE Package Repository

    Document the process for submitting a package for inclusion in the main TCE package repository.

* Package Maintenance

    Once a package has been created and accepted into TCE it must be maintained. The expectations of maintaining a package need to documented and include at a minimum the following.

    * Community support
    * Operational issues, enhancements and bugs 
    * Version updates
    * Security and CVE response
    * Metadata
    * Orphaning
    * Retirement

### Hosting

This documentation should be hosted separate from the existing package documentation, with its own look and feel to differentiate it. Ideally, a subdomain could be used for direct access, something like `maintainers.tanzucommunityedittion.io`.

## User Stories

* Package Creation

  Joe Engineer has just completed writing his Foo-tastic software that provides the Foo capability to Kubernetes clusters. Being an avid TCE fan, Joe wants to create a package that allows for easy installation and customization of Foo-tastic to TCE. Joe reads up on how to create a package from the TCE documentation. Joe then sets about creating a package that includes the Foo-tastic software. He is able to create a Schema and overlays that will allow users to customize the installation of the software. End to end tests are written to show that the package works as intended and a unit test is provided for a tricky ytt template. Finally Joe pushes the package to an OCI registry so that it is available to others  

* Package Submission to TCE

  Having created the Foo-tastic package, Joe wants it included in the main TCE package repository. Joe comes to the TCE documentation and finds the section for writing a proposal to include his third party package. Joe is able to submit the necessary documentation as outlined in the Submission process. The proposal to add Foo-tastic package is reviewed by the TCE team and is approved. Foo-tastic is added to the package repository.

* Package Maintenance

  A critical security CVE is released for the base container image that is used in Foo-tastic. Joe sees that according to the package mantainership documents that he is required to release a new version of the Foo-tastic package when the base image CVE has been patched.

**Comment by joshrosso** [comment]
@seemiller the PR has largely turned into the work to complete this rather than the proposal.

Can you update this issue with details on what's being proposed:

* topics we want to cover
* audience
* how we're going to expose the information

**Comment by seemiller** [comment]
Reopening to capture desire to host these documents separate from other documentation

**Comment by joshrosso** [comment]
The proposal closed out based on work done in https://github.com/vmware-tanzu/community-edition/pull/2980.

We made a call as a project to keep this content in GitHub for the near term, reference:

https://github.com/vmware-tanzu/community-edition/tree/main/docs/packaging
