### ISSUE TITLE
Establish Tanzu Community Edition Feature Lifecycle

### ISSUE THREAD

**Issue by qnetter** [vmware-tanzu/community-edition#2738]
### Introduction
New features and capabilities for Tanzu Community Edition are initially proposed and considered through the documented proposal process. The feature lifecycle applies once a feature is accepted for initial implementation. 

Note that this lifecycle applies only to features introduced into the core of Tanzu Community Edition, or into Tanzu Framework on its behalf. Upstream projects, including Kubernetes, often have their own published lifecycles, which are similarly structured but for which the time periods and deprecation windows are likely to differ.

The lifecycle stage of Tanzu Community Edition originated features and capabilities will be indicated in product documentation, and changes will be indicated in the release notes.

The timeframes proposed here are shorter than they are for more long-lived upstream projects. This reflects the fact that one of the key roles of the Tanzu Community Edition distribution is as an innovation engine. However, as users become more dependent on it and clusters and cluster farms grow, it is possible that timeframes may be extended.

Lifecycle times are specified in months and releases. A lifecycle milestone release may be a major or minor release, but may not be a patch release unless the minor release on which it is dependent was withdrawn or never released to the public.

### Stages

The lifecycle includes the following stages:

- Alpha: Some of the basic functionality of the feature as it was proposed is implemented. The feature may be further implemented, or existing functionality may change based on feedback. If the feature is intended to have GUI support, it need not be implemented for the Alpha state. 
If the feature receives significant negative feedback in the Alpha stage, it may be deprecated in any release and removed from the following release - in other words, its deprecation window is one release or one month, whichever comes later (1/1).

- Beta: the full functionality of the MVF (minimum viable feature) from the proposal is implemented. Additional content in the proposal indicated as post-MVF may be included, but is not necessary. If there is GUI support, it must be present. Functionality is subject to improvement based on feedback, but functionality should not be removed unless there is broad community consensus that it is not needed. 
If the feature receives significant negative feedback in the Beta stage, it may be deprecated in any minor release and removed after two releases or a three-month period - in other words, its deprecation window is two releases or three months, whichever comes later (⅔).

- Stable: the functionality delivered in the Beta, potentially modified and improved by Beta user feedback, is included, accepted by the community, and fully tested. Changes to the functionality once a feature is accepted as Stable must be requested via GitHub issues and are subject to review by maintainers if relatively minor, or if major, must go through the proposal process. 
Once a feature is Stable, it is not expected to change rapidly, and users should be able to count on its being in the project code for a reasonably long period, such that they can depend on it for usage for periods that can be well accommodated by their maintenance cycles. Once a feature is accepted as Stable, it may be deprecated in a release and removed after four releases or a six-month period - in other words, its deprecation window is four releases or six months, whichever comes later (4/6).

## Describe alternatives you've considered

We had earlier considered Experimental/Stable in alignment with other projects, but now feel alignment - at least in structure - with Kubernetes is worthwhile.

**Comment by joshrosso** [comment]
@qnetter sorry for the lag on this, we'll get on it in next week's review cycle.

question that will come up:

Where do you propose we publish this information?

**Comment by qnetter** [comment]
Probably a top-level MD doc in the repo. Also in the reference guide.

**Comment by joshrosso** [comment]
> Probably a top-level MD doc in the repo.

What do you propose the MD file is called? Or would you like it added to an existing MD file?

> Also in the reference guide.

What is the the reference guide?

**Comment by qnetter** [comment]
> > Probably a top-level MD doc in the repo.
> 
> 
> 
> What do you propose the MD file is called? Or would you like it added to an existing MD file?

I'm open to ideas. We could put it up as LIFECYCLE.md, but that may be too general. We could put it in a doc lower down in the hierarchy and link it from ROADMAP.md - it would take up too much space inline. 

> > Also in the reference guide.
> 
> 
> 
> What is the the reference guide?

One of the manuals in the Documentation section of the website.

**Comment by joshrosso** [comment]
> through the documented proposal process.

We should link this.

> If there is GUI support, it must be present.

This seems like a strange statement

**Comment by jpmcb** [comment]
One thing I would like called out is how these feature lifecycles relate to the release semver, primarily when a deprecation of a stable feature happens. In my mind, that would be a major version bump (example `1.2.3 -> 2.0.0`)

**Comment by stmcginnis** [comment]
Since we are talking about lifecycle, should we call out deprecated and removed/EOL in the stages?

**Comment by nrb** [comment]
>>    If there is GUI support, it must be present.

> This seems like a strange statement

I read it as "If a feature has a GUI component, the GUI component must be present in the beta," whereas the alpha does not require the GUI component to be present.

**Comment by joshrosso** [comment]
Due to lack of follow-up and still getting our feet under us around versioning schemes, we'll close this proposal.

Let's re-open and/or revise once we've got bandwidth to evaluate where we should put this information and how to version our assets.
