### ISSUE TITLE
Fix AWS E2E test pipeline failure: NAT Gateway issue

### ISSUE THREAD

**Issue by karuppiah7890** [vmware-tanzu/community-edition#2739]
We have a new failure that I don’t think I have noticed before. An error occurred in AWS E2E test pipeline for management and workload cluster

The error occurred while creating management cluster

https://github.com/vmware-tanzu/community-edition/actions/runs/1583365456/attempts/1
- https://github.com/vmware-tanzu/community-edition/runs/4535910329?check_suite_focus=true

```
Error: unable to set up management cluster: unable to wait for cluster and get the cluster kubeconfig: error waiting for cluster to be provisioned (this may take a few minutes): cluster creation failed, reason:'RouteTableReconciliationFailed', message:'4 of 8 completed'
```

I was able to get an error message from the diagnostics data from the failed pipeline

[aws-e2e-fail-diagnostics-1.zip](https://github.com/vmware-tanzu/community-edition/files/7732214/aws-e2e-fail-1.zip)

```
E1215 16:18:36.717013       1 awscluster_controller.go:211] controllers/AWSCluster "msg"="failed to reconcile network" "error"="no nat gateways available in \"us-east-2a\" for private subnet \"subnet-01f51bf59327baa10\", current state: map[]" "awsCluster"="test-mc-9540" "cluster"="test-mc-9540" "namespace"="tkg-system" 
```

I reran the pipeline to check if it was any intermittent issue / some AWS network issue but the error occurred again. This time the error occurred while creating workload cluster

https://github.com/vmware-tanzu/community-edition/actions/runs/1583365456/attempts/2
- https://github.com/vmware-tanzu/community-edition/runs/4544087021?check_suite_focus=true

```
Error: unable to wait for cluster and get the cluster kubeconfig: error waiting for cluster to be provisioned (this may take a few minutes): cluster creation failed, reason:'RouteTableReconciliationFailed', message:'4 of 8 completed'
```

I was able to get a similar error message again from the diagnostics data from the failed pipeline

[aws-e2e-fail-diagnostics-2.zip](https://github.com/vmware-tanzu/community-edition/files/7732236/aws-e2e-fail-diagnostics-2.zip)

```
E1216 08:03:53.521835       1 awscluster_controller.go:211] controllers/AWSCluster "msg"="failed to reconcile network" "error"="no nat gateways available in \"us-east-2a\" for private subnet \"subnet-0ddc78b79b6b1bdad\", current state: map[]" "awsCluster"="test-wld-12132" "cluster"="test-wld-12132" "namespace"="default" 
```

**Comment by karuppiah7890** [comment]
To dig into the code of CAPA provider, I checked into what version of CAPA we were running and found out from the diagnostics data and from the BOM file (URL from pipeline logs) - `projects.registry.vmware.com/tce/tkg-bom:v1.4.0` that we were using `projects.registry.vmware.com/tkg/cluster-api/cluster-api-aws-controller:v0.6.6_vmware.1` CAPA container image which I think refers to CAPA `v0.6.6` but yet to confirm given there's a `_vmware.1` along with it

https://github.com/kubernetes-sigs/cluster-api-provider-aws/tree/v0.6.6

Also, the logs from the diagnostics data don't show any version when the `manager` container started, they all show empty version

```
setup "msg"="starting manager"  "version"=""
```

And looking at the CAPA code - both `main` and `v0.6.6`, the error message comes from this part of the code -

https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/4ca623be01b48cc6a28f83d600b582aa7417498e/pkg/cloud/services/network/natgateways.go#L315

It's still not clear how this happens. I'm gonna try and dig into it

**Comment by karuppiah7890** [comment]
I wasn’t able to reproduce the issue today while using my AWS account

Also noticed that the last run was fine - https://github.com/vmware-tanzu/community-edition/actions/runs/1591579190

**Comment by joshrosso** [comment]
@karuppiah7890 let us know if this is an issue with automation or our bootstrapping. Wasn't super clear reading through it. For now, putting it in the `icebox` but happy to get an engineer to support troubleshooting if it's reproducible.

**Comment by karuppiah7890** [comment]
Noticed this issue coming up again here - https://github.com/vmware-tanzu/community-edition/actions/runs/1825093144 - https://github.com/vmware-tanzu/community-edition/runs/5144653651?check_suite_focus=true , diagnostics data -
[diagnostics-data.zip](https://github.com/vmware-tanzu/community-edition/files/8079009/diagnostics-data-feb-10.zip)
