### ISSUE TITLE
Error when login to a management cluster with server endpoint .

### ISSUE THREAD

**Issue by hasaranga001** [vmware-tanzu/community-edition#2747]
## Bug Report

I'm trying to remotely log in to a management cluster using the Server endpoint and it failed (see below error message ) However, I can successfully login into the same management cluster with the kubeconfig .  (I haven't integrated AD authentication (LDAP) for this management cluster)
Also, I have tested remotely logging in to a different management cluster which has enabled LDAP and it worked (It prompted a web-based authentication for AD ). Does that mean I can only use server endpoint if we have integrated LDAP?

## Expected Behavior

Should be able to access management cluster remotely via Server Endpoint.

## Steps to Reproduce the Bug

Create a management cluster without Authentication (LDAP) integration.
Try to login to it with Server Endpoint (tanzu login)

## Screenshots or additional information and context

1st : Unsuccessful with server endpoint.
2nd : Successful with kubeconfig to the same management cluster ,       
```
PS C:\Users\lpmha> tanzu login
? Select a server + new server
? Select login type Server endpoint
? Enter server endpoint https://10.7.156.89:6443
? Give the server a name tanzuwin6
✖  Error creating kubeconfig with tanzu pinniped-auth login plugin: failed to get pinniped-info: failed to get pinniped-info from the cluster
Error: exit status 1
✖  exit status 1

PS C:\Users\lpmha> tanzu login
? Select a server + new server
? Select login type Local kubeconfig
? Enter path to kubeconfig (if any) C:\Users\lpmha\Downloads\config
? Enter kube context to use tanzuwin6-admin@tanzuwin6
? Give the server a name tanzuwin6
✔  successfully logged in to management cluster using the kubeconfig tanzuwin6

```

## Environment Details

* Build version (`tanzu version`): v0.9.1
* Deployment (Managed/Standalone cluster):  Managed
* Infrastructure Provider (Docker/AWS/Azure/vSphere):   vSphere
* Operating System (client): Tried with both Ubuntu /  Windows

## Diagnostics and log bundle
✖  Error creating kubeconfig with tanzu pinniped-auth login plugin: failed to get pinniped-info: failed to get pinniped-info from the cluster

**Comment by stmcginnis** [comment]
@ankeesler - is this something you can help with? Or @vuil, can you help route it to the right person? Thanks!

**Comment by vuil** [comment]
@prkalle can you PTAL as well?

**Comment by ankeesler** [comment]
ah i think i remember what the issue is here. that `failed to get pinniped-info from the cluster` happens when the pinniped package has not been installed on the cluster, i.e., when using `tanzu login --server https://<mgmt-cluster-addr>` we expect that the pinniped package has already been installed.

this is probably not a fair assumption on our part, and we should also give better error messages. perhaps we should open an issue in tanzu-framework to improve this 1) ux and 2) error message?

> Does that mean I can only use server endpoint if we have integrated LDAP?

so the answer is yes, as of right now, you need to have setup the pinniped package on your cluster in order to use `tanzu login --server https://<mgmt-cluster-addr>` flow

**Comment by prkalle** [comment]
I agree with @ankeesler on giving a better error message and currently `tanzu login` only works when cluster is configured with pinniped.

**Comment by stmcginnis** [comment]
Thanks everyone! I'll get a new issue opened up in `tanzu-framework` and keep this one here so we can track and make sure it gets into a TCE release.

**Comment by hasaranga001** [comment]
Thank you all for your feedback.

**Comment by jpmcb** [comment]
We'll use this issue to track https://github.com/vmware-tanzu/tanzu-framework/issues/1444

Thanks again for bringing this to our attention!

**Comment by thesteve0** [comment]
I know we are tracking in the other bug so is it ok for this to get stale.
