### ISSUE TITLE
Update maintainers for vsphere-cpi

### ISSUE THREAD

**Issue by mcwumbly** [vmware-tanzu/community-edition#2749]
I believe the maintainers list for the vsphere-cpi is out of date. This should be updated:

https://github.com/vmware-tanzu/community-edition/blob/5b8537e2c64b902553b57956af0ba650b18b2387/addons/packages/vsphere-cpi/metadata.yaml#L10-L13

Perhaps it should be sync'd with this member list?
https://github.com/orgs/vmware-tanzu/teams/pkg-vsphere-cpi-owners/members

Not sure if that list is up to date, but it looks closer to me...

cc @vmware-tanzu/pkg-vsphere-cpi-owners

**Comment by joshrosso** [comment]
Resolved based on #2756
