### ISSUE TITLE
Unable to deploy TKG 1.4 on vSphere 7, getting stuck at "Start creating management cluster." init.go line 202

### ISSUE THREAD

**Issue by hsduiii** [vmware-tanzu/community-edition#2751]
I just cant deploy TKG, i tried everything and im always getting the same error, dhcp is ok, ssh public key is ok, DRS is enabled, also HA, i have docker, kubectl, tanzu cli installed in bootstrap machine, i created a user with the required permissions. It always fails at Creating management cluster step. It makes no changes in vSphere but does create the cluster in the boostrap machine.

![imagen](https://user-images.githubusercontent.com/37885943/147142899-056ae1c3-5b48-4c1f-8eeb-8e9127d2949d.png)

![tanzu_error](https://user-images.githubusercontent.com/37885943/147143241-6c237f0f-0350-480e-ae78-33d3692fc25b.PNG)

**Comment by stmcginnis** [comment]
Hi @hsduiii  - TKG is a commercially supported product. I would recommend you contact support for help resolving this issue.

**Comment by hsduiii** [comment]
:V okok, thanks!

**Comment by stmcginnis** [comment]
One thing that may help (I'm fairly sure it would be the same) from the TCE docs would be the [Troubleshooting manually](https://tanzucommunityedition.io/docs/latest/tsg-bootstrap/#troubleshooting-manually) section.

Most of the times that I've seen bootstrap failures, I've been able to see what was actually going on by tailing the logs from the capv-controller pod. There will be a lot of failure messages as it does its normal reconciliation loops, but anything where the line starts with an `E` might be a clue to a legitimate failure in something the provider is trying to do.

**Comment by hsduiii** [comment]
Thanks a lot @stmcginnis.  Greetings!
