### ISSUE TITLE
Unable to create kind standalone cluster in ubuntu rootless docker

### ISSUE THREAD

**Issue by michaelmok2021** [vmware-tanzu/community-edition#2754]
## Bug Report

I am trying to deploy a standalone cluster in Ubuntu 21.10 Docker Rootless environment. I believe I have install all the require library including kind, tanzu 0.10.0 RC2, docker-ce, etc. See below the error encountered

## Expected Behavior

Standalone cluster to be provisioned.

## Steps to Reproduce the Bug

Followed instruction from to setup deployment environment. [Getting Started](https://tanzucommunityedition.io/docs/latest/getting-started/)

## Screenshots or additional information and context

![tanzu-screenshot](https://user-images.githubusercontent.com/77700571/147427163-8118f7d8-875d-456f-bea5-4759f6169333.png)

## Environment Details

* Build version - tanzu 0.10.0 RC-2
* Deployment - Standalone cluster
* Infrastructure Provider - Docker Rootless
* Operating System - Ubuntu Desktop 21.10

**Comment by stmcginnis** [comment]
Hello @michaelmok2021! I'm not sure if we have tested with rootless environments. It requires cgroups v2, and I know we have issues with that currently. There are more details of some caveats here: https://kind.sigs.k8s.io/docs/user/rootless/

As a test, it might be interesting to try installing `kind` and trying to create a kind cluster directly to see if you can get that to work. https://kind.sigs.k8s.io/docs/user/quick-start/#installation

If you are interested and would like to try, we are also looking at replacing the current standalone cluster implementation. You could try running the proposed replacement to see if you have any better luck: https://github.com/vmware-tanzu/community-edition/pull/2376

**Comment by michaelmok2021** [comment]
Hello @stmcginnis. See attached my attempt at creating kind cluster directly in rootless environment. Note Ubuntu 21.10 has cgroups v2 enabled. The kind cluster appears to be working. 

![kind-ubuntu-1](https://user-images.githubusercontent.com/77700571/147627224-51a23fa5-2e3b-4e1d-a03b-73c014dec8d2.jpg)

Would there are any plan to support running tanzu managed or standalone cluster in rootless environment? Thanks.

**Comment by qnetter** [comment]
> Hello @stmcginnis. See attached my attempt at creating kind cluster directly in rootless environment. Note Ubuntu 21.10 has cgroups v2 enabled. The kind cluster appears to be working.
> 
> ![kind-ubuntu-1](https://user-images.githubusercontent.com/77700571/147627224-51a23fa5-2e3b-4e1d-a03b-73c014dec8d2.jpg)
> 
> Any plan to support running tanzu managed or standalone cluster in rootless environment? Thanks.

Please open an issue, and let others vote. Community requests have significant importance in our planning.

**Comment by michaelmok2021** [comment]
@qnetter , would I need to create another issue or would this issue be sufficient. Perhaps I can edit the title of this issue to mention rootless docker?

**Comment by joshrosso** [comment]
@michaelmok2021 This issue is perfect.

Thanks for raising the issue around rootless deployment models. I'm gonna put this in our icebox for now but we'll review it for future milestones. We have some changes coming to this deployment model that might enable what you're looking for. I'll make a note for us to revisit in our next milestone.

**Comment by joshrosso** [comment]
@stmcginnis @jpmcb let's make a note to try rootless in `unmanaged`. I wonder if it's at all feasible.

**Comment by joshrosso** [comment]
I verified today that `unmanaged` works in rootless mode. Since we'll be removing standalone in v0.11.0, i'll close this issue.
