### ISSUE TITLE
Can't create a cluster due to OS image not detected

### ISSUE THREAD

**Issue by baodongli** [vmware-tanzu/community-edition#2793]
## Bug Report

On Mac, following https://tanzucommunityedition.io/docs/latest/vsphere-install-standalone/, I can't create a Tanzu standalone cluster on vsphere due to empty OS Image list.

## Expected Behavior

The Os Image drop down list should list the images from the vSphere client.

## Steps to Reproduce the Bug

Following https://tanzucommunityedition.io/docs/latest/vsphere-install-standalone/, photon-3-kube-v1.21.2+vmware.1-tkg.3-6345993713475494409.ova and created the required template on my vSphere Client.

I issued the below command
```
tanzu standalone-cluster create --ui
```

While filling up the required information, at the OS Image section, I got the following warning and and the OS Image drop down list is empty:

```
Your standalone cluster will be deployed with Tanzu Kubernetes release (TKr) v1.21.2+vmware.1-tkg.1. We are unable
to detect a VM template that belongs to this Tanzu Kubernetes release. You must install a VM template that belongs
to Tanzu Kubernetes release v1.21.2+vmware.1-tkg.1 to continue with deployment of the standalone cluster. You may 
click the refresh icon to reload the OS image list once the appropriate VM template has been installed.
```

## Screenshots or additional information and context

![image](https://user-images.githubusercontent.com/3081257/148809300-ebcf1c93-122f-46f2-b31c-b08403b4a581.png)

![image](https://user-images.githubusercontent.com/3081257/148809508-1aa38cf4-a36b-4aec-a72d-efb4b64b2855.png)## Environment Details

* Build version (`tanzu version`): 0.9.1
* Deployment (Managed/Standalone cluster): Standalone
* Infrastructure Provider (Docker/AWS/Azure/vSphere): vSphere
* Operating System (client): Mac OS

**Comment by stmcginnis** [comment]
Hi @baodongli! You mention the image photon-3-kube-v1.21.2+vmware.1-tkg.3-6345993713475494409.ova, but that is not one of the available images on the download page. Please make sure you are using the template from one of the supported versions.

https://customerconnect.vmware.com/downloads/get-download?downloadGroup=TCE-090

I believe once you get one of the versions from that download page, it should then show up in the drop down list for you to select.

**Comment by baodongli** [comment]
Hi @stmcginnis thanks for your quick response. I used this link to download the OVA: 
https://customerconnect.vmware.com/downloads/details?downloadGroup=TKG-141&productId=988&rPId=82536. That's probably why it doesn't work. Let me try the link you provided.

A quick question about the cni plugin. The only option provided on the cluster create page is Antrea. Is Calico supported as well?

**Comment by baodongli** [comment]
Hi @stmcginnis I was able to proceed with the image. But now I got this error message:
unable to set up standalone cluster, : unable to create bootstrap cluster: failed to create kind cluster tkg-kind-c7ea5feel3qvb74e02u0: failed to init node with kubeadm: command "docker exec --privileged tkg-kind-c7ea5feel3qvb74e02u0-control-plane kubeadm init --skip-phases=preflight --config=/kind/kubeadm.conf --skip-token-print --v=6" failed with error: exit status 1

What could be wrong? Are there any logs that I can look for errors?

**Comment by stmcginnis** [comment]
Great! At least one roadblock down. ;)

For this next error, I'm wondering if you are running on Windows or MacOS, using Docker Desktop? The latest versions of Docker Desktop switched over to using cgroupv2, and unfortunately the bootstrap image we have out there doesn't work with that yet.

A quick way to check would be to run `docker info | grep Cgroup`. One of the lines should show the "Cgroup version". If it is not `1`, then that's likely our issue.

If that is the case, a possible workaround would be to downgrade Docker Desktop to a version prior to v4.3.0. That would get us back to a version that uses cgroupv1.

**Comment by baodongli** [comment]
# docker info | grep Cgroup 
WARNING: No swap limit support
Cgroup Driver: cgroupfs

it doesn't show Cgroup version.

I'm on a Ubuntu machine with docker engine 18.06.1-ce. Which version do you suggest? 
# docker version
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a
 Built:             Tue Aug 21 17:24:58 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       e68fc7a
  Built:            Tue Aug 21 17:23:24 2018
  OS/Arch:          linux/amd64
  Experimental:     false

**Comment by qnetter** [comment]
What kernel version?

**Comment by stmcginnis** [comment]
I have the same environments on one of my test machines. That version of Docker looks a little old though. Can you do an `apt update` and see if you have a newer package available? This is what I have on my machine:

```
Client: Docker Engine - Community
 Version:           20.10.12
 API version:       1.41
 Go version:        go1.16.12
 Git commit:        e91ed57
 Built:             Mon Dec 13 11:45:33 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.12
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.12
  Git commit:       459d0df
  Built:            Mon Dec 13 11:43:42 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.12
  GitCommit:        7b11cfaabd73bb80907dd23182b9347b4245eb5d
 runc:
  Version:          1.0.2
  GitCommit:        v1.0.2-0-g52b36a2
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Comment by baodongli** [comment]
# uname -a
Linux localhost 3.13.0-170-generic #220-Ubuntu SMP Thu May 9 12:40:49 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

It's ubuntu trusty, kind of old. 

Let me upgrade them.

thanks

**Comment by stmcginnis** [comment]
Whoa, yep, Trusty is quite old at this point. There could be other contributing factors based on older packages in that environment.

Since the last release of trusty went "end of standard support" in 2019, it might be a good time to upgrade that. If you can at least upgrade Docker CE we can see if that takes care of it, but that old of a platform makes me a little nervous that we're going to run into other unexpected issues.

**Comment by baodongli** [comment]
After upgrading ubuntu and installing the latest docker, I was able to deploy a cluster successfully. Thank you @stmcginnis and @qnetter for all the helps. I'm closing this issue.
