### ISSUE TITLE
Document cgroupsv2 requirement

### ISSUE THREAD

**Issue by joshrosso** [vmware-tanzu/community-edition#2796]
## Description

Now that docker desktop uses cgroupsv2 by default, it's becoming commonly problematic for our users that they cannot bootstrap. We must document this ASAP.

## Location

`*`

## Additional Context

None

**Comment by jorgemoralespou** [comment]
I would suggest a Known Limitations section on the docs.

**Comment by joshrosso** [comment]
Addressed in https://github.com/vmware-tanzu/community-edition/pull/2806

@kcoriordan FYI on @jorgemoralespou suggestion wrt known limitation.
