### ISSUE TITLE
TCE build-test-release in containerized environments

### ISSUE THREAD

**Issue by karuppiah7890** [vmware-tanzu/community-edition#2809]
This issue is to track TCE build-test-release (btr) in containerized environments for us to be able to run TCE build-test-release in infrastructure like Prow which are containerized environments (Prow = K8s = pods = containers)

I have noticed that TCE build should be pretty easy and straight forward in a containerized environment

For TCE test in containerized environments, I have raised an issue in Tanzu Framework regarding it - https://github.com/vmware-tanzu/tanzu-framework/issues/1475

I'm yet to try out TCE release in containerized environments, but I think there shouldn't be any hiccups there and that it should be pretty straight forward like TCE build

**Comment by joshrosso** [comment]
Putting this in icebox only because we don't know what release this is targeted for or if it'll be out of band of an "official" release. Feel free to update the milestone if you want to bind yourself to a specific TCE release.

Thanks!
