### ISSUE TITLE
Automate publishing artifacts to Tanzu Network

### ISSUE THREAD

**Issue by karuppiah7890** [vmware-tanzu/community-edition#2826]
Currently TCE is released and distributed in various avenues like [GitHub Releases](https://github.com/vmware-tanzu/community-edition/releases), Package Managers ([Homebrew](https://brew.sh/), [Chocolatey](https://chocolatey.org)), [VMware Customer Connect](https://customerconnect.vmware.com/), [Tanzu Network](https://network.tanzu.vmware.com)

This issue is to target automation for releasing to Tanzu Network . TCE product on Tanzu Network - https://network.tanzu.vmware.com/products/tanzu-community-edition/

We could explore and use Tanzu Network APIs and try to automate publishing artifacts and other metadata to the TCE product on Tanzu Network, whenever we do TCE releases

**Comment by joshrosso** [comment]
@karuppiah7890 putting this in `icebox` only because we don't know what release this is targeted for or if it'll be out of band of an "official" release. Feel free to update the milestone if you want to bind yourself to a specific TCE release.

Thanks!
