### ISSUE TITLE
Fix the link to CPI repo

### ISSUE THREAD

**Issue by lubronzhan** [vmware-tanzu/community-edition#2833]
## Bug Report

In CPI readme, the link to github is CAPV, instead of CPI https://github.com/kubernetes/cloud-provider-vsphere

https://github.com/vmware-tanzu/community-edition/tree/9b6fe7b5c89fd4b87b575253c6c01eea5410c743/addons/packages/vsphere-cpi/1.22.4

## Expected Behavior

The link should be correct

## Environment Details

* Build version (`tanzu version`): 
* Deployment (Managed/Standalone cluster): 
* Infrastructure Provider (Docker/AWS/Azure/vSphere): 
* Operating System (client):

**Comment by joshrosso** [comment]
@kcoriordan can you keep track of this to ensure we get the broken link fixed?

**Comment by kcoriordan** [comment]
https://github.com/kubernetes/cloud-provider-vsphere
