### ISSUE TITLE
Introduce an Application Toolkit Package

### ISSUE THREAD

**Issue by kartiklunkad26** [vmware-tanzu/community-edition#2848]
# Proposal: Introduce an Application Toolkit Package

# Summary
We are introducing an Application Toolkit Meta-Package to simplify the installation of all the packages that are important for a developer to create and iterate on Tanzu workloads. 

# Problem Statement

The introduction of carvel packaging technology has significantly improved the installation experience of tools on Kubernetes. We've also seen a wide adoption of the packaging technology for several tools on TCE. 

Installing each of the individual packages manually can be cumbersome and error-prone. 

# Proposal

**Meta-Package**

A meta-package is a set of components (Carvel packages). Once that meta-package is defined, a profile can be implemented based on the need to enable an intent-based installation experience of some or all of the specified packages.

Further details regarding the Metapackage as a concept has been introduced in the [Design Doc](https://github.com/vmware-tanzu/community-edition/pull/2911)

We are introducing an **App-Platform** (name can still change) metapackage which will initially consists of the below packages. This will expand in the future. 

**Phase 1 Packages**

| Packages                |
| ----------------------- |
| Contour                 |
| Cert-manager            |
| Source Controller       |
| knative-serving         |
| kpack                   |
| Cartographer            |

**User Experience**

Here is the flow of the installation experience using the developer profile of Application Toolkit Meta-Package 

1. Listing all the packages as they relate to Application Toolkit (there can be additional non-Application Toolkit packages here)  

`tanzu package available list`

```
NAME                                     DISPLAY-NAME             SHORT-DESCRIPTION
  
app-toolkit.tanzu.vmware.com             Application Toolkit             Package to install a set of Application Toolkit components
contour.tanzu.vmware.com                 Contour                  Used as a Ingress Controller
cert-manager.tanzu.vmware.com            Cert-Manager             Used to install certificates
source-controller.tanzu.vmware.com       Source Controller        Used to watch the git repositories
knative-serving.tanzu.vmware.com         Knative Serving          Used to convert images to Knative services
kpack.tanzu.vmware.com                   Kpack                    Used to convert source code into images
cert-injection.webhook.tanzu.vmware.com  Cert-Injection Webhook   Used to inect certificates into the running containers
cartographer.tanzu.vmware.com            Cartographer             Used to create software supply-chains
ootb-basic-supply-chain.tanzu.vmware.com OOTB Basic Supply Chain  Used to install a basic supply chain going from git repository to running Knative Service. 
```

2. Installing a profile
* List version information for the package by running:

```
tanzu package available list app-toolkit.tanzu.vmware.com 
```
* Create a `app-toolkit-config-values.yaml` file. This configuration file will have configuration required to deploy foo and the subordinate packages. 

**Example Config for Application Toolkit**
```
kpack: 
  kp_default_repository: "KP-DEFAULT-REPO"
  kp_default_repository_username: "KP-DEFAULT-REPO-USERNAME"
  kp_default_repository_password: "KP-DEFAULT-REPO-PASSWORD"
supply_chain: basic

ootb_supply_chain_basic:
  registry:
    server: "SERVER-NAME"
    repository: "REPO-NAME"
  gitops:
    ssh_secret: ""
```
**Note** *Accurate configuration variables will be defined later*

* Install the metapackage
```
tanzu package install app-toolkit -p app-toolkit.tanzu.vmware.com -v 1.0.0 --values-file app-toolkit-config-values.yml
```

See Also
- 
- [Proposal: Introduce Tanzu Workload Creation Capability](https://github.com/vmware-tanzu/community-edition/issues/2847)

**Comment by joshrosso** [comment]
@kartiklunkad26, thanks for getting this rolling.

As you alluded to, we do need a proposal to understand what is being suggested here, why it's important, and some details on how we'll get there.

Please note our [proposal process is documented here](https://github.com/vmware-tanzu/community-edition/tree/main/docs/designs). We try to keep the process light-weight and **not not** always require a design doc, although we may suggestion one. If you feel a full design doc is justified, you are welcome to create one, however, adding details to this issue might suffice.

**Comment by kartiklunkad26** [comment]
@joshrosso I've introduced more detail regarding the User Experience above. I've also created a PR for the Design Doc that describes the Metapackage as a concept in general. 

Let me know if this is helpful, and what content would you like us to provide next that we can include in this issue :)

**Comment by kartiklunkad26** [comment]
@joshrosso heads-up @mstergianis and Chris Samp have started work on this. Michael/Chris - feel free to ask the TCE team questions here or in the #tanzu-community-edition Slack channel in Kubernetes workspace.

**Comment by kartiklunkad26** [comment]
Heads-up - I've removed references to the "developer" profile mostly, and focused on the "App-Platform" metapackage. The name may change!

**Comment by kartiklunkad26** [comment]
Additional detail - we are proposing this change to go in to the TCE v0.11 release.

**Comment by joshrosso** [comment]
Read this proposal, it seems the core of what we're suggesting is:

1. A package called "App platform"
2. A set of additional packages (some which already exist) including:

    | Packages                |
    | ----------------------- |
    | Contour                 |
    | Cert-manager            |
    | Source Controller       |
    | knative-serving         |
    | kpack                   |
    | Cert-injection webhook  |
    | Cartographer            |
    | OOTB Basic Supply Chain |

3. App Package installing and configuring all of the above.

Please let me know if I've got it wrong!

**Comment by joshrosso** [comment]
Sent message to the mailing list.

Reference: https://groups.google.com/g/tanzu-community-edition/c/IQ7aNVSlZw0

We’re currently planning to keep the RFC window open until 02/14/2022.

**Comment by vrabbi** [comment]
This looks great and would indeed bring huge value to tce! I have built such a package repo and meta package that i use for this same use case and it has made the installation process very easy and quick!
You can see the one i have built at https://github.com/vrabbi/tap-oss

**Comment by kartiklunkad26** [comment]
@joshrosso you've got it right!

**Comment by krisapplegate** [comment]
Our intention is also to let the app-platform meta-package live in the TCE repo. All of the packages that it deploys are included in that same repo so there's no need to add anything external.

**Comment by thesteve0** [comment]
Sorry have been on PTO. Love the idea and really excited about it. 
I do think we are missing external-DNS as one of the packages. Not such an issue for a local docker install, but for any use case, managed or unmanaged, I would want to be able to hook up External DNS so I can have a real URL for my workloads. 

In terms of metadata required in the developer-values.yaml - how do you propose to document what information is needed and what is required. I see documenting the use of the metapackage to be complicated.  Will they have to basically go to every subpackage and read the documentation or will it all be documented on the metapackage page?

Are you also thinking of providing reasonable defaults for some of the subpackages with reasonable defaults - lowering the required information burden on the end user.  Because we are assuming a user "profile", I think ti would be quite reasonable to fill in quite a bit of defaults since we are already assuming prior knowledge of the desired outcome. 

I am not sure if this is a formatting issue but I wasn't sure if they `package list` had a way to show that there are actual subpackages. Is there some way with the package list to also be able to give users information on where to find more information on the package (not really specific to this RFC) and what specific information is needed for sub-packages.

**Comment by kartiklunkad26** [comment]
Hey Steve. thank you fro this feedback! I'll reply to the feedback individually. 

> I do think we are missing external-DNS as one of the packages. Not such an issue for a local docker install, but for any use case, managed or unmanaged, I would want to be able to hook up External DNS so I can have a real URL for my workloads.

Will definitely look at external-dns and whether this is worth incorporating into App-Platform. 

>In terms of metadata required in the developer-values.yaml - how do you propose to document what information is needed and what is required. I see documenting the use of the metapackage to be complicated. Will they have to basically go to every subpackage and read the documentation or will it all be documented on the metapackage page?

We will provide a minimal `app-platform-values.yml` file in the documentation. Users can query the schema of the individual packages, in case they want to add additional configuration from the individual packages to the meta-package values file. 

>Are you also thinking of providing reasonable defaults for some of the subpackages with reasonable defaults - lowering the required information burden on the end user. Because we are assuming a user "profile", I think ti would be quite reasonable to fill in quite a bit of defaults since we are already assuming prior knowledge of the desired outcome.

There will be reasonable defaults provided by each package that will be preserved. We may add overriding metapackage default configuration as and when it makes sense, but that might be a rare case. 

Regarding the profile - initially we had planned to add a "developer" profile, but for now we are focused on releasing the App-Platform Meta-Package for Developers and DevSecOps users. So for now, there is no profile defined. 

> I am not sure if this is a formatting issue but I wasn't sure if they package list had a way to show that there are actual subpackages. Is there some way with the package list to also be able to give users information on where to find more information on the package (not really specific to this RFC) and what specific information is needed for sub-packages.

I don't think there's a API that gives you the list of sub-packages within a Meta-Package as it isn't a first class concept in  Carvel yet.

**Comment by mstergianis** [comment]
> I don't think there's a API that gives you the list of sub-packages within a Meta-Package as it isn't a first class concept in Carvel yet.

Agreed. Looking into the CRD for [`Package`](https://carvel.dev/kapp-controller/docs/v0.32.0/packaging/#package), which is where I think we'd want to put a list, I think the best place would be the `releaseNotes` key. Where you might do something like
```yaml
releaseNotes: |-
  One liner describing the changes.

  Extended information including a list of packages
otherKeys: {}
```

And hope :crossed_fingers: that the tanzu cli renders that in a sane way. :shrug: we're stuck between a rock and a hard place no matter how I see it though, so the least evil thing will win IMO

**Comment by jorgemoralespou** [comment]
I find that as part of the discussion happening on this thread there's a lot of good ideas that should somehow be tracked. I understand that this RFC is just "create a App platform package" so let's keep it that way, but there's a lot of comments (in this and the related "metapackage proposal") that could be added as RFE and Issues to improve the packaging experience in TCE. Not to hammer the same nail over and over, but I would not want to replicate what has been created in TAP as a way to "downstream" our commercial efforts into Open Source Software, but rather use this project to really look at the desirable experience and work with the other projects to be the real "upstream" instead.

**Comment by kartiklunkad26** [comment]
@jorgemoralespou good point. I was wondering myself the best way to track all the Meta-Package related feedback that we have received. I'll create a issue focusing on the "introduction of meta-package as a concept in TCE", that will mostly be a "docs" story rather than a "new capability of TCE", and we can use that as a good place to capture all of the feedback. 

That sound good?

**Comment by jorgemoralespou** [comment]
Not sure if better to have individual issues tracking smaller feature requests. I would defer to the TCE team for what they consider best way. @joshrosso @vkorbes

**Comment by kartiklunkad26** [comment]
I'll use that docs issue to capture the feedback, and then will create individual issues after that.

**Comment by joshrosso** [comment]
Following up from internal conversations:

* @kartiklunkad26 owns this work item (atm)
* Deadline for merging is `03/18` for inclusion in `v0.11.0`

**Comment by joshrosso** [comment]
Also, adding @seemiller who can support this effort from the TCE side.
