### ISSUE TITLE
How do I get an invitation to join the organization

### ISSUE THREAD

**Issue by thuongtruong1009** [vmware-tanzu/community-edition#2857]
## Description
Hi there!
My name is Tran Nguyen Thuong Truong - @thuongtruong1009
Currently, I learning front-end.
I want to learn more and more about open-source code.
Hope to cooperate with you in the future.

## Location
VietNam

**Comment by stmcginnis** [comment]
Welcome @thuongtruong1009!

There is no need to join the organization. Please see our contributing docs for instructions on how to submit PRs and get started working with the source code:

https://tanzucommunityedition.io/docs/latest/contribute/contributing/#contribution-workflow

There is a little more information about our Google Group and our Slack channel under the Community section on our site:

https://tanzucommunityedition.io/community/

There are a few Issues labeled [good-first-issue](https://github.com/vmware-tanzu/community-edition/issues?q=is%3Aissue+is%3Aopen+label%3Ahelp-wanted), but feel free to browse for anything that looks interesting to you. We don't have a lot of front end development issues right now, but that may change in the future.

Just let us know if you have any questions! :)
