### ISSUE TITLE
Add possibility to annotate the service account of ExternalDNS

### ISSUE THREAD

**Issue by TYsewyn** [vmware-tanzu/community-edition#2863]
## Feature Request

This feature would allow developers and operators to use ExternalDNS on GKE clusters that have workload identity enabled.
[Workload Identity](https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity) allows workloads in your GKE clusters to impersonate Identity and Access Management (IAM) service accounts to access Google Cloud services.

## Describe alternatives you've considered

An annotation that is manually added to the service account of ExternalDNS will eventually be overwritten by subsequent reconciliation runs.

**Comment by jpmcb** [comment]
cc @vmware-tanzu/pkg-external-dns-owners

**Comment by christianang** [comment]
Hi @TYsewyn,

This feature makes sense to me. We will add it to our backlog, but we aren't sure when we will get to it. If you or anyone else would like to make a PR we be happy to offer any help necessary to make the contribution.

Thinking out loud on how I would approach implementation. This should just require a ytt overlay to be added to [here](https://github.com/vmware-tanzu/community-edition/tree/main/addons/packages/external-dns/0.10.0/bundle/config/overlays) in the package. This can change the [external-dns-serviceaccount.yaml](https://github.com/vmware-tanzu/community-edition/blob/main/addons/packages/external-dns/0.10.0/bundle/config/upstream/external-dns-serviceaccount.yaml) similar to how the [overlay-deployment.yaml](https://github.com/vmware-tanzu/community-edition/blob/main/addons/packages/external-dns/0.10.0/bundle/config/overlays/overlay-deployment.yaml#L30-L33) finds and overwrites the spec.
