### ISSUE TITLE
Include `unmanaged-cluster` in release package for TCE v0.10.0+

### ISSUE THREAD

**Issue by joshrosso** [vmware-tanzu/community-edition#2867]
## Feature Request

With the inclusion of https://github.com/vmware-tanzu/community-edition/pull/2376, we should update any build/install/package automation to include `unmanaged-cluster`. I believe this means updates to:

* https://github.com/vmware-tanzu/community-edition/blob/27317fcd3f6b574f393ee396fc81c967eba39a20/hack/release/package-release.sh#L69-L77
* https://github.com/vmware-tanzu/community-edition/blob/27317fcd3f6b574f393ee396fc81c967eba39a20/hack/release/install.bat#L37-L39

_There may be other files_

@karuppiah7890 is this something that you or someone from your team can tackle?

Thanks in advanced!

**Comment by karuppiah7890** [comment]
@joshrosso Good catch! Yes, we need to take care of these to release the new plugin as part of v0.10.0 ! I'll try to raise a PR for this 😄
