### ISSUE TITLE
Unable to deploy management cluster with NSX-ALB

### ISSUE THREAD

**Issue by matthias-ontec** [vmware-tanzu/community-edition#2871]
## Bug Report

We are trying to deploy a management cluster (production) with NSX as control plane endpoint provider.
Unfortunately the deployment fails after bootstrapping with
"error: unable to recognize "/tmp/kubeapply-1460201063": no matches for kind "AKODeploymentConfig" in version "networking.tkg.tanzu.vmware.com/v1alpha1"

The behavior is the same for v0.9.1 and v.0.10.0rc2.

See screenshots below.

## Expected Behavior

Management cluster provisioned successfully.

## Steps to Reproduce the Bug

Followed getting started guide for management clusters.

## Screenshots or additional information and context

![screenshot1](https://user-images.githubusercontent.com/98034852/150153096-c6ba5641-1a42-4a71-b5a2-baae3f724369.png)

## Environment Details

* Build version (`tanzu version`): v0.10.0rc2
* Deployment (Managed/Standalone cluster): Managed Cluster
* Infrastructure Provider (Docker/AWS/Azure/vSphere): vSphere
* Operating System (client): Ubuntu 20.04 (Photon for control planes)

**Comment by joshrosso** [comment]
cc @vmware-tanzu/pkg-ako-operator-owners, any ideas on this bootstrap failure?

**Comment by XudongLiuHarold** [comment]
Hi @matthias-ontec , this error is because ytt template apply order, it will still apply after a retry and we fixed this in the latest release. 
Could you tell what's the final state you are seeing when you create management cluster? Does it stick on initializing control plane machine? Are you able to see virtual service for this management cluster on your Avi Controller? And could you please also check the ako-operator/tkg-system and ako/tkg-system pod status in your bootstrap kind cluster? Thanks!

**Comment by XudongLiuHarold** [comment]
Hi @matthias-ontec , it looks like errors happen in AKO pod instead of the error you shared here. Could you please share more logs of AKO so we can know what exactly happened? Thanks.

**Comment by matthias-ontec** [comment]
Hi @XudongLiuHarold , attached the file below. This is the output of the AKO pod. Version used is 1.4.0. Thanks!

[avi-log.log](https://github.com/vmware-tanzu/community-edition/files/7906935/avi-log.log)

**Comment by XudongLiuHarold** [comment]
Hi @matthias-ontec , which Cloud you are using on Avi Controller? 
From the log, it looks like this is a NSX-T cloud, which is not supported in AKO 1.4.0.

Could you please to switch to a vCenter cloud on your Avi Controller?

**Comment by matthias-ontec** [comment]
@XudongLiuHarold , it is a NSX-T cloud. Would that be supported in 1.6.0? We cannot switch to vCenter cloud due to basic license of Avi.

**Comment by XudongLiuHarold** [comment]
Hi @matthias-ontec ,  I am afraid that we are not supported NSX-T cloud for using AVI to provide control plane VIP yet.

**Comment by matthias-ontec** [comment]
Hi @XudongLiuHarold , thank you very much for the quick response! What would be our options then?
Is it possible to use AVI as load balancer in the workload cluster? Could we use it with cloud type "No Orchestrator"?

**Comment by XudongLiuHarold** [comment]
Hi @matthias-ontec , I think you can still use AVI to provide Load Balance type of service, but you can't use it to provide control plane VIP.

You can still install the latest version of AKOO/AKO, but use kube-vip to provide control plane VIP, after your management cluster created, you can
```
kubectl edit adc install-ako-for-all
kubectl edit adc install-ako-for-management-cluster
```
both fill `spec.extraConfigs.networksConfig.nsxtT1LR` with correct value, then you will be able to use AVI to provide load balance type of service in all of your TKG clusters.

**Comment by matthias-ontec** [comment]
Hi @XudongLiuHarold , thank you for clarification! How could we get the current package (or repo) of AKO?
In the tanzu repo I could only find version 1.4.0, which doesn't have this parameter.
How could I get the latest repo / packages?

I appreciate your assistance very much!
