### ISSUE TITLE
Add subnote to docs that mention to not use `:latest` when adding a package repository

### ISSUE THREAD

**Issue by ciberkleid** [vmware-tanzu/community-edition#2875]
## Feature Request

Not sure if there are others, but I see at least three places where the latest version of TCE is mentioned:
1. This repo. At the time of creation of this issue, [0.9.1](https://github.com/vmware-tanzu/community-edition/releases/tag/v0.9.1) is labeled as latest
2. The package installation instructions in the docs, which at the time of creation of this issue, also say 0.9.1:
     URL: https://tanzucommunityedition.io/docs/latest/package-management/
```
tanzu package repository add tce-repo \
  --url projects.registry.vmware.com/tce/main:0.9.1
```
3. The tag on the package image on Harbor. 
     This is where I see a discrepancy. On Harbor, main:0.9.1 and main:latest
```
~$ docker images
REPOSITORY                                   TAG                  IMAGE ID       CREATED        SIZE
projects.registry.vmware.com/tce/main        latest               f454986a53e1   N/A            273kB
projects.registry.vmware.com/tce/main        0.9.1                2835b13e3647   N/A            217kB
```

It would be great if the image were also in sync so that using :latest would be an option.
As it is, it is not clear what that latest image relates to, so it cannot be used with confidence.

In fact, the docs could use :latest in the example commands and then have a link to where the user can look up the latest. Otherwise it is not clear to the user if the docs are up to date or if there is something newer, and perhaps not entirely obvious where to look.

**Comment by joshrosso** [comment]
Hey @ciberkleid there's a few reasons we keep latest out of sync and only for development.

Without going into all of them, the primary limitation is how our hosted-harbor instance caches the `:latest` tag at the CDN level. It leads to non-deterministic resolution of `:latest` as it can resolve to different underlying images depending on the region of the world you are in.

For this reason and a few others, we highly recommend **not** using `latest` for resolving the TCE package reposioty.

Hope this clears things up, feel free to re-open the issue if there is follow-up required from us!

**Comment by ciberkleid** [comment]
Thanks for the explanation, @joshrosso! Makes sense. In that case, I would turn this into a documentation request... I think it would be helpful if the docs were explicit about discouraging the use of `latest` and providing info on where to verify what the latest version is. If other users are like me, the question will come up in their minds when they come to that section of the docs (point 2 above), so it would be good to have the answer there and save the user the doubt and discovery effort.

**Comment by kcoriordan** [comment]
Opening a new issue for 'adding a comment to the docs explaining to the user not to use latest' as per request from @ciberkleid.
