### ISSUE TITLE
Run plugin/config initialization script as part of brew install

### ISSUE THREAD

**Issue by garrying** [vmware-tanzu/community-edition#2907]
## Feature Request
Currently, after running `brew install vmware-tanzu/tanzu/tanzu-community-edition`, there is a post-installation step that prompts users to run `configure-tce.sh` to complete installation and reference to an uninstall script.

As an enhancement, `configuration-tce` operations we could be included as a seamless post-install step, that does not require users to run a script separately after the installation of the binary. Installation/uninstall shortened to a single step:
- `brew install vmware-tanzu/tanzu/tanzu-community-edition`: Installs binary, and performs configuration (possibly with output describing post-install actions)
- `brew uninstall vmware-tanzu/tanzu/tanzu-community-edition`: Uninstalls binary, and runs actions that are part of `uninstall.sh`

## Describe alternatives you've considered
- The current output, and mentions in the docs, makes visible that running the script is a separate post-install action if a user is attentive to brew install output. There could be some improvements in adding more emphasis to the output (possible limitations in the kinds of output supported)
- Approaches that are closer to changing the `tanzu` binary:
  - A `tanzu` command that would be a sort of shortcut to `configure-tce` from within the `tanzu` CLI workflow. There is an existing  `init` command; not sure if it is suppose to operate the same way the `configure-tce` script.
  - Run `configure-tce.sh` as part of a user running `tanzu` for the first time.
  - Display helpful output to run `configure-tce` if a user has not run the configuration script yet.

## Additional context

Docs describing installation:
- https://tanzucommunityedition.io/docs/latest/cli-installation/
- https://github.com/vmware-tanzu/community-edition#installation

**Comment by karuppiah7890** [comment]
Thanks @garrying ! This has been on my mind for sometime too, no one wants to read all the installation output and run more commands to finish an installation 😅 We can do better to enhance the experience. This is a great step in that direction 😄

**Comment by karuppiah7890** [comment]
Ideally just `brew install` and `brew uninstall` should be enough and any user, without reading extra docs would try to do just that to do the installation and uninstallation of any software, very rarely extra steps like modifying `.bashrc` file etc to update `PATH` environment variable etc. It's good that more folks have started thinking about this issue. I'm hoping we will reach at a good solution to make the experience better

**Comment by garrying** [comment]
I can imagine instructions on configuring shell completion (`tanzu completion ...`) being shown after `brew install`—recalling other installations I've seen. Something to consider for a new issue!

**Comment by kartiklunkad26** [comment]
+1 for this feature. Are there technical reasons of why we have defined the configure-tce.sh as a follow-up step to `brew install` command?

**Comment by seemiller** [comment]
Yes, there are technical concerns why running the `configure-tce.sh` script is a manual step after `brew install`.

First item to know is that tanzu-framework, on which TCE is based, utilizes the `~/.config/tanzu` directory for storing configuration. Notice that this location is in the user's home account.

Second, Homebrew runs installations inside of a child, subprocess. This child process is essentially a sandbox that is restricted to the `/usr/local` directory. Homebrew installs are not allow to perform any operation outside of this directory.

Given that information, you can see the problem. Homebrew cannot modify the user's home account. TCE needs to modify the user's home account. The only way to configure TCE is to manually run a post-`brew install` command.

**Comment by joshrosso** [comment]
Sorry, didn't mean to close.

I do think this issue hits at a very desirable feature: You should be able to 1-click/1-command install the components of TCE.

**Comment by kartiklunkad26** [comment]
If the implementation is where it makes it difficult to do it part of brew install, I can imagine `init` type of commands with the tanzu CLI that can help initialize the environment including plugins. I also imagine the `init` process should be consistent for the Tanzu CLI across all Tanzu products but that might be a stretch user outcome.

**Comment by seemiller** [comment]
Should this issue be handled in Framework if we're considering changes to the CLI?
