### ISSUE TITLE
Package Management doc issue at: /docs/latest/package-management

### ISSUE THREAD

**Issue by eshanks16** [vmware-tanzu/community-edition#2909]
## Description

This page directs you to github where there are {Package}.yaml files used for examples. If you use one of those files, and try to deploy with it, you get an error becausee there are #@ lines in the file and it can't deploy correctly. Users will need to know to remove those lines or replace the file with a usable yaml file.

"expected to not find annotations inside data values file (hint: remove comments starting with '#@'

**Comment by stmcginnis** [comment]
Are we missing some details here @seemiller?
