### ISSUE TITLE
Increasing Number of Maintainer Approvals for PR

### ISSUE THREAD

**Issue by pnbrown** [vmware-tanzu/community-edition#2931]
## Bug Report

[GOVERNANCE.md](https://github.com/vmware-tanzu/community-edition/blob/main/GOVERNANCE.md) requires that we have two maintainers review each PR. Our current automated checks only require one approval.

**Comment by dvonthenen** [comment]
Once we move packages into their own repos, we can look into implementing this. This would cause 2 approvals for package PRs.

**Comment by stmcginnis** [comment]
I think the point was we need to update the governance doc to actually reflect how we are doing things. We should also remove the wording about waiting 5 days to merge PRs.

I think now that we have a documented feature proposal process in place, that addresses the majority of what the current content of the governance doc was getting at. But it's kind of muddled, as is. We may want to think about expanding or clarifying what scenarios it is referring to.

**Comment by pnbrown** [comment]
The wording of the 5 days is coming in another PR. Changing the approvers was a different issue.

**Comment by jonasrosland** [comment]
So is the consensus of the maintainers then that you don't want to implement 2 approvers for PRs? It's a common rule that many other projects follow. Just want to make sure we're doing the right thing here.

**Comment by seemiller** [comment]
Enabled "2 approvers required to merge a PR"
