### ISSUE TITLE
Prometheus: Allow to specify tlsCertificateSecretName

### ISSUE THREAD

**Issue by doddatpivotal** [vmware-tanzu/community-edition#2946]
## Feature Request

Currently you must provide the contents of you tlsCertificate in the data-values file for prometheus.  This is undesirable in cases were the tlsCertificate is being managed by cert-manger. 

I'd like to see a tlsCertificateSecretName parameter, so that that the user can simply reference the secret that contains the credentials.

## Additional context

This improvement was just made to harbor 2.3.3, and it would be great to see it in prometheus as well.  I will be creating an issue for grafana addon too. #2947

**Comment by joshrosso** [comment]
@vmware-tanzu/pkg-prometheus
