### ISSUE TITLE
Url linter should not fail on certificate error

### ISSUE THREAD

**Issue by stmcginnis** [vmware-tanzu/community-edition#2948]
## Bug Report

A recent patch adding an adopter is failing on the link to their web site with the error:

```
Error: Get "https://terasky.com/": x509: certificate signed by unknown authority
```

Going to the site directly, it looks like their certificate is fine. So this maybe isn't picking up the host's configured certificate authorities.

But after talking this through, in general we should not care about invalid certs, only that the link actually goes somewhere. So the check should set `InsecureSkipVerify` to `true` so these types of errors are ignored.

The source code for this tool should also be moved in to the `community-edition` repo so we can make updates there.

## Expected Behavior

Test should pass if the URL actually goes to somewhere legitimate.

## Steps to Reproduce the Bug

Run local tests against #2944

**Comment by karuppiah7890** [comment]
cc @aman556 who was recently working on this to move the url linter to TCE repo. Related PR - #2746

**Comment by aman556** [comment]
Thanks @stmcginnis for pointing this out will have a look and try to resolve this.

**Comment by aman556** [comment]
@stmcginnis issue is resolved for complete contests please have a look at https://github.com/vmware-tanzu/community-edition/pull/2746#discussion_r793540434. Once [#2746 ](https://github.com/vmware-tanzu/community-edition/pull/2746) got merge this issue will be resolved.
Thanks!
