### ISSUE TITLE
Missing Release Process page in TOC

### ISSUE THREAD

**Issue by garrying** [vmware-tanzu/community-edition#2958]
## Description

`/docs/latest/contribute/release-process/ ` is being indexed in Algolia, and appears as a search result, because it is listed in `sitemap.xml`. The page is not in the TOC or linked in other pages as far as I can tell.
- Should the page be listed on the site?
- and is the content still relevant? Last major update was in July, 2021

## Location

- https://tanzucommunityedition.io/docs/latest/contribute/release-process/
- https://github.com/vmware-tanzu/community-edition/blob/main/docs/site/content/docs/latest/contribute/release-process.md

**Comment by jpmcb** [comment]
Good catch - we are thinking this isn't something that needs to be generated. Assigning David to move this somewhere where it _won't_ get generated into the docs site.
