### ISSUE TITLE
Add comment not to use 'latest' in docs

### ISSUE THREAD

**Issue by kcoriordan** [vmware-tanzu/community-edition#2977]
## Description
Add a comment to the docs explaining to the user not to use latest' as per request from @ciberkleid in #2977.

Hey @ciberkleid there's a few reasons we keep latest out of sync and only for development.

From @joshrosso  in #2977
`Without going into all of them, the primary limitation is how our hosted-harbor instance caches the :latest tag at the CDN level. It leads to non-deterministic resolution of :latest as it can resolve to different underlying images depending on the region of the world you are in. For this reason and a few others, we highly recommend not using latest for resolving the TCE package reposioty.`

From @ciberkleid in #2977

`I would turn this into a documentation request... I think it would be helpful if the docs were explicit about discouraging the use of latest and providing info on where to verify what the latest version is. If other users are like me, the question will come up in their minds when they come to that section of the docs (point 2 above), so it would be good to have the answer there and save the user the doubt and discovery effort.`

**Comment by kcoriordan** [comment]
@ciberkleid 

Hi Cora


The version is kept dynamically up to date in multiple locations in the doc. Is the ask here to add a note in each of these locations to **not** use latest -as I think this could get clunky ?

The version (dynamic) appears in these topics: 


Work with Packages
https://tanzucommunityedition.io/docs/latest/package-management/

Installing a Package in the Getting Started guide
https://tanzucommunityedition.io/docs/latest/getting-started/#installing-a-package

Tanzu Community Edition Installation in the Getting Started guide for Windows, Mac, and Linux
https://tanzucommunityedition.io/docs/latest/getting-started/#tanzu-community-edition-installation

**Comment by joshrosso** [comment]
Moving to `icebox` until we get follow-up. Thanks!

**Comment by ciberkleid** [comment]
Hi, sorry... this got lost in my inbox :(

Yeah, I think it's very common to assume you can use latest and if we
cannot ensure that the image tagged `latest` is safe for use, then we
should make a concerted effort to be really clear about it.

**Comment by joshrosso** [comment]
Thanks @ciberkleid!

Would you be interested in making the contribution to our docs?

For now, we'll leave this as help wanted in hopes it'll get picked up from someone.

Thanks!
