### ISSUE TITLE
Error deploying - Images not pulling

### ISSUE THREAD

**Issue by inacioikeda** [vmware-tanzu/community-edition#2979]
## Bug Report

Hello everybody.

I have a problem at the time of deploy, where some images are not downloaded, causing the installation not to finish.

## Expected Behavior

![image](https://user-images.githubusercontent.com/8295045/151835560-b5d57f4a-d2a9-4501-ae41-a18bf2bd2756.png)
   
## Steps to Reproduce the Bug

1. tanzu management-cluster create --file confs/cluster-mgmt/cluster-mgmt.yaml

## Screenshots or additional information and context
![image](https://user-images.githubusercontent.com/8295045/151835072-bac63fa7-4482-4045-a0d4-3d1ea2fd19d6.png)
![image](https://user-images.githubusercontent.com/8295045/151835265-c48e8f9a-a032-4784-8319-19314e8b5233.png)

## Environment Details

* Build version (`tanzu version`): v0.10.0-rc2
* Deployment (Managed/Standalone cluster): Management
* Infrastructure Provider (Docker/AWS/Azure/vSphere): vSphere
* Operating System (client): Ubuntu 20.04

thanks and best regards

**Comment by joshrosso** [comment]
Hi @inacioikeda,

This is a really obscure behavior! Seems like the manifest said the layer of the container image with different from what it actually is/was.

I'm not able to re-produce this exact behavior, I wonder if it was a blip or something in the networking layer
Any chance you can try to delete everything and recreate the cluster?

Let me know if you get the same behavior!

![image](https://user-images.githubusercontent.com/6200057/151838327-73bbcea8-aa28-45e5-8099-12e9ea5c9b61.png)

**Comment by inacioikeda** [comment]
I'll re-create, but this action already done before.

Thanks

**Comment by joshrosso** [comment]
Thanks! I double verified there is no issue with the container image:

```
$ crane manifest projects.registry.vmware.com/tkg/cluster-api/kubeadm-bootstrap-controller:v0.3.23_vmware.1 | jq .
{
  "schemaVersion": 2,
  "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
  "config": {
    "mediaType": "application/vnd.docker.container.image.v1+json",
    "size": 1139,
    "digest": "sha256:ea5f6d31e200c812093e1ca0285b792db53345ad641e7809c13fa31441b01915"
  },
  "layers": [
    {
      "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
      "size": 681839,
      "digest": "sha256:03a0a57ab6ff1e6962479560efda46f8552429975f94d187e0042b887b4af390"
    },
    {
      "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
      "size": 20070304,
      "digest": "sha256:cbab0246ad5ff40de4b58b9261c0ff47713b3b3a36f7f37b6c8de9c0a89032c9"
    }
  ]
}
```

```
tar xv -f test.tar
sha256:ea5f6d31e200c812093e1ca0285b792db53345ad641e7809c13fa31441b01915
03a0a57ab6ff1e6962479560efda46f8552429975f94d187e0042b887b4af390.tar.gz
cbab0246ad5ff40de4b58b9261c0ff47713b3b3a36f7f37b6c8de9c0a89032c9.tar.gz
manifest.json
```

```
$ ls -l cbab0246ad5ff40de4b58b9261c0ff47713b3b3a36f7f37b6c8de9c0a89032c9.tar.gz
-rw-r--r-- 1 josh josh 20070304 Dec 31  1969 cbab0246ad5ff40de4b58b9261c0ff47713b3b3a36f7f37b6c8de9c0a89032c9.tar.gz
```

You _could_ try these steps on your bootstrap machine to verify!

**Comment by inacioikeda** [comment]
After redeploy again (3 once), the image was pulled and the cluster is up.

Thanks and best regards.

**Comment by joshrosso** [comment]
@inacioikeda you're welcome. Thanks for following up with us.
