### ISSUE TITLE
Allow to inject a cluster local CA to the nodes

### ISSUE THREAD

**Issue by jorgemoralespou** [vmware-tanzu/community-edition#2986]
## Feature Request
When using cert-manager for certificate generation and using a [CA Issuer](https://cert-manager.io/docs/configuration/ca/) we might need to also inject that CA into the node's containerd so that it can be used to secure an in cluster registry and images can be pulled from it. This is typically useful for local development environments where a developer might have a local CA generated on his laptop that he wants the cluster to use (so there's trust between his/her machine and the cluster) and images can be built and push into a cluster's hosted registry and images can be pulled from that registry by the cluster's containerd.
This gives a full "TLS secured" environment for development, and removes a lot of issues that pop up for people using self signed certificates for development, which should be prevented as much as possible.

I have developed a Carvel package that does this [localca-injector-package] (https://github.com/failk8s-packages/localca-injector-package) but it would be nice to have this being part of TCE. 

Also, for unmanaged clusters, one could add the CA to the config so that when the cluster is created the CA is present on the node and containerd properly configured, even if the user is not using cert-manager. Allowing unmanaged clusters to inject a CA also helps on the corporate CA use case.

**Comment by stmcginnis** [comment]
cc @qnetter

**Comment by cmoulliard** [comment]
A solution is to mount the CA certificate like this part of the TCE Kind config https://kind.sigs.k8s.io/docs/user/private-registries/#use-a-certificate. Example:  https://github.com/snowdrop/k8s-infra/blob/main/kind/kind-tls-secured-reg.sh#L116-L148

**Comment by cmoulliard** [comment]
My 2 cents. It is currently really hard for local developments to deal with private registry and to configure them accordingly as that requests to:

1. Generate a self signed certificate (ideally trusted by the K8s CA or a CA trusted by the browsers) where the DNS Names match the private registry - [see](https://github.com/halkyonio/tce/blob/main/scripts/kind_gen_load_cert.sh#L64-L112) 
2. Update the docker, containerd, ... config file to include the hostnames of the private registry - [see](https://github.com/halkyonio/tce/blob/main/scripts/kind_gen_load_cert.sh#L120-L131)
3. Restart the containerd service or docker daemon or ... - [see](https://github.com/halkyonio/tce/blob/main/scripts/kind_gen_load_cert.sh#L144)
4. Mount the CA, TLS crt and TLS key files within the kind control plane - [see](https://github.com/halkyonio/tce/blob/main/scripts/kind_gen_load_cert.sh#L138)
5. Create a secret containing the CA, TLS crt and TLS key files to the private registry - [see](https://github.com/halkyonio/tce/blob/main/scripts/install_harbor.sh#L154-L157)
6. Update within the control plane the CA certificates - [see](https://github.com/halkyonio/tce/blob/main/scripts/kind_gen_load_cert.sh#L141)

**Remark**: As TCE supports the certificate manager (able to generate a selfsigned certificate), then you can rely (also) on it to perform the step 1.

So, even if you document it somewhere as kind team did it [here](https://kind.sigs.k8s.io/docs/user/private-registries/), such a work is still something really difficult to be done manually, needed for local (disconnected) development and will offer a real added value around the Tanzu client (vs kind only, rancher, ...).
