### ISSUE TITLE
Provide stop/start lifecycle hooks in unmanaged clusters

### ISSUE THREAD

**Issue by jorgemoralespou** [vmware-tanzu/community-edition#2987]
## Feature Request
For unmanaged clusters it would be ideal to be able to have a start/stop feature so that you don't have the cluster up and running always. Given this cluster is local, it would help on saving resources on the developer's machine when he's not using the cluster to be able to stop it. Similar to what Docker Desktop does now with the ability to pause DD to save resources:

![image](https://user-images.githubusercontent.com/78350/151977651-9e5c2011-90b9-4c05-984e-bef18922eb0c.png)

And similar to Code Ready Containers (OpenShift's local clusters) that let you start/stop the cluster. Same as minikube.
![image](https://user-images.githubusercontent.com/78350/151977765-f2a8aec4-4a31-4648-a0b4-5f459a35bcf2.png)

**Comment by joshrosso** [comment]
In order to do this, we should expand the cluster provider interface to offer these hooks. Cluster providers can choose what they'd like to do (if anything) when these hooks are triggered.

Along with this work, we should introduce the ability to see "Status" when listing clusters, an example would be:

```
$ tanzu uc ls
  NAME     PROVIDER   STATUS
  testit2  kind       Running
```

A few key important notes on the above:

* We should introduce the ability to retrieve status in the cluster provider interface
* We should have a time-based requirement for returning status (max a few seconds)
* If no status is returned or status query times out, we should report the `STATUS` as `Unknown`.

At this time, we'll have @stmcginnis own this work going into `v0.12.0`. Subject to change.

**Comment by jorgemoralespou** [comment]
If Status is implemented, I would probably think that defining not only a state, but a struct with State and potentially other additional info would be awesome, to have things in the future in there.
Also, if Status is implemented, would be awesome if Running is really when all the bootstrapped pods are really Running, and not when some are still pending.

**Comment by joshrosso** [comment]
> If Status is implemented, I would probably think that defining not only a state, but a struct with State and potentially other additional info would be awesome, to have things in the future in there.
> Also, if Status is implemented, would be awesome if Running is really when all the bootstrapped pods are really Running, and not when some are still pending.

That make sense and appreciate the feedback.

To make sure expectations are clear, we're likely to not do that level of introspection for this initial work. But could be a follow-up thing to consider.

**Comment by jorgemoralespou** [comment]
Sure. No problem. Continuous improvement.

**Comment by stmcginnis** [comment]
The tricky thing about this is that I don't believe kind provides a way to start and stop a cluster.  Kind gives a nice abstraction where it can be used with either docker or podman. We will likely need to go around kind and figure out which runtime is in use and interact directly with it to perform the start/stop operations, breaking some of the abstraction kind provides.

**Comment by jorgemoralespou** [comment]
I agree this night be tricky, and specially when new provides are added, but this is a workflow that the unmanaged cluster should support given the target use and audience of this cluster typology.

**Comment by jpmcb** [comment]
> The first step needs to be introducing this functionality into the cluster provider interface. After that is done, it is up to the provider to determine whether they want to implement this functionality.

+1 - the provider should be the one to determine if it's possible and make an implementation; we should create the API around that to make it exposed. A provider very may opt out and not enable this

Anecdotally, while it might be tricky with `kind`, it looks like it is fairly simple in `minikube` with:

```
❯ minikube --help
minikube provisions and manages local Kubernetes clusters optimized for development workflows.

Basic Commands:
  ...
  pause          pause Kubernetes
  unpause        unpause Kubernetes

```

**Comment by jorgemoralespou** [comment]
Minikube does also provide start and stop, which are the heavyweight version of pause/unpause. The former does start/stop the VM (if running on a vm), the latter start/stop the k8s cluster only.

**Comment by joshrosso** [comment]
@stmcginnis taking this from you to free you up for UI/Installer related tasks.
