### ISSUE TITLE
Document node pool management and use of different VM types

### ISSUE THREAD

**Issue by kcoriordan** [vmware-tanzu/community-edition#2988]
## Description

Do we need to add content about Manage Node Pools of Different VM Types

https://kubernetes.slack.com/archives/C02GY94A8KT/p1643719823284929

](https://docs.vmware.com/en/VMware-Tanzu-Kubernetes-Grid/1.4/vmware-tanzu-kubernetes-grid-14/GUID-tanzu-k8s-clusters-node-pool.html)

**Comment by joshrosso** [comment]
Yes, let's add this at some point. Not urgent though.
