### ISSUE TITLE
Add example application deployment to docs

### ISSUE THREAD

**Issue by kcoriordan** [vmware-tanzu/community-edition#3002]
## Description

@thesteve0 
Do we want to add an example in doc showing how to Deploy a Test Workload.
If so do we want to reuse one of the ones listed here or provide something new

Here is a simple example that @thesteve0 tested that works:
https://docs.vmware.com/en/VMware-vSphere/7.0/vmware-vsphere-with-tanzu/GUID-5DFC347C-694B-4288-96DA-EAEB5818D951.html

Here is another example that needs a load balancer
https://docs.vmware.com/en/VMware-Tanzu-Kubernetes-Grid/1.4/vmware-tanzu-kubernetes-grid-14/GUID-tanzu-k8s-clusters-tutorial.html

**Comment by joshrosso** [comment]
Sounds great. Can we introduce a Guide for `Deploying a sample app` and link it at the end of our getting started guide.

Something like "Next Steps", perhaps?

**Comment by thesteve0** [comment]
I see it as a test that your workload or unmanaged cluster is actually working.

**Comment by joshrosso** [comment]
This won't happen this release. Sorry ya'll. Help-wanted still out there. For now, moving to v0.12.0

**Comment by kcoriordan** [comment]
@thesteve0 - when you tested this: https://docs.vmware.com/en/VMware-vSphere/7.0/vmware-vsphere-with-tanzu/GUID-5DFC347C-694B-4288-96DA-EAEB5818D951.html

Did you test on vSphere? the prerequisite section links to vsphere doc which references the supervisor cluster. Is this prereq required, or can this example work on the other cloud providers?

**Comment by thesteve0** [comment]
Sorry - just saw this. Did not test on anything but AWS and unmanaged
