### ISSUE TITLE
Remove `standalone-cluster` from e2e tests in `external-dns` addon

### ISSUE THREAD

**Issue by jpmcb** [vmware-tanzu/community-edition#3008]
cc @vmware-tanzu/pkg-external-dns-owners team

We are removing the deprecated `standalone-cluster` plugin in v0.11.0 of TCE. The e2e tests currently rely on `standalone-cluster`.

We are introduced `unamanged-cluster` in v0.10.0 which should suffice for your e2e tests.

Reference: https://github.com/vmware-tanzu/community-edition/issues/3005

**Comment by joshrosso** [comment]
cc @vmware-tanzu/pkg-external-dns-owners

**Comment by tylerschultz** [comment]
Hi Friends,

We're looking to remove the reference to `./test/docker/run-tce-docker-standalone-cluster.sh` from the `external-dns` test `README.md` and replace it with a reference to an updated script and/or Makefile task that uses `unmanaged-cluster`. 
There doesn't appear to be such scripts or Makefile tasks yet. We can certainly add a task/script, but we'd like to check in with you first. Thoughts?

**Comment by stmcginnis** [comment]
@karuppiah7890 @rajaskakodkar is that script something your team maintains for release testing?

I would assume we would want something similar using `unmanaged-clusters`, but not sure who is best to own that.

**Comment by jpmcb** [comment]
I've created this issue to track work for replacing `standalone` e2e tests with `unamanged` ones: https://github.com/vmware-tanzu/community-edition/issues/3045

For now @tylerschultz, can your team use managed clusters with this script? 
```
./test/docker/run-docker-managed-cluster.sh
```

**Comment by christianang** [comment]
I think we will just point to the getting started guide to explain how to deploy a cluster. Thus removing the need for maintenance of this Readme when scripts change.
