### ISSUE TITLE
Add Cartographer as a package to TCE

### ISSUE THREAD

**Issue by jwntrs** [vmware-tanzu/community-edition#3024]
# Add Cartographer as a package to TCE

### Problem
A path to production is a way of codifying an application’s value stream map as it makes its way from a developer’s workstation to a production environment.

Although Kubernetes has a rich ecosystem of APIs and tools to do the work, managing the communication paths between these resources can still be a big pain.

### What is Cartographer?
Cartographer allows users to configure Kubernetes resources into re-usable supply chains that can be used to define all of the stages that an Application Workload must go through to get to an environment. We call these stages the path to production.

Cartographer separates controls between a user responsible for defining a Supply Chain (known as an App Operator) and a user responsible for creating the application (the Developer). These roles are not necessarily mutually exclusive, but provide the ability to create a separation concerns which means developers can focus on writing code, and platforms teams can focus on smoothing and securing their path to production.

### How does Cartographer work? 

Cartographer allows users to define all of the steps that an application must go through to create an image and Kubernetes configuration. Users achieve this with the Supply Chain abstraction.

The supply chain consists of resources that are specified via Templates. Each template acts as a wrapper for existing Kubernetes resources and allows them to be used with Cartographer. Cartographer supply chain templates include:

    Source Template
    Image Template
    Config Template
    Generic Template

Unlike many other existing Kubernetes native workflow tools, Cartographer does not “run” any of the objects themselves. Instead, it monitors the execution of each resource and templates the following resource in the supply chain after a given resource has completed execution and updated its status.

### Feature Ask
The ask is to make Cartographer available as a Tanzu package as part of Tanzu Community Edition.

**Comment by joshrosso** [comment]
Hi @jwntrs,

Please review our [package maintainer documentation](https://github.com/vmware-tanzu/community-edition/tree/main/docs/packaging).

If you're good with the above, let us know and we're happy to then approve this proposal and can accept a PR whenever your package is ready.

If you (or your team) cannot do what's described in those docs, let us know so we can figure out a plan.

Thank you!

**Comment by cirocosta** [comment]
Hi @joshrosso , I'll be the one pushing a PR to include the Cartographer package - just went through the documentation and **everything sounds good!** 

We have created a `package-for-cartographer` repository under `vmware-tanzu` (should be made public soon - repository created but still private, just waiting for approval), but the repository is currently publishing the artifacts to `ghcr.io` as I don't yet have credentials to `projects.registry.vmware.com` (I'll reach out directly to figure that one out).

Thank you!

**Comment by kartiklunkad26** [comment]
@seemiller can give you access to the registry @cirocosta.

**Comment by joshrosso** [comment]
@seemiller @cirocosta do you have the appropriate permissions now?

**Comment by seemiller** [comment]
I added @cirocosta to the TCE Harbor project 4 days ago, he should be able to push packages.

**Comment by cirocosta** [comment]
Yes, thank you @seemiller ! 

@joshrosso , #3262 ready for review 👍
