### ISSUE TITLE
Proposal: Provide meaningful exit error codes for `unmanaged-cluster`

### ISSUE THREAD

**Issue by jorgemoralespou** [vmware-tanzu/community-edition#3025]
## Feature Request
When executing the plugin from within a script it is almost impossible to know what is the reason of a failure without parsing the output file and processing it. It'll be ideal that every error would provide a different error exit code (!=0) and that these are documented so that embedding "unmanaged-cluster" functionality in other tools can be easier.

**Comment by jpmcb** [comment]
Love this!

Wondering if this needs it's own proposal or if @stmcginnis's proposal around improving error handling and visibility during bootstrapping incorporates this. But regardless, this probably warrants it's own proposal so we can have some buy in from the community on what the codes might mean.

**Comment by stmcginnis** [comment]
I agree, this is good as its own proposal. And also agree, this would be a good thing.

The only thing I am not sure of is the way cobra handles error returns and if there is a way to tell it to provide different exit codes. But from what I've seen, the `RunE` method of implementing commands rarely gives what we want, and we should probably just use `Run` and print out our own errors and exit directly so we have control over this. Just some thoughts for the dev side.

**Comment by jpmcb** [comment]
Happy to write this proposal unless @jorgemoralespou is passionate about it! 👀

**Comment by jorgemoralespou** [comment]
@jpmcb I'm never passionate about anything ;-) so you can go ahead, but TBH I think this could just be part of @stmcginnis's proposal around improving error handling and visibility during bootstrapping. I could understand not including it there if the proposal would extend to error codes across all the plugins and commands. But then, maybe this should be moved to tanzu-framework, or defined here and then discussed for incorporation in TF, as in that case, would be generic to all plugins and commands.

**Comment by nrb** [comment]
@jorgemoralespou can you provide a few examples of what errors you're thinking of? Doesn't need to be a proposal, but it'll help us understand what categories you've got in mind.

**Comment by jorgemoralespou** [comment]
Sure. When creating a cluster (I'm only thinking about unmanaged now), it goes through multiple steps (prereqs check, pulling down image, parsing tkr, pulling down kapp-controller, installing package repository,...). What we would like is to have a different error code for every error in these steps so that if e.g. we get error code -13 we know it means that kapp-controller image could not be pulled, if we get -2 it means that prerequirements (docker memory) could not be satisfied,... and so on, as my understanding is that stderr and stdout provide already human readable output and this would need to be parsed to be understood by a machine scripted process.
These error code should be well documented and not change.
