### ISSUE TITLE
Provide a linkable non-version scoped page for each package

### ISSUE THREAD

**Issue by tcdowney** [vmware-tanzu/community-edition#3029]
## Description

This is a suggestion. It would be nice if each package had a higher level "landing page" that wasn't scoped to a particular version or an evergreen "latest" version. For example, I want to be able to write documentation that instructs users to install the latest version of Contour from TCE and link them to it. Right now I can only link to a specific version so anytime Contour is updated I need to update the link on my end.

## Location

This relates to all of the package pages in general.

## Additional Context

It would be nice if there was a "latest" version in this drop down or if the main package name was a link.

![Screen Shot 2022-02-03 at 10 50 54 AM](https://user-images.githubusercontent.com/2096955/152400279-44f36c5a-71f2-4e54-996f-f4d33ce14189.png)

**Comment by nrb** [comment]
This sounds like a good idea. @seemiller should we update our docs automation to make the latest version of package's README the landing page?

I think this will likely be pushed out to v0.12.0 or later as we figure out higher level versioning of TCE docs, too.
