### ISSUE TITLE
Determine how the v0.11.0 release BOM will be produced

### ISSUE THREAD

**Issue by joshrosso** [vmware-tanzu/community-edition#3033]
We're aiming to release `v0.11.0` in the late March time-frame.

Due to new requirements to use an `antrea-standard` package, we moved to leveraging a Bill of Materials (BOM) produced by Tanzu Framework.

Let's use this issue to get details on who will produce the BOM for the TCE v0.11.0 release.

**Comment by joshrosso** [comment]
Hi @navidshaikh, while we're still pretty far out, I wanted to get in front of this future release and make sure we know who will be producing the v0.11.0 BOM and what's needed from the TCE team.

When March rolls around, what info is needed from us to kick off this process?

**Comment by navidshaikh** [comment]
tanzu-framework v0.16.0 [release](https://github.com/vmware-tanzu/tanzu-framework/releases) (see release notes) onwards, we're defaulting to ship antrea-standard in the releases. So if you're planning to pin tanzu-framework at v0.16.0 (or any other higher release), we should be good (we'd need to check about the promotion of artifacts to prod registry though).

If TCE March release would like to pin to tanzu-framework v0.15.0 or earlier, we'll need to issue a patch release.

I think we can resume this conversation once TCE figured which tanzu-framework release to vendor for its next release.

**Comment by joshrosso** [comment]
> tanzu-framework v0.16.0 [release](https://github.com/vmware-tanzu/tanzu-framework/releases) (see release notes) onwards, we're defaulting to ship antrea-standard. So if you're planning to pin tanzu-framework at v0.16.0 (or any other higher release), we should be good (we'd need to check about the promotion of artifacts to prod registry though).

@navidshaikh we will pin to `v0.16.0` or greater.

With that now known, what should be our first step when it's time to release?

**Comment by joshrosso** [comment]
@navidshaikh what's unclear is the pinning of the **compatibility file**, which drives the correlation of the TKG-BOM and TKR-BOM.

Looking at the 0.16.0 tag:

https://github.com/vmware-tanzu/tanzu-framework/blob/1fdb45bc1fda2597b85f56a2ea3adb6bc51e814f/Makefile#L61-L67

Framework is pointing to `framework-zshippable/tkg-compatibility`. Seems like will not guarantee the right compatibility file / BOMs, right?

**Comment by navidshaikh** [comment]
The tag on this image determines the right compatibility file. Tanzu CLI takes care of it by mapping to the correct compatibility file with its own version (v0.16.0 in this case), see the tip of v01.6.0 tag https://github.com/vmware-tanzu/tanzu-framework/commit/1fdb45bc1fda2597b85f56a2ea3adb6bc51e814f

As long as the correct image coordinate (registry and name) is given, we should be good. Ensuring the compatibility file is present in the tag of the image, is being done part of the tanzu-framework release (and promotion of artifacts to the prod registry).

**Comment by joshrosso** [comment]
Ok, I think this all sounds good.

One comment for future readers of this thread, we'll like ping ourselves to v0.17.0 (or possibly even higher) for our v0.11.0 release.

I'll keep this ticket open until we release, but please note @navidshaikh's steps described at:

https://github.com/vmware-tanzu/community-edition/issues/3033#issuecomment-1030118313

**Comment by joshrosso** [comment]
This conversation is no longer relevant based on https://github.com/vmware-tanzu/community-edition/issues/3286.

We'll continue the conversation there.
