### ISSUE TITLE
Implement `unmanaged-cluster` e2e tests

### ISSUE THREAD

**Issue by jpmcb** [vmware-tanzu/community-edition#3045]
## Feature Request

Since `standalone-cluster` is being removed, including all associated bits and tests, we should replace those tests with `unamanged-cluster` ones

## Additional context

Tracker issue: https://github.com/vmware-tanzu/community-edition/issues/3005
PR to remove e2e tests: https://github.com/vmware-tanzu/community-edition/pull/3007

cc @vmware-tanzu/tce-releng

**Comment by joshrosso** [comment]
@karuppiah7890 assigned this work to you for v0.11.

Feel free to delegate or let us know if it's unrealistic for v0.11.

Thanks :rocket: !
