### ISSUE TITLE
Failed to create kind cluster

### ISSUE THREAD

**Issue by vfarcic** [vmware-tanzu/community-edition#3049]
## Bug Report

When creating a management cluster, the following error pops up:

```
✘ [0205 22:00:55.35728]: init.go:166] unable to set up management cluster, : unable to create bootstrap cluster: failed to create kind cluster tkg-kind-c7ve93tmk1u6m2g1pk5g: failed to init node with kubeadm: command "docker exec --privileged tkg-kind-c7ve93tmk1u6m2g1pk5g-control-plane kubeadm init --skip-phases=preflight --config=/kind/kubeadm.conf --skip-token-print --v=6" failed with error: exit status 1
```

I tried it on an Intel and Silicon (M1) Mac and, in both machines, I tried deploying it as Docker and on AWS. The error is always the same.

The `kind create cluster` command works.

```bash
docker version
```

```
Client:
 Cloud integration: v1.0.22
 Version:           20.10.11
 API version:       1.41
 Go version:        go1.16.10
 Git commit:        dea9396
 Built:             Thu Nov 18 00:36:09 2021
 OS/Arch:           darwin/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.11
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.9
  Git commit:       847da18
  Built:            Thu Nov 18 00:35:39 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.12
  GitCommit:        7b11cfaabd73bb80907dd23182b9347b4245eb5d
 runc:
  Version:          1.0.2
  GitCommit:        v1.0.2-0-g52b36a2
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

## Expected Behavior

Management cluster created

## Steps to Reproduce the Bug

Install latest Tanzu community edition CLI on a Mac, execute `tanzu management-cluster create --ui` and try to create a management cluster.

## Screenshots or additional information and context

N/A

## Environment Details

* Build version (`tanzu version`):
```
version: v0.2.1
buildDate: 2021-09-29
sha: ceaa474
```
* Deployment (Managed/Standalone cluster): Managed
* Infrastructure Provider (Docker/AWS/Azure/vSphere): Docker and AWS 
* Operating System (client): macOS

**Comment by stmcginnis** [comment]
Hi @vfarcic - thanks for reporting this.

[ARM is not currently supported](https://github.com/vmware-tanzu/community-edition/issues/2171), so unfortunately you will not be able to deploy from that machine.

Can you verify you are not using cgroupv2 on the Linux machine? If you run `docker info | grep Cgroup` that should show the version.

**Comment by stmcginnis** [comment]
Sorry, I mean on the Intel machine, not Linux. Intel MacOS is supported. We just need to make sure you are running a version of Docker Desktop prior to 4.3 when they switched over to cgroupv2.

**Comment by vfarcic** [comment]
I upgraded docker desktop yesterday so it is definitely never than 4.3. Is there an issue associated with the work on the support for cgroupv2 so that I can follow?

**Comment by stmcginnis** [comment]
OK, downgrading to anything prior to 4.3.0 should get things working for you. 4.2.x still used cgroupv1.

Support in TCE is dependent on changes in tanzu-framework. Those changes appear to have been made, but we need a newer release of TCE that uses a release that includes it. The tracking issue in the `community-edition` repo can be found here: https://github.com/vmware-tanzu/community-edition/issues/2798

**Comment by seemiller** [comment]
Looks like a resolution was found, feel free to reopen if we missed anything.
