### ISSUE TITLE
Can not connect to a Cluster after it has restarted using Antrea CNI (docker provider)

### ISSUE THREAD

**Issue by jorgemoralespou** [vmware-tanzu/community-edition#3058]
## Bug Report
When creating a cluster with Docker provider (managed or unmanaged) and the cluster is restarted you can no longer connect to the cluster's API server when Antrea is the CNI. It works when using calico as the CNI.

Some pointers from the TCE team, says that [this antrea issue](https://github.com/antrea-io/antrea/issues/1113) might be related and that it's also related to the [code in here](https://github.com/antrea-io/antrea/blob/e23cf3b5714d15ae66a33196c1f870196065f651/hack/kind-fix-networking.sh#L17-L23)

## Expected Behavior
You can connect to the cluster after it has restarted.

## Steps to Reproduce the Bug
Create an unmanaged cluster with default config. Reboot docker. Try to connect again. 

## Environment Details

* Build version (`tanzu version`): 0.9.1 and 0.10.0
* Deployment (Managed/Standalone cluster): managed and unmanaged
* Infrastructure Provider (Docker/AWS/Azure/vSphere): Docker 
* Operating System (client): Not sure. It fails at least on Mac.

**Comment by jpmcb** [comment]
Is this actually something the TCE team can execute against?

For `unmanaged` cluster, we simply consume the BOM from upstream `tanzu-framework` which gives us the antrea CNI to use. This is why this issue exists for both managed and unmanaged. If this is as simple as bumping the version of antrea that's in the BOM, than we should transfer this issue to `tanzu-framework`.

For `unmanaged`, we _do_ already provide that patch:
https://github.com/vmware-tanzu/community-edition/blob/5b7e4b6a87f61bfeea325e5cc07618b4a6d8094a/cli/cmd/plugin/unmanaged-cluster/cluster/kind.go#L286-L289

**Comment by jorgemoralespou** [comment]
@jpmcb does the above comment mean that antrea on unmanaged clusters work fine and do survive restarts?

**Comment by jpmcb** [comment]
No - Antrea clusters still won't survive after a restart.

My comment was more around _who_ is able to execute on this problem. Since we merely consume upstream components, I'm not sure where this should land.

This issue deserves more investigation to figure out what's going on.

**Comment by joshrosso** [comment]
> Is this actually something the TCE team can execute against?

It is. The investigation and work here involves the building of our kind image. The goal would be to build it in such a way that the node patching is not required or done automatically during at the right time of node (container) initialization.

**Comment by joshrosso** [comment]
Initially, we'll give this to @stmcginnis as proposed work is in place to make this possible.

Ideally this is something where, if resolved properly, we can remove our patch code used when antrea is the CNI from unmanaged-cluster.
