### ISSUE TITLE
Need more documentation / help on tanzu package install command

### ISSUE THREAD

**Issue by nilarte** [vmware-tanzu/community-edition#3077]
## Description

We are trying to deploy tanzu packages on this setup from here:

However facing issues

ubuntu@ip-172-16-6-116:~$ kubectl config get-contexts
CURRENT   NAME                              CLUSTER        AUTHINFO             NAMESPACE
*         tkg-mgmt-aws-admin@tkg-mgmt-aws   tkg-mgmt-aws   tkg-mgmt-aws-admin
          tkg-wl-aws-admin@tkg-wl-aws       tkg-wl-aws     tkg-wl-aws-admin
ubuntu@ip-172-16-6-116:~$ kubectl config current-context
tkg-mgmt-aws-admin@tkg-mgmt-aws

tanzu package install contour   --package-name contour.community.tanzu.vmware.com   --version 1.19.1
| Installing package 'contour.community.tanzu.vmware.com'
| Getting namespace 'default'
| Getting package metadata for 'contour.community.tanzu.vmware.com'
Error: failed to find a package with name 'contour.community.tanzu.vmware.com' in namespace 'default': internalpackagemetadatas.internal.packaging.carvel.dev "contour.community.tanzu.vmware.com" not found
Usage:
  tanzu package install INSTALLED_PACKAGE_NAME --package-name PACKAGE_NAME --version VERSION [flags]

So what flags we are missing? 

## Location

https://github.com/vmware-tanzu/community-edition/blob/main/addons/packages/contour/1.19.1/README.md

**Comment by stmcginnis** [comment]
Hi @nilarte - can you run `tanzu package repository list --all-namespaces` to verify the package namespace, then `tanzu package available list --namespace ${NS}` to verify the contour package is showing up?

**Comment by seemiller** [comment]
I suspect that the package repository is installed into the `tanzu-package-repo-global` namespace.

If so, then your install command needs to be like this, where the `--namespace` parameter refers to the namespace that the package repository is installed into.

```shell
tanzu package install contour --package-name contour.community.tanzu.vmware.com --version 1.19.1 --namespace tanzu-package-repo-global
```

**Comment by nilarte** [comment]
Thanks @seemiller @stmcginnis 
TCE package repository was indeed not added to tanzu-package-repo-global namespace
I referred another issue [https://github.com/vmware-tanzu/community-edition/issues/3084](url) 
And added repo via :
This command
**tanzu package repository add tce-repo --url projects.registry.vmware.com/tce/main:0.9.1 --namespace tanzu-package-repo-global**
Now I can see contour package
**ubuntu@ip-172-16-6-116:~$ tanzu package available list --namespace tanzu-package-repo-global | grep contour                 contour.community.tanzu.vmware.com             Contour             An ingress controller                                
contour.tanzu.vmware.com                       Contour             An ingress controller**

However seems like this might not have contour version 19.1
tanzu package install contour --package-name contour.community.tanzu.vmware.com --version 1.19.1 --namespace tanzu-package-repo-global
/ Installing package 'contour.community.tanzu.vmware.com'
| Getting namespace 'tanzu-package-repo-global'
| Getting package metadata for 'contour.community.tanzu.vmware.com'

**Error: failed to resolve package 'contour.community.tanzu.vmware.com' with version '1.19.1'**

So how to match available contour version in local package repo?
I see in windows Powershell available package list also shows version 
But not in Linux shell somehow

**Comment by seemiller** [comment]
@nilarte The `0.9.1` repo might not have Contour `1.19.1`, but `0.9.2` does. The package repository version `0.9.2` was release early last week and the documentation may not have been updated.

You can check the available versions of a package using this command:

```shell
tanzu package available list contour.community.tanzu.vmware.com --namespace tanzu-package-repo-global
```

**Comment by nilarte** [comment]
Thanks a lot @seemiller 
I think 0.9.2 does not have community contour package.
ubuntu@ip-172-16-6-116:~$ tanzu package repository list --namespace tanzu-package-repo-global
| Retrieving repositories...
  NAME            REPOSITORY                                                      STATUS               DETAILS
  tanzu-standard  projects.registry.vmware.com/tkg/packages/standard/repo:v1.4.1  Reconcile succeeded
  **tce-repo        projects.registry.vmware.com/tce/main:0.9.2                     Reconcile succeeded**
  
  ubuntu@ip-172-16-6-116:~$ tanzu package available list  --namespace tanzu-package-repo-global                             / Retrieving available packages...
  NAME                           DISPLAY-NAME  SHORT-DESCRIPTION                                                          
  cert-manager.tanzu.vmware.com  cert-manager  Certificate management                                                     
  **contour.tanzu.vmware.com       Contour       An ingress controller**                                                      
  external-dns.tanzu.vmware.com  external-dns  This package provides DNS synchronization functionality.                   
  fluent-bit.tanzu.vmware.com    fluent-bit    Fluent Bit is a fast Log Processor and Forwarder                           
  grafana.tanzu.vmware.com       grafana       Visualization and analytics software                                       
  harbor.tanzu.vmware.com        Harbor        OCI Registry                                                               
  multus-cni.tanzu.vmware.com    multus-cni    This package provides the ability for enabling attaching multiple network interfaces to pods in Kubernetes
prometheus.tanzu.vmware.com    prometheus    A time series database for your metrics                        
------------------------------------------------------------------------------------------------

**I went back to 0.9.1 and it has contour.community.tanzu.vmware.com  1.18.1**
We could install 1.18.1 successfully.
That's ok for now and we can leave with 1.18.1
Thanks for all the help!

**Comment by seemiller** [comment]
@nilarte I think that you might have missed it in my last post, if you use the `tanzu package repository list` command and pass the name of a package, you'll get the versions available.

```shell
tanzu package available list contour.community.tanzu.vmware.com
| Retrieving package versions for contour.community.tanzu.vmware.com...
  NAME                                VERSION  RELEASED-AT
  contour.community.tanzu.vmware.com  1.17.1   2021-07-23T18:00:00Z
  contour.community.tanzu.vmware.com  1.17.2   2021-07-23T18:00:00Z
  contour.community.tanzu.vmware.com  1.18.1   2021-07-23T18:00:00Z
  contour.community.tanzu.vmware.com  1.19.1   2021-10-26T00:00:00Z
```

You can also use `kubectl` to get the same information.

```shell
kubectl get packages -A
NAMESPACE    NAME                                                                      PACKAGEMETADATA NAME                                 VERSION                 AGE
default      cert-manager.community.tanzu.vmware.com.1.3.3                             cert-manager.community.tanzu.vmware.com              1.3.3                   2h51m59s
default      cert-manager.community.tanzu.vmware.com.1.4.4                             cert-manager.community.tanzu.vmware.com              1.4.4                   2h51m59s
default      cert-manager.community.tanzu.vmware.com.1.5.4                             cert-manager.community.tanzu.vmware.com              1.5.4                   2h51m59s
default      cert-manager.community.tanzu.vmware.com.1.6.1                             cert-manager.community.tanzu.vmware.com              1.6.1                   2h51m59s
default      contour.community.tanzu.vmware.com.1.17.1                                 contour.community.tanzu.vmware.com                   1.17.1                  2h51m59s
default      contour.community.tanzu.vmware.com.1.17.2                                 contour.community.tanzu.vmware.com                   1.17.2                  2h51m59s
default      contour.community.tanzu.vmware.com.1.18.1                                 contour.community.tanzu.vmware.com                   1.18.1                  2h51m59s
default      contour.community.tanzu.vmware.com.1.19.1                                 contour.community.tanzu.vmware.com                   1.19.1                  2h51m59s
...
```

**Comment by nilarte** [comment]
@seemiller I was pretty certain that with 0.9.2 I saw only contour.tanzu.vmware.com  and NOT contour.community.tanzu.vmware.com in package list

So in foll. commands only first one returned results
tanzu package available list contour.tanzu.vmware.com --namespace tanzu-package-repo-global
tanzu package available list contour.community.tanzu.vmware.com --namespace tanzu-package-repo-global


Right now I am set at 9.0.1 
I can go back to 9.0.2 and re-check but will need some time

**Comment by seemiller** [comment]
@nilarte Based on the conversations here and off-issue in Slack, is there any further action to be taken on this issue?
