### ISSUE TITLE
List of Pre-flight Checks for creating clusters

### ISSUE THREAD

**Issue by joshrosso** [vmware-tanzu/community-edition#3080]
## Feature Request

A primary issue of cluster creation is that it starts and often finds pre-req issues during creation. This causes a bad UX since users find they need to make adjustments after creation has started (meaning they need to delete what was created, make adjustments, and restart).

This can be mitigated by introducing pre-flight checks to the cluster bootstrap process. This issue tracks common issues we see users having with prerequisites and includes a correlated issue in `tanzu-framework` to the need.

## List of Pre-Flight Checks

* https://github.com/vmware-tanzu/tanzu-framework/issues/1643
* https://github.com/vmware-tanzu/tanzu-framework/issues/1644
* https://github.com/vmware-tanzu/tanzu-framework/issues/1645
* https://github.com/vmware-tanzu/tanzu-framework/issues/1646

**Comment by AnilSankar75** [comment]
This will help immensely with improving the user experience for the user. For example a preflight check to ensure the right AWS region (Run preflight checks for Key pairs ) is selected prior to installing the bootstrap cluster and then failing would save time and improve the UX.
