### ISSUE TITLE
[Docs] [](/docs/latest/getting-started-standalone/) Adding the TCE Package Repository command should refer to v0.9.2

### ISSUE THREAD

**Issue by kartiklunkad26** [vmware-tanzu/community-edition#3084]
## Description

The docs refer to v0.9.1 for the TCE Package Repository. This means kpack won't be available for installation. 

## Location

https://tanzucommunityedition.io/docs/latest/getting-started-standalone/#creating-clusters

In the section of Installing a Package

Install the Tanzu Community Edition package repository into the tanzu-package-repo-global namespace.

`tanzu package repository add tce-repo --url projects.registry.vmware.com/tce/main:0.9.1 --namespace tanzu-package-repo-global
`

**Comment by kcoriordan** [comment]
I wasn't aware of this, so the package repository should be = v0.9.2 
but the latest TCE release remains at v0.9.1
?

**Comment by stmcginnis** [comment]
Yeah, we needed to release a new package repo update to pick up kpack, but that didn't correspond to a full TCE release. So there is a newer package repo.

Is there a way we can set a docs variable to pick this up that would default to be the same as the normal release version, but would allow us to update it to something else if needed?

**Comment by kcoriordan** [comment]
OK, I can add a variable for this
When v0.10.0 goes out, will the package repo change to `0.10.0`

**Comment by kcoriordan** [comment]
OK so I created a variable and this should probably get updated by automation when the repo is tagged for final GA?
and if we need a different pkg repo version between releases, we can update the pkg-repo variable manually
