### ISSUE TITLE
Improve Day 0 experience with TCE setup on AWS by supporting default installs.

### ISSUE THREAD

**Issue by AnilSankar75** [vmware-tanzu/community-edition#3088]
## Feature Request

Improve the day 0 user experience for new users adopting TCE when they are trying to Deploy a Management or Standalone Cluster to AWS. Prior to starting the installs we should support preflight checks that ensure that minimum system requirements for the install are met. (Memory, CPu etc.) This will ensure that the overall experience is a lot faster and better. In following the [documentation ](https://tanzucommunityedition.io/docs/latest/aws/), our install rightfully supports a lot of configuration for the advanced user , however it would be great value add if we can support the with preconfigured " plain vanilla" install...For example profiles and other identity management settings and enabling cloud formation stack by default would simplify this for the user who is simply trying out ... May of the settings in the install are optional and the install screens should pre select the defaults to improve the user experience.

![image](https://user-images.githubusercontent.com/77680585/153066083-f6625e3f-7230-4520-a99e-7cca94284400.png)
![image](https://user-images.githubusercontent.com/77680585/153066134-eae5fd44-423a-4bef-b88a-dd822ecf61ac.png)

**Comment by joshrosso** [comment]
Tracking issues:

* https://github.com/vmware-tanzu/community-edition/issues/3088
