### ISSUE TITLE
Do we want to document alternative workaround for cgroup1 issue?

### ISSUE THREAD

**Issue by kcoriordan** [vmware-tanzu/community-edition#3094]
## Description

Based on  Eric Shanks  experience deploying TCE in this [blog](https://theithollow.com/2022/01/17/tanzu-community-edition-on-vsphere-installation-notes/)

We have a work around documented for cgroup1 [issue ](https://github.com/vmware-tanzu/community-edition/issues/2798) - 
PR https://github.com/vmware-tanzu/community-edition/pull/2837 - to use a docker version that leverages cgroup 1

Do we want to mention or note the alternative workaround used by Eric -  prebuild a kind cluster and use the tanzu cli and the prebuilt kind cluster to deploy the management cluster.

**Comment by ndwinton** [comment]
It looks like there is a better workaround provided by Docker itself as of Docker Desktop 4.4.2, see [the release notes](https://docs.docker.com/desktop/mac/release-notes/#bug-fixes-and-minor-changes-1). There is also more detail in [this issue](https://github.com/docker/for-mac/issues/6073).

Changing the value of `deprecatedCgroupv1` to `true` in `~/Library/Group Containers/group.com.docker/settings.json` causes Docker to revert to cgroups v1 (on a Mac, I would expect something similar on Windows)

**Comment by seemiller** [comment]
Can confirm that the workaround does indeed work! (at least on a Mac)

**Comment by martinborgman** [comment]
The statement in the Docker documentation says it all.

> Added a deprecated option to settings.json: "deprecatedCgroupv1": true, which switches the Linux environment back to cgroups v1. If your software requires cgroups v1, you should update it to be compatible with cgroups v2. Although cgroups v1 should continue to work, it is likely that some future features will depend on cgroups v2. It is also possible that some Linux kernel bugs will only be fixed with cgroups v2.

So why do we need this workaround?

**Comment by joshrosso** [comment]
We'll continue tracking this for v0.11.

If https://github.com/vmware-tanzu/community-edition/issues/2798 resolves as we expect. We can simple close this as a side-effect.

**Comment by joshrosso** [comment]
I own the validation for #2798 so i'll follow up here.

**Comment by joshrosso** [comment]
This will be closed via https://github.com/vmware-tanzu/community-edition/issues/2798
