### ISSUE TITLE
Set up regular jobs to check tanzu-framework compatibility

### ISSUE THREAD

**Issue by stmcginnis** [vmware-tanzu/community-edition#3106]
## Feature Request

It would be great to set up a periodic job to run that pulls in the tanzu-framework and does some basic steps like building and creating an unmanaged cluster or something. Just so we know when something breaking happens.

Today we pick a release of tanzu-framework and stay on that until the next TCE release. Usually the delta between the version we use and the current tanzu-framework release at the time of TCE release should be small, but as we've seen with delays in our v0.10.0 release, there could be times where there are a lot of changes by the time we pick up the next tanzu-framework release.

We are experiencing this now as we move from v0.10.0 development to v0.11.0. We are going from tanzu-framework v0.10.0 to tanzu-framework v0.16.0. There were a lot of changes that happened between those releases, that we now need to play catch up to find and adjust to accomodate.

If we had a regular job that would build against the current source in `main` for `tanzu-framework`, and/or the latest release, even if we are not able to make changes immediately to allow that to pass, we can be aware of those breaking changes and plan for them. If there are any challenges or questions, we can contact the engineers on tanzu-framework that made the changes and ask questions while the change is still fresh in their mind.

Some things to decide for doing this:

- Should we be building framework or pulling their OCI assets
- How do we validate compatibility (for example, is creating an unmanaged cluster adequate, when it has 0 deps on tanzu-framework)
- Who should execute on this integration testing (Rel Eng vs Core Eng)

## Describe alternatives you've considered

It may be nice to have a job in the `tanzu-framework` repo itself that builds and runs TCE with every change, but we may not be at the point yet where that wouldn't be more than a distraction for the tanzu-framework developers.

**Comment by joshrosso** [comment]
We've decided that in the v0.11.0 we'll figure out a plan here.

**Comment by joshrosso** [comment]
Realistically, we won't get to evaluating this until v0.12.0. Could even be later.

**Comment by stmcginnis** [comment]
Given we're staying on `tanzu-framework` v0.11.x for awhile, I think we can move this out to v0.13.0 or icebox for now.
