### ISSUE TITLE
Use --depth 1 once issue related to it in Github CLI get resolve

### ISSUE THREAD

**Issue by aman556** [vmware-tanzu/community-edition#3119]
## Description

To clone the repository in any script we don’t want to pull the complete history by using `git clone REPO_NAME`. There is a option in git command to avoid this by using `git clone --depth 1` but there is a [issue](https://github.com/cli/cli/issues/2979#issuecomment-780490392) in Github cli for this that with `--depth 1` `gh pr create` give error. Due to which can’t use this option for now in scripts mentioned below.
- [hack/choco/update-choco-package.sh](https://github.com/vmware-tanzu/community-edition/blob/main/hack/choco/update-choco-package.sh)
- [hack/homebrew/update-homebrew-package.sh](https://github.com/vmware-tanzu/community-edition/blob/main/hack/homebrew/update-homebrew-package.sh)

The motive of this issue is to track the issue and use `--depth 1` once the other issue get resolved.

**Comment by vschoener** [comment]
FYI. I had this issue lately and we decided to use `treeless clone` instead for our CI for a custom need. 
We found this article https://github.blog/2020-12-21-get-up-to-speed-with-partial-clone-and-shallow-clone/ that explains a different way to clone a repo.

Blobless and treeless works great to use `gh pr create` right after :) You can pick the one that works best for your need.

**Comment by stmcginnis** [comment]
Awesome, thanks for the pointer @vschoener !!

**Comment by dvonthenen** [comment]
This looks like it's in the code base already. Closing.
