### ISSUE TITLE
[Unmanaged Clusters] add support for multi node clusters

### ISSUE THREAD

**Issue by vrabbi** [vmware-tanzu/community-edition#3121]
## Feature Request

I would like to be able to define a multi node kind cluster to be provisioned via the unamanged cluster plugin.

## Describe alternatives you've considered
Deploy a cluster manually via kind and then use the existing kubeconfig in the tce unamanged cluster config file to target that pre created cluster.

## Additional context
For testing of many features on k8s, it is beneficial to have multi node clusters such as, testing CNI inter node functionality, testing daemonsets, simulating failed nodes etc.
Kind has this ability and having it configurable would solve many use cases. Minikube eas something i used to use often but moved to kind as it supports multi node configuration. This would allow for me to use unmanaged clusters and gain the benefits of TCE simply and effectively.

**Comment by thesteve0** [comment]
I would like this as well. If I want to test or develop anything HA I would need at least two worker nodes, but preferably at least 3

**Comment by joshrosso** [comment]
Sounds good. We can do this easily.

I want to clearly set the expectation though that we will **not** support scaling existing clusters, but add support for creating new multi-node clusters.

If scaling existing clusters (a lot more to think about here) is a need, let us know. We'd likely need a new issue.

**Comment by vrabbi** [comment]
For me personally scaling isnt needed.
