### ISSUE TITLE
Add Create Metapackage section 

### ISSUE THREAD

**Issue by cgsamp** [vmware-tanzu/community-edition#3124]
## Description

A meta-package includes a group of existing TCE packages. While a meta-package shares structure with a TCE package, many of the steps are not required. 

Referring to 
https://tanzucommunityedition.io/docs/latest/package-creation-step-by-step/
Step 1 would be simpler, because there is no upstream or overlay directory required. Steps 2-5 are not required at all. We would also discuss concepts unique to meta-packages.

A separate section is warranted, as the package creation process is quite complex, and trying to discuss two concepts at the same time could be difficult for the reader.

We propose creating two sections: "Create an Upstream Package" that is the current "Create a Package" documentation, and "Create a Meta Package" that is the new document discussed here.

## Location

This would appear in the Packages section, parallel to the current Create Package and Work with Packages sections

## Additional Context

We are building the App Platform meta-package within TCE. These instructions do not fit within App Platform documentation and belong in this separate section, to help community members who might like to create a meta-package for other reasons.

NOTE that @mstergianis and @cgsamp propose to author this document

**Comment by seemiller** [comment]
@cgsamp Thanks for submitting this issue. We've looked over it, got a question...

Why do you not see the need for upstream and/or overlay directories?
