### ISSUE TITLE
Download links pointing to unreleased version

### ISSUE THREAD

**Issue by alexbarbato** [vmware-tanzu/community-edition#3143]
## Description

Right now the public docs are pointing to downloading the community edition are pointing to an unreleased version.

## Location
The public docs page - https://tanzucommunityedition.io/docs/latest/cli-installation/
The code (for mac) - https://github.com/vmware-tanzu/community-edition/blob/main/docs/site/content/docs/assets/cli-install-mac.md

An example:
```bash
cd <DOWNLOAD-DIR>
tar xzvf ~/<DOWNLOAD-DIR>/tce-darwin-amd64-{{< release_latest >}}.tar.gz
```

resolving to:
```bash
cd <DOWNLOAD-DIR>
tar xzvf ~/<DOWNLOAD-DIR>/tce-darwin-amd64-v0.10.0.tar.gz
```

**Comment by jpmcb** [comment]
Let's plan to disconnect the automation that is associated with bumping the version in the docs site and associated yaml file here: https://github.com/vmware-tanzu/community-edition/pull/3138/files
