### ISSUE TITLE
Netlify preview cancelled 

### ISSUE THREAD

**Issue by kcoriordan** [vmware-tanzu/community-edition#3157]
## Description

(There might be a dup of this issue but I can't find it)
In the PR checks, **sometimes** the Netflify preview is canceled with message:
`netflify/quirky-franklin-8969be/deploy-preview - Deploy Preview cancelled `

the preview link can be created manually by adding the `PR-NUMBER` into:

`https://deploy-preview-_<PR-NUMBER>_--quirky-franklin-8969be.netlify.app/`

It's an inconsistent behavior. It seems to be related to these 

![image](https://user-images.githubusercontent.com/80768390/154266720-d0b8d5dc-299f-4f9c-b066-d3ea415fe2de.png)

these are some examples: 

https://github.com/vmware-tanzu/community-edition/pull/3120

https://github.com/vmware-tanzu/community-edition/pull/3122

https://github.com/vmware-tanzu/community-edition/pull/2862

**Comment by jpmcb** [comment]
cc @jonasrosland might know or have context? 👀

**Comment by jonasrosland** [comment]
This happens sometimes, I've now reached out to Netlify's support.
The deploy log states `Failed during stage 'checking build content for changes': Canceled build due to no content change` which is obviously incorrect.

**Comment by joshrosso** [comment]
Going to close for now. Let's re-open if it continues to be a large issue.
