### ISSUE TITLE
Improve documentation for users for creating workload clusters.

### ISSUE THREAD

**Issue by AnilSankar75** [vmware-tanzu/community-edition#3163]
## Description

I was following this documentation https://tanzucommunityedition.io/docs/latest/workload-clusters/ 
to create workload clusters on AWS infrastructure. 
1. The step 10 captures this command line "tanzu cluster create <WORKLOAD-CLUSTER-NAME> --file <CONFIG-FILE>"
and below it says that if workload cluster name is not specified it will pick from the configuration file.  I dont think that option works as you constantly get this error from the command line if you run it without the cluster name 
"C:\Users\anilsankar>tanzu cluster create --file "C:\Temp\awsworkloadcluster"
Error: cluster name is required, please provide cluster name"
this behaviour is from a windows client PC.

2.It will be ideal to include an actual example that can be edited to be run on the clients machines 

The optional step "Attach a workload cluster to Tanzu Mission Control [¶](https://tanzucommunityedition.io/docs/latest/workload-clusters/#optional-attach-a-workload-cluster-to-tanzu-mission-control)"
currently does not work and it should be updated .

## Location

https://tanzucommunityedition.io/docs/latest/workload-clusters/

**Comment by kcoriordan** [comment]
@AnilSankar75 
I'm following up on both points above, do you have any more details on where the failure occurred with the attach the wl cluster to TMC?

**Comment by AnilSankar75** [comment]
@kcoriordan , Sorry just saw this comment, Basically I was just trying to create workload cluster independently with the TCE [documentation ](https://tanzucommunityedition.io/docs/latest/workload-clusters/)prior to attaching to TMC... and currently it does not pick up the workload cluster name from the configuration file...You have to specify in the command like...(Contrary to what step 10 says in the documentation.)

**Comment by kcoriordan** [comment]
I think this might be a Tanzu Frame work issue, as far as I can gather the information in doc is correct.
Do you think there is an issue with your cluster name in the config file:
>Workload cluster names must be must be 42 characters or less, and must comply with DNS hostname requirements as amended in [RFC 1123](https://tools.ietf.org/html/rfc1123).

https://github.com/vmware-tanzu/tanzu-framework

**Comment by stmcginnis** [comment]
I've filed an issue in `tanzu-framework` for this: https://github.com/vmware-tanzu/tanzu-framework/issues/1753

We can use this issue to track that to inclusion in a TCE release.
