### ISSUE TITLE
Bug Report Template refers to Standalone instead of Unmanaged cluster

### ISSUE THREAD

**Issue by kartiklunkad26** [vmware-tanzu/community-edition#3181]
## Bug Report

Bug Report Template should refer to Unmanaged cluster

**Comment by jpmcb** [comment]
Note that this is being slated for `v0.11.0`. The newly shipped `v0.10.0` of TCE has _both_ the unmanaged and standalone cluster plugins.

**Comment by jpmcb** [comment]
This was already tackled in https://github.com/vmware-tanzu/community-edition/pull/3169 and is on the `next` branch.

The `next` branch will merge into `main` soon and the issues template will reflect that change.
