### ISSUE TITLE
Mirror Tanzu CLI Installation on Managed Clusters with Unmanaged Clusters

### ISSUE THREAD

**Issue by kartiklunkad26** [vmware-tanzu/community-edition#3213]
## Description
The docs to install Tanzu CLI are nicely simplified for Unmanaged Clusters in the Getting Started section.  We should use the same for Managed Clusters as well. 

## Location
Location that needs updating -> [Getting Started with Managed Clusters](https://tanzucommunityedition.io/docs/latest/getting-started/)

[Getting Started with Unmanaged Clusters](https://tanzucommunityedition.io/docs/latest/getting-started-unmanaged/)

## Additional Context

**Comment by joshrosso** [comment]
Agree with this sentiment. Won't block v0.11 release, moving to v0.12

**Comment by kartiklunkad26** [comment]
@kcoriordan

**Comment by kcoriordan** [comment]
Hey Kartik, this should have been closed when PR 3459 was merged - right?
@kartiklunkad26
