### ISSUE TITLE
Azure docs reference incorrect image name

### ISSUE THREAD

**Issue by seemiller** [vmware-tanzu/community-edition#3215]
## Bug Report

When installing on Azure, the [documentation](https://tanzucommunityedition.io/docs/latest/azure-mgmt/#accept-the-base-image-license) states that you must first accept a license agreement for the `k8s-1dot21dot2-ubuntu-2004` image. For the latest release, that image is actually `k8s-1dot21dot5-ubuntu-2004`.

## Expected Behavior

The documentation should reference the correct image to approve the license for.

## Steps to Reproduce the Bug

Try to install TCE to Azure following the documentation. The process will timeout during the stage of "scaling up" the management cluster with a generic message.

To actually see the problem, you must look at the logs of the capz-controller-manager pod.

```shell
kubectl logs capz-controller-manager-794d9b899b-h9kq2 -n capz-system --kubeconfig /Users/seemiller/.kube-tkg/tmp/config_OwJRZBNb
...
E0222 18:22:12.088995       1 controller.go:257] controller-runtime/controller "msg"="Reconciler error" "error"="failed to create AzureMachineService: failed to create virtual machine: failed to create VM tce22mgr-control-plane-prqln in resource group tce22: compute.VirtualMachinesClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code=\"ResourcePurchaseValidationFailed\" Message=\"User failed validation to purchase resources. Error message: 'You have not accepted the legal terms on this subscription: '09d77e6a-6154-4098-a191-5de31f319155' for this plan. Before the subscription can be used, you need to accept the legal terms of the image. To read and accept legal terms, use the Azure CLI commands described at https://go.microsoft.com/fwlink/?linkid=2110637 or the PowerShell commands available at https://go.microsoft.com/fwlink/?linkid=862451. Alternatively, deploying via the Azure portal provides a UI experience for reading and accepting the legal terms. Offer details: publisher='vmware-inc' offer = 'tkg-capi', sku = 'k8s-1dot21dot5-ubuntu-2004', Correlation Id: '0698b903-9f4f-4c60-808b-433349521da9'.'\"" "controller"="azuremachine" "name"="tce22mgr-control-plane-prqln" "namespace"="tkg-system"
```

## Environment Details

* Build version (`tanzu version`): 
* Deployment (Managed/Standalone cluster): 
* Infrastructure Provider (Docker/AWS/Azure/vSphere): 
* Operating System (client):

**Comment by joshrosso** [comment]
@kcoriordan could we prioritize doing a quick fix here for v0.10.0 docs (the live site)

Hit up @seemiller if you have Q on what the image should be.
