### ISSUE TITLE
tanzu management-cluster create --ui fails to open browser

### ISSUE THREAD

**Issue by LarryBetson** [vmware-tanzu/community-edition#3217]
## Bug Report

Installing Tanzu Commnuity edition on vSphere using a CentOS-7 VM as the bootstrap node. 

## Expected Behavior

When I run this command:
`tanzu management-cluster create --ui `
I expect it to open a browser or if I click the link that it will open up in my browser. I get this error and when I try to ctrl-click the link nothing comes up in my browser.
```
Validating the pre-requisites...
Serving kickstart UI at http://127.0.0.1:8080
unable to open browser: exit status 3
```

## Steps to Reproduce the Bug

`tanzu management-cluster create --ui `

## Environment Details

* Tanzu version: v0.10.1, buildDate: 2022-02-22, sha: 401d55b
* Deployment - Standalone 
* Infrastructure Provider - vSphere 
* Operating System (client) - CentOS Linux release 7.9.2009 (Core)

**Comment by stmcginnis** [comment]
Thanks for reporting this @LarryBetson. Just to confirm, you have a full desktop environment on this machine, right?

If not, or if connecting remotely via SSH, you may need to follow the headless installation instructions found here: https://tanzucommunityedition.io/docs/latest/headless-install/

One thing we can check - can you run `xdg-open https://tanzucommunityedition.io` and verify the system is able to launch a browser instance?

**Comment by LarryBetson** [comment]
Thank you for the quick response. 

I do not have a full desktop environment on the bootstrap node. It's a minimal install with just the tools required or installed as needed. And yes I am connecting to the bootstrap node via ssh. So, yes this would be considered a headless environment then.

I can easily destroy the node and create a new one with a desktop environment. You can close this issue out as I just did that and the web UI works fine through centos desktop version. Thank you.

**Comment by v-aj-armada-ai** [comment]
I am using Ubuntu VM. I am facing the same issue. Could you please suggest any fixes?

ubuntu@master:~$ tanzu management-cluster create --ui

Validating the pre-requisites...
Serving kickstart UI at http://127.0.0.1:8080
unable to open browser: exit status 3

**Comment by amarnathcommits** [comment]
I am using a ubuntu VM and I am facing the same issue. Can anybody help me?

ubuntu@master:~$ tanzu management-cluster create --ui

Validating the pre-requisites...
Serving kickstart UI at http://127.0.0.1:8080
unable to open browser: exit status 3
