### ISSUE TITLE
🙏 Please downgrade minimal requirements to 2 CPU (instead of 4)

### ISSUE THREAD

**Issue by adriens** [vmware-tanzu/community-edition#3222]
## 🗣️ Feedback

Hi I wanted to write a katacoda scenario for my team mates. Everything ran pretty well until I faced the minimal requirement of CPUs.

I made an issue to Katacoda Team, and they thold be we were stuck on 2 CPU on the community edition of Katacoda.

I guess it would be really worth try to downgrade minimal requirements so people could play with it on Katacoda community

## 🙏 Suggested Changes

👉 For Docker install, downgrade minimal nb. of CPU from 4️⃣  to 2️⃣ 

## 📑 Environment Details

- Katacoda community version

## Katacoda feedbacks

https://oreilly-media-support.atlassian.net/servicedesk/customer/portal/1/KHD-1499

![image](https://user-images.githubusercontent.com/5235127/155251795-1d5b017d-1e25-4cc8-88fc-7c2cc090f8bb.png)

![image](https://user-images.githubusercontent.com/5235127/155251869-8d22ddba-f379-4149-96e8-397eeac35912.png)

**Comment by jpmcb** [comment]
Hi @adriens - thanks for opening this issue with this feedback!

For `management-cluster`, I don't believe we can go much lower than 4 CPUs. But have you [considered trying `unmanaged-cluster`?](https://github.com/vmware-tanzu/community-edition/tree/main/cli/cmd/plugin/unmanaged-cluster#readme)

It's a single node cluster that deploys ontop of kind with much lower resource requirements. All the "tanzu bits" get installed there, including kapp controller and our package repo.

**Comment by jorgemoralespou** [comment]
@jpmcb isn't there a minimium requirements preflight check for any type of cluster? Although I guess that for Docker on Linux that does not exist, as it'll take whatever the host can take.

**Comment by jpmcb** [comment]
Yes, there are also pre-flight checks for `unmanaged-cluster`, but it's resource requirements are much smaller:

https://github.com/vmware-tanzu/community-edition/blob/36d86446867fce6b09d4c098d80e66ecf2e46998/cli/cmd/plugin/unmanaged-cluster/cluster/kind.go#L24-L25

So only 1 CPU for unmanaged

**Comment by adriens** [comment]
Hmmm, these are pretty good news ❣️ 

Here is the final command I run : 

```
tanzu management-cluster create -i docker --name tanzu-community.katacoda.com -v 10 --plan dev --ceip-participation=false
```

Which command would you like me to consider to switch to `unmanaged-cluster` ❔ 🙏

**Comment by stmcginnis** [comment]
You could instead run:

```
brew install vmware-tanzu/tanzu/tanzu-community-edition
/home/tanzu/.linuxbrew/Cellar/tanzu-community-edition/v0.10.0/libexec/configure-tce.sh

tanzu unmanaged-cluster create tanzu-community.katacoda.com
```

That would get you a one node cluster, running in docker, that uses a minimal amount of RAM and CPU.

**Comment by adriens** [comment]
Hi @jpmcb .

I could not work on that item but I should be able to do it this morning. Hence, a feedback should come within a few hours today 🤞

**Comment by adriens** [comment]
Here we go for the feedbacks 🎆 : 

Actually : 

```
brew install vmware-tanzu/tanzu/tanzu-community-edition /home/tanzu/.linuxbrew/Cellar/tanzu-community-edition/v0.10.0/libexec/configure-tce.sh
```

leads to the following log : 

```
Warning: No available formula or cask with the name "/home/tanzu/.linuxbrew/cellar/tanzu-community-edition/v0.10.0/libexec/configure-tce.sh".
Please tap it and then try again: brew tap /home
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
```
![image](https://user-images.githubusercontent.com/5235127/156071876-7358fc87-a161-4076-b522-a3b40c4c7877.png)

**Comment by adriens** [comment]
What should I do to _"tap it"_ 🙏 ❔

**Comment by stmcginnis** [comment]
Hey @adriens - looks like you have a typo in that command that combined the two lines. First, just run:

```
brew install vmware-tanzu/tanzu/tanzu-community-edition
```

Then that will give you the next step to run the setup script that does a few things that brew isn't able to handle. It will likely be `/home/tanzu/.linuxbrew/Cellar/tanzu-community-edition/v0.10.0/libexec/configure-tce.sh`, but check the output to make sure.

Hope that helps!

**Comment by adriens** [comment]
Now, got this : 

![image](https://user-images.githubusercontent.com/5235127/156076571-5915eb73-a2dd-410a-9264-a4a505984426.png)

**Comment by adriens** [comment]
I could go a bit further now.

When I run

```
tanzu management-cluster create -i docker --name tanzu-community.katacoda.com -v 10 --plan dev --ceip-participation=false
```

I get : 

![image](https://user-images.githubusercontent.com/5235127/156077378-00094385-0708-4067-b736-bcab4a452ea5.png)

hence back to the CPU limitation 🤔

**Comment by adriens** [comment]
Gues I should now try 

```
tanzu unmanaged-cluster create tanzu-community.katacoda.com
```

**Comment by adriens** [comment]
I'm building a new session from scratch ...

**Comment by adriens** [comment]
Fianlly these commands 👇 

```
brew install vmware-tanzu/tanzu/tanzu-community-edition
/home/tanzu/.linuxbrew/Cellar/tanzu-community-edition/v0.10.0/libexec/configure-tce.sh
```

```
tanzu unmanaged-cluster create tanzu-community.katacoda.com
```

lead me to 👇 


![image](https://user-images.githubusercontent.com/5235127/156078820-6f6e25ea-696e-46b4-b79e-d3445ddafe98.png)

**Comment by jpmcb** [comment]
@adriens - This is working for me on a new VM:

Linux brew is installed:
```
$ which brew
/home/linuxbrew/.linuxbrew/bin/brew
```

Install TCE:
```
$ brew install vmware-tanzu/tanzu/tanzu-community-edition
```

Run script to configure TCE:
```
/home/linuxbrew/.linuxbrew/Cellar/tanzu-community-edition/v0.10.0/libexec/configure-tce.sh
```

And I am able to create an unmanaged-cluster:
```
$ tanzu unmanaged-cluster create test

📁 Created cluster directory

🔧 Resolving Tanzu Kubernetes Release (TKR)
...
```

Looks like you may have tried to do an uninstall from that latest screenshot or is that output from `unmanaged-cluster create`?

**Comment by jpmcb** [comment]
Hi @adriens - checking in again! 👀 

Any more luck getting an unmanaged-cluster up and running?

**Comment by adriens** [comment]
Hi @jpmcb , sorry for lack of feedback form my part as I could not dedicate the time I would have liked to to this task.

I'm working on it this morning ❣️ 🙌  and will let you know 🤞

**Comment by adriens** [comment]
Now, things are going pretty well... I could go trough Katacoda CPU limitations... but now facin memmory limitations 😢 
![image](https://user-images.githubusercontent.com/5235127/157532547-33785d97-abc2-45f7-896b-c5e01fb229ca.png)

Note sure we'll can go over this one 🥲

**Comment by stmcginnis** [comment]
Yeah, looks like those instances actually have a little less than 2 GiB of memory.

It doesn't sound like you'll be running very resource hungry things with this. You could try updating your `tanzu unmanaged-cluster create` command to include the `--skip-preflight` argument. That will disable ALL preflight checks, but if you are deploying this into a known environment, and are able to do what you need to do without the full 2GiB RAM, then that might be fine for your case.

**Comment by adriens** [comment]
> It doesn't sound like you'll be running very resource hungry things with this.

Absolutely. I just want to show how to get a minimalist TCE instance up and running.

👉 Yes, I'm giving it a try right now 🚀

**Comment by adriens** [comment]
⏳ 🤞 
![image](https://user-images.githubusercontent.com/5235127/157535685-3d27da0c-146b-4c19-9fa9-9106ae211296.png)

**Comment by adriens** [comment]
![image](https://user-images.githubusercontent.com/5235127/157535766-2f516211-773e-4a83-b028-5ab1c949dadf.png)

**Comment by adriens** [comment]
![image](https://user-images.githubusercontent.com/5235127/157536150-90d8f77d-428f-48bf-8a2c-2b534787ceb5.png)

**Comment by adriens** [comment]
Looks good ❣️

**Comment by adriens** [comment]
![image](https://user-images.githubusercontent.com/5235127/157536482-eb4a89b7-338a-499a-8c56-a90e29d725ba.png)

**Comment by adriens** [comment]
And finally 
![image](https://user-images.githubusercontent.com/5235127/157536979-c253d1a7-2e06-4820-b38f-169435ada134.png)

**Comment by adriens** [comment]
`K9S` user experience : 

![image](https://user-images.githubusercontent.com/5235127/157537072-2c342200-7b31-4496-9f9d-dd3fba3c534d.png)

**Comment by adriens** [comment]
@jpmcb , according to your knwoledge, what kind of dummy like deloyment could I run to finalize this short intro ? Any TCE content you could point so I can add it at the end of this "TCE install for dummies" ❔

**Comment by adriens** [comment]
@jpmcb : here we go on [Katacoda](https://katacoda.com/opt-labs/courses/tanzu-community) :gift:

**Comment by adriens** [comment]
I thnonk we can close the issue now :rocket:

**Comment by jpmcb** [comment]
> according to your knwoledge, what kind of dummy like deloyment could I run to finalize this short intro ? Any TCE content you could point so I can add it at the end of this "TCE install for dummies" grey_question

There are a few solution guides that might be interesting on our docs site. Maybe having a user install the prometheus, grafana stack would be cool? https://tanzucommunityedition.io/docs/latest/docker-monitoring-stack/

Will close this out! Thanks for the great feedback! I'll open a new issue to add a `skip-preflight` flag like Sean suggested

**Comment by adriens** [comment]
@jpmcb : 

> There are a few solution guides that might be interesting on our docs site. Maybe having a user install the prometheus, grafana stack would be cool?

Putting 💯 💵  on that ⚡

**Comment by adriens** [comment]
Sorry it's in french, but here is the [full dedicated DEV.to post](https://dev.to/optnc/running-tanzu-unmanaged-cluster-on-very-low-resources-15g1)
