### ISSUE TITLE
Create OCI Plugin Releases

### ISSUE THREAD

**Issue by joshrosso** [vmware-tanzu/community-edition#3234]
## Summary

We should create a script that can:

1. Copy TF plugins into TCE's OCI repo
2. Create a plugin release manifest
3. Push the plugin release manifest to TCE's OCI repo

### 1. Copy TF plugins into TCE's OCI repo

We must be able to copy TF's plugin releases using `imgpkg`. The following image shows how the copy should occur:

![image](https://user-images.githubusercontent.com/6200057/155419820-95abda81-b649-4abf-843c-b41b221e90cc.png)

### 2. Create a plugin release manifest

Pull and unpack the contents of `projects.registry.vmware.com/tce/cli-plugins/release:v0.10.0-dev.5` to see a finalized release manifest. See https://github.com/vmware-tanzu/community-edition/pull/3112/files to understand how this is done. Using this PR, polish up the steps and wire in a simplified scrip that can execute and create this manifest.

Note that you will point to CLI images that have already been pushed, that work is part of:

* https://github.com/vmware-tanzu/community-edition/issues/3233

### 3. Push the plugin release manifest to TCE's OCI repo

The manifest (bundle) produced in step 2, should be pushed to `projects.registry.vmware.com/tce/cli/release:${TCE-VERSION}`

## Additional Information

See the PR here:

* https://github.com/vmware-tanzu/community-edition/pull/3112/files

That demonstrates the model described above.

**Comment by joshrosso** [comment]
@karuppiah7890 is added here. @seemiller owns the initial work. Release engineering should then handle the triggering of it (via automation) and maintencne of it over time.

@karuppiah7890 feel free to assign someone from your team if you're not the right human.

**Comment by joshrosso** [comment]
This won't be relevant for `v0.12.0` because we cannot afford to change this model until _potentially_ `v0.13.0`.

**Comment by johnSchnake** [comment]
@joshrosso ping me if I can help with this. I keep having packaging conversations w.r.t. Sonobuoy (the conformance plugin) and I'd like to just be involved more with how it is/will be implemented here. I'm considering doing something like this for the Sonobuoy repo itself, so if landing something there would be helpful, let me know.

**Comment by joshrosso** [comment]
> @joshrosso ping me if I can help with this. I keep having packaging conversations w.r.t. Sonobuoy (the conformance plugin) and I'd like to just be involved more with how it is/will be implemented here. I'm considering doing something like this for the Sonobuoy repo itself, so if landing something there would be helpful, let me know.

@johnSchnake, apologies I missed this notification.

Will do. Near-term we're stopping our incrementing of tanzu-framework and aren't going to change anything about our plugin model.  Depending on where you're looking to include Sonobuoy (e.g. TKG) doing this work may still be valuable on your end.

Happy to chat more in Slack on this if I can clarify.
