### ISSUE TITLE
Doc that on umanaged clusters, the only options for provider is kind or none

### ISSUE THREAD

**Issue by thesteve0** [vmware-tanzu/community-edition#3238]
## Description
In reading more about unmanaged clusters, the doc says:
``` By default, they run locally via kind with Tanzu components installed atop```

But according to Sean:
```We've implemented a provider interface, but right now the only options are kind or none , using the --provider switch. There are some use cases being worked out for none where this plugin can be used to tie in to other workflows to get the tanzu bits on top of a cluster created outside of TCE.```

A quick note in the doc to state that only those options are supported would be good for clarity.

**Comment by jpmcb** [comment]
I'm not sure this would actually be helpful to end users in our main documentation.

We do document this in the [`unmanaged-cluster` README](https://github.com/vmware-tanzu/community-edition/tree/main/cli/cmd/plugin/unmanaged-cluster#readme) which _consumers_ of the `unmanaged-cluster` go code can go to and find out more about how it works and it's APIs.

**Comment by joshrosso** [comment]
Let's expand the reference documentation to list available providers.

@kcoriordan can you add a new section which specified the list of available providers. They should be `none` or `kind`, today.

**Comment by jpmcb** [comment]
Now, with the introduction of the `minikube` provider, users can specify: `kind`, `minikube`, or `none` (only usable with the `-e` flag for using an existing cluster).

Today, in the unmanaged-cluster ref documentation, we have a section on both the `minikube` and `kind` provider:
https://github.com/vmware-tanzu/community-edition/blob/main/docs/site/content/docs/ref-unmanaged-cluster.md#using-a-different-cluster-provider

We also have a section on using an existing cluster:
https://github.com/vmware-tanzu/community-edition/blob/main/docs/site/content/docs/ref-unmanaged-cluster.md#using-a-different-cluster-provider

Is this sufficient? Can we close this issue?

**Comment by kcoriordan** [comment]
I think it's called out clearly now @jpmcb closing this.
