### ISSUE TITLE
Until #3058 is fixed, can we make calico the default CNI for unmanaged clusters

### ISSUE THREAD

**Issue by thesteve0** [vmware-tanzu/community-edition#3239]
## Feature Request

There is already a bug #3058 which tracks the problem that unmanaged clusters are non-reachable after a machine or docker restart. If we made calico the default CNI for unmanaged clusters then it would provide a much better experience for users on their local machine. 

Developers and sysadmins generally do not want to have to delete and recreate their clusters when they restart their machines. This issue will make it harder to gain adoption for unmanaged clusters for anything but ephemeral test clusters. 

Antrea will still be available as an option and once Antrea is fixed we can then set that back to the default. 

Since this is just a configuration change, it would be great if we could target the 0.11 release

**Comment by stmcginnis** [comment]
cc @jpmcb

**Comment by jpmcb** [comment]
Created https://github.com/antrea-io/antrea/issues/3386

Waiting to hear back if there's a simple fix that we could potentially apply in our `unmanaged-cluster` kind provider

**Comment by joshrosso** [comment]
Pasting in a screenshot from slack so everyone is in the loop.

Let's actually *not* wait and switch to Calico now. We can revisit switching back if this is changed. This has been approved by PM. See below. Thanks all!

![image](https://user-images.githubusercontent.com/6200057/156814217-d644e8a9-5be0-480e-94b6-02fbc4e3f9b8.png)
