### ISSUE TITLE
Failure while deploying management cluster (Vcentre)

### ISSUE THREAD

**Issue by snehalbiche** [vmware-tanzu/community-edition#3243]
## Bug Report
while deploying management cluster it fails with the below message on UI:

 [0223 09:24:03.46246]: clusterclient.go:523] cluster control plane is still being initialized: WaitingForControlPlane  
 [0223 09:24:18.52096]: clusterclient.go:523] cluster control plane is still being initialized: ScalingUp ‼ 
 [0223 09:54:33.50469]: init.go:700] Failure while deploying management cluster, Here are some steps to investigate the cause: ‼ 
 [0223 09:54:33.50479]: init.go:701] Debug: ‼
 [0223 09:54:33.50481]: init.go:702] kubectl get po,deploy,cluster,kubeadmcontrolplane,machine,machinedeployment -A --kubeconfig /home/krachchh/.kube-tkg/tmp/config_ze9wtEpD ‼ 
 [0223 09:54:33.50487]: init.go:703] kubectl logs deployment.apps/<deployment-name> -n <deployment-namespace> manager --kubeconfig /home/krachchh/.kube-tkg/tmp/config_ze9wtEpD ‼ 
 [0223 09:54:33.50499]: init.go:706] To clean up the resources created by the management cluster: ‼ 
 [0223 09:54:33.50502]: init.go:707] tanzu management-cluster delete ✘ 
 
 [0223 09:54:33.50507]: init.go:85] unable to set up management cluster, : unable to wait for cluster and get the cluster kubeconfig: error waiting for cluster to be provisioned (this may take a few minutes): timed out waiting for cluster creation to complete: cluster control plane is still being initialized: ScalingUp 

machine.cluster.x-k8s.io/tanzumgmtt-control-plane-22dnl  pod remains in provisioning state and is unable to resolve the issue, looked at the tanzu document for requirement on Vsphere deployment and all looks good to me.  
even tried connecting to nodes but its refusing connection and also unable to fetch log or describe pod to know more about this error. 

NAMESPACE    NAME                                  PHASE
tkg-system   cluster.cluster.x-k8s.io/tanzumgmtt   Provisioned

NAMESPACE    NAME                                                                         INITIALIZED   API SERVER AVAILABLE   VERSION            REPLICAS   READY   UPDATED   UNAVAILABLE
tkg-system   kubeadmcontrolplane.controlplane.cluster.x-k8s.io/tanzumgmtt-control-plane                                        v1.21.5+vmware.1   1                  1         1

NAMESPACE    NAME                                                        PROVIDERID                                       PHASE          VERSION
tkg-system   machine.cluster.x-k8s.io/tanzumgmtt-control-plane-22dnl     vsphere://42354c0e-0453-f765-175a-26bc549a050b   Provisioning   v1.21.5+vmware.1
tkg-system   machine.cluster.x-k8s.io/tanzumgmtt-md-0-549ccff488-gbglf                                                    Pending        v1.21.5+vmware.1
tkg-system   machine.cluster.x-k8s.io/tanzumgmtt-md-0-549ccff488-jztrc                                                    Pending        v1.21.5+vmware.1
tkg-system   machine.cluster.x-k8s.io/tanzumgmtt-md-0-549ccff488-z64br                                                    Pending        v1.21.5+vmware.1

NAMESPACE    NAME                                                 PHASE       REPLICAS   READY   UPDATED   UNAVAILABLE
tkg-system   machinedeployment.cluster.x-k8s.io/tanzumgmtt-md-0   ScalingUp   3                  3         3
## Expected Behavior

up and running management cluster on vsphere 

## Steps to Reproduce the Bug
1) with two ESXi cluster 
2) install tanzu cli
3) run command tanzu management-cluster create --ui --bind <IP>:5555 --browser none
4) follow on-screen instructions

## Environment Details

* Build version (`tanzu version`): 
* version: v0.10.1
buildDate: 2022-02-14
sha: 401d55b
* Deployment (Managed/Unmanaged cluster): Managed
* Infrastructure Provider (Docker/AWS/Azure/vSphere): vSphere
* Operating System (client): ubuntu 18.4
[bootstrap.tkg-kind-c8b3ukkpfsecuombo470.diagnostics.tar.gz](https://github.com/vmware-tanzu/community-edition/files/8130330/bootstrap.tkg-kind-c8b3ukkpfsecuombo470.diagnostics.tar.gz)
[home.zip](https://github.com/vmware-tanzu/community-edition/files/8130332/home.zip)
[management-cluster.tanzumgmtt.diagnostics.tar.gz](https://github.com/vmware-tanzu/community-edition/files/8130333/management-cluster.tanzumgmtt.diagnostics.tar.gz)

## Diagnostics and log bundle

diagnostics logs are attached.

**Comment by snehalbiche** [comment]
ok so this "tanzumgmtt-control-plane-22dnl" is control plan VM but not sure about why control plan is in provisioning state?
is this because K8S cluster is not coming up? I am even unable to login to control plan VM to find out whats wrong :( 

                "name": "tanzumgmtt-control-plane-22dnl",
                "namespace": "tkg-system",
                "ownerReferences": [
                    {
                        "apiVersion": "controlplane.cluster.x-k8s.io/v1alpha3",
                        "blockOwnerDeletion": true,
                        "controller": true,
                        "kind": "KubeadmControlPlane",
                        "name": "tanzumgmtt-control-plane",
                        "uid": "f81879b9-765c-43fd-9e75-8c5abc4eab80"
                    }
                ],
                "resourceVersion": "4261",
                "uid": "a13b9298-57fa-4e6b-968e-8b6f4176bd56"
            },
            "spec": {
                "bootstrap": {
                    "configRef": {
                        "apiVersion": "bootstrap.cluster.x-k8s.io/v1alpha3",
                        "kind": "KubeadmConfig",
                        "name": "tanzumgmtt-control-plane-2dtfk",
                        "namespace": "tkg-system",
                        "uid": "c4a40b90-d640-48c5-9ac5-d433fc291895"
                    }
                },
                "infrastructureRef": {
                    "apiVersion": "infrastructure.cluster.x-k8s.io/v1alpha3",
                    "kind": "VSphereMachine",
                    "name": "tanzumgmtt-control-plane-jdqqv",
                    "namespace": "tkg-system",
                    "uid": "d3fff422-45d1-4c25-b0b5-7a62588064ec"
                },
                "metadata": {},
                "providerID": "vsphere://42354c0e-0453-f765-175a-26bc549a050b",
                "version": "v1.21.5+vmware.1"
            },
            "status": {
                "addresses": [
                    {
                        "address": "10.14.7.72",
                        "type": "ExternalIP"
                    }
                ],
                "bootstrapReady": true,
                "infrastructureReady": true,
                "lastUpdated": "2022-02-23T14:24:05Z",
                "phase": "Provisioning"
            }
        },

**Comment by snehalbiche** [comment]
ok now I have even tried deploying standalone cluster and it confirms issue with brining up k8s cluster.
 [0225 07:56:58.65997]: clusterclient.go:523] cluster control plane is still being initialized: WaitingForKubeadmInit

The question is : my control plan is having single IP address assigned using DHCP and its running on internal VLAN? is that a problem? does this control plan needs access to public network to reach K8S and download binaries?

**Comment by stmcginnis** [comment]
> does this control plan needs access to public network to reach K8S and download binaries?

Yes, looks like this may be the source of your problems. The cluster needs internet access to pull container images, so this could be why the deployment fails.

**Comment by snehalbiche** [comment]
Hi Sean McGinnis,

Thanks for replying, could you please let me know then if we need internet access which will be a public interface then where the DHCP comes into the picture? and if the same image is used to deploy worker nodes and as normally org don't want to expose cluster and worker nodes to the internet then how to assign to limit this exposure in internal test labs?

Thanks,
Snehal

**Comment by stmcginnis** [comment]
Typically this is done just using the normal DHCP services on a subnet. You mention exposing nodes to the internet - are you directly exposed publicly? I would highly recommend against that. It would be best to have your local subnet - with DHCP services - limited to local traffic, with some sort of router providing access to the internet.

**Comment by snehalbiche** [comment]
let me describe more:

In our lab, we have public VLAN and private VLAN. the internet can be only reached using proxy on public VLAN. 

This public VLAN strictly does not allow DHCP and IP addresses to be configured manually. 

In this case, I won't be able to bring up a DHCP server on public VLAN which will configure IP address to control plan and worker nodes. 
neither using private VLANs VM's will be able to access the internet. 

in this case what should be the solution to deploy the Tanzu community edition?

**Comment by stmcginnis** [comment]
In this case, other than using a different environment, you will need to set up a DHCP server within your private VLAN as well as some sort of proxy to allow internet access.

Some notes about network requirements can be found here: https://tanzucommunityedition.io/docs/latest/vsphere/#before-you-begin

**Comment by stmcginnis** [comment]
Closing this as the requirements for networking are documented here: https://tanzucommunityedition.io/docs/latest/vsphere/#before-you-begin

If there are any other issues after addressing those prerequisites, let's open a new issue and track it there.
