### ISSUE TITLE
Run e2es on Windows-based systems

### ISSUE THREAD

**Issue by dvonthenen** [vmware-tanzu/community-edition#3247]
## Feature Request

Putting this in the v0.11.0 milestone knowing this probably won't get completed by then... it's simply just to track and prioritize this so that it can be moved into the v0.12.0/next milestone.

We need to duplicate the goals of the e2es currently done on Linux but exercise the functionality on the Windows platform. This can (and should) be done in the easiest way possible. This could mean (and just floating some ideas) that we use windows GitHub runners, or spin up Windows VMs on Azure, or etc. We should probably scope which method we want to use. Just a reminder, we probably don't want to expose repo secrets when implementing this functionality.

**Comment by joshrosso** [comment]
As stated in original description, moving to v0.12.0

**Comment by joshrosso** [comment]
Assigning @karuppiah7890 as the initial owner of this ticket.

We'll leave it to @karuppiah7890 to assess if this is possible for `v0.12.0` and/or delegate it to other(s).
