### ISSUE TITLE
Improve scaling docs to include troubleshooting steps

### ISSUE THREAD

**Issue by jakerobinson** [vmware-tanzu/community-edition#3253]
## Description

I am having an issue with scaling and would like to know where the log files are located. It would be helpful if there was a small troubleshooting section on this page (and possibly every page) to detail how to see what is going on for both learning and troubleshooting purposes.

## Location

https://tanzucommunityedition.io/docs/latest/scale-cluster/

## Additional Context

`tanzu cluster get <cluster name>` is handy for an overview, but where do I go from here?

```
$ tanzu cluster get sand1-tanzu-workload01
  NAME                    NAMESPACE  STATUS    CONTROLPLANE  WORKERS  KUBERNETES        ROLES   
  sand1-tanzu-workload01  default    updating  1/1           1/2      v1.21.2+vmware.1  <none>  
ℹ  

Details:

NAME                                                                       READY  SEVERITY  REASON         SINCE  MESSAGE         
/sand1-tanzu-workload01                                                    True                            2d3h                   
├─ClusterInfrastructure - VSphereCluster/sand1-tanzu-workload01            True                            2d3h                   
├─ControlPlane - KubeadmControlPlane/sand1-tanzu-workload01-control-plane  True                            2d3h                   
│ └─Machine/sand1-tanzu-workload01-control-plane-h7q9k                     True                            2d3h                   
└─Workers                                                                                                                         
  └─MachineDeployment/sand1-tanzu-workload01-md-0                                                                                 
    ├─Machine/sand1-tanzu-workload01-md-0-6f4787dd49-6874k                 True                            16h                    
    └─Machine/sand1-tanzu-workload01-md-0-6f4787dd49-cm86j                 False  Warning   CloningFailed  6m37s  1 of 2 completed
    ```

**Comment by kcoriordan** [comment]
Doing some research on this, asking the TKG team, but as such not sure what to add here yet.

**Comment by pspinrad** [comment]
If it helps, this staged TKG topic explains how to access logs, including local cluster logs.  The local logs aren't in TKG yet but are in newer versions of Tanzu Framework: https://docs-staging.vmware.com/en/draft/VMware-Tanzu-Kubernetes-Grid/1.6/vmware-tanzu-kubernetes-grid-16/GUID-troubleshooting-tkg-logs.html

**Comment by kcoriordan** [comment]
@jakerobinson - can you take a look at the PR to see if this helps. thanks

**Comment by jakerobinson** [comment]
Looks good to me, Kay!
