### ISSUE TITLE
Upgrade version of misspell used for macOS Monterey support

### ISSUE THREAD

**Issue by stmcginnis** [vmware-tanzu/community-edition#3265]
## Bug Report

There is a panic running the misspell checks on macOS Monterey. This is a known issue with the project.

Filing this issue to track updating once https://github.com/client9/misspell/issues/190 is fixed and so any
others hitting this issue can find that it is something we are aware of.

## Expected Behavior

No boom.

## Environment Details

* Build version (`tanzu version`): 
* Deployment (Managed/Unmanaged cluster): 
* Infrastructure Provider (Docker/AWS/Azure/vSphere): 
* Operating System (client):

**Comment by joshrosso** [comment]
@karuppiah7890 throwing this rel-eng's way.

Please let us know if there isn't bandwidth to knock this out in v0.11.0 -- core eng could also pick it up.

**Comment by stmcginnis** [comment]
I was reminded of this issue today so took a quick look at the upstream issue status. There actually hasn't been any commits merged to this project since 2018, despite quite a few issues and PRs being filed since then. The project may be dead, so we may have to either find an alternative or fork the project if we want to continue using it.
