### ISSUE TITLE
Proposal for adding Flux Helm Controller to TCE

### ISSUE THREAD

**Issue by hemakshis** [vmware-tanzu/community-edition#3271]
### Problem
The main goal here is to provide an automated operator that can bootstrap and continuously reconcile the cluster state from helm charts releases present in the customers registry. 

The helm-controller is a Kubernetes operator, allowing one to declaratively manage Helm chart releases. It is part of a composable [GitOps toolkit](https://fluxcd.io/docs/components/) and depends on [source-controller](https://github.com/fluxcd/source-controller) to acquire the Helm charts from Helm repositories.

### What is FluxCD Helm Controller?
The Helm Controller is a Kubernetes operator, allowing one to declaratively manage Helm chart releases with Kubernetes manifests.

The desired state of a Helm release is described through a Kubernetes Custom Resource named HelmRelease. Based on the creation, mutation or removal of a HelmRelease resource in the cluster, Helm actions are performed by the controller.

### Features:

* Watches for HelmRelease objects and generates HelmChart objects
* Supports HelmChart artifacts produced from HelmRepository and GitRepository sources
* Fetches artifacts produced by [source-controller](https://github.com/fluxcd/source-controller) from HelmChart objects
* Watches HelmChart objects for revision changes (including semver ranges for charts from HelmRepository sources)
* Performs automated Helm actions, including Helm tests, rollbacks and uninstalls
* Offers extensive configuration options for automated remediation (rollback, uninstall, retry) on failed Helm install, upgrade or test actions
* Runs Helm install/upgrade in a specific order, taking into account the depends-on relationship defined in a set of HelmRelease objects
* Prunes Helm releases removed from cluster (garbage collection)
* Reports Helm releases statuses (alerting provided by notification-controller)
* Built-in Kustomize compatible Helm post renderer, providing support for strategic merge, JSON 6902 and images patches

### Feature Ask

The ask is to make FluxCD Helm Controller available as a Tanzu package as part of Tanzu Community Edition. Through TCE, this package will be available within the TKG standard repository following the upstream -> downstream model from TCE to TKG.

**Comment by stmcginnis** [comment]
Please update description with a link to a publicly accessible design doc. Thanks!

**Comment by hemakshis** [comment]
Hi @stmcginnis I have removed the links to internal design docs as they cannot be accessed publicly. I have updated the description with links to open source documentations and why we need this package available as part of the community edition.

**Comment by joshrosso** [comment]
@chaudharyalka 2 questions on this package:

1. Do we have a team resourced to maintain this package over time?
2. @kartiklunkad26 this package has relation to the work your team is doing, do you have any thoughts on this or feel it's entirely independent.

**Comment by kartiklunkad26** [comment]
While this is in the Flux family, this is different from the FluxCD Source Controller package.

**Comment by joshrosso** [comment]
Thanks @hemakshis we're good to get this package into TCE whenever ya'll are ready.

If you haven't reviewed it, checkout our [package maintainer docs](https://github.com/vmware-tanzu/community-edition/tree/main/docs/packaging), which should help guide you along the process.

Let us know here or in slack if we can help!
