### ISSUE TITLE
UI Plugin: Route client HTTP calls to management-cluster plugin

### ISSUE THREAD

**Issue by miclettej** [vmware-tanzu/community-edition#3274]
The existing Tanzu CLI management cluster plugin includes an HTTP server and REST layer that can be leveraged for several UI functions. Some of these functions include authentication with a cloud provider, discovery of resources on a cloud provider, and starting deployment of a management cluster.

The new TCE UI plugin should attempt to route any HTTP calls related to the above functionality from its own UI to the management cluster plugin so that existing APIs can be leveraged. 

This may require that the TCE UI plugin starts the management cluster plugin's HTTP server in a browserless state at a specified IP address and port. The TCE UI plugin's backend should field HTTP requests from its own UI and then forward calls to the management cluster plugin's HTTP server that is running on the specified IP and port.

**Comment by stmcginnis** [comment]
We may want to think about either duplicating (with the goal of eventually migrating?) some of this functionality from the management-cluster plugin to the new UI plugin so we don't need to launch a second web server to serve these calls. Or importing the code so we can have one library that contains the logic, but can be used by two different services.

**Comment by miclettej** [comment]
@stmcginnis absolutely and let's maybe chat offline to see how we can go about this. Having a single library sounds ideal, and I would like to talk through how we can make that happen.
