### ISSUE TITLE
Velero Carvel package not support multiple BSL yet.

### ISSUE THREAD

**Issue by blackpiglet** [vmware-tanzu/community-edition#3301]
## Bug Report

Velero Carvel package only supports one BSL yet, and cannot specify which plugins to install.

## Expected Behavior

Should support multiple BSL. Should support to install plugins as BSL expected.

## Environment Details

* Build version (`tanzu version`): 0.10.0
* Deployment (Managed/Unmanaged cluster): Managed cluster
* Infrastructure Provider (Docker/AWS/Azure/vSphere): All
* Operating System (client): MacOS

**Comment by nrb** [comment]
This is a tracking issue for the Velero package maintainers
