### ISSUE TITLE
Automate docs update for new Azure image license approvals

### ISSUE THREAD

**Issue by seemiller** [vmware-tanzu/community-edition#3307]
## Feature Request

When deploying a cluster to Azure, you must first accept the license agreement for the base image. With new releases of TCE, the name/version of the image changes. For an end user, the only means of determining the name of the image that needs to be used is to look at the logs of the capz-controller-manager pod. Not very user friendly. 

We should automate updating the documentation with the correct name/version of the images. This way, end-users will always have easy access to the correct image name.

## Additional context

#3215 is the inspiration for this issue.

**Comment by karuppiah7890** [comment]
Related #2586

**Comment by kcoriordan** [comment]
Working with Mary to add this as a checklist item as following doc versioning, we're not using shortcodes for versioning

**Comment by kcoriordan** [comment]
@seemiller This will be handled by a checklist item. See row 3 here: 
https://docs.google.com/spreadsheets/d/1zQ7N9t3Jznzi8hzY7LW088Wzo7XdOqeZQJ5sIOaLXyQ/edit#gid=1527055808
