### ISSUE TITLE
Setup binary signing based on new binary build/directory structure

### ISSUE THREAD

**Issue by joshrosso** [vmware-tanzu/community-edition#3320]
With our move to `v0.11.1`, updates must be made to support our (downstream) signing automation against our binary.

This issue tracks the need,  most work will happen outside this repo.

**Comment by dvonthenen** [comment]
Release gates on a test/fake build can be found here:
https://github.com/vmware-tanzu/community-edition/runs/5428597964?check_suite_focus=true
https://github.com/vmware-tanzu/community-edition/actions/runs/1936047674

This verifies both Mac and Windows are signed.
This verified Mac, Windows, and Linux tarballs are installable and you can run the tanzu CLI using all plugins
