### ISSUE TITLE
"minimum 2 GiB of memory is required" message but machine has plenty of memory

### ISSUE THREAD

**Issue by brito-rafa** [vmware-tanzu/community-edition#3324]
## Bug Report

(The problem/solution is obvious but documenting here how to solve.)

When creating an unmanaged cluster, running:
```
tanzu unmanaged-cluster create mytce
```
got the following error message:
```
"failed to create cluster, Error: system checks detected issues, please resolve first: [minimum 2 GiB of memory is required]"
```

but the machine has plenty of memory (command line for Mac):
```
vm_stat | perl -ne '/page size of (\d+)/ and $size=$1; /Pages\s+([^:]+)[^\d]+(\d+)/ and printf("%-16s % 16.2f Mi\n", "$1:", $2 * $size / 1048576);' | grep free
free:                     7470.71 Mi
```

But 2GB is the docker resources default and it is not enough:
```
docker info | grep -i memory
Total Memory: 1.939GiB
```

After increasing the default (Preferences->Resources - see screenshot), I was able to create the unmanaged cluster.

After change:
```
docker info | grep -i memory
 Total Memory: 5.805GiB
```

## Screenshots or additional information and context

<img width="1153" alt="docker-resources" src="https://user-images.githubusercontent.com/8331576/156613296-6157b8e0-6429-4c51-b1c5-cd711814ff1b.png">

## Environment Details

* Build version (`tanzu version`):   v0.10.1
* Deployment (Managed/Unmanaged cluster): Unmanaged
* Infrastructure Provider (Docker/AWS/Azure/vSphere):  Docker
* Operating System (client): Mac

**Comment by stmcginnis** [comment]
Glad you figured it out @brito-rafa! Docker Desktop is a bit different than running Docker natively like on Linux, so I agree it's not immediately obvious that you need to go to the Docker Desktop settings for this.

This issue will be great as a breadcrumb if someone comes searching here if they don't see the [notes in our docs](https://tanzucommunityedition.io/docs/latest/support-matrix/#infrastructure-providers-target-platforms).
