### ISSUE TITLE
Unable to install any Tanzu Plugins - Error: could not read artifact storage: object doesn't exist

### ISSUE THREAD

**Issue by NeckBeardPrince** [vmware-tanzu/community-edition#3333]
## Bug Report

This is my first time using Tanzu, so I might be missing something.
Running `tanzu init` everything looks good. But when running `tanzu management-cluster create --ui`.

```
Error: plugin "management-cluster" does not exist, try using `tanzu plugin install management-cluster` to install or `tanzu plugin list` to find plugins

✖  plugin "management-cluster" does not exist, try using `tanzu plugin install management-cluster` to install or `tanzu plugin list` to find plugins
```

Trying to install

```
Error: could not read artifact "artifacts/management-cluster/v0.10.1/tanzu-management-cluster-darwin_amd64": storage: object doesn't exist

✖  could not read artifact "artifacts/management-cluster/v0.10.1/tanzu-management-cluster-darwin_amd64": storage: object doesn't exist
```

## Environment Details

* Build version (`tanzu version`): 
```
version: v0.10.1
buildDate: 2022-02-14
sha: 401d55b
```

* Deployment (Managed/Unmanaged cluster): Nothing, yet
* Infrastructure Provider (Docker/AWS/Azure/vSphere): Tried on Docker, but these commands don't seem to be provider specfiic.
* Operating System (client):  macOS Monterey - Intel

**Comment by stmcginnis** [comment]
Hey @NeckBeardPrince! I'm not entirely sure, but this may be due to running `tanzu init`. Was there a reason for running that?

It might just need to be cleaned up. If you installed from the `tgz` file, you can go back in to the extracted directory. From there, run `uninstall.sh` to clean things up, then `install.sh` again to get things back to the right place.

If this was installed via brew, the easiest thing might be to just uninstall, then `brew install` again and run the script it prompts.

If neither of those work we will have to dig in a little deeper to see what is going on.

**Comment by NeckBeardPrince** [comment]
> Hey @NeckBeardPrince! I'm not entirely sure, but this may be due to running `tanzu init`. Was there a reason for running that?
> 
> It might just need to be cleaned up. If you installed from the `tgz` file, you can go back in to the extracted directory. From there, run `uninstall.sh` to clean things up, then `install.sh` again to get things back to the right place.
> 
> If this was installed via brew, the easiest thing might be to just uninstall, then `brew install` again and run the script it prompts.
> 
> If neither of those work we will have to dig in a little deeper to see what is going on.

> > Hey @NeckBeardPrince! I'm not entirely sure, but this may be due to running `tanzu init`. Was there a reason for running that?

It was part of the `./install.sh`.

I did the install and uninstall using both the brew path and the tarball path

**Comment by stmcginnis** [comment]
Ah, OK - thanks! Let me ask around and see if anyone has seen this error before.

**Comment by stmcginnis** [comment]
Hi @NeckBeardPrince. I've asked a few folks, but we haven't seen this before. Just curious - did you have the commercial TKG version of things installed on this system prior to this, or maybe one of the TCE release candidates?

One other thing we can try here. If you can run the `uninstall.sh` script, that will clean things up again. The key thing I'm thinking of is getting rid of the files under `~/.config/tanzu`. That has all the metadata settings for the CLI. Then if you run `install.sh` again, that will reinitialize things again. The hope is the removal of `~/.config/tanzu` will get rid of whatever is pointing to an invalid storage location.

**Comment by vfarcic** [comment]
I'm facing the same issue. In the past, I could not run Tanzu due to issue with Docker. Now I wanted to give it another try since "docker issue" is fixed and the result is the same errors @NeckBeardPrince reported. I did follow all the suggestions from the comment (uninstall the CLI, remove `~/.config/tanzu`, install the CLI again).

**Comment by vfarcic** [comment]
I did run it during the initial installation thinking that there's no need to run it on each upgrade. Now (after re-running `configure-tce.sh` it works. Thanks a ton, @kartiklunkad26.

**Comment by stmcginnis** [comment]
Hi @NeckBeardPrince - wondering if you every got a chance to try that last suggestion or if you're still having issues here. If you get a chance, please let us know. Thanks!

**Comment by NeckBeardPrince** [comment]
> Hi @NeckBeardPrince - wondering if you every got a chance to try that last suggestion or if you're still having issues here. If you get a chance, please let us know. Thanks!

Sorry, yeah I did try that and no luck, same issue. My company has decided against moving forward with Tanzu, so I've removed it.
