### ISSUE TITLE
Set Harbor registry to prevent mutating tags

### ISSUE THREAD

**Issue by joshrosso** [vmware-tanzu/community-edition#3348]
## Feature Request

Today, we're at risk for anyone with appropriate access to accidentally overwrite an existing tag in Harbor. This could cause us a lot of pain. To overwrite a tag (which should almost never happen) a user should have to log in to our Harbor, delete the existing tag/image (manually) then re-push the image.

This should be possible to do via https://goharbor.io/docs/2.0.0/working-with-projects/working-with-images/create-tag-immutability-rules.

**Comment by seemiller** [comment]
@joshrosso Yes, we should be able to enable this feature ourselves in our TCE project on Harbor.

Do you want to enable this for all repositories within our project, or just the `main` project that is our package repository?

At a minimum I think that we should enable this for our `main` project.

However, I don't think that we would want to do this for all the packages that are pushed to our project. Consider: packages are versioned with the same version of the major software component packaged within. Engineer pushes package:1.0.0, containing software at version 1.0.0. Engineer changes <something> within the package but software is still 1.0.0. According to our rules, the package should still be tagged 1.0.0, so when engineer pushes updated package, we want to move the 1.0.0 tag to the latest package.

**Comment by joshrosso** [comment]
Let's do it for the entire project. Regarding your edge-case:

> However, I don't think that we would want to do this for all the packages that are pushed to our project. Consider: packages are versioned with the same version of the major software component packaged within. Engineer pushes package:1.0.0, containing software at version 1.0.0. Engineer changes within the package but software is still 1.0.0. According to our rules, the package should still be tagged 1.0.0, so when engineer pushes updated package, we want to move the 1.0.0 tag to the latest package.

When this happens, the package tag should **still not be overwritten**. Instead, the use of build meta should be attached to the next iteration of the package. That is covered here:

https://github.com/vmware-tanzu/community-edition/blob/main/docs/packaging/maintenance/maintenance.md#version-updates

@seemiller once we make this change, and validate it work via trying to overwrite and image, can you commend in here and close this issue?

**Comment by joshrosso** [comment]
To validate once we do this:

* [ ] images pushed with no tag fail
* [ ] images pushed with existing tag fail
* [ ] images pushed with new tag succeed and we see latest move to that newest image

**Comment by seemiller** [comment]
@joshrosso the `and` of the third case fails. `latest` is treated like any other label, and once it is associated to an image, it's stuck there.

**Comment by joshrosso** [comment]
@seemiller: Sounds good. This is fine.

Even if latest worked, our CDN prevents it from being viable.

Can you put your testing steps here so we have them for reference? Then you can close this issue.

**Comment by seemiller** [comment]
Test steps:

- Images pushed with no tag will only fail if the repository already exists and has the `latest` tag associated to it.
```
❯ # Create a folder and test file
❯ mkdir immutable
❯ echo 1 > immutable/foo.txt
❯ # Push/create image 
❯ imgpkg push -i projects.registry.vmware.com/tce/seemiller/immutabletest -f immutable
dir: .
file: test.txt
Pushed 'projects.registry.vmware.com/tce/seemiller/test@sha256:f003627dda2b6dadf439726ae1f00b51321394e5c963dd450df9f266cce49a81'
Succeeded
❯ imgpkg tag list -i projects.registry.vmware.com/tce/seemiller/test
Tags

Name  
latest  
sha256-f003627dda2b6dadf439726ae1f00b51321394e5c963dd450df9f266cce49a81.imgpkg

2 tags

Succeeded
```

- Change the contents and re-push, it will fail as `latest` is already used
```
❯ echo 2 >> immutable/test.txt
❯ imgpkg push -i projects.registry.vmware.com/tce/seemiller/test -f immutable
dir: .
file: test.txt

imgpkg: Error: Writing 'projects.registry.vmware.com/tce/seemiller/test:latest':
Writing image:
PUT https://projects.registry.vmware.com/v2/tce/seemiller/test/manifests/latest:
PRECONDITION:
Failed to process request due to 'seemiller/test:latest' configured as immutable.
```

- Change the contents, push with a tag, then change the contents and push with the same tag
```
❯ echo 3 >> immutable/test.txt
❯ imgpkg push -i projects.registry.vmware.com/tce/seemiller/test:3 -f immutable
dir: .
file: foo.txt
file: test.txt
Pushed 'projects.registry.vmware.com/tce/seemiller/test@sha256:7229f95c155c54663dc24e39822428885952bacd287f6d8d996f9886798455ea'
Succeeded
❯ echo 33 >> immutable/test.txt
❯ imgpkg push -i projects.registry.vmware.com/tce/seemiller/test:3 -f immutable
dir: .
file: foo.txt
file: test.txt

imgpkg: Error: Writing 'projects.registry.vmware.com/tce/seemiller/test:3':
  Writing image:
    PUT https://projects.registry.vmware.com/v2/tce/seemiller/test/manifests/3:
      PRECONDITION:
        Failed to process request due to 'seemiller/test:3' configured as immutable.
```
