### ISSUE TITLE
Create a new `TKr` for unmanaged-cluster usage in the `v0.11.0` release

### ISSUE THREAD

**Issue by joshrosso** [vmware-tanzu/community-edition#3354]
Once the official v0.11.0 bill of materials (BOM) is created (based on TKG 1.5.1). We should resolve the most recent (via k8s version) TKR that is compatible with that release.

You can see an example of how the TKR can be derived here:

https://github.com/vmware-tanzu/community-edition/issues/3286#issuecomment-1055541743

Based on this, the TKR we'd use would be `v1.22.5+vmware.1-tkg.3`.

With the above, the following needs to happen to resolve this issue:

* [x] Build a new kind image based on the k8s version in the TKR
    * use newest version of kind
    * https://github.com/vmware-tanzu/community-edition/issues/3376
* [x] Push the kind image to our registry (same location as existing image) 
* [x] Pull the TKR down
* [x] Mutate the TKR to include the kind image we built and pushed
* [x] Push the modified TKR (to the same location as the existing TCE-unmanged TKR)
* [x] Change the default TKR in the `unmanaged-cluster` code to push to this TKR

**Comment by joshrosso** [comment]
@jpmcb assigning this to you for `v0.11.0`. Let me know if you want to hop on a zoom to go over any of these steps (these are things I've done in the past)

Thanks!

**Comment by joshrosso** [comment]
@jpmcb, your now unblocked to start this process.

You can access the BOM at `projects-stg.registry.vmware.com/tkg/tkr-bom:v1.22.5_vmware.1-tkg.3-tf-v0.11.2`.

**Comment by jpmcb** [comment]
Made new image and pushed with
```
$ ./cli/cmd/plugin/unmanaged-cluster/hack/create-kind-image.sh v1.22.5
```

Verified with
```
$ crane ls projects.registry.vmware.com/tce/kind/node
v1.20.4_vmware.1
v1.21.2_vmware.1
v1.21.5
v1.22.2
v1.22.5
```

Pushed a new TKR:
```
$ crane ls projects.registry.vmware.com/tce/tkr
sha256-2fd337282cf17357c6329f441dc970ec900145faef9e2ec6122f98fa75d529c3.imgpkg
sha256-33f63314fb72ead645715f6ac85128c0fe0fd380d14f0a79eddba3dd361b73dd.imgpkg
sha256-ac6566268e0f113a4b91bab870a34353685e886f97e248633bb2c2fcf6490dc8.imgpkg
v1.21.5
v1.21.5-1
v1.21.5-2
v1.21.5-3
v1.22.2
v1.22.5
```

Verified contents:
```
$ crane export projects.registry.vmware.com/tce/tkr:v1.22.5 - | tar xv
tkr-bom-v1.22.5.yaml

$ rg -C 3 repository
tkr-bom-v1.22.5.yaml
137-      kindNodeImage:
138-        imagePath: kind/node
139-        tag: v1.22.5
140:        repository: projects.registry.vmware.com/tce
141-  load-balancer-and-ingress-service:
142-  - version: v1.6.1+vmware.2
143-    images:
```
