### ISSUE TITLE
Reintroduce cartographer to the `main.yaml`

### ISSUE THREAD

**Issue by joshrosso** [vmware-tanzu/community-edition#3367]
Main should be tracking v0.11.0, so cartographer should be present there.

If we need to push a patch release. for say `v0.10`, of our package repo, we should backport the change off a `v0.10.X` tag, cherry-pick relevant commits, and create a `v0.10.Y` tag, where `Y` = `X + 1`.

So largely, let's plan to revert:

* https://github.com/vmware-tanzu/community-edition/pull/3336

If there's questions on the viability of introducing patches, please sync with @dvonthenen.

**Comment by cmoulliard** [comment]
Without the cartographer, it is really hard to streamline the process from source to image to deploy except if you generate yourself the k8s manifest to deploy your application AND you build/push the container image too

**Comment by joshrosso** [comment]
> Without the cartographer, it is really hard to streamline the process from source to image to deploy except if you generate yourself the k8s manifest to deploy your application AND you build/push the container image too

 Hey @cmoulliard, just to make sure we're on the same page, we still have every intent to include cartographer in our next release. This issue is more about keeping our pre-release descriptors up to date. Hope this helps clarify!

**Comment by seemiller** [comment]
@cmoulliard See this [PR](https://github.com/vmware-tanzu/community-edition/pull/3373) for FluxCD
