### ISSUE TITLE
Dependabot pipeline is failing

### ISSUE THREAD

**Issue by lubronzhan** [vmware-tanzu/community-edition#3372]
## Bug Report

Dependabot pipeline is failing
https://github.com/vmware-tanzu/community-edition/runs/5442359619

## Expected Behavior
Dependabot pipeline pass

## Steps to Reproduce the Bug
Create a PR that modify CPI package or other packages

## Environment Details

* Build version (`tanzu version`): 
* Deployment (Managed/Unmanaged cluster): 
* Infrastructure Provider (Docker/AWS/Azure/vSphere): 
* Operating System (client):

**Comment by jpmcb** [comment]
Looks like #3371 fixed this. Thanks for your contribution!!! 👏🏼
