### ISSUE TITLE
`tanzu diagnostics` collection has issues with unmanaged clusters

### ISSUE THREAD

**Issue by stmcginnis** [vmware-tanzu/community-edition#3382]
## Bug Report

First, noticed the README for the `diagnostics` plugin still refers to `standalone-clusters` and does not mention `unmanaged-clusters`.

Tried just running `diagnostics collect`, but it did not automatically pick up the unmanaged cluster present on my system.

Then tried to run against an `unmanaged-cluster` after getting the current flags from the help output. Created new unmanaged cluster successfully. Then tried running `collect --unmanaged-cluster-name beepbeep` and failed with:

```
$ ./artifacts/linux/amd64/cli/diagnostics/v0.11.0-fake.5/tanzu-diagnostics-linux_amd64 collect --unmanaged-cluster-name beepbeep
2022/03/07 11:11:46 Warn: skipping cluster diagnostics: bootstrap cluster: no kind cluster found
2022/03/07 11:11:46 Warn: skipping cluster diagnostics: management cluster: clusterName not set
2022/03/07 11:11:46 Warn: skipping cluster diagnostics: workload cluster: cluster name not set
2022/03/07 11:11:46 Info: Retrieving unmanaged cluster: cluster=beepbeep; context=beepbeep-admin@beepbeep; kubeconfig=/home/smcginnis/.kube/config;
2022/03/07 11:11:46 Info: Capturing pod logs: cluster=beepbeep; kubeconf="kube_config"(cluster_context = "beepbeep-admin@beepbeep", path = "/home/smcginnis/.kube/config")
2022/03/07 11:11:46 Warn: skipping cluster diagnostics: exec failed: Traceback (most recent call last):
  scripts/unmanaged_cluster.star:29:27: in <toplevel>
  scripts/unmanaged_cluster.star:18:24: in diagnose_unmanaged_cluster
  scripts/lib.star:54:17: in capture_k8s_objects
  <builtin>: in kube_get
Error: could not initialize search client: context "beepbeep-admin@beepbeep" does not exist
```

Looks like the context name for the unmanaged cluster should actually be `kind-beepbeep`.

## Expected Behavior

Diagnostics collection should recognize unmanaged clusters on the system and should retrieve from a specific cluster when given a name.

## Steps to Reproduce the Bug

```
tanzu uc create foo
tanzu diagnostics collect
tanzu diagnostics collect --unmanaged-cluster-name foo
```

**Comment by jpmcb** [comment]
This is because kind names clusters and their context with a `kind-` prefix.

If I create an `unmanaged-cluster`:
```
$ tanzu unmanaged-cluster create diag-test
```

The cluster name and context appear as:
```
$ k config view --minify
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: DATA+OMITTED
    server: https://127.0.0.1:36995
  name: kind-diag-test
contexts:
- context:
    cluster: kind-diag-test
    user: kind-diag-test
  name: kind-diag-test
current-context: kind-diag-test
kind: Config
preferences: {}
users:
- name: kind-diag-test
  user:
    client-certificate-data: REDACTED
    client-key-data: REDACTED
```

Is this something that `diagnostics` should attempt to introspect?

It's too heavy handed to assume that all unmanaged-clusters have a `kind-` prefix and I don't think a pre-flight check to see if a cluster is a `kind` cluster makes sense.

But it is a poor UX to expect the user to know that there is a hidden `kind-` prefix.

I think this is actually something `unmanaged-cluster` needs to fix. We shouldn't have a hidden `kind-` prefix
