### ISSUE TITLE
Docs refer to config file named after the cluster but they have a random name

### ISSUE THREAD

**Issue by berndtj** [vmware-tanzu/community-edition#3454]
## Description

In describing how to get the clusterconfig the documents suggest that the files should be named according to the management cluster name.

```
If you deployed the management cluster from the installer interface, the configuration file is here: ~/.config/tanzu/tkg/clusterconfigs/<MGMT-CLUSTER-NAME>.yaml
```

However this is not the case (see https://github.com/vmware-tanzu/community-edition/issues/2172).

## Location

[](https://tanzucommunityedition.io/docs/latest/workload-clusters/)

## Additional Context

This can be fixed by addressing the underlying issue in tanzu framework, or updating the docs.

**Comment by stmcginnis** [comment]
Thanks for raising the awareness on this. Let's continue on with https://github.com/vmware-tanzu/community-edition/issues/2172
