### ISSUE TITLE
Verify with TMC team that the `TKGVERSION` annotation exposed by TCE is ok

### ISSUE THREAD

**Issue by joshrosso** [vmware-tanzu/community-edition#3456]
In the `v0.11.0`, TCE clusters will expose a `TKGVERSION` annotation on the cluster object that will contain the TKG BOM version **and build metadata that references the framework release**.

Any example of the potential `TKGVERSION` is:

```
v1.5.1-tf-v0.11.2
```

We need to verify this is OK with the TMC team.

Please note that `edition` will also still be exposed as an annotation, stating `tce`.

**Comment by steven-zou** [comment]
@joshrosso

**Comment by joshrosso** [comment]
Thanks for verifying @steven-zou.

The new plan of record is:

`TKGVERSION`: `v1.5.1-tf-v0.11.2`
`edition`: `tce`

I'll let you know if anything changes.
