### ISSUE TITLE
Promote v0.11.0 BOM to production harbor.

### ISSUE THREAD

**Issue by joshrosso** [vmware-tanzu/community-edition#3478]
This issue tracks the validation of the `projects-stg.registry.vmware.com/tkg/tkg-bom:v1.5.1-tf-v0.11.2` BoM.

Once it is validated, we must promote all BOM-related assets to `projects.registry.vmware.com`

**Comment by joshrosso** [comment]
@karuppiah7890 @navidshaikh, current plan:

1. We get initial RC out.
2. TCE core engineering validates it.
3. We run e2e tests against the RC, which will point to `proejct-stg`.
4. Based on that result, we'll request promotion.

@navidshaikh can you (or working with @ZihanJiang96), give us your best quote on how long promotion to production Harbor would take?

**Comment by navidshaikh** [comment]
Zihan suggested count 1 day for it.

**Comment by joshrosso** [comment]
@navidshaikh can we please promote the artifacts to prod?
