### ISSUE TITLE
Please add External-DNS to the Application Toolkit package for managed clusters

### ISSUE THREAD

**Issue by thesteve0** [vmware-tanzu/community-edition#3499]
@kartiklunkad26 

Application developers are going to be able to want to route requests using DNS to any workload cluster they deploy. External DNS makes this experience much nicer

This does not apply to unmanaged clusters since they are only on a developers local machine UNLESS we ship with some good nip.io configuration they can use.

**Comment by seemiller** [comment]
@kartiklunkad26 Here's a feature request for your team. Please consider it!

**Comment by kartiklunkad26** [comment]
@seemiller thanks will track it. @thesteve0 thanks for raising this! We will consider it in our planning for App Toolkit :)
