### ISSUE TITLE
Grafana and Prometheus installation failure 

### ISSUE THREAD

**Issue by aman556** [vmware-tanzu/community-edition#3510]
## Bug Report

- While installing Prometheus and Grafana by following [documentation](https://tanzucommunityedition.io/docs/latest/docker-monitoring-stack/#deploy-grafana) failing with the error.
```
Error: resource reconciliation failed: kapp: Error: Expected to find kind 'cert-manager.io/v1alpha2/Issuer', but did not:
- Kubernetes API server did not have matching apiVersion + kind
- No matching CRD was found in given configuration. Reconcile failed: Error (see .status.usefulErrorMessage for details)
Error: exit status 1
```
- Noticed that the PR [#3496](https://github.com/vmware-tanzu/community-edition/pull/3496) has updated the config files but still it is failing. 
- Local repo is rebased with upstream.
## Expected Behavior

The installation has to be successful.

## Steps to Reproduce the Bug

- Install all the prerequisites packages i.e
 ```
 NAME          PACKAGE-NAME                             PACKAGE-VERSION  STATUS                                                                
  cert-manager  cert-manager.community.tanzu.vmware.com  1.6.1            Reconcile succeeded                                                   
  contour       contour.community.tanzu.vmware.com       1.19.1           Reconcile succeeded  
  ```
Local-path-storage is-already  in unmanaged cluster so didn’t installed that. 
- Now try to install Grafana or Prometheus
## Environment Details

* Build version (`tanzu version`): v0.11.2
* Deployment (Managed/Unmanaged cluster): Umanaged
* Infrastructure Provider (Docker/AWS/Azure/vSphere): Docker
* Operating System (client): Mac

**Comment by stmcginnis** [comment]
I believe this is a know issue that @seemiller was working on.

Also related? https://github.com/vmware-tanzu/community-edition/issues/3036

**Comment by aman556** [comment]
Hello @stmcginnis don't know that the reason is same for failure both the time so just raised this one too.

**Comment by karuppiah7890** [comment]
Might be related - #3525 but not sure. Gotta dig in and check

**Comment by seemiller** [comment]
@aman556 Grafana and Prometheus both had [minor tweaks](https://github.com/vmware-tanzu/community-edition/pull/3496) to their packages recently. If you use the `v0.10.3` or `v0.11.01 package repository, you should be able to install both packages using versions `7.5.7-1` and `2.27.0-1`.

**Comment by seemiller** [comment]
Please reopen the issue if my last comment does not work for you.
