### ISSUE TITLE
`unmanaged-cluster` with existing cluster requires name

### ISSUE THREAD

**Issue by karuppiah7890** [vmware-tanzu/community-edition#3524]
## Description

For docs related to installing Tanzu components in existing cluster over [here](https://tanzucommunityedition.io/docs/latest/ref-unmanaged-cluster/#install-to-existing-cluster), following the commands leads to an error

```
$ minikube start
😄  minikube v1.25.2 on Ubuntu 20.04 (xen/amd64)
✨  Automatically selected the docker driver. Other choices: ssh, none
👍  Starting control plane node minikube in cluster minikube
🚜  Pulling base image ...
💾  Downloading Kubernetes v1.23.3 preload ...
    > preloaded-images-k8s-v17-v1...: 505.68 MiB / 505.68 MiB  100.00% 54.71 Mi
    > gcr.io/k8s-minikube/kicbase: 379.06 MiB / 379.06 MiB  100.00% 23.76 MiB p
🔥  Creating docker container (CPUs=2, Memory=8000MB) ...
🐳  Preparing Kubernetes v1.23.3 on Docker 20.10.12 ...
    ▪ kubelet.housekeeping-interval=5m
    ▪ Generating certificates and keys ...
    ▪ Booting up control plane ...
    ▪ Configuring RBAC rules ...
🔎  Verifying Kubernetes components...
    ▪ Using image gcr.io/k8s-minikube/storage-provisioner:v5
🌟  Enabled addons: storage-provisioner, default-storageclass
🏄  Done! kubectl is now configured to use "minikube" cluster and "default" namespace by default

$ tanzu unmanaged-cluster create -e ~/.kube/config --cni=none
Failed to initialize configuration. Error cluster name must be provided
Error: exit status 1

✖  exit status 1 

```

The fix is to add a cluster name in the command. Actually any cluster name will do but in order to not change the kube config I have used the same cluster name as provided by `minikube`

```
$ tanzu unmanaged-cluster create -e ~/.kube/config --cni=none minikube

📁 Created cluster directory

🔧 Resolving Tanzu Kubernetes Release (TKR)
   projects.registry.vmware.com/tce/tkr:v1.21.5
   Downloaded to: /home/ubuntu/.config/tanzu/tkg/unmanaged/bom/projects.registry.vmware.com_tce_tkr_v1.21.5               
   Rendered Config: /home/ubuntu/.config/tanzu/tkg/unmanaged/minikube/config.yaml
   Bootstrap Logs: /home/ubuntu/.config/tanzu/tkg/unmanaged/minikube/bootstrap.log

🔧 Processing Tanzu Kubernetes Release

🎨 Selected base image
   projects.registry.vmware.com/tce/kind/node:v1.21.5

📦 Selected core package repository
   projects.registry.vmware.com/tkg/packages/core/repo:v1.21.2_vmware.1-tkg.1

📦 Selected additional package repositories
   projects.registry.vmware.com/tce/main:0.10.1

📦 Selected kapp-controller image bundle
   projects.registry.vmware.com/tkg/packages/core/kapp-controller:v0.23.0_vmware.1-tkg.1

🚀 Using existing cluster
   Warning: Components installed using this method will need to be manually removed.

   To troubleshoot, use:

   kubectl ${COMMAND} --kubeconfig /home/ubuntu/.kube/config

📧 Installing kapp-controller
   kapp-controller status: Running                

📧 Installing package repositories
   Core package repo status: Reconcile succeeded             

🌐 Installing CNI
   No CNI installed: CNI was set to none.

✅ Cluster created

🎮 kubectl context set to minikube

View available packages:
   tanzu package available list
View running pods:
   kubectl get po -A
Delete this cluster:
   tanzu unmanaged delete minikube
$ 
```

This issue seems to be present in other commands (in the same page) as well, like https://tanzucommunityedition.io/docs/latest/ref-unmanaged-cluster/#disable-cni-installation

```bash
$ tanzu unmanaged-cluster create --cni=none
Failed to initialize configuration. Error cluster name must be provided
Error: exit status 1

✖  exit status 1 
```

https://tanzucommunityedition.io/docs/latest/ref-unmanaged-cluster/#customize-the-distribution

```
$ tanzu unmanaged-cluster create --tkr projects.registry.vmware.com/tce/tkr:v1.22.2
Failed to initialize configuration. Error cluster name must be provided
Error: exit status 1

✖  exit status 1 
```

Also, we use `unmanaged-clusters` in https://tanzucommunityedition.io/docs/latest/ref-unmanaged-cluster/#cant-upgrade-kubernetes , notice the extra `s` at the end. We just use it as a term here, maybe we could still stick to `unmanaged-cluster` without the `s` following the plugin / command name

## Location

https://tanzucommunityedition.io/docs/latest/ref-unmanaged-cluster/#install-to-existing-cluster

https://tanzucommunityedition.io/docs/latest/ref-unmanaged-cluster/#disable-cni-installation

https://tanzucommunityedition.io/docs/latest/ref-unmanaged-cluster/#customize-the-distribution

https://tanzucommunityedition.io/docs/latest/ref-unmanaged-cluster/#cant-upgrade-kubernetes

## Additional Context

None

**Comment by karuppiah7890** [comment]
cc @kcoriordan

**Comment by jorgemoralespou** [comment]
@karuppiah7890 I'm not quite sure why a cluster name would be required in this case, since you're just `tanzufying` an existing cluster that is in any case, managed externally and not by the `tanzu unmanaged-cluster` management part.

**Comment by jpmcb** [comment]
> I'm not quite sure why a cluster name would be required in this case

Good point. Right now, `unmanaged-cluster` needs a name anytime `create` is called since it attempts to initilize a valid configuration regardless of if it's using an existing cluster or not.

> since you're just tanzufying an existing cluster that is in any case, managed externally and not by the tanzu unmanaged-cluster management part.

This makes me think we should either

a) not require a name given an existing cluster
b) attempt to generate a dummy name (much like `kind` will) if none is provided, bypassing this case

Tagging @joshrosso - will discuss in our UX sync

**Comment by jpmcb** [comment]
Let's pull the name of the cluster from the provided `kubeconfig`. The cluster already has a name, so if the user provides a kubeconfig, just introspect the kubeconfig and use that name

**Comment by jorgemoralespou** [comment]
Does this use case, generate any tanzu specific file? Where is that name used?

**Comment by stmcginnis** [comment]
Information about the cluster will be populated under `~/.config/tanzu/tkg/unmanaged`. The name used will be the name of the cluster in the kubeconfig file.

```
$ kind create cluster --name kind-test
Creating cluster "kind-test" ...
 ✓ Ensuring node image (kindest/node:v1.21.1) 🖼
 ✓ Preparing nodes 📦
 ✓ Writing configuration 📜
 ✓ Starting control-plane 🕹️
 ✓ Installing CNI 🔌
 ✓ Installing StorageClass 💾
Set kubectl context to "kind-kind-test"
You can now use your cluster with:

kubectl cluster-info --context kind-kind-test

Thanks for using kind! 😊
~
$ k get nodes
NAME                      STATUS     ROLES                  AGE   VERSION
kind-test-control-plane   NotReady   control-plane,master   8s    v1.21.1
~
$ k config get-contexts
CURRENT   NAME                            CLUSTER          AUTHINFO            NAMESPACE
*         kind-kind-test                  kind-kind-test   kind-kind-test
~
$ ~/bin/tanzu uc create -e ~/.kube/config --cni=none

📁 Created cluster directory

🔧 Resolving Tanzu Kubernetes Release (TKR)
   projects.registry.vmware.com/tce/tkr:v0.17.0
   TKR exists at /home/smcginnis/.config/tanzu/tkg/unmanaged/bom/projects.registry.vmware.com_tce_tkr_v0.17.0
   Rendered Config: /home/smcginnis/.config/tanzu/tkg/unmanaged/kind-kind-test/config.yaml
   Bootstrap Logs: /home/smcginnis/.config/tanzu/tkg/unmanaged/kind-kind-test/bootstrap.log

🔧 Processing Tanzu Kubernetes Release

🎨 Selected base image
   projects.registry.vmware.com/tce/kind:v1.22.4

📦 Selected core package repository
   projects.registry.vmware.com/tce/repo-10:0.10.0

📦 Selected additional package repositories
   projects.registry.vmware.com/tce/main:v0.11.0

📦 Selected kapp-controller image bundle
   projects.registry.vmware.com/tce/kapp-controller-multi-pkg:v0.30.1

🚀 Using existing cluster
   Warning: Components installed using this method will need to be manually removed.

   To troubleshoot, use:

   kubectl ${COMMAND} --kubeconfig /home/smcginnis/.kube/config

📧 Installing kapp-controller
   kapp-controller status: Running

📧 Installing package repositories
   Core package repo status: Reconcile succeeded

🌐 Installing CNI
   No CNI installed: CNI was set to none.

✅ Cluster created

🎮 kubectl context set to kind-kind-test

View available packages:
   tanzu package available list
View running pods:
   kubectl get po -A
Delete this cluster:
   tanzu unmanaged delete kind-kind-test
~
$ tree ~/.config/tanzu/tkg/
bom/           compatibility/ config.yaml    providers/     .tanzu.lock    unmanaged/
~
$ tree ~/.config/tanzu/tkg/unmanaged/
/home/smcginnis/.config/tanzu/tkg/unmanaged/
├── bom
│   └── projects.registry.vmware.com_tce_tkr_v0.17.0
└── kind-kind-test
    ├── bootstrap.log
    └── config.yaml
```

**Comment by jorgemoralespou** [comment]
@stmcginnis 
I see, we save bootstrap.log and config.yaml. Is this installation process `idempotent`? Meaning, when I delete my existing cluster, this files won't be deleted. If I create again a cluster with this same name, would the process succeed and update this files? For `named` unmanaged cluster there's a check for existing config files and if they exist, cluster creation fails.

**Comment by stmcginnis** [comment]
Can you clarify @jorgemoralespou ? Do you mean you have a cluster, you then use `tanzu uc create -e [kube_config_path]`, then you delete the cluster using minikube or kind? In that case, `tanzu uc create` would still know about the cluster and would fail to create it again. At least that is what should happen once https://github.com/vmware-tanzu/community-edition/issues/3542 is fixed.

If by idempotent you mean just running that `tanzu uc create` call multiple times, that would not work. After working around the bug above to get the right context, if I try to run the `uc create` against the same cluster again I get:

```
$ tanzu uc create -e ~/.kube/config --cni=none
directory /home/smcginnis/.config/tanzu/tkg/unmanaged/kind-uctest already exists, this cluster must be deleted before proceeding
Error: exit status 2

✖  exit status 2
```

**Comment by jorgemoralespou** [comment]
@stmcginnis yes, that's what I meant. And to me, that's a bad experience because now, deleting a cluster seems to be a 2 step process, delete the cluster in the real infrastructure/manager and then "delete/forget" in TCE uc list of clusters.

**Comment by stmcginnis** [comment]
Yeah, that's fair. And "deleting" a cluster from TCE doesn't actually do anything to the cluster, so I think that could be a bit confusing too. Might be good to file an issue on this.
