### ISSUE TITLE
Use the latest stable release of TCE package repository in E2E tests

### ISSUE THREAD

**Issue by karuppiah7890** [vmware-tanzu/community-edition#3525]
We currently use a hard coded version of `v0.9.1` which has old versions of the packages

https://github.com/vmware-tanzu/community-edition/blob/31d4dd887a5fda946da77e983b49eef4017b2d8e/test/add-tce-package-repo.sh#L11

This was a miss in the testing. Due to this we have been using older packages of gatekeeper and fluent bit in our E2E tests and the older packages refer to older K8s yamls, like using `CustomResourceDefinition` from `apiextensions.k8s.io/v1beta1` in case of gatekeeper. This is causing E2E test failures when trying to use latest version of K8s which has `CustomResourceDefinition` in `apiextensions.k8s.io/v1` API group

**Comment by heww** [comment]
Agree, the old package of the harbor also can't be deployed in k8s 1.22 due to the old version of the resource.
