### ISSUE TITLE
UI: selecting to start fresh does not clear previous data

### ISSUE THREAD

**Issue by stmcginnis** [vmware-tanzu/community-edition#3530]
## Bug Report

When launching the kickstart UI with `tanzu mc create --ui`, if you've previously started a deployment it will prompt if you want to resume with the previous data or start fresh. Even if you select to start fresh, the previous data is kept in many of the fields.

I have also seen this remove some of the defaults like subnet CIDRs that shouldn't be affected.

This was most recently seen when starting an Azure deployment, though I believe I've seen it on other infra providers.

Mostly noting this for now so we have a record as I'm sure others will run in to this. We are using an older version of tanzu-framework, so it's possible this has already been resolved in newer releases. This will be revalidated once we bump our tanzu-framework dependency to one of the more recent releases.

## Expected Behavior

Starting fresh should not include previously entered subscription or client IDs. Common defaults such as service and pod CIDR should not be cleared.

## Steps to Reproduce the Bug

Launch wizard and go through filling out all fields, but not continue on to actually deployment. Close UI and stop running console process. Restart console process to relaunch UI. Select the option to start fresh and observe behavior.

## Environment Details

* Build version (`tanzu version`): v0.11.2
* Deployment (Managed/Unmanaged cluster): managed
* Infrastructure Provider (Docker/AWS/Azure/vSphere): azure
* Operating System (client): darwin

**Comment by swalner-vmware** [comment]
> HI @stmcginnis on top of tree we have removed that prompt until we have time to implement it correctly. TF v0.19 should have the code that removes the prompt.

This means that the UI _**always**_ re-uses the previous values (of non-sensitive fields)

**Comment by joshrosso** [comment]
Given this is something in far newer version of framework and we cannot bump beyond `v0.11.x` in the `v0.12.0` TCE release, I'm moving this out to evaluate in `v0.13.0`.
