### ISSUE TITLE
Add `unmanaged-cluster` unit tests

### ISSUE THREAD

**Issue by jpmcb** [vmware-tanzu/community-edition#3536]
## Feature Request

Currently, we have limited unit tests for `unmanaged-cluster`. Most are focused on the `config` package. This was technical debt taken on by the team as we moved quickly on `unmanaged-cluster`. But now that it is becoming more feature rich, we should retroactively add additional unit tests for to ensure it's correctness and speed development work in the future.

**Comment by joshrosso** [comment]
As @jpmcb mentions, this test coverage needs to be expanded for all packages.

Once we get closer to `v0.12.0`, we'll likely delegate packages to specific core engineering members.

**Comment by joshrosso** [comment]
Per slack today: @jpmcb is going to get an ordering of which packages need testing most and delegate those to the team.

**Comment by jpmcb** [comment]
Packaging stack rank ordering:

1. `tanzu` - Instrumentation of entire `unmanaged-cluster`
    - Assigned: @dvonthenen 
    - Current coverage: 0%

3. `cluster` - Cluster providers
    - Assigned: @joshrosso 
    - Current coverage:
      - Kind provider: 34% 
        - Validation of docker info
        - Merging kind configs (including nodes)
      - Minikube provider: 0%
      - Noop provider: 0%
5. `config` - Consuming and providing config options for unmanaged-cluster
    - Assigned: @stmcginnis 
    - Current coverage: 57.6%
7. `tkr` - Consuming and providing a compatible TKr
    - Assigned: @jpmcb 
    - Current coverage:
      - Compatibility: 28.6%
      - tkr: 0%
      - image: 0%

Nice to haves, all with 0% coverage. We can pick these up as we finish the above.
9. Kapp
10. kubeconfig
11. Log
12. Packages

---

Assignment methodology: [Used the wheel of names](https://wheelofnames.com/) and removed names as I went down

Coverage methodology: `go test ./... -coverprofile=cover.out`. Coverage profile: [cover.txt](https://github.com/vmware-tanzu/community-edition/files/8506392/cover.txt)

To generate profile HTML page: `go tool cover -html=cover.txt`

**Comment by dvonthenen** [comment]
I'm plugging away on the `tanzu` package... there is a lot there.

**Comment by jpmcb** [comment]
@dvonthenen I absolutely have more bandwidth if you want to divide and concur?

**Comment by dvonthenen** [comment]
> @dvonthenen I absolutely have more bandwidth if you want to divide and concur?

I'm making good progress.... almost there with at least some initial tests we can always iterate on.

**Comment by joshrosso** [comment]
A lot of great progress here. I know some unit tests didn't make it in in time due to competing priorities (mine included) -- moving this to the next milestone for continuation.
