### ISSUE TITLE
`unmanaged-cluster` should use `antrea` as default CNI

### ISSUE THREAD

**Issue by jpmcb** [vmware-tanzu/community-edition#3564]
## Feature Request

We should switch back to `antrea` as the default CNI for `unmanaged-cluster`. We had temporarily switched to `calico` as the default CNI in support of users needing a persistent cluster that could survive docker system restarts.

#### Requirements:
- `unmanaged-cluster` must be able to survive a docker restart

#### Upstream tracking issues:
- [x] https://github.com/antrea-io/antrea/issues/3386

#### Supporting PRs:
- [ ] https://github.com/vmware-tanzu/community-edition/pull/3560
- [ ] https://github.com/vmware-tanzu/community-edition/pull/3686

#### Related issues:
- https://github.com/vmware-tanzu/community-edition/issues/3058

**Comment by thesteve0** [comment]
Woooohooo

**Comment by joshrosso** [comment]
Moving this to `at-risk` as antrea does not appear to be able to install on Docker Desktop running on an M1 mac.

Ref: https://github.com/vmware-tanzu/community-edition/pull/3560#issuecomment-1086254595

**Comment by joshrosso** [comment]
Unfortunately, do to latency in getting the packages updates, this won't make the release. Moving to v0.13.0
