### ISSUE TITLE
unmanaged-cluster with existing kubeconfig should be idempotent

### ISSUE THREAD

**Issue by jorgemoralespou** [vmware-tanzu/community-edition#3580]
## Bug Report
When `tanzufying` an existing cluster, the process should be idempotent because the unmanaged-cluster is not even created by TCE, it only installs stuff on top of an existing cluster, so it makes no sense to have fail in the following scenario:

- create a cluster outside TCE with name test
- create a TCE cluster with kubeconfig option (Tanzufy the cluster)
- delete the cluster outside TCE test
- create the TCE cluster with kubeconfig option (Tanzufy your new cluster)

This should work, but currently it fails because we keep track of bootstrap.log and config.yaml files for that cluster in the TCE filesystem are when the cluster is not managed by TCE, so deletion of the cluster will not remove this files.

```
$ kind create cluster --name kind-test
Creating cluster "kind-test" ...
 ✓ Ensuring node image (kindest/node:v1.21.1) 🖼
 ✓ Preparing nodes 📦
 ✓ Writing configuration 📜
 ✓ Starting control-plane 🕹️
 ✓ Installing CNI 🔌
 ✓ Installing StorageClass 💾
Set kubectl context to "kind-kind-test"
You can now use your cluster with:

kubectl cluster-info --context kind-kind-test

Thanks for using kind! 😊
~
$ k get nodes
NAME                      STATUS     ROLES                  AGE   VERSION
kind-test-control-plane   NotReady   control-plane,master   8s    v1.21.1
~
$ k config get-contexts
CURRENT   NAME                            CLUSTER          AUTHINFO            NAMESPACE
*         kind-kind-test                  kind-kind-test   kind-kind-test
~
$ ~/bin/tanzu uc create -e ~/.kube/config --cni=none

📁 Created cluster directory

🔧 Resolving Tanzu Kubernetes Release (TKR)
   projects.registry.vmware.com/tce/tkr:v0.17.0
   TKR exists at /home/smcginnis/.config/tanzu/tkg/unmanaged/bom/projects.registry.vmware.com_tce_tkr_v0.17.0
   Rendered Config: /home/smcginnis/.config/tanzu/tkg/unmanaged/kind-kind-test/config.yaml
   Bootstrap Logs: /home/smcginnis/.config/tanzu/tkg/unmanaged/kind-kind-test/bootstrap.log

🔧 Processing Tanzu Kubernetes Release

🎨 Selected base image
   projects.registry.vmware.com/tce/kind:v1.22.4

📦 Selected core package repository
   projects.registry.vmware.com/tce/repo-10:0.10.0

📦 Selected additional package repositories
   projects.registry.vmware.com/tce/main:v0.11.0

📦 Selected kapp-controller image bundle
   projects.registry.vmware.com/tce/kapp-controller-multi-pkg:v0.30.1

🚀 Using existing cluster
   Warning: Components installed using this method will need to be manually removed.

   To troubleshoot, use:

   kubectl ${COMMAND} --kubeconfig /home/smcginnis/.kube/config

📧 Installing kapp-controller
   kapp-controller status: Running

📧 Installing package repositories
   Core package repo status: Reconcile succeeded

🌐 Installing CNI
   No CNI installed: CNI was set to none.

✅ Cluster created

🎮 kubectl context set to kind-kind-test

View available packages:
   tanzu package available list
View running pods:
   kubectl get po -A
Delete this cluster:
   tanzu unmanaged delete kind-kind-test
~
$ tree ~/.config/tanzu/tkg/
bom/           compatibility/ config.yaml    providers/     .tanzu.lock    unmanaged/
~
$ tree ~/.config/tanzu/tkg/unmanaged/
/home/smcginnis/.config/tanzu/tkg/unmanaged/
├── bom
│   └── projects.registry.vmware.com_tce_tkr_v0.17.0
└── kind-kind-test
    ├── bootstrap.log
    └── config.yaml

$ tanzu uc create -e ~/.kube/config --cni=none
directory /home/smcginnis/.config/tanzu/tkg/unmanaged/kind-uctest already exists, this cluster must be deleted before proceeding
Error: exit status 2

✖  exit status 2
```

See more context here: https://github.com/vmware-tanzu/community-edition/issues/3524#issuecomment-1070852748 and below in comments

## Environment Details

* Build version (`tanzu version`): 0.11.rc2
* Deployment (Managed/Unmanaged cluster): unmanaged-cluster
* Infrastructure Provider (Docker/AWS/Azure/vSphere): docker
* Operating System (client): mac

**Comment by joshrosso** [comment]
Quick note here that the TCE engineering team talked about this and there's some philosophy/nuance left to be discussed. Let's revisit conversations around this before we pick up the work.

@stmcginnis @jpmcb if you have any async input, feel free to add some thoughts here.

**Comment by stmcginnis** [comment]
More context as there was some thought this should be idempotent, only in that once you `tanzu uc rm foo` to remove the metadata so TCE doesn't complain of the cluster already existing.

Created a kind cluster with `kind create cluster`, then verified I could see the one node with `k get nodes`. Cluster appeared healthy.

Made this a tanzu cluster with:

```
$ tanzu uc create --cni=none -e ~/.kube/config

📁 Created cluster directory

🔧 Resolving Tanzu Kubernetes Release (TKR)
   projects.registry.vmware.com/tce/tkr:v0.17.0
   TKR exists at /home/smcginnis/.config/tanzu/tkg/unmanaged/bom/projects.registry.vmware.com_tce_tkr_v0.17.0
   Rendered Config: /home/smcginnis/.config/tanzu/tkg/unmanaged/kind-kind/config.yaml
   Bootstrap Logs: /home/smcginnis/.config/tanzu/tkg/unmanaged/kind-kind/bootstrap.log

🔧 Processing Tanzu Kubernetes Release

🎨 Selected base image
   projects.registry.vmware.com/tce/kind:v1.22.4

📦 Selected core package repository
   projects.registry.vmware.com/tce/repo-10:0.10.0

📦 Selected additional package repositories
   projects.registry.vmware.com/tce/main:v0.11.0

📦 Selected kapp-controller image bundle
   projects.registry.vmware.com/tce/kapp-controller-multi-pkg:v0.30.1

🚀 Using existing cluster
   Warning: Components installed using this method will need to be manually removed.

   To troubleshoot, use:

   kubectl ${COMMAND} --kubeconfig /home/smcginnis/.kube/config

📧 Installing kapp-controller
   kapp-controller status: Running

📧 Installing package repositories
   Core package repo status: Reconcile succeeded

🌐 Installing CNI
   No CNI installed: CNI was set to none.

✅ Cluster created

🎮 kubectl context set to kind-kind

View available packages:
   tanzu package available list
View running pods:
   kubectl get po -A
Delete this cluster:
   tanzu unmanaged delete kind-kind
```

Then had to switch my context back due to https://github.com/vmware-tanzu/community-edition/issues/3542 - so I did `k config use-context kind-kind` and `k get nodes` worked again. Again, everything seems happy.

Then ran `tanzu uc rm kind-kind` to remove the cluster from tanzu management.

So theoretically back to starting state, with the cluster still having the tanzu components which we point out during cluster creation with the message "Warning: Components installed using this method will need to be manually removed."

Tried to bring the existing cluster back under tanzu management and get a failure with kapp-controller:

```
$ tanzu uc create --cni=none -e ~/.kube/config

📁 Created cluster directory

🔧 Resolving Tanzu Kubernetes Release (TKR)
   projects.registry.vmware.com/tce/tkr:v0.17.0
   TKR exists at /home/smcginnis/.config/tanzu/tkg/unmanaged/bom/projects.registry.vmware.com_tce_tkr_v0.17.0
   Rendered Config: /home/smcginnis/.config/tanzu/tkg/unmanaged/kind-kind/config.yaml
   Bootstrap Logs: /home/smcginnis/.config/tanzu/tkg/unmanaged/kind-kind/bootstrap.log

🔧 Processing Tanzu Kubernetes Release

🎨 Selected base image
   projects.registry.vmware.com/tce/kind:v1.22.4

📦 Selected core package repository
   projects.registry.vmware.com/tce/repo-10:0.10.0

📦 Selected additional package repositories
   projects.registry.vmware.com/tce/main:v0.11.0

📦 Selected kapp-controller image bundle
   projects.registry.vmware.com/tce/kapp-controller-multi-pkg:v0.30.1

🚀 Using existing cluster
   Warning: Components installed using this method will need to be manually removed.

   To troubleshoot, use:

   kubectl ${COMMAND} --kubeconfig /home/smcginnis/.kube/config

📧 Installing kapp-controller
failed to install kapp-controller, Error: namespaces "tkg-system" already exists
Error: exit status 9

✖  exit status 9
```

**Comment by jpmcb** [comment]
A few thoughts:

---

> only in that once you tanzu uc rm foo to remove the metadata so TCE doesn't complain of the cluster already existing.

I agree - we do need to fix the no-op provider to attempt to remove any metadata when / if the cluster is deleted using `unmanaged-cluster delete`. But even that feels alittle weird. Maybe instead of storing the bootstrap log and the configuration used in a named location, we store it in a temp folder with a timestamp? Something like:
```
$ cat /tmp/bootstrap-myCluster-2022-03-18-00:UTC00.log 
Created cluster directory ...
```
Since `unmanaged-cluster` doesn't need to know about these existing clusters, it probably shouldn't attempt to manage and track **_metadata_** about those clusters.

> So looks like it has an imperative command that tries to create the namespace and does not like that it already exists.

That seems simple enough to check and create if it doesn't exist.

I think it makes sense that `create` is idempotent: it's simply ensuring that the necessary components and resources are installed on the cluster. If not, it will add them. If they are, it should automatically reconcile and move on.

**Comment by stmcginnis** [comment]
> Maybe instead of storing the bootstrap log and the configuration used in a named location, we store it in a temp folder with a timestamp?

The downside of that is it's inconsistent with other behavior, and it might be cleared from /tmp before they realize they need it.

That may be fine, but just to throw out another idea - if `provider == "none"` we could just ignore the check if it's already present. That way if someone were to run `tanzu uc create -e` multiple times for the same cluster, the bootstrap log would just append each time it happens. That would give a record of all activity in case of problems.
