### ISSUE TITLE
Proposal: Introduce `wizard` bootstrapping plugin

### ISSUE THREAD

**Issue by jpmcb** [vmware-tanzu/community-edition#3588]
In addition to the [Guided Graphical UI #3235](https://github.com/vmware-tanzu/community-edition/issues/3235), we should consider implementing a `wizard` CLI plugin. This plugin would walk users through bootstrapping a management / unmanaged cluster, _right in the CLI._

### _But why?_

Some users don't have access to a web browser (like in a headless environment or when on a remote server). Or their network configuration won't allow for easily tunneling a request to their bootstrapping machine (like deploying through a jumpbox).

This issue needs a formal proposal and is a placeholder

---

Examples:
- [AWS CLI configuration wizard](https://docs.aws.amazon.com/cli/latest/userguide/cli-usage-wizard.html)
- [Powerlevel10k wizard](https://github.com/romkatv/powerlevel10k#configuration-wizard)

**Comment by joshrosso** [comment]
:+1: When it comes around to proposal let's reconsider the trade-offs of embedding this functionality alongside plugins that benefit from a wizard, vs doing a dedicated wizard plugin.
