### ISSUE TITLE
Make edition (e.g. TCE) detectable in workload clusters

### ISSUE THREAD

**Issue by vaamarnath** [vmware-tanzu/community-edition#3593]
## Feature Request

Currently, TCE cluster's (be it management or workload cluster) metadata is same as the TKG clusters'. The `edition` is added only to management cluster's cluster CR as part of this change #3456. 

Instead, it would be great to enhance the `tkg-metadata` config map in `tkg-system-public` namespace to include the TCE related metadata as well. This would establish a well defined contract for other integrations like TMC to discover any of TCE / TKG information.

**Comment by usahai30** [comment]
Currently `tkg-metadata` configmap in `tkg-system-public` namespace has `VMware Tanzu Kubernetes Grid` as `kubernetesProvider`. Maybe we should have `Tanzu Community Edition`-

```
> kubectl get cm -n tkg-system-public tkg-metadata -ojson | jq -r '.data."metadata.yaml"'
cluster:
  name: tce-mgmt
  type: management
  plan: dev
  kubernetesProvider: VMware Tanzu Kubernetes Grid
  tkgVersion: v1.5.1-tf-v0.11.2
  infrastructure:
    provider: vsphere
bom:
  configmapRef:
    name: tkg-bom
```

**Comment by joshrosso** [comment]
> Instead, it would be great to enhance the tkg-metadata config map in tkg-system-public namespace

@vaamarnath For extreme clarity: by **instead**, you're proposing:

1. No longer putting the edition in the cluster CR.
2. Putting the edition in the `tkg-metadata` config map.

**Comment by joshrosso** [comment]
> Currently `tkg-metadata` configmap in `tkg-system-public` namespace has `VMware Tanzu Kubernetes Grid` as `kubernetesProvider`. Maybe we should have `Tanzu Community Edition`-
> 
> ```
> > kubectl get cm -n tkg-system-public tkg-metadata -ojson | jq -r '.data."metadata.yaml"'
> cluster:
>   name: tce-mgmt
>   type: management
>   plan: dev
>   kubernetesProvider: VMware Tanzu Kubernetes Grid
>   tkgVersion: v1.5.1-tf-v0.11.2
>   infrastructure:
>     provider: vsphere
> bom:
>   configmapRef:
>     name: tkg-bom
> ```

Fair point, we'll delegate this decision to the Tanzu Framework maintainers.

For TCE, the provider is still "TKG" in my eyes, but it does depend on how one defines TKG.

**Comment by steven-zou** [comment]
> 1. No longer putting the edition in the cluster CR.

This is not correct, the LCM operator running in the MC needs this edition to determine which LCM extension should be launched to serve the TCE WC LCM requests.

**Comment by vaamarnath** [comment]
@steven-zou, `tkg-metadata` exists on the management cluster as well. I assume, LCM operator would be able to read the cluster metadata from this source of truth as well. this is how extensions on TMC retrieve the cluster's metadata. 

having said that, I don't have strong opinions on the above one. we could have `edition` added to both cluster CRs as well as the TKG metadata config map for completeness. 

@joshrosso yeah, I agree maybe "provider" has to be still be "TKG" and we include a new field "edition" in the metadata config map.

**Comment by joshrosso** [comment]
> having said that, I don't have strong opinions on the above one. we could have edition added to both cluster CRs as well as the TKG metadata config map for completeness.

@steven-zou is this what we should mover forward with?

If not, can you let us know an ideal state we'd like to see?

**Comment by steven-zou** [comment]
> > having said that, I don't have strong opinions on the above one. we could have edition added to both cluster CRs as well as the TKG metadata config map for completeness.
> 
> @steven-zou is this what we should move forward with?
> 
Yes. I think so.

For clarifying, the current LCM code supports reading editions from the CAPI cluster as the CAPI cluster has been retrieved before. If reading TKG meta from the cm, then we need to introduce more code changes. I don't think it's worthy of doing it.

**Comment by usahai30** [comment]
@joshrosso We need TCE related information in configmap for both management and workload clusters.

**Comment by joshrosso** [comment]
@steven-zou @usahai30 @vaamarnath, the PR in framework is up at:

* https://github.com/vmware-tanzu/community-edition/issues/3593

Please take a look. Once merged, we'll backport it into framework `v0.11.X` and include it in TCE `v0.12.0`.

**Comment by joshrosso** [comment]
I verified in (internal) framework SIG today that this source change is all that's needed and our downstream build processes will pick it up and push it to the image registry.

![image](https://user-images.githubusercontent.com/6200057/160884707-6b0da9c0-3e99-4906-a04a-256d8c153c63.png)

**Comment by vaamarnath** [comment]
> @steven-zou @usahai30 @vaamarnath, the PR in framework is up at:
> 
>     * [Add edition to `tkg-metadata` configmap tanzu-framework#1949](https://github.com/vmware-tanzu/tanzu-framework/pull/1949)
> 
> 
> Please take a look. Once merged, we'll backport it into framework `v0.11.X` and include it in TCE `v0.12.0`.

the changes looks good. as described on the PR description, we expect the `edition` field for both management and workload clusters.

thanks for fixing this @joshrosso!

**Comment by joshrosso** [comment]
PR is closed so closing this.

Tracking the backporting can be tracked at:

* https://github.com/vmware-tanzu/community-edition/issues/3803

**Comment by joshrosso** [comment]
@vaamarnath @steven-zou @usahai30 here are initial results for ya'll to look over and validate using the newest change to tanzu-framework (aka TCE v0.12.0):

## Management cluster

```sh
kubectl get cluster -n tkg-system tkg-mgmt-docker-20220408082653
```

```yaml
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  annotations:
    TKGOperationInfo: '{"Operation":"Create","OperationStartTimestamp":"2022-04-08
      14:29:05.37698683 +0000 UTC","OperationTimeout":1800}'
    TKGOperationLastObservedTimestamp: 2022-04-08 14:29:20.421475249 +0000 UTC
    TKGVERSION: v1.5.3-tf-v0.11.4
    edition: tce
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"cluster.x-k8s.io/v1beta1","kind":"Cluster","metadata":{"annotations":{"osInfo":",,","tkg/plan":"dev"},"labels":{"cluster-role.tkg.tanzu.vmware.com/management":"","tanzuKubernetesRelease":"v1.22.8---vmware.1-tkg.1-tf-v0.11.4","tkg.tanzu.vmware.com/cluster-name":"tkg-mgmt-docker-20220408082653"},"name":"tkg-mgmt-docker-20220408082653","namespace":"tkg-system"},"spec":{"clusterNetwork":{"pods":{"cidrBlocks":["100.96.0.0/11"]},"serviceDomain":null,"services":{"cidrBlocks":["100.64.0.0/13"]}},"controlPlaneRef":{"apiVersion":"controlplane.cluster.x-k8s.io/v1beta1","kind":"KubeadmControlPlane","name":"tkg-mgmt-docker-20220408082653-control-plane"},"infrastructureRef":{"apiVersion":"infrastructure.cluster.x-k8s.io/v1beta1","kind":"DockerCluster","name":"tkg-mgmt-docker-20220408082653"}}}
    osInfo: ',,'
    tkg/plan: dev
  creationTimestamp: "2022-04-08T14:34:42Z"
  finalizers:
  - cluster.cluster.x-k8s.io
  generation: 2
  labels:
    cluster-role.tkg.tanzu.vmware.com/management: ""
    tanzuKubernetesRelease: v1.22.8---vmware.1-tkg.1-tf-v0.11.4
    tkg.tanzu.vmware.com/cluster-name: tkg-mgmt-docker-20220408082653
  name: tkg-mgmt-docker-20220408082653
  namespace: tkg-system
  resourceVersion: "2735"
  uid: b317fa16-19ee-42b9-b0b3-91e1eeb2239b
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      - 100.96.0.0/11
    services:
      cidrBlocks:
      - 100.64.0.0/13
  controlPlaneEndpoint:
    host: 172.18.0.9
    port: 6443
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1beta1
    kind: KubeadmControlPlane
    name: tkg-mgmt-docker-20220408082653-control-plane
    namespace: tkg-system
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: DockerCluster
    name: tkg-mgmt-docker-20220408082653
    namespace: tkg-system
status:
  conditions:
  - lastTransitionTime: "2022-04-08T14:34:48Z"
    status: "True"
    type: Ready
  - lastTransitionTime: "2022-04-08T14:34:48Z"
    status: "True"
    type: ControlPlaneInitialized
  - lastTransitionTime: "2022-04-08T14:34:48Z"
    status: "True"
    type: ControlPlaneReady
  - lastTransitionTime: "2022-04-08T14:34:42Z"
    status: "True"
    type: InfrastructureReady
  controlPlaneReady: true
  infrastructureReady: true
  observedGeneration: 2
  phase: Provisioned
```

```sh
kubectl get cm -n tkg-system-public tkg-metadata -o yaml
```

```yaml
apiVersion: v1
data:
  metadata.yaml: |
    cluster:
      name: tkg-mgmt-docker-20220408082653
      type: management
      plan: dev
      kubernetesProvider: VMware Tanzu Kubernetes Grid
      tkgVersion: v1.5.3-tf-v0.11.4
      edition: tce
      infrastructure:
        provider: docker
    bom:
      configmapRef:
        name: tkg-bom
kind: ConfigMap
metadata:
  annotations:
    tkg.tanzu.vmware.com/addon-type: metadata/tkg
  creationTimestamp: "2022-04-08T14:30:57Z"
  name: tkg-metadata
  namespace: tkg-system-public
  resourceVersion: "775"
  uid: c11d3206-5275-4dcb-b20a-48532b9d3dff
```

**Comment by usahai30** [comment]
Thanks @joshrosso 👍
