### ISSUE TITLE
Document how to upgrade your CLI from one version to another

### ISSUE THREAD

**Issue by jorgemoralespou** [vmware-tanzu/community-edition#3597]
## Description
We need to document the upgrade process of the CLI and what happens with the running clusters, whether they need to also be upgraded or not, before or after upgrading the cli, or whatever makes sense.

## Location
Installation Guide (maybe an upgrade chapter)?

## Additional Context
https://kubernetes.slack.com/archives/C02GY94A8KT/p1647616048177049

**Comment by joshrosso** [comment]
@kcoriordan can you investigate whether we have existing TKG-assets/docs around this that we could re-use?

**Comment by dvonthenen** [comment]
So I checked this and and installing v0.11.0 and then doing an install.sh on v0.12.0-rc.2 seems to upgrade all relevant plugins correctly and give us the behavior that we want. I think it should be documented like this for this issue https://github.com/vmware-tanzu/community-edition/issues/3597

in think to help out the end user, if we detect there are managed or unmanaged clusters out there, we will prompt with a "are you really sure?" and then also provide an override for automation and scripts uninstall.

will follow up with a PR on that

**Comment by dvonthenen** [comment]
PTAL https://github.com/vmware-tanzu/community-edition/pull/4211

**Comment by kcoriordan** [comment]
https://kubernetes.slack.com/archives/C02GY94A8KT/p1650901692066999
