### ISSUE TITLE
No mention of the `--tkr` option in the managed cluster documentation

### ISSUE THREAD

**Issue by dbbaskette** [vmware-tanzu/community-edition#3605]
## Description

There is no mention of using --tkr for creating clusters with a specific Kubernetes version in any of the managed cluster sections of the documentation.  It is briefly mentioned in the unmanaged section of the docs (https://tanzucommunityedition.io/docs/latest/ref-unmanaged-cluster/#customize-the-distribution), but that is the only mention in the documentation.

**Comment by joshrosso** [comment]
Good callout, I think this is something we should knock out before the v0.11.0 release is over.

**Comment by kcoriordan** [comment]
I can pick this up now, will try and draft something from here:
[****](https://docs.vmware.com/en/VMware-Tanzu-Kubernetes-Grid/1.5/vmware-tanzu-kubernetes-grid-15/GUID-tanzu-k8s-clusters-k8s-versions.html?hWord=N4IghgNiBcIC4GsBOIC+Q)
