### ISSUE TITLE
Create a BoM for `v0.12.0` based on the newest TKG `v1.5.x`

### ISSUE THREAD

**Issue by joshrosso** [vmware-tanzu/community-edition#3622]
This issue tracks the work to create the BoM and compatibility files for TCE `v0.12.0`.

This release graph should be based off the newest version of TKG `v1.5.x`.

It should also be referencing the newest version of framework, which mean the following should be resolve before this work is done:

* https://github.com/vmware-tanzu/community-edition/issues/3621

**Comment by joshrosso** [comment]
@navidshaikh preemptively adding you as the contact for v0.12.0.

Feel free to delegate elsewhere if you are not the right human. ty!

**Comment by joshrosso** [comment]
BOM is now available in staging. Smoke tests requested (internally).

Moving this back to `on-track`.

**Comment by dvonthenen** [comment]
We are close to cutting an RC... just giving some extra time to get the `apps` plugin integrated for RC1.
