### ISSUE TITLE
Concierge: [SPIKE] building Mac DMG with Electron-Builder

### ISSUE THREAD

**Issue by swalner-vmware** [vmware-tanzu/community-edition#3631]
## Feature Request
Explore electron-builder as a way to build a .dmg binary for Mac to install the Concierge

**Comment by dvonthenen** [comment]
Hi @swalner-vmware  This task is two-fold:
1. What this issue captures
2. Any downstream signing implications (must be addressed concurrently). If you need information about this, DM or post in the internal slack channel since we downstream build processes aren't open to the public.

**Comment by swalner-vmware** [comment]
@dvonthenen, thanks for mentioning the signing aspect, especially for Windows.
For this story, we're just focusing on the immediate production of the Mac DMG (unsigned), so I've modified the description accordingly. As you have pointed out, we'll need to address the signing aspect, and we'll have another GitHub issue for that.

**Comment by dvonthenen** [comment]
My understanding is that final signed build process we use has facilities for producing dmg, msi, rpm/deb files. If the goal is just to produce these items, it probably makes a lot of sense to use what's currently in place on the build systems.

**Comment by swalner-vmware** [comment]
Thanks, @dvonthenen. I've added your comment to https://github.com/vmware-tanzu/community-edition/issues/3920. This issue was just a spike to make sure the Electron-builder tool would work as advertised, which encompassed both the simple build and including the TCE artifact. Issue https://github.com/vmware-tanzu/community-edition/issues/3920 is meant to address your concern of merging the generation of these artifacts into a "real" build process
