### ISSUE TITLE
Debug and live updates for Tanzu workloads with VSCode

### ISSUE THREAD

**Issue by kartiklunkad26** [vmware-tanzu/community-edition#3647]
# Debug and live updates for Tanzu workloads with VSCode

Application developers spend a majority of their time working with code in IDEs. Iterating on their application from within the IDE saves a ton of time for them.

Enabling capabilities that will help them iterate and debug their code on Kubernetes within the IDE itself we believe will be valuable.

## Feature Request

Application developers spend a majority of their time iterating on application code within the IDE. With the advent of containers, and Kubernetes - updating and debugging their code from within the IDE and validating the output has become challenging and become a longer loop. 

By providing these capabiltiies from within the IDE, we can enable them to shorten the inner loop. 

### Bill of Materials
In addition to the pre-requisites, we need to bring these components to TCE to enable this capability. 

1. Convention Service or Workload Conventions  (PR to be linked in the Cartograper project)

**Comment by joshrosso** [comment]
@kartiklunkad26 is this work still relevant for `v0.12.0`.

if so, who should we assign to the work for point of contact?

**Comment by kartiklunkad26** [comment]
I’m not sure why we added for v0.12. This isn’t relevant for v0.12.

**Comment by joshrosso** [comment]
probably my misunderstanding. Moved to `icebox`.
