### ISSUE TITLE
Implement unmanaged-cluster E2Es

### ISSUE THREAD

**Issue by dvonthenen** [vmware-tanzu/community-edition#3689]
## Implement E2Es for unmanaged-clusters

This issue tracks work for unmanaged-clusters E2E tests.

### Verification

- [ ] Execute/run e2e tests for unmanaged-clusters. This should exercise:
  - [ ] create cluster
  - [ ] simple inspection of the cluster to make sure it's running
  - [ ] delete cluster
  - [ ] simple inspection to make sure the cluster is deleted
- [ ] Is this workflow being triggered by the daily build?
- [ ] Is this workflow being triggered by modifications to Makefile?

### Issues found as a result of the audit?

We should prioritize these and determine if they are absolutely required for the workflow to function correctly and be reproducible.

- None yet

**Comment by dvonthenen** [comment]
I totally missed this issue https://github.com/vmware-tanzu/community-edition/issues/3045 created @jpmcb 

Will tag that issue here and keep this issue around in favor of a more detailed explanation.

**Comment by jpmcb** [comment]
Happy to close that too - that issue was a placeholder since we were ripping out all the standalone stuff (including it's end to end tests)

**Comment by aman556** [comment]
Hey @dvonthenen from the above checklist we have tried to covered all the things in [#3810](https://github.com/vmware-tanzu/community-edition/pull/3810). Just want to know your thought process on checking the deletion of unmanaged cluster.
So there are multiple ways to check this like
- One way to check docker container for that cluster  but in future take UC on other providers like minikube, AWS ,Azure etc, we have to add or change the way
- `tanzu uc list` to check the cluster is in the list or not 

Just a thought what happen if `tanzu uc delete` failed is that  uc will be part of tanzu uc list or not?
