### ISSUE TITLE
unable to stand up bootstrap cluster in MacOS 11.6

### ISSUE THREAD

**Issue by carlosonunez** [vmware-tanzu/community-edition#3733]
## Bug Report

I can't get `tanzu management-cluster create --ui` to work on my Intel MacBook Pro running MacOS Big Sur 11.6. I also cannot get `kind create cluster --name test --image=projects.registry.vmware.com/tkg/kind/node:v1.21.5_vmware.1_v0.8.1` to work, as it `times out waiting for the condition` while waiting for the control plane to enter a `Ready` state.

Note that I _am_ able to create Kind clusters with both the `kindest/node:1.21.2` and `kindest/node:1.23.4`.

I'm running Docker through Lima with `dockerd` as the CRI.

## Expected Behavior

`tanzu management-cluster create` creates the Kind bootstrap cluster and proceeds with creating a management cluster.

## Steps to Reproduce the Bug

1. Remove Docker Desktop if installed.
2. Install Docker with Lima. I wrote my own instructions [here](https://blog.carlosnunez.me/post/docker-desktop-alternative-for-mac/) but there are many others describing how to do this.
3. Download the TCE CLI with Homebrew: `brew install vmware-tanzu/tanzu/tanzu-community-edition`
4. Run `tanzu management-cluster create`
## Environment Details

* Build version (`tanzu version`): v0.10.1
* Deployment (Managed/Unmanaged cluster): Managed
* Infrastructure Provider (Docker/AWS/Azure/vSphere): AWS
* Operating System (client):

```
ProductName:    macOS
ProductVersion: 11.6
BuildVersion:   20G165
```

**Comment by carlosonunez** [comment]
After looking at the logs from `kubelet` in the Kind Docker container, it appears that it can't download Docker images for some of the Kubernetes control plane components. See below; full gist [here](https://gist.github.com/carlosonunez/cf33248532e50a4e99ff85745f1821f4):

```
Mar 25 04:02:11 test-control-plane kubelet[226]: E0325 04:02:11.451867     226 remote_image.go:114] "PullImage from image service failed" err="rpc error: code = NotFound desc = failed to pull and unpack image \"k8s.gcr.io/kube-controller-manager:v1.21.5_vmware.1\": failed to resolve reference \"k8s.gcr.io/kube-controller-manager:v1.21.5_vmware.1\": k8s.gcr.io/kube-controller-manager:v1.21.5_vmware.1: not found" image="k8s.gcr.io/kube-controller-manager:v1.21.5_vmware.1"
```

```
Mar 25 04:02:11 test-control-plane kubelet[226]: E0325 04:02:11.567555     226 kuberuntime_image.go:51] "Failed to pull image" err="rpc error: code = NotFound desc = failed to pull and unpack image \"k8s.gcr.io/kube-apiserver:v1.21.5_vmware.1\": failed to resolve reference \"k8s.gcr.io/kube-apiserver:v1.21.5_vmware.1\": k8s.gcr.io/kube-apiserver:v1.21.5_vmware.1: not found" image="k8s.gcr.io/kube-apiserver:v1.21.5_vmware.1"
```

I can confirm that I cannot download them on my own machine:

```
$: docker pull k8s.gcr.io/kube-apiserver:v1.21.5_vmware.1
Error response from daemon: manifest for k8s.gcr.io/kube-apiserver:v1.21.5_vmware.1 not found: manifest unknown: Failed to fetch "v1.21.5_vmware.1" from request "/v2/kube-apiserver/manifests/v1.21.5_vmware.1".
```

Finally, from looking at the list of tags for some of these images with `curl -L https://k8s.gcr.io/v2/kube-apiserver/tags/list`, I can't find any images tagged with `vmware` in them (unless they require secrets).

**Comment by stmcginnis** [comment]
That is definitely not the right place for it to be pulling that image.

Could you provide the output of `grep imageRepository ~/.config/tanzu/tkg/bom/*`?

**Comment by carlosonunez** [comment]
Environment was clean before I installed. I did another install today and ensured that the tanzu directory was purged from XDG_DIR. Same result. I'll send a gif demonstrating the behavior I'm experiencing.

**Comment by stmcginnis** [comment]
Sorry, still not sure what could be causing this. It looks like something is forcing the image pull to go to a different location on your machine, but not sure how or why.

Can you paste the output from going to Docker Desktop > Preferences > Docker Engine? Doesn't seem likely, but just want to confirm there aren't any changes to the Docker daemon config that could be causing problems.

Also maybe check the settings of Docker Desktop > Preferences > Resources > Proxies?

**Comment by carlosonunez** [comment]
I'm using Lima to run the underlying Docker VM and mounting it to /var/run/docker.sock. I'll try and record a GIF of a clean install in about two weeks (when I have some spare time to do so).
