### ISSUE TITLE
tanzu 0.11.0-rc.2 on vSphere :  The virtual disk is either corrupted or not a supported format.

### ISSUE THREAD

**Issue by gbonazzoli** [vmware-tanzu/community-edition#3748]
The problem with version 10.1 was present too, but tanzu was able to create the management cluster anyway.

tanz Version 10.1 got 3 or 4 times the same cloning error but it was able to fullfill the operation.

With version 0.11.0-rc2 the same error is fatal and the installation process is only waiting and do not retry to clone the virtual machine.

See the error got on vCenter:

<img width="1269" alt="Screenshot 2022-03-28 at 12 26 04" src="https://user-images.githubusercontent.com/17742862/160379095-9480a882-6cfe-4dce-bbc2-60eb7cf65e33.png">

**Comment by stmcginnis** [comment]
This would appear to be a problem in your vSphere environment with the template disk. Just using the vSphere UI, are you able to create a VM using the same template? I would expect it to give you the same error.

You could try deleting the template and redeploying. Might be worth redownloading the OVA too just to make sure you have an uncorrupted image.

**Comment by gbonazzoli** [comment]
Yes you are right,

the problem lays on one of my host that occasionally gets an error in the cloning operation.

But 10.1 was aware of the error and retries till success, 11.0 doesn't catch the error and waits indefinitively.

In my personal view it is a little regression.

**Comment by stmcginnis** [comment]
@gab-satchi - do you know if there was a change in behavior here with the CAPV provider?

**Comment by gab-satchi** [comment]
not sure of any recent changes. cc: @srm09

**Comment by stmcginnis** [comment]
Any ideas on this one @srm09? It sounds like the cluster-api-provider-vsphere is less resilient than it was.

This isn't a TCE issue per se, but want to make sure if there is anything to track in that project that we capture it before closing this issue.

**Comment by stmcginnis** [comment]
We will keep this issue open to track any necessary updates to TCE, but created an issue in `tanzu-framework` to see what needs to be done: https://github.com/vmware-tanzu/tanzu-framework/issues/1980
