### ISSUE TITLE
Add Service Binding for Kubernetes package to TCE

### ISSUE THREAD

**Issue by atmandhol** [vmware-tanzu/community-edition#3752]
### Problem
Today in Kubernetes, the exposure of secrets for connecting application workloads to external services such as REST APIs, databases, event buses, and many more is manual and bespoke. Each service provider suggests a different way to access their secrets, and each application developer consumes those secrets in a custom way to their workloads. While there is a good deal of value to this flexibility level, large development teams lose overall velocity dealing with each unique solution. To combat this, we already see teams adopting internal patterns for how to achieve this workload-to-service linkage.

https://servicebinding.io specifies a Kubernetes-wide specification for communicating service secrets to workloads in an automated way. It aims to create a widely applicable mechanism but /without/ excluding other strategies for systems that it does not fit easily. The benefit of Kubernetes-wide specification is that all of the actors in an ecosystem can work towards a clearly defined abstraction at the edge of their expertise and depend on other parties to complete the chain.

### Service Bindings for Kubernetes

Service Bindings for Kubernetes ([GitHub - vmware-tanzu/servicebinding: Service Bindings for Kubernetes](https://github.com/vmware-tanzu/servicebinding)) implements the  [Service Binding Specification for Kubernetes](https://servicebinding.io/spec/core/1.0.0/) v1.0.0.

### How does it work?
This implementation provides support for:
*  [Provisioned Service](https://github.com/servicebinding/spec/tree/v1.0.0#provisioned-service) 
*  [Workload Projection](https://github.com/servicebinding/spec/tree/v1.0.0#workload-projection) 
*  [Service Binding](https://github.com/servicebinding/spec/tree/v1.0.0#service-binding) 
*  [Direct Secret Reference](https://github.com/servicebinding/spec/tree/v1.0.0#direct-secret-reference) 
*  [Role-Based Access Control (RBAC)](https://github.com/servicebinding/spec/tree/v1.0.0#role-based-access-control-rbac) 

### What is not implemented?
The following are not implemented:
*  [Workload Resource Mapping](https://github.com/servicebinding/spec/tree/v1.0.0#workload-resource-mapping) 
* Extensions including:
	*  [Binding Secret Generation Strategies](https://github.com/servicebinding/spec/blob/v1.0.0/extensions/secret-generation.md) 

### Feature Ask
The ask is to make [GitHub - vmware-tanzu/servicebinding: Service Bindings for Kubernetes](https://github.com/vmware-tanzu/servicebinding) available as a Tanzu package as part of Tanzu Community Edition.

**Comment by stmcginnis** [comment]
@kartiklunkad26 is this something the app toolkit team would be doing?

**Comment by seemiller** [comment]
servicebinding [releases a package](https://github.com/vmware-tanzu/servicebinding/releases/tag/v0.7.1)! This would be a very quick and easy to implement I think.

**Comment by kartiklunkad26** [comment]
@stmcginnis one of the developer-focused teams (cc: @atmandhol)

App toolkit team will also bring this package into their meta-package (cc: @dambor)

**Comment by cmoulliard** [comment]
> App toolkit team will also bring this package into their meta-package (cc: @dambor)

When is it planned to add the service binding within the app-toolkit ?

**Comment by kartiklunkad26** [comment]
@joshrosso @seemiller The team is waiting on approval from TCE engineering team to start work on this. Please let us know if this will be reviewed.
