### ISSUE TITLE
Version drop down does not change selected version

### ISSUE THREAD

**Issue by stmcginnis** [vmware-tanzu/community-edition#3771]
## Description

When looking at the docs, I tried to select a different version to compare the last release with the current release. I am able to click on the drop down and select the other version, but the page refreshes and brings me back to where I was.

If I manually edit the version string in the URL, that does switch me over to the right version of the docs. But again on the other version, if I try to use the drop down to select the other one to go back, I am now stuck on the version I entered in the URL.

## Location

All docs pages, as far as I can tell.

**Comment by stmcginnis** [comment]
Initially saw this on macOS using Brave. Also observed the behavior using Safari.

**Comment by jpmcb** [comment]
I'm seeing the same behavior:

![drop-down-no-work](https://user-images.githubusercontent.com/23109390/160636155-d9454535-0011-4626-b940-e16e09a2a099.gif)

System:
- Firefox developer edition 97.0 (64 bit version)
- Pop OS 21.04

**Comment by jpmcb** [comment]
Seeing the same behavior on Chrome:

![chrome-versioned-not-working](https://user-images.githubusercontent.com/23109390/160637115-f7e42f96-8405-42d9-bc64-dfbb260e2350.gif)

Version 98.0.4758.102 (Official Build) (64-bit)

**Comment by joshrosso** [comment]
@stmcginnis @jpmcb was the PR we approved at https://github.com/vmware-tanzu/community-edition/pull/3871 in relation to this issue?

If so, can we attach it and close this one. Thanks!

**Comment by stmcginnis** [comment]
Yep, that was the fix. It should be working now.
