### ISSUE TITLE
Enable `unmanaged-cluster` providers to access logger

### ISSUE THREAD

**Issue by jpmcb** [vmware-tanzu/community-edition#3778]
## Feature Request

Currently, the `unmanaged-cluster` provider API has no way to bubble up log messages or warnings.

We should consider adding some kind of interface that the providers can interact with in order to bubble up important log messages.

Use cases:
- One provider cannot implement multiple control planes, but others can. The provider that cannot use this feature should be able to log a warning to the user that the `--control-plane-node-count` configuration is being ignored.
- A provider may want to log a warning about some "failure state" that does not require the deployment of the cluster to cease, but _does_ require some user attention. For example; some resource in the cluster did not reconcile (like a provider specific namespace) but deploying `tanzu` bits can proceed 

## Describe alternatives you've considered

As our cluster providers get more and more granular, they may drift in the user and developer experience. The top level `tanzu` package cannot know about all edge cases or coordinate all possible scenerios between different cluster providers. The `cluster` package gives us alot of flexability to enable cluster providers to do what they will with certain configurations.

But there is no good way to surface those through the cluster providers into the logger. Right now, the `tanzu` package (where the logger is initialized and accessible), would need to introspect the provider, determine what special log message may need to be logged, and then log it.

## Additional context

This has surfaced as part of #3674

**Comment by stmcginnis** [comment]
It may be worth adding a `context` to the standard set of arguments we pass in to the provider interface. That would allow us to add things like timeouts if we need to. Then we could pass around things like the logger similar to https://github.com/kubernetes-sigs/cluster-api/blob/7069af2c806b440bcdc5ef50a9d25dd594db9bbc/internal/log/log.go#L38

Otherwise we could handle passing the logging instance in the calls where we instantiate a new provider.

**Comment by jpmcb** [comment]
I like that idea.

I've also considered the idea of adding string channels that the provider could push logs to. Then, the `tanzu` package could attempt to pop off messages from the channel in the `wait` loop and log them generically without having to pass in the logger itself.

It'd require a bit more async, parallel programming code, but could be a generic enough approach that doesn't bloat the provider APIs

**Comment by jpmcb** [comment]
I also realize that's why this part of the `Manager` interface is sort of weird:

https://github.com/vmware-tanzu/community-edition/blob/97ac483c2a4884be1c288871cf7059431c88232b/cli/cmd/plugin/unmanaged-cluster/cluster/cluster.go#L44-L46

It returns a slice of strings to be logged by the `tanzu` package. But we don't want to have one of these methods for every situation. So may be better to approach it more generically and consumable by both the provider and the `tanzu` package
