### ISSUE TITLE
Provide arm64 images for external-dns

### ISSUE THREAD

**Issue by jorgemoralespou** [vmware-tanzu/community-edition#3782]
## Feature Request

To fully support arm64 based architectures, as requested in https://github.com/vmware-tanzu/community-edition/issues/2171 we need all the images to provide arm64 arch images.

External-dns does not provide arm64 image

**Comment by jorgemoralespou** [comment]
@vmware-tanzu/pkg-external-dns-owners FYI

**Comment by mcwumbly** [comment]
We (@vmware-tanzu/pkg-external-dns-owners ) were discussing this issue this morning and have a few questions we'd like to answer to help us prioritize this, so just noting them here:

1. When do we expect `unmanaged-cluster` to support arm64? 
    Currently we lean on that for running our e2e tests, so it'd be nice to have that to validate this when we pick it up.
2. Does external-dns produce arm64 images upstream? if not, is there an issue upstream to track that?
    We should probably be able to answer this ourselves, but we haven't gotten around to looking just yet.

**Comment by stmcginnis** [comment]
> When do we expect unmanaged-cluster to support arm64?

The last (current) release supports this.

**Comment by jorgemoralespou** [comment]
Keep
