### ISSUE TITLE
Provide arm64 images for Cartographer

### ISSUE THREAD

**Issue by jorgemoralespou** [vmware-tanzu/community-edition#3783]
To fully support arm64 based architectures, as requested in https://github.com/vmware-tanzu/community-edition/issues/2171 we need all the images to provide arm64 arch images.

Cartographer does not provide arm64 image

**Comment by jorgemoralespou** [comment]
@vmware-tanzu/pkg-cartographer-owners FYI cc/ @kartiklunkad26 @cirocosta @waciumawanjohi

**Comment by cirocosta** [comment]
hey @ThomasVitale , thanks for the call out - we have https://github.com/vmware-tanzu/cartographer/issues/791 in there 😁

**Comment by ThomasVitale** [comment]
@cirocosta that's great, thank you!
