### ISSUE TITLE
Provide arm64 based images for Grafana

### ISSUE THREAD

**Issue by jorgemoralespou** [vmware-tanzu/community-edition#3785]
To fully support arm64 based architectures, as requested in https://github.com/vmware-tanzu/community-edition/issues/2171 we need all the images to provide arm64 arch images.

Grafana does not provide arm64 image

**Comment by jorgemoralespou** [comment]
@vmware-tanzu/pkg-grafana-owners FYI

**Comment by stealthybox** [comment]
not stale
