### ISSUE TITLE
Github Label request for App Toolkit

### ISSUE THREAD

**Issue by kartiklunkad26** [vmware-tanzu/community-edition#3798]
## Problem Statement
App Toolkit as a package leverages TCE as the community, and the user engagement interface. This means that TCE users will raise issues typically in the TCE repo about App Toolkit. 

## Request 

From a tracking and collecting user feedback perspective, it will be really helpful if we can create a label `area/packages/app-toolkit` so that I can label any incoming issues correspondingly. 

## Describe alternatives you've considered

My alternative is to manually look for the issues today, and it is not sustainable at all :)

**Comment by seemiller** [comment]
@kartiklunkad26 Does `package/app-toolkit` for a label work?

**Comment by kartiklunkad26** [comment]
Totally!
