### ISSUE TITLE
Secrets intermittently not getting set for CI jobs

### ISSUE THREAD

**Issue by karuppiah7890** [vmware-tanzu/community-edition#3813]
This is to fix Azure E2E test failures https://github.com/vmware-tanzu/community-edition/runs/5747017419?check_suite_focus=true#step:5:2578

**Comment by dvonthenen** [comment]
Putting context to this issue... initially discussed here:
https://kubernetes.slack.com/archives/C02GY94A8KT/p1654775158525349

and then has also seen another instance here:
https://kubernetes.slack.com/archives/C02GY94A8KT/p1655905852637739

The upshot is that the secrets are set, but it seems like maybe the GitHub CI service itself isn't passing the secret down to the pipeline. The Azure instance it looks like we are using self-hosted runners and in the second instance with the dependabot we are using GitHub hosted runners which eliminates which runners we use.

Need to investigate this some more.
