### ISSUE TITLE
Ensure TCE packages are tagged in Harbor

### ISSUE THREAD

**Issue by seemiller** [vmware-tanzu/community-edition#3823]
## Feature Request

The Harbor OCI Registry will garbage collect (i.e. delete) images/bundles that do not have tags. TCE has encountered issues in the past where packages "disappear".  A package would be referenced by a tag, which then resolved to a SHA. The tag is removed from the image on Harbor.  Harbor runs GC and deletes the image. Any TCE cluster using a package repository that references that image will now fail to reconcile. 

A tool, `tagger`, was created to scan the TCE Harbor project and add a tag to any image/bundle that does not already have multiple tags associated to it. We should run the `tagger` process in a workflow or on a scheduled basis to ensure that our images/bundles will always be tagged and available.

## Describe alternatives you've considered

One means to ensure that an image/bundle always has 2 tags is to push the image/bundle with a program like `imgpkg` which will now automatically add a tag (that contains the SHA for uniqueness) to a newly created image/bundle. However, there is no guarantee that a user will use a newer version of `imgpkg` with this feature.

**Comment by joshrosso** [comment]
@seemiller what's the status on this one?

I believe we just needed to get with @dvonthenen and knock this out.

**Comment by seemiller** [comment]
Might need to create a robot account. I'll check that and get with @dvonthenen

**Comment by seemiller** [comment]
@dvonthenen Can you use the `robot$github-ci` account, or should we make a new one?

**Comment by dvonthenen** [comment]
> @dvonthenen Can you use the `robot$github-ci` account, or should we make a new one?

Will take a look to see if we can.

What about the `config.json` file? where can I find that? I don't see it in the `tagger` folder.

**Comment by seemiller** [comment]
the `config.json` references the Docker config that contains the login credentials. If you were to run tagger locally, it's mapping your `~/.docker/config.json` to `/root/.docker/config.json` in the container.

**Comment by dvonthenen** [comment]
gotcha

**Comment by seemiller** [comment]
You can look at your own file on your local workstation. TBH, I'm not quite sure how it works since there aren't any creds actually in that file
