### ISSUE TITLE
TCE Management Cluster will not survive reboot/restart in Docker

### ISSUE THREAD

**Issue by RussellHamker** [vmware-tanzu/community-edition#3842]
## Bug Report

After creating a fresh tce management cluster and validating it is ready, we reboot the VM/docker instance. Upon reboot, HAProxy docker image does not restart and tce mgmt cluster will not come up. Reviewing docker network config, it looks as though the docker containers IPs switch.

## Expected Behavior

Upon reboot, tce management cluster should come up on specific order with specific IPs so that mgmt cluster start approapriately.

## Steps to Reproduce the Bug

1. Create Cluster:
cat <<EOF > tce-mgmt.yaml
CLUSTER_CIDR: 100.96.0.0/11
CLUSTER_NAME: tce-mgmt
CLUSTER_PLAN: dev
ENABLE_MHC: "false"
IDENTITY_MANAGEMENT_TYPE: none
INFRASTRUCTURE_PROVIDER: docker
LDAP_BIND_DN: ""
LDAP_BIND_PASSWORD: ""
LDAP_GROUP_SEARCH_BASE_DN: ""
LDAP_GROUP_SEARCH_FILTER: ""
LDAP_GROUP_SEARCH_GROUP_ATTRIBUTE: ""
LDAP_GROUP_SEARCH_NAME_ATTRIBUTE: cn
LDAP_GROUP_SEARCH_USER_ATTRIBUTE: DN
LDAP_HOST: ""
LDAP_ROOT_CA_DATA_B64: ""
LDAP_USER_SEARCH_BASE_DN: ""
LDAP_USER_SEARCH_FILTER: ""
LDAP_USER_SEARCH_NAME_ATTRIBUTE: ""
LDAP_USER_SEARCH_USERNAME: userPrincipalName
OIDC_IDENTITY_PROVIDER_CLIENT_ID: ""
OIDC_IDENTITY_PROVIDER_CLIENT_SECRET: ""
OIDC_IDENTITY_PROVIDER_GROUPS_CLAIM: ""
OIDC_IDENTITY_PROVIDER_ISSUER_URL: ""
OIDC_IDENTITY_PROVIDER_NAME: ""
OIDC_IDENTITY_PROVIDER_SCOPES: ""
OIDC_IDENTITY_PROVIDER_USERNAME_CLAIM: ""
OS_ARCH: ""
OS_NAME: ""
OS_VERSION: ""
SERVICE_CIDR: 100.64.0.0/13
TKG_HTTP_PROXY_ENABLED: "false"
EOF

tanzu management-cluster create -f tce-mgmt.yaml --cni=calico

2. Validate Cluster
kubectl config use-context tce-mgmt-admin@tce-mgmt
kubectl get nodes

3. Reboot VM/Docker
4. Find that HA Proxy will not start

## Screenshots or additional information and context

![image](https://user-images.githubusercontent.com/102260516/161087847-e6386e51-19c9-4337-ab13-19ceeb67bfdf.png)
Post reboot
![image](https://user-images.githubusercontent.com/102260516/161088193-3f52546f-7ad7-4170-b14c-b4742c79852e.png)
![image](https://user-images.githubusercontent.com/102260516/161088696-27e5b97e-5f5a-42d6-9d7a-a046adb5467a.png)
![image](https://user-images.githubusercontent.com/102260516/161089042-800a29f7-3849-4c3c-95f0-bbfa7778482e.png)
Post reboot after getting HAProxy running manually (docker start container)
![image](https://user-images.githubusercontent.com/102260516/161089222-be2c2013-e6a1-42c5-aaaf-ec03c48ad8d6.png)

## Environment Details

* Build version (`tanzu version`): v0.11
* Deployment (Managed/Unmanaged cluster):  Management Cluster
* Infrastructure Provider (Docker/AWS/Azure/vSphere):  Docker
* Operating System (client): Ubuntu 20.04

**Comment by jpmcb** [comment]
This looks like the same issue as https://github.com/vmware-tanzu/community-edition/issues/832

Closing - let me know if this is indeed different!
