### ISSUE TITLE
Define what does `Tanzuify` a cluster mean

### ISSUE THREAD

**Issue by jorgemoralespou** [vmware-tanzu/community-edition#3845]
## Feature Request
In some issues we talk about tanzufying a cluster. There's a feature on unmanaged-clusters that installs some bits on an existing cluster. It's not clear what these bits are and how they relate to the `productised` version of Tanzu Clusters (TKG) to Managed TCE clusters. It'll be ideal to define what does `tanzufying a cluster` means, what should be expected on every `tanzufyied` cluster.

**Comment by thesteve0** [comment]
Given the number of packages that require cert-manager, we should just install it by default in any Tanzu Community Edition install. I would also strongly argue contour is probably another good candidate. For both of these I would say they are the default but can always be changed or left out at time of "installation" of Tanzu Community Edition
