### ISSUE TITLE
`aws-nuke-tear-down` should not use the flags --access-key-id and --secret-access-key 

### ISSUE THREAD

**Issue by rajaskakodkar** [vmware-tanzu/community-edition#3851]
## Bug Report

Currently, https://github.com/vmware-tanzu/community-edition/blob/d4b6d1ad83b9e6d8aeb9a00ebd0a1bbfecace719/test/util/aws-nuke-tear-down.sh#L6 is used to nuke AWS resources when cluster provisioning fails in AWS E2E test through the make target https://github.com/vmware-tanzu/community-edition/blob/d4b6d1ad83b9e6d8aeb9a00ebd0a1bbfecace719/Makefile#L488

Function `aws-nuke-tear-down` is using aws-nuke through this command https://github.com/vmware-tanzu/community-edition/blob/d4b6d1ad83b9e6d8aeb9a00ebd0a1bbfecace719/test/util/aws-nuke-tear-down.sh#L9 where `--access-key-id "$AWS_ACCESS_KEY_ID" --secret-access-key "$AWS_SECRET_ACCESS_KEY"` flags are passed. This assumes that the access-key-id and secret-access-key are exported in the env. 

This model poses the risk of exposing these variables if the parent script calling this make target runs with `set -x`.

## Expected Behavior
AFAIK this make target is used in CI https://github.com/vmware-tanzu/community-edition/blob/d4b6d1ad83b9e6d8aeb9a00ebd0a1bbfecace719/.github/workflows/e2e-aws-management-and-workload-cluster.yaml#L74        however, Github Actions does not expose the values if they are set as Secret values in the config. For e.g look at https://github.com/vmware-tanzu/community-edition/runs/4764887999?check_suite_focus=true#step:5:1634 where ACCOUNT_ID Is denoted by `***`.

But even if we run this make target with a script having `set -x` it should not expose AWS creds in the logs.

## Steps to Reproduce the Bug
Run the following script
```
#!/bin/bash
set -x
git clone https://github.com/vmware-tanzu/community-edition && cd community-edition
make  aws-management-and-workload-cluster-e2e-test
```

## Screenshots or additional information and context
`aws-nuke-tear-down` should probably use aws profile to authenticate with AWS or any other method to make sure that the logs never expose AWS creds.

## Environment Details

* Build version (`tanzu version`): v0.11.0
* Deployment (Managed/Unmanaged cluster): Managed cluster
* Infrastructure Provider (Docker/AWS/Azure/vSphere): AWS
* Operating System (client): linux/darwin

**Comment by rajaskakodkar** [comment]
cc: @karuppiah7890

**Comment by Priyankasaggu11929** [comment]
X-posting from slack discussion:

---

From what I understood, we can drop the `--access-key-id` & `--secret-access-key` flags entirely from the script.

When the flags are not mentioned, the `aws-nuke` command looks for either of the two things:
- It checks whether there is a `default` profile set in the `~/.aws/credentials` file (with access_key_id & secret_access_key) in the host filesystem.
- Or if there is no default profile set, it can work if we export the following two env variables in the path:
    - `export AWS_ACCESS_KEY_ID=<value>`
    - `export AWS_SECRET_ACCESS_KEY=<value>`
    
Which in case of TCE tests, these [env variables are mandatory requirement to be made available in the path](https://github.com/vmware-tanzu/community-edition/blob/main/test/aws/deploy-tce-managed.sh#L11-L19) along with others like `Account ID` which aws-nuke requires.

Test run snippet (in case of using above env variables)

```
~/work-personal/config on ☁️  psaggu@vmware.com
❯ aws-nuke -c config.yaml
aws-nuke version v2.17.0 - Mon Jan 31 10:11:19 UTC 2022 - <redacted>

Do you really want to nuke the account with the ID <redacted> and the alias '<redacted>'?
Do you want to continue? Enter account alias to continue.
> <redacted>

eu-west-1 - OpsWorksUserProfile - arn:aws:iam::<redacted> - Cannot delete OpsWorksUserProfile of calling User
eu-west-1 - EC2RouteTable - rtb-2d5ea755 - [DefaultVPC: "true"] - would remove
eu-west-1 - EC2DHCPOption - dopt-c8a2a3ae - [DefaultVPC: "true"] - would remove
eu-west-1 - SNSSubscription - Owner: <redacted> ARN: arn:aws:sns:<redacted> - would remove 

....
....
Scan complete: 240 total, 167 nukeable, 73 filtered.

The above resources would be deleted with the supplied configuration. Provide --no-dry-run to actually destroy resources.
```

**Comment by dvonthenen** [comment]
>
> * Or if there is no default profile set, it can work if we export the following two env variables in the path:
>   
>   * `export AWS_ACCESS_KEY_ID=<value>`
>   * `export AWS_SECRET_ACCESS_KEY=<value>`
> 

This is already true today... in the GitHub workflow. You just need to call the utility without the parameters.
https://github.com/vmware-tanzu/community-edition/blob/main/.github/workflows/e2e-aws-management-and-workload-cluster.yaml#L69-L74

We should fix this sooner than later, but having said that... we also only allow privileged users to create workflows and to also execute tests. Third-party contributors need to have an `/ok-to-test` for the workflows to be kicked off. Unless you are able to insert yourself into the execution path of this e2e, you aren't getting the creds.... still not totally impossible.

**Comment by dvonthenen** [comment]
Who is going to look into addressing this?

**Comment by Priyankasaggu11929** [comment]
@dvonthenen, I've raised PR 3873 for removing the asked flags from the script.
