### ISSUE TITLE
Create a public daily automated update like the internal one

### ISSUE THREAD

**Issue by thesteve0** [vmware-tanzu/community-edition#3869]
## Feature Request

There is a daily update automatically generated that gives the status of the next release and various features in the release. This update is shared in internal channels at VMware. Because this update discusses issues and integration with non-FOSS projects, it is understandable that is is not shared publicly. 

That said, given that:
1. Many of the projects Tanzu Community Edition uses and integrates are FOSS
2. This information would be extremely helpful in community building, transparency, and efforts to get more involvement from the community
we should have something similar that publishes every day to the public slack channel.

I am not sure how the report is generated but it seems we need some way to identify non-shareable information but assume, by default all issues are shareable. 

The current situation is not community friendly. The community channel is missing:
1. The announcement about feedback on v0.12 by April 1
2. That work on V0.12 has begun
3. What issues are considered key to v0.12
4. Status on these issues
4. Release date, possible slippage, and why (even in a vague sense)

## Additional context
It was indicated that this is actually a feature that needs leadership to prioritize so tagging leaders or stakeholders on this issue. I can't find Eddie's github tag. 
@vkorbes @amandakatona @microwavables

**Comment by thesteve0** [comment]
May be a won't fix because of the way the k8s slack admins run their permissions
For context see the related issue
https://github.com/vmware-tanzu/community-edition/issues/3870

**Comment by dims** [comment]
"because of the way the k8s slack admins run their permissions" - k8s admins have VERY good reasons to run things the way they do, underlying issue is that slack is NOT built for open communities and it is built primarily to sell to enterprises.

**Comment by thesteve0** [comment]
> k8s admins have VERY good reasons to run things the way they do, 

Wasn't commenting on that - was just making clear where the issue resides - as in we have no control over this

**Comment by microwavables** [comment]
After speaking with the team, seems like this is something we will look into after v0.12.0.
