### ISSUE TITLE
Publish nightly build, test, and integration results to the public channel

### ISSUE THREAD

**Issue by thesteve0** [vmware-tanzu/community-edition#3870]
## Feature Request

Since we already have nightly builds along with tests and integration, we should find a way to publish those results to the public channel. This would help with community engagement and transparency. 

Even if the public can't see all the detailed results - summary results, maybe listing failures and such, would be really helpful

**Comment by dvonthenen** [comment]
I investigated this one and spoke with several k8s slack admins about the possibility. The big issue is that the only way to do this is through slack integrations and there isn't a way to do granular permissions for integrations to specific users to specific channels.

It's the main reason why I had to post daily build notifications to GitHub Discussions:
https://github.com/vmware-tanzu/community-edition/discussions/categories/daily-builds

**Comment by joshrosso** [comment]
Let's evaluate if we want developer advocacy to take this on and provide a report each day.

Since this is something we cannot due from and engineering perspective putting it in the icebox for now.

**Comment by thesteve0** [comment]
Yeah and it might be a won't fix because of the way the admins run the k8s slack
