### ISSUE TITLE
App Toolkit docs require tanzu apps plugin which is not in TCE

### ISSUE THREAD

**Issue by ThomasVitale** [vmware-tanzu/community-edition#3872]
## Description

The documentation for the App Toolkit package provides getting started instructions based on the `tanzu apps` plugin which is not part of TCE yet (the future inclusion is tracked here: https://github.com/vmware-tanzu/community-edition/issues/2696).

Until then, `kubectl` could be used (perhaps in combination with `kp`). Proposed solution: https://github.com/ThomasVitale/community-edition/commit/e91c63ef3acd24597800e2fdeb6c933cdbc016e8

## Location

Website page: https://tanzucommunityedition.io/docs/v0.11/package-readme-app-toolkit-0.1.0/
Source page: https://github.com/vmware-tanzu/community-edition/blob/main/addons/packages/app-toolkit/0.1.0/README.md

**Comment by joshrosso** [comment]
cc @kartiklunkad26 

If we do make this fix, note that it needs to be backported into our v0.11.0 docs. If we get this plugin in, as planned, for v0.12.0 this likely won't be an issue for that release/docs.

**Comment by kartiklunkad26** [comment]
@ThomasVitale thank you for your contribution! Appreciate it! :D 

Given we would be contributing Tanzu Apps CLI plug-in in a few weeks to TCE, would you be okay to wait until then? 

We do mention in the pre-requisite to get the Apps CLI plug-in from the plug-in repo for now..

**Comment by joshrosso** [comment]
@dvonthenen @kartiklunkad26, the RC contains the app CLI plugin now, right?

If so, can we close this?

**Comment by kartiklunkad26** [comment]
@joshrosso yeah we can close this :)

**Comment by ThomasVitale** [comment]
@kartiklunkad26 that's great, thank you!
