### ISSUE TITLE
Need to modify OVA template in order to configure node's booting

### ISSUE THREAD

**Issue by gbonazzoli** [vmware-tanzu/community-edition#3877]
I'v tried to logon into the VM created from the OVA `photon-3-kube-v1.22.5+vmware.1-tkg.2-tce-011.ova` at the login prompt with `root/changeme`.

But it doesn't work.

I need to enter in the VM in order to customize it by modifing the configuration in `/etc/default/docker` with 

`DOCKER_OPTS="--insecure-registry reg.poltronesofa.com"`

In this way every node of every cluster I made is ready to use my private registry.

How can i enter ?

**Comment by stmcginnis** [comment]
Hi @gbonazzoli - logging in locally with a password is disabled. Part of the deployment is providing an SSH key that gets configured for log in. See https://tanzucommunityedition.io/docs/v0.11/tips/#connect-to-cluster-nodes-with-ssh for details on how to connect to the VM.

**Comment by stmcginnis** [comment]
You may want to avoid manually modifying the nodes though. There is some information here about configuring tanzu to use a private registry: https://docs.vmware.com/en/VMware-vSphere/7.0/vmware-vsphere-with-tanzu/GUID-376FCCD1-7743-4202-ACCA-56F214B6892F.html

I don't think we have anything in the TCE docs, at least yet.

**Comment by gbonazzoli** [comment]
Thank you @stmcginnis 

I connected through ssh to the deprivileged `capv` user (in vSphere) and then `sudo bash` to become root.
Than I modified `/etc/default/docker` and rebooted the node.

And it works like a charm.

I can finally work with my private container registry.

Do you think that if I transform this modified virtual machine into the `photon-3-kube-v1.22.5+vmware.1-tkg.2-tce-011.ova` template, tanzu will be equally happy ?

**Comment by stmcginnis** [comment]
> Do you think that if I transform this modified virtual machine into the photon-3-kube-v1.22.5+vmware.1-tkg.2-tce-011.ova template, tanzu will be equally happy ?

I don't believe that would work. There are modifications done to the VM with cloud-init, so the currently running configuration is not what would be expected when initially deploying the template.

**Comment by joshrosso** [comment]
@kcoriordan, engineering talked and we think details about using a private registry would be great for our docs. Is this something we could target for a future release?
