### ISSUE TITLE
`tanzu uc delete uc_name` is not failing in form of error 

### ISSUE THREAD

**Issue by aman556** [vmware-tanzu/community-edition#3883]
## Bug Report

`tanzu uc delete uc_name` is not failing like a failure with error specifically with exit status 1.
If I am deleting a cluster with wrong command then it is failing with exit status 1. 
```
tanzu uc deletee abc           
Error: unknown command "deletee" for "unmanaged-cluster"

Did you mean this?
        delete

Run 'unmanaged-cluster --help' for usage.
Error: exit status 1
```
In similar manner the below failure should work
```
tanzu uc delete abc 

🧪 Deleting cluster: abc
Failed to delete cluster. Error: failed to locate the cluster's config file at /Users/amansha/.config/tanzu/tkg/unmanaged/abc
```
It is printing the failing log but not passing err message if we are running this in a function like
```
func cliRunner(name string, input io.Reader, args ...string) (string, error) {
	fmt.Fprintf(ginkgo.GinkgoWriter, "+ %s %s\n", name, strings.Join(args, " "))

	var stdOut bytes.Buffer
	mwriter := io.MultiWriter(&stdOut, os.Stderr)
	cmd := exec.Command(name, args...)
	cmd.Stdin = input
	cmd.Stdout = mwriter
	cmd.Stderr = mwriter

	err := cmd.Run()
	if err != nil {
		rc := -1
		if ee, ok := err.(*exec.ExitError); ok {
			rc = ee.ExitCode()
		}

		return "", fmt.Errorf("%s\nexit status: %d", err.Error(), rc)
	}
	return stdOut.String(), err
}

```
that err variable is empty every-time if it fails also then also err will be empty.
## Steps to Reproduce the Bug
`tanzu uc delete ` should fail rigorously with exit status 1.

## Environment Details

* Build version (`tanzu version`): v0.11.2
* Deployment (Managed/Unmanaged cluster): Unmanaged 
* Infrastructure Provider (Docker/AWS/Azure/vSphere): Docker
* Operating System (client): Mac

**Comment by karuppiah7890** [comment]
Not sure why the exit status is not set to 1. I see here that logging is done but no errors are returned -

https://github.com/vmware-tanzu/community-edition/blob/488f7c98335daf7edd91c243ce790c0015b59d40/cli/cmd/plugin/unmanaged-cluster/cmd/delete.go#L52-L55

Unlike

https://github.com/vmware-tanzu/community-edition/blob/488f7c98335daf7edd91c243ce790c0015b59d40/cli/cmd/plugin/unmanaged-cluster/cmd/delete.go#L42-L44

**Comment by aman556** [comment]
Thanks @karuppiah7890 for looking into code and putting here. Agree nil should replace with err.

**Comment by jpmcb** [comment]
Thanks for surfacing this! Taking a look today 👀
