### ISSUE TITLE
App Toolkit RBAC Role does not follow best practices

### ISSUE THREAD

**Issue by scothis** [vmware-tanzu/community-edition#3888]
## Bug Report

An RBAC Role within AppToolkit does not follow best practices

- the `apiGroups` should not have versions
- avoid wildcards
- `kapp.k14s.io` does not have real resources
- there should be a separate rule for each api group containing only the resources within that api group

 https://github.com/vmware-tanzu/community-edition/blob/6a6e6a9f3152b0a33ef2e9165b1b0bde374d2218/addons/packages/app-toolkit/0.1.0/test/example_sc/rbac.yaml#L18-L43

## Expected Behavior

I expect RBAC resources to follow best practices.

**Comment by kartiklunkad26** [comment]
This is really helpful feedback. Thank you @scothis! 

@krisapplegate @ryanmattcollins Do we need further information to fix this?

**Comment by ryankilroy** [comment]
No, I don't believe this has been addressed yet
