### ISSUE TITLE
`unmanaged-cluster` should be able to consume a local TKR

### ISSUE THREAD

**Issue by jpmcb** [vmware-tanzu/community-edition#3902]
## Feature Request

For unmanaged-cluster, we should enable consuming a _local_ TKR file:

Given I have a local TKR file, the following fails:

```
❯ ./unmanaged-cluster create test --provider minikube --tkr tkr-bom.yaml

📁 Created cluster directory

🔧 Resolving Tanzu Kubernetes Release (TKR)
   tkr-bom.yaml
   Downloading to: /home/jmcb/.config/tanzu/tkg/unmanaged/bom/tkr-bom.yaml.             failed getting TKR BOM. Error: failed to download tkr image: Collecting images: Working with index.docker.io/library/tkr-bom.yaml:latest: GET https://index.docker.io/v2/library/tkr-bom.yaml/manifests/latest: UNAUTHORIZED: authentication required; [map[Action:pull Class: Name:library/tkr-bom.yaml Type:repository]]
```

It'd be great if this worked and could intelligently tell if it was a file path vs a url. The flow would actually be pretty simple:
```
1. attempt to open path provided in --tkr
2. If opens, great! it's a local TKR, use that
3. If fails, attempt to use as registry URL
```

## Describe alternatives you've considered

Right now, `unmanaged-cluster` devs (or users with a TKR locally like in an air gapped environment) have to push it to some registry and provide that registry url for the `--tkr` file. This is a slow feedback loop when working against a new, in flight TKR

**Comment by karuppiah7890** [comment]
@jpmcb About the local TKR, what about the scenario where there's a local file but it's not accessible by the current user due to permission issues? Should we consider a separate flag like `--local-tkr` or `--tkr-file` and have `--tkr` for TKRs present in a registry

**Comment by jpmcb** [comment]
> what about the scenario where there's a local file but it's not accessible by the current user due to permission issues

File system permissions are a bit out of scope for what `unmanaged-clsuter` can handle. If the user does not have access to the file, attempting to use that file should fail.

> a separate flag like ... `--tkr-file` and have `--tkr` for TKRs present in a registry

Yes, I think separate flags works well and is a better, more straight forward UX. Would likely make the implementation simpler too. And w

**Comment by karuppiah7890** [comment]
> File system permissions are a bit out of scope for what unmanaged-clsuter can handle. If the user does not have access to the file, attempting to use that file should fail.

Yeah, makes sense. I was just wondering about the case where you said the tool will be intelligent, so, if the file is not accessible but present, it should give error that file is not accessible assuming it can find that it's present with whatever permissions it has but just not read it, in any other case, say directory under which the file is present itself is not accessible then it can't even read if a file is present or not, in which case it might end up looking for the TKR in the registry if we have a logic where we automatically check registry when no file is accessible / available. So yeah, it's tricky to show proper error or information depending on the intent (file TKR vs registry TKR) and situation (file TKR not accessible but is intended)

> Yes, I think separate flags works well and is a better, more straight forward UX. Would likely make the implementation simpler too.

Awesome!
