### ISSUE TITLE
Demo for User Contributed Packages

### ISSUE THREAD

**Issue by pnbrown** [vmware-tanzu/community-edition#391]
## Feature Request

It would be great to include the necessary files for a "Hello World" demo package for us to use as an instructional tool for folks to create and contribute their own packages. We want to make the adoption as smooth as possible and a demo package that could become a workshop seems ideal to that end.

**Comment by seemiller** [comment]
@pnbrown Is this still a relevant issue? There are at least 2 articles/guides for creating packages:

- https://tanzucommunityedition.io/docs/latest/solutions-opinionated-install-package/
- https://tanzucommunityedition.io/docs/latest/packages-create-example/

**Comment by pnbrown** [comment]
I think those are probably sufficient.
