### ISSUE TITLE
Add Tekton as a TCE package

### ISSUE THREAD

**Issue by alexandreroman** [vmware-tanzu/community-edition#3926]
## Feature Request

As a developer, I can rely on App-Toolkit to build and deploy Kubernetes apps to my TCE cluster. This works great when building images from a Git repo. However, with the existing App-Toolkit package I cannot run advanced use cases, such as running unit tests.
I wish I could use Tekton to run these use cases.

Integration with a Cartographer supply chain would be great, but this could be described / implemented with an other feature request.

## Describe alternatives you've considered

Tekton Pipelines is easy to install.
For example:
`kubectl apply -f https://storage.googleapis.com/tekton-releases/pipeline/previous/v0.34.1/release.yaml`

## Additional context

I've been working on a TCE package for Tekton for a few days.
Please have a look at https://github.com/alexandreroman/tekton-tanzu-extra, a TCE package which is part of my own package repo. This package only includes Tekton Pipelines though.

Feel free to reuse this source code for the implementation.

**Comment by kartiklunkad26** [comment]
@alexandreroman thanks for raising this issue. We are definitely looking to make this happen soon. Will keep you posted :)

**Comment by ThomasVitale** [comment]
I also worked on an [implementation of a Tekton Pipelines package](https://github.com/neptunus-platform/package-for-tekton-pipelines) since it's really useful when working with App Toolkit and defining supply chains. If there's anything I can do to help bringing this to TCE, I'm available.
