### ISSUE TITLE
Doc preview url in PRs not working for new toc entries

### ISSUE THREAD

**Issue by kcoriordan** [vmware-tanzu/community-edition#3939]
## Bug Report

Per versioning design, in a PR when I want to preview doc changes/addition:
I select the preview link, and change the url from `/docs/v0.11/` to `/docs/edge/`
This works ok, but if I select a new topic from the toc, the link defaults to `docs/v0.11/edge/`

related to: #3906 
## Environment Details

* Build version (`tanzu version`): 
* Deployment (Managed/Unmanaged cluster): 
* Infrastructure Provider (Docker/AWS/Azure/vSphere): 
* Operating System (client):

**Comment by joshrosso** [comment]
@kcoriordan @jonasrosland we discussed in retro today that we'll assign this to ya'll for v0.12.0.

If it turns out something core eng should work on, just let us know and we'll reassign.

Appreciate it!

**Comment by jonasrosland** [comment]
I'll spend some time on this today and tomorrow.
