### ISSUE TITLE
Expose all the versions that make up a TCE release.

### ISSUE THREAD

**Issue by joshrosso** [vmware-tanzu/community-edition#3940]
When we release TCE, we should have an easy way to expose users to all the software that underlies a release.

We also have multiple TKrs that make up a release, so we need to introspect our `tkg-bom`, which points to our `tkr-compatibility`, then for each tkr in that compatibility file, we should gather this data. Output would look something like:

* v1.22.5
    * calico-version:
    * antrea-version:
    * vsphere-csi-version: 
* v1.21.7
    * calico-version:
    * antrea-version:
    * vsphere-csi-version:

**Comment by joshrosso** [comment]
This is not required for `v0.12.0`, so marking it as a nice-to-have in case we can get to it.

**Comment by joshrosso** [comment]
Pulling @dvonthenen off this as it's a nice-to-have and we have a lot on our plate for this release :)

**Comment by kcoriordan** [comment]
I  can pull this out of BOM and add to support matrix when RC1 is available.

**Comment by joshrosso** [comment]
@kcoriordan it'll be a lot of work to pull all this info out without automation/generation.

But if you think it's something you can tackle for this release, we appreciate it.

**Comment by joshrosso** [comment]
We may backport something like this in docs for v0.12.0. But since it didn't make the cut, moving to v0.13.0 for now.

**Comment by joshrosso** [comment]
We should continue evaluating this for v0.13.0 at a minimum. Moving it to that milestone.
