### ISSUE TITLE
Restore Golang Cache Step in GitHub workflow is timing out

### ISSUE THREAD

**Issue by karuppiah7890** [vmware-tanzu/community-edition#3961]
Example - https://github.com/vmware-tanzu/community-edition/actions/runs/2074379555/attempts/1 - https://github.com/vmware-tanzu/community-edition/runs/5780484278?check_suite_focus=true

https://github.com/vmware-tanzu/community-edition/actions/runs/2140183772/attempts/1 - https://github.com/vmware-tanzu/community-edition/runs/5953769059?check_suite_focus=true

Restore Golang Cache job took up 6 hours to execute, timing out the GitHub workflow as [6 hours is the default max timeout time for jobs](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idtimeout-minutes)

**Comment by karuppiah7890** [comment]
Currently we rerun pipelines to mitigate the issue. We gotta find the root cause of the issue and fix it!

**Comment by karuppiah7890** [comment]
Another example of a long running golang cache restore step - https://github.com/vmware-tanzu/community-edition/runs/5966325203?check_suite_focus=true

**Comment by karuppiah7890** [comment]
Another instance of this - https://github.com/vmware-tanzu/community-edition/actions/runs/2229271363/attempts/1

**Comment by karuppiah7890** [comment]
Another instance of this - https://github.com/vmware-tanzu/community-edition/actions/runs/2227548282

**Comment by karuppiah7890** [comment]
Another instance! https://github.com/vmware-tanzu/community-edition/actions/runs/2228697052

**Comment by dvonthenen** [comment]
Yea, it happens frequently and I thought decreasing the cache size might help. I have a feeling it because of the number of runners accessing the cache over the internet on the AWS instances. Will need to look into this more.

**Comment by stmcginnis** [comment]
We may want to use this workaround: https://github.com/actions/cache/issues/720#issuecomment-1030412967

**Comment by stmcginnis** [comment]
Decided to give it a shot: https://github.com/vmware-tanzu/community-edition/pull/4225

**Comment by dvonthenen** [comment]
Seems pretty reasonable! Let's go for it.

**Comment by stmcginnis** [comment]
Took a quick look at some of the jobs that have run since the workaround was merged. Looks like we are successfully hitting the timeout, but continuing on and completing the job despite the hang.

https://github.com/vmware-tanzu/community-edition/runs/6216422345?check_suite_focus=true#step:5:606
https://github.com/vmware-tanzu/community-edition/runs/6216046333?check_suite_focus=true#step:5:606
