### ISSUE TITLE
Running TCE / `tanzu` CLI E2E tests using a tanzu CLI plugin

### ISSUE THREAD

**Issue by karuppiah7890** [vmware-tanzu/community-edition#3968]
## Feature Request

@mohitsharma-in shared this idea of creating a Tanzu CLI plugin to run E2E tests for TCE, TF

## Describe alternatives you've considered

None

## Additional context

None

**Comment by dvonthenen** [comment]
This seems like an interesting idea. I think that if we did create something like this, we would not want to ship this to end-users.
