### ISSUE TITLE
Determine the viability of start/stop lifecycle hooks in unmanaged-cluster for the kind provider

### ISSUE THREAD

**Issue by joshrosso** [vmware-tanzu/community-edition#3977]
With https://github.com/vmware-tanzu/community-edition/pull/3804 in place, we can now start/stop single-node kind clusters we install Tanzu atop.

However, kind does not support this as a first-class feature, see:

* https://github.com/kubernetes-sigs/kind/issues/2715

Today, we drop a layer below kind and talk to `docker` to do start/stop-like functionality.

In our next release, we should consider whether we want to keep this approach for kind. Considerations include things like:

* Is upstream `kind` interested in us contributing this?
* If not, are we comfortable with the technical debt it brings on?
* etc

_note: minikube has first-class support for start/stop and could continue to offer this feature independent of this decision_

**Comment by jorgemoralespou** [comment]
I too think this is very interesting for developers as they might use a workflow similar to the described here: http://jorgemoral.es/posts/2018-07-12-care-and-feed-minishift-dev-envs/. (Although the blog uses minishift/minikube) it is relevant to the "enhanced" development workflow experience.
