### ISSUE TITLE
Broken link for docs

### ISSUE THREAD

**Issue by johnSchnake** [vmware-tanzu/community-edition#4010]
## Description

https://tanzucommunityedition.io/docs/v0.11/latest/contribute/contributing/ results in a 404

## Location

Linked from this location https://github.com/vmware-tanzu/community-edition/blob/0f06a7490249102c04eeb157b11fc5d87b5d836a/CONTRIBUTING.md#nested-makefiles

**Comment by stmcginnis** [comment]
Thanks John. The link is correct in the current version in `main`. Is there a reason you are trying to use that from an older commit?

**Comment by johnSchnake** [comment]
Hm; I didnt realize I was using an older version at all. I must have linked to there from somewhere else. I've tried finding what I was looking at immediately prior and having trouble since I've bounced around so many similar pages.

I'm assuming I was looking at some code corresponding to that version and it followed me.

Glad its a non-issue. 👍
