### ISSUE TITLE
Doc preview updates not showing in edge

### ISSUE THREAD

**Issue by kcoriordan** [vmware-tanzu/community-edition#4059]
When I create a PR with doc edits, I can’t see edits to existing files in edge preview and  new file shows in toc, but gives a link error.
ref: #https://github.com/vmware-tanzu/community-edition/pull/4058

## Expected Behavior
I expect to see updates to existing file and new file

## Steps to Reproduce the Bug

- I create a PR, edit an existing file and add another new file https://github.com/vmware-tanzu/community-edition/pull/4058
- I click on the netlify preview link in the PR, select the Documentation tab and change the url from docs/v0.11/ to docs/edge
- updates to existing file not showing, new file showing in toc, but link broken

## Environment Details

* Build version (`tanzu version`): 
* Deployment (Managed/Unmanaged cluster): 
* Infrastructure Provider (Docker/AWS/Azure/vSphere): 
* Operating System (client):

**Comment by jonasrosland** [comment]
@a-mccarthy will take a look at this!

**Comment by a-mccarthy** [comment]
@jonasrosland from my digging today, it looks like there are some issues with how the folders are set up. i'm basing this off how we have this set up in Harbor, https://github.com/goharbor/website/, which hopefully isn't too different for what you are going for here.

It looks like the main problem is that load-docs.sh isn't accounting for local changes when it pulls docs in from the branches. 

Hugo builds the site based on whats in the /content folder and it looks like the load-docs.sh correctly pulls down all the files from the repo and puts it into versioned folders in the /content/docs folder. But load-docs.sh doesn't move the local changes into a place were they can be seeing in a local build or PR preview. 

<img width="356" alt="Screen Shot 2022-04-27 at 3 30 26 PM" src="https://user-images.githubusercontent.com/20771501/165608541-24b3ad3c-ce3d-4a8f-8eb2-0f60009e96ba.png">

^ after running `make prepare`, local changes in `architecture.md` are there, but not in a version folder so they wont show up. 


In Harbor, we get around this by keeping the docs in a separate folder other than the /content folder.  So we have a separate /docs folder which holds the docs, and when we build the site using `load-docs.sh` we pull content from the versions release branches from the branch's `/docs` folder and copy it into the local `/content/docs/v{release-branch}` folder. 

We also use a folder link for our edge version of the docs. The /edge version should be the place where the changes you are trying to make show up in your local and PR preview (at least this in true on Harbor, so i assume its what you are going for here). To do this, we link the docs in our /docs folder to the content/docs/edge folder. 

<img width="328" alt="Screen Shot 2022-04-27 at 3 37 56 PM" src="https://user-images.githubusercontent.com/20771501/165612406-6591f40c-3470-4951-b56c-9241a175db0a.png">

^ So when you make a change in /docs, its populated to the /content/docs/edge folder, hugo detects the change in /edge, and rebuilds the site to show the new changes. 

The /main folder isn't really needed. it gets created based on when is in the main branch, but if your PR merges then whatever you have in edge, will be become whats in the main branch. So having it is a bit redundant.

Notes:
* We keep non-versioned docs content still in the /content folder. So things like the community page, which doesnt need to be versioned is still there.
* We also gitignore things in the content/docs folder. bc the files we care about are in the /docs folder.
