### ISSUE TITLE
Versioned docs feedback

### ISSUE THREAD

**Issue by jpmcb** [vmware-tanzu/community-edition#4064]
## Feedback

We've been with the versioned docs for a bit now and going into another release, we should evaluate and gather feedback on how this has been going

### Issues related:

General:
- [x] https://github.com/vmware-tanzu/community-edition/issues/4055
- [x] https://github.com/vmware-tanzu/community-edition/issues/3750

Packages:
- [ ] https://github.com/vmware-tanzu/community-edition/issues/3931

Local dev workflows:
- [x] https://github.com/vmware-tanzu/community-edition/issues/3687
- [x] https://github.com/vmware-tanzu/community-edition/issues/4060
- [x] https://github.com/vmware-tanzu/community-edition/issues/4059

Blogs:
- [x] https://github.com/vmware-tanzu/community-edition/issues/4061

**Comment by kcoriordan** [comment]
fixed by #4319

**Comment by kcoriordan** [comment]
Hey @jpmcb - closing now as this is all working, the main fix being #4319
Just the #3931 is still open and that is already assigned to a release.
