### ISSUE TITLE
Make TCE version available in cluster's metadata

### ISSUE THREAD

**Issue by usahai30** [vmware-tanzu/community-edition#4088]
## Feature Request

Version info available in tkg-metadata consists of TKG version with tanzu framework version appended to it. There is no way, today, to correlate framework version to TCE version. Version that users see on github repo is different from this framework version.
For eg - For TCE github version v0.12 the version info available in `tkg-metadata` will be `v1.5.3-tf-v0.11.4`

This request is to make the version that we would publicly share or reference or tag in the TCE GH available in `tkg-metadata` config map in `tkg-system-public`. This would establish a well-defined contract for other integrations like TMC to enable/disable features on the cluster based on versions. Also, TMC will show this version on its UI for users to understand which TCE version are they running on.

**Comment by dvonthenen** [comment]
Yes, please! We need this!

@dvonthenen reminder to link the other issue to this one.
