### ISSUE TITLE
[Docs] [](/docs/v0.11/package-readme-app-toolkit-0.1.0/)

### ISSUE THREAD

**Issue by kurtbaker09** [vmware-tanzu/community-edition#4090]
## Description
During the last step of the example, there's an issue with referencing the workload example which needs to be updated.

## Location
https://tanzucommunityedition.io/docs/v0.11/package-readme-app-toolkit-0.1.0/#usage-example

## Additional Context

Issue from command prompt when running the steps
```
$ tanzu apps workload create -f https://raw.githubusercontent.com/cgsamp/tanzu-simple-web-app/main/example/workload.yaml
Error: unable to open file "https://raw.githubusercontent.com/cgsamp/tanzu-simple-web-app/main/example/workload.yaml": open https://raw.githubusercontent.com/cgsamp/tanzu-simple-web-app/main/example/workload.yaml: no such file or directory
Error: exit status 1

✖  exit status 1
```

https://raw.githubusercontent.com/cgsamp/tanzu-simple-web-app/main/example/workload.yaml

Needs to be... 

https://raw.githubusercontent.com/cgsamp/tanzu-simple-web-app/main/config/workload.yaml

**Comment by dvonthenen** [comment]
hey @kartiklunkad26 just an FYI on this new issue popping up at triage

**Comment by kartiklunkad26** [comment]
@kurtbaker09 thank you for raising this! yes we need to fix this! Will do so.
