### ISSUE TITLE
Generically check that all plugins havent been installed in release gate pipeline

### ISSUE THREAD

**Issue by karuppiah7890** [vmware-tanzu/community-edition#4099]
Examples of current pipeline - https://github.com/vmware-tanzu/community-edition/runs/6045143205?check_suite_focus=true , https://github.com/vmware-tanzu/community-edition/runs/6045143326?check_suite_focus=true

Code where we check the existence (but not version) of all the CLI plugins and the core CLI

https://github.com/vmware-tanzu/community-edition/blob/201caff7129d4fe0236550cf6a5ba72a57b8bced/test/release-build-test/check-release-build.sh#L48-L68

https://github.com/vmware-tanzu/community-edition/blob/201caff7129d4fe0236550cf6a5ba72a57b8bced/test/release-build-test/check-release-build.ps1#L52-L116

**Comment by karuppiah7890** [comment]
We are basically trying to ensure that the installed `tanzu` CLI plugins are available for use (are installed correctly and exist and work). The installation logs show which plugins are installed, example -

```bash
====================================
 Installing Tanzu Community Edition
====================================

Installing tanzu cli to /usr/local/bin/tanzu

Checking for required plugins...
Installing plugin 'apps:v0.6.0'
Installing plugin 'builder:v0.11.4'
Installing plugin 'cluster:v0.11.4'
Installing plugin 'codegen:v0.11.4'
Installing plugin 'conformance:v0.12.0-rc.2'
Installing plugin 'diagnostics:v0.12.0-rc.2'
Installing plugin 'kubernetes-release:v0.11.4'
Installing plugin 'login:v0.11.4'
Installing plugin 'management-cluster:v0.11.4'
Installing plugin 'package:v0.11.4'
Installing plugin 'pinniped-auth:v0.11.4'
Installing plugin 'secret:v0.11.4'
Installing plugin 'unmanaged-cluster:v0.12.0-rc.2'
Successfully installed all required plugins
✔  successfully initialized CLI 
```

**Comment by dvonthenen** [comment]
The current way of checking is far too brittle for any new plugin that is add you need to modify the script. This needs to be dynamic. You can just walk the names of yaml files in the `discovery` folder in the page, parse that name out, and then call version.
