### ISSUE TITLE
Tanzue Manage Cluster UI unable to detect OS Image

### ISSUE THREAD

**Issue by michaelh704** [vmware-tanzu/community-edition#4100]
## Bug Report

After fresh install of Windows 11 with TCE 0.11.0, the UI to deploy cluster does not detect OS images. 

## Expected Behavior

When OS image drop down clicked, available OS images displayed. I have uploaded both photon OS and ubuntu, neither are found.

Deploy Windows 11, install docker desktop, WSL update, etc, run tanzu management-cluster create --ui and try to create management cluster, no OS image was found. I have tried 3 times, followed instructions exactly with no other errors/issues.

![image](https://user-images.githubusercontent.com/33662138/163997094-87ca5990-aa2a-48bd-8193-941417c88678.png)
![image](https://user-images.githubusercontent.com/33662138/163997274-1b2b49bc-8551-4114-ab99-c412d2fe78c0.png)

## Environment Details

* Build version (`tanzu version`): 0.11.0
* Deployment (Managed/Unmanaged cluster): n/a
* Infrastructure Provider (Docker/AWS/Azure/vSphere): vSphere 7.0.3 u3d
* Operating System (client): Win 11 pro

**Comment by stmcginnis** [comment]
Hi Michael - did you download the OVAs from [Customer Connect](https://customerconnect.vmware.com/en/downloads/details?downloadGroup=TCE-0110&productId=1266&rPId=86727). As it shows, you have `tkg.2`, but TCE is looking for `tkg.3`, so you don't have the necessary templates deployed in your environment.

**Comment by michaelh704** [comment]
> Hey @michaelh704! Thanks for opening your first issue. We appreciate your contribution and welcome you to our community! We are glad to have you here and to have your input on Tanzu Community Edition.

Yep, I downloaded them from the link in the Prepare to Deploy a Cluster to vSphere section here: https://tanzucommunityedition.io/docs/v0.11/vsphere/

It links to: https://customerconnect.vmware.com/downloads/get-download?downloadGroup=TCE-0110

![image](https://user-images.githubusercontent.com/33662138/163998364-aa42764c-c2e7-4d0b-a4b5-b2d2d2fe5469.png)

**Comment by stmcginnis** [comment]
Hmm, I'm unable to reproduce this. I spun up a clean system and made sure I removed all existing templates from my vSphere environment. I then downloaded the v1.22.5 OVA from Customer Connect, deployed it to my environment, and converted it to a template. I then downloaded and installed the v0.11.0 release of TCE, ran `tanzu management-cluster create --ui` and walked through the wizard. When I got to the image selection step, it recognized the template that I had uploaded.

I see the file from your second screenshot, but can you confirm you've deployed that OVA and then converted it from a VM to a template?

**Comment by vrabbi** [comment]
it looks from the photo that you uploaded the ova to a datastore but instead you need todeploy a vm from the ova and then convert that VM to a template. currently it looks like its just a file on your datastore
