### ISSUE TITLE
Tanzu CLI update from 10.1 to 11 failed with - Error: could not read artifact "artifacts/pinniped-auth/v0.11.4/tanzu-pinniped-auth-linux_amd64": storage: object doesn't exist

### ISSUE THREAD

**Issue by trantor1** [vmware-tanzu/community-edition#4102]
## Bug Report

Tanzu cli update from commandline not working at this moment and failed with

`
Error: could not read artifact "artifacts/pinniped-auth/v0.11.4/tanzu-pinniped-auth-linux_amd64": storage: object doesn't exist
`

## Steps to Reproduce the Bug

* user@k8s-mgmt:~$ tanzu version
version: v0.10.1
buildDate: 2022-02-14
sha: 401d55b

* user@k8s-mgmt:~$ tanzu update
     the following updates will take place: 
     core v0.10.1 → v0.11.4
     package v0.10.1 → {v0.11.4 %!s(*cli.GCPBucketRepository=&{tce-tanzu-cli-framework artifacts core 0x13d53a0})}
     pinniped-auth v0.10.1 → {v0.11.4 %!s(*cli.GCPBucketRepository=&{tce-tanzu-cli-framework artifacts core 0x13d53a0})}
     secret v0.10.1 → {v0.11.4 %!s(*cli.GCPBucketRepository=&{tce-tanzu-cli-framework artifacts core 0x13d53a0})}
     cluster v0.10.1 → {v0.11.4 %!s(*cli.GCPBucketRepository=&{tce-tanzu-cli-framework artifacts core 0x13d53a0})}
     kubernetes-release v0.10.1 → {v0.11.4 %!s(*cli.GCPBucketRepository=&{tce-tanzu-cli-framework artifacts core 0x13d53a0})}
     login v0.10.1 → {v0.11.4 %!s(*cli.GCPBucketRepository=&{tce-tanzu-cli-framework artifacts core 0x13d53a0})}
     management-cluster v0.10.1 → {v0.11.4 %!s(*cli.GCPBucketRepository=&{tce-tanzu-cli-framework artifacts core 0x13d53a0})}
would you like to continue? [y/n] y

## Environment Details

* Build version (`tanzu version`): version: v0.10.1, buildDate: 2022-02-14, sha: 401d55b
* Deployment (Managed/Unmanaged cluster): Managed
* Infrastructure Provider (Docker/AWS/Azure/vSphere): vSphere
* Operating System (client): Ubuntu 20.04.4 LTS, x86_64

**Comment by Aradiv** [comment]
i get the same error but with a different plugin 
```
? would you like to continue? [y/n] y
Error: could not read artifact "artifacts/conformance/v0.11.0/tanzu-conformance-linux_amd64": storage: object doesn't exist

✖  could not read artifact "artifacts/conformance/v0.11.0/tanzu-conformance-linux_amd64": storage: object doesn't exist
```
