### ISSUE TITLE
There is no information on whether a package requires a config file

### ISSUE THREAD

**Issue by thesteve0** [vmware-tanzu/community-edition#4111]
## Bug Report

This might be a doc issue but I actually think this is a deficiency in the package listing command. 
There is no easy to find information on whether a config file is required for a package to work properly, let alone what contents of that file would be required. 

This page, https://tanzucommunityedition.io/docs/main/ref-unmanaged-cluster/#installing-packages-during-bootstrapping, talks about a config file being optional.  The bottom of that section has this text

For further information on [packages and configuring packages, read the documentation.](https://tanzucommunityedition.io/docs/main/package-management/)

But that link should probably be to https://tanzucommunityedition.io/docs/main/package-management/#configuring-a-package
That doc takes a few reads for me to understand - but that should be a doc issue.

Docs aside, there should be guidance in the `tanzu` cli when I list packages that says whether a configuration file is required or recommended for proper functioning. Or maybe there should be a details page for a package obtained through:
`tanzu package available list contour.community.tanzu.vmware.com/1.20.1`
which contains
1. Is a configuration required
2. Example how to get the --values-schema
3. Link to the page in the doc for that version - https://tanzucommunityedition.io/docs/main/package-readme-contour-1.20.1/

## Expected Behavior

Self-discovery of configuration and detailed information for a package

**Comment by LukeShortCloud** [comment]
This has also been a challenge I have faced during my first few Tanzu package deployments.

Related to this, in an ideal world, no package would need configuration values and should deploy for lab/demo purposes with sane default values. For example, Harbor requires setting a username and password. As an end-user, I would expect that to at least have simple values like "admin" and "admin" or, better yet, have the password be random and auto-generated.

As it is today, this all makes approaching Tanzu packages for newcomers a not-so-great experience.
