### ISSUE TITLE
Fix expected cluster name in the docs for unmanaged clusters

### ISSUE THREAD

**Issue by thesteve0** [vmware-tanzu/community-edition#4115]
## Description

Any of our doc that talks about setting a kubectl context won't work for unmanaged clusters. It doesn't work because our current doc assumes the kube context = the tanzu cluster name, but we pre-pend the provider type to the cluster name for unmanaged clusters. 

 We need to update the docs to let the user know their cluster name is NOT the name they use to set the context. The name is 
`<provider-type>-<clustername>' and that `kind` is going to be prepended by default.

## Location

Not sure, but it is probably a lot of places

**Comment by jpmcb** [comment]
Example of where we instruct to set the context: https://tanzucommunityedition.io/docs/main/sample/

**Comment by kcoriordan** [comment]
https://kubernetes.slack.com/archives/C02GY94A8KT/p1651077006770439
