### ISSUE TITLE
Internet-Restricted Environment: Unable to set up management cluster 

### ISSUE THREAD

**Issue by snehalbiche** [vmware-tanzu/community-edition#4119]
## Bug Report

Trying to deploy Tanzu community edition in Internet restricted environment. followed VMware docs to setup Harbor registry as per link https://docs.vmware.com/en/VMware-Tanzu-Kubernetes-Grid/1.4/vmware-tanzu-kubernetes-grid-14/GUID-mgmt-clusters-airgapped-environments.html

publish image script ran successfully and other images are available on the harbor internal registry. 

even below pods are coming up using harbor registry:

tkg@tkgbootstrap:~$ kubectl get pods -A --kubeconfig=/home/tkg/.kube-tkg/tmp/config_UTmsSgtO
NAMESPACE                           NAME                                                                  READY   STATUS    RESTARTS   AGE
capi-kubeadm-bootstrap-system       capi-kubeadm-bootstrap-controller-manager-7798d45856-hzxn2            1/1     Running   0          20m
capi-kubeadm-control-plane-system   capi-kubeadm-control-plane-controller-manager-86d68bbdb5-krp2w        1/1     Running   0          20m
capi-system                         capi-controller-manager-588f78ccc4-hh9t9                              1/1     Running   0          20m
capv-system                         capv-controller-manager-66d5556b98-8969z                              1/1     Running   0          20m
cert-manager                        cert-manager-7df456cd5f-dqpwk                                         1/1     Running   0          20m
cert-manager                        cert-manager-cainjector-6c4786898-rb74m                               1/1     Running   0          20m
cert-manager                        cert-manager-webhook-6bcf7dff85-2znmg                                 1/1     Running   0          20m
kube-system                         coredns-6765cf8944-jvzwm                                              1/1     Running   0          20m
kube-system                         coredns-6765cf8944-wtldn                                              1/1     Running   0          20m
kube-system                         etcd-tkg-kind-c9fs7iau0g6n224aofq0-control-plane                      1/1     Running   0          21m
kube-system                         kindnet-sst9n                                                         1/1     Running   0          20m
kube-system                         kube-apiserver-tkg-kind-c9fs7iau0g6n224aofq0-control-plane            1/1     Running   0          21m
kube-system                         kube-controller-manager-tkg-kind-c9fs7iau0g6n224aofq0-control-plane   1/1     Running   0          21m
kube-system                         kube-proxy-vhx27                                                      1/1     Running   0          20m
kube-system                         kube-scheduler-tkg-kind-c9fs7iau0g6n224aofq0-control-plane            1/1     Running   0          21m
local-path-storage                  local-path-provisioner-547f784dff-x66b8                               1/1     Running   0          20m

but on the control plane node it's unable to fetch or initalize kubeadm. 
tkg@tkgbootstrap:~$ kubectl get nodes -A --kubeconfig=/home/tkg/.kube-tkg/tmp/config_UTmsSgtO
NAME                                          STATUS   ROLES                  AGE   VERSION
tkg-kind-c9fs7iau0g6n224aofq0-control-plane   Ready    control-plane,master   22m   v1.22.5+vmware.1

need to know the reason why? I am unable to login into the control plan node and find out what's wrong. need help or step by step documentation on what's missing in the configuration so the control plane node will reach to harbor registry and download the required packages and images 

## Expected Behavior

management and worker cluster deployed successfully 

## Steps to Reproduce the Bug

1) setup DHCP for internal network
2) setup Tanzu CLI and pre-req
3) setup harbor registry 
4) add below parameters in a cluster config file
TKG_CUSTOM_IMAGE_REPOSITORY: tkgbootstrap.tanzu.lab/tkg
TKG_CUSTOM_IMAGE_REPOSITORY_SKIP_TLS_VERIFY: true 
TKG_CUSTOM_IMAGE_REPOSITORY_CA_CERTIFICATE: "<CERT>"

5) run command "tanzu management-cluster create tanzumgmt  --file tkg-mgmt-cluster.yaml -v 6" 

## Screenshots or additional information and context

output of command:

tanzu management-cluster create tanzumgmt  --file tkg-mgmt-cluster.yaml -v 6

compatibility file (/home/cisco/.config/tanzu/tkg/compatibility/tkg-compatibility.yaml) already exists, skipping download
BOM files inside /home/cisco/.config/tanzu/tkg/bom already exists, skipping download
CEIP Opt-in status: false

Validating the pre-requisites...
Identity Provider not configured. Some authentication features won't work.
WARNING: key is not a string: %!s(int=1)WARNING: key is not a string: %!s(int=1)Checking if VSPHERE_CONTROL_PLANE_ENDPOINT 10.14.7.200 is already in use

Setting up management cluster...
Validating configuration...
Using infrastructure provider vsphere:v1.0.2
Generating cluster configuration...
WARNING: key is not a string: %!s(int=1)WARNING: key is not a string: %!s(int=1)Setting up bootstrapper...
Fetching configuration for kind node image...
kindConfig: 
 &{{Cluster kind.x-k8s.io/v1alpha4}  [{  map[] [{/var/run/docker.sock /var/run/docker.sock false false } {/etc/containerd/tkg-registry-ca.crt /tmp/tkg-registry-ca.crt809402610 false false }] [] [] []}] {ipv4 0  100.96.0.0/11 100.64.0.0/13 false } map[] map[] [apiVersion: kubeadm.k8s.io/v1beta2
kind: ClusterConfiguration
imageRepository: projects.registry.vmware.com/tkg
etcd:
  local:
    imageRepository: projects.registry.vmware.com/tkg
    imageTag: v3.5.0_vmware.7
dns:
  type: CoreDNS
  imageRepository: projects.registry.vmware.com/tkg
  imageTag: v1.8.4_vmware.7] [] [[plugins]
[plugins.'io.containerd.grpc.v1.cri']
[plugins.'io.containerd.grpc.v1.cri'.registry]
[plugins.'io.containerd.grpc.v1.cri'.registry.configs]
[plugins.'io.containerd.grpc.v1.cri'.registry.configs.'tkgbootstrap.tanzu.lab']
[plugins.'io.containerd.grpc.v1.cri'.registry.configs.'tkgbootstrap.tanzu.lab'.tls]
insecure_skip_verify = true
ca_file = '/etc/containerd/tkg-registry-ca.crt'
] []}
Creating kind cluster: tkg-kind-c9fqvniu0g6i6el7gon0
Creating cluster "tkg-kind-c9fqvniu0g6i6el7gon0" ...
Ensuring node image (tkgbootstrap.tanzu.lab/tkg/kind/node:v1.22.5_vmware.1) ...
Image: tkgbootstrap.tanzu.lab/tkg/kind/node:v1.22.5_vmware.1 present locally
Preparing nodes ...
Writing configuration ...
Starting control-plane ...
Installing CNI ...
Installing StorageClass ...
Waiting 2m0s for control-plane = Ready ...
Ready after 18s 
Bootstrapper created. Kubeconfig: /home/cisco/.kube-tkg/tmp/config_8EtoB1DY
Installing providers on bootstrapper...
Fetching providers
Installing cert-manager Version="v1.5.3"
Waiting for cert-manager to be available...
Installing Provider="cluster-api" Version="v1.0.1" TargetNamespace="capi-system"
Installing Provider="bootstrap-kubeadm" Version="v1.0.1" TargetNamespace="capi-kubeadm-bootstrap-system"
Installing Provider="control-plane-kubeadm" Version="v1.0.1" TargetNamespace="capi-kubeadm-control-plane-system"
Installing Provider="infrastructure-vsphere" Version="v1.0.2" TargetNamespace="capv-system"
installed  Component=="cluster-api"  Type=="CoreProvider"  Version=="v1.0.1"
installed  Component=="kubeadm"  Type=="BootstrapProvider"  Version=="v1.0.1"
installed  Component=="kubeadm"  Type=="ControlPlaneProvider"  Version=="v1.0.1"
installed  Component=="vsphere"  Type=="InfrastructureProvider"  Version=="v1.0.2"
Waiting for provider infrastructure-vsphere
Waiting for provider bootstrap-kubeadm
Waiting for provider cluster-api
Waiting for provider control-plane-kubeadm
Waiting for resource capi-kubeadm-bootstrap-controller-manager of type *v1.Deployment to be up and running
pods are not yet running for deployment 'capi-kubeadm-bootstrap-controller-manager' in namespace 'capi-kubeadm-bootstrap-system', retrying
Waiting for resource capi-kubeadm-control-plane-controller-manager of type *v1.Deployment to be up and running
Waiting for resource capv-controller-manager of type *v1.Deployment to be up and running
pods are not yet running for deployment 'capi-kubeadm-control-plane-controller-manager' in namespace 'capi-kubeadm-control-plane-system', retrying
pods are not yet running for deployment 'capv-controller-manager' in namespace 'capv-system', retrying
Waiting for resource capi-controller-manager of type *v1.Deployment to be up and running
pods are not yet running for deployment 'capi-controller-manager' in namespace 'capi-system', retrying
Passed waiting on provider bootstrap-kubeadm after 5.199371434s
Passed waiting on provider control-plane-kubeadm after 5.227644724s
pods are not yet running for deployment 'capv-controller-manager' in namespace 'capv-system', retrying
Passed waiting on provider cluster-api after 5.270009921s
Passed waiting on provider infrastructure-vsphere after 10.230091066s
Success waiting on all providers.
Start creating management cluster...
patch cluster object with operation status: 
        {
                "metadata": {
                        "annotations": {
                                "TKGOperationInfo" : "{\"Operation\":\"Create\",\"OperationStartTimestamp\":\"2022-04-20 07:03:02.399410213 +0000 UTC\",\"OperationTimeout\":1800}",
                                "TKGOperationLastObservedTimestamp" : "2022-04-20 07:03:02.399410213 +0000 UTC"
                        }
                }
        }
cluster control plane is still being initialized: WaitingForControlPlane
cluster control plane is still being initialized: WaitingForControlPlane, retrying
cluster control plane is still being initialized: Cloning @ Machine/tanzumgmt-control-plane-b6htq
cluster control plane is still being initialized: Cloning @ Machine/tanzumgmt-control-plane-b6htq, retrying
cluster control plane is still being initialized: PoweringOn @ Machine/tanzumgmt-control-plane-b6htq
cluster control plane is still being initialized: PoweringOn @ Machine/tanzumgmt-control-plane-b6htq, retrying
cluster control plane is still being initialized: PoweringOn @ Machine/tanzumgmt-control-plane-b6htq, retrying
cluster control plane is still being initialized: PoweringOn @ Machine/tanzumgmt-control-plane-b6htq, retrying
cluster control plane is still being initialized: WaitingForKubeadmInit
cluster control plane is still being initialized: WaitingForKubeadmInit, retrying
cluster control plane is still being initialized: WaitingForKubeadmInit, retrying

## Environment Details

* Build version (`tanzu version`): 
* version: v0.11.2
buildDate: 2022-03-24
sha: 6431d1d

* Deployment (Managed/Unmanaged cluster): Managed
* Infrastructure Provider (Docker/AWS/Azure/vSphere):  vSphere 6.7
* Operating System (client): Ubuntu

**Comment by stmcginnis** [comment]
Thanks, TCE does not support airgapped deployment yet. This is being tracked here: https://github.com/vmware-tanzu/community-edition/issues/460

Will close this and reference in that issue so we can keep it in one place, but this is useful information!
