### ISSUE TITLE
Docs: Packaging process docs have broken image links

### ISSUE THREAD

**Issue by jpmcb** [vmware-tanzu/community-edition#4126]
## Bug Report

Images under the following page: https://tanzucommunityedition.io/docs/v0.11/designs/package-process/

are broken

![Screen Shot 2022-04-20 at 2 15 12 PM](https://user-images.githubusercontent.com/23109390/164315161-46240694-1d7b-4d8b-8469-1dc78730c704.png)

## Expected Behavior

See images in docs page

## Steps to Reproduce the Bug

Go to the [package process docs page](https://tanzucommunityedition.io/docs/v0.11/designs/package-process/) and see no images. Open developer console to see 404 links

**Comment by stmcginnis** [comment]
May be related, or have a similar fix required: https://github.com/vmware-tanzu/community-edition/issues/4084
