### ISSUE TITLE
Load images from host into UC node

### ISSUE THREAD

**Issue by jorgemoralespou** [vmware-tanzu/community-edition#4145]
## Feature Request
Provide a way to load images from the host into the Unmanaged cluster so that we can lower the time it takes to a working cluster, if we have those images available.

When creating a cluster, a lot of images are pulled down from internet, as there's no mechanism to cache the images on the host, they are downloaded directly into the kind-node and the minikubeVM. It'll be nice to provide a way to specify in the Unmanaged cluster config a way to cache (save and restore) images from the UC node into the host, so that when creating/deleting clusters frequently, time to a working cluster is minimized.

How I see this working would be something like:
- Specify in the UC config a list of images that should be saved/restored/both
- If when the cluster is created, the images are available, push the ones with "restore/both" to the UC node.
- If they are not available, download from the remote registry and save the images on the host for next cluster bootstrap if defined as `to be saved` in the config
- The process should still potentially check for the SHA of the images to prevent nefarious use, although this is nice to have, since the images would come from the user's host
- Additionally provide `tanzu uc` commands for:
  -  list images on node
  - save image
  - load image
  - add image to the config, create commands

## Describe alternatives you've considered
We can use raw configuration for minikube and kind, but it would be ideal to have an OOTB way for all UC in a consistent manner.

## Additional context
- Somehow raised in this issue: https://github.com/vmware-tanzu/community-edition/issues/3955
- Asked in this k8s slack thread: https://kubernetes.slack.com/archives/C02GY94A8KT/p1650545629347499

**Comment by cmoulliard** [comment]
Ideally a new command could be supported by the client such as `tanzu load container-image`. the code to be developed should not be too complex. See by example what kind [do](https://github.com/kubernetes-sigs/kind/blob/main/pkg/cmd/kind/load/docker-image/docker-image.go#L175)
