### ISSUE TITLE
Re-introduce TMC registration to the kickstart UI

### ISSUE THREAD

**Issue by joshrosso** [vmware-tanzu/community-edition#4146]
We had initially disabled TMC registration from appearing in the kickstart UI via edition detection in framework.

now that TCE clusters can be registered with TMC, we should consider re-enabling this.

**Comment by miclettej** [comment]
Hi @joshrosso do we need this change in any specific Tanzu Framework patch release or okay to just re-introduce on framework main branch?

**Comment by joshrosso** [comment]
I need to verify we want to do this with PM first. Then, if so, main is adequate. We’ll backport the change should we need it in a future release.

**Comment by vrabbi** [comment]
as this was removed from TKG in the 1.5.x releases from the UI, does it make sense to simply follow the same path here and not have TMC registration part of the kickstart process?

**Comment by miclettej** [comment]
@vrabbi good question. The process for registering a cluster with TMC during management cluster creation is not a smooth user experience. When this feature was first released in the kickstart UI, users could simply copy the registration URL from TMC which would publicly expose the registration YAML. That was eventually changed and accessing the registration YAML now requires authentication. Without a reasonable user experience to assist in the auth process, registering a management cluster through the kickstart UI is not much of a convenience.

**Comment by mcarpendale** [comment]
@miclettej if TMC requires auth now - could that auth be added to process - then pull URL. The "convenience" is user experience, its done during creation from a single window - not bouncing around to different UI's
