### ISSUE TITLE
Diagnostics plugin e2e tests hard coded to test with TCE v0.10.0

### ISSUE THREAD

**Issue by stmcginnis** [vmware-tanzu/community-edition#4158]
## Bug Report

The setup for the `diagnostics` plugin tries to get the v0.10.0 release of TCE:

https://github.com/vmware-tanzu/community-edition/blob/main/cli/cmd/plugin/diagnostics/e2e-test/setup-e2e-test.sh#L11

This should be unnecessary and should just use the current code base for everything.

**Comment by vladimirvivien** [comment]
@seemiller @dvonthenen 
Is the unmanaged cluster plugin a good model for how the Makefile should work ?
https://github.com/vmware-tanzu/community-edition/blob/main/cli/cmd/plugin/unmanaged-cluster/Makefile
I am leaning in doing it how it's done there.

**Comment by vladimirvivien** [comment]
This PR https://github.com/vmware-tanzu/community-edition/pull/4106 is also related.

**Comment by vladimirvivien** [comment]
This can be closed, it was fixed in #4106
