### ISSUE TITLE
Diagnostics plugin e2e tests assume `kind` is available

### ISSUE THREAD

**Issue by stmcginnis** [vmware-tanzu/community-edition#4159]
## Bug Report

The e2e tests for the `diagnostics` plugin assume that `kind` is available on the system. It uses this to spin up a cluster, which it then uses to test data collection.

## Expected Behavior

Test code should either import `kind` as a dependency and programmatically create a cluster, or it should now use the `unmanaged-cluster` command to create a cluster to use.

**Comment by aman556** [comment]
I think we can close this now as we have used unmanged cluster for Diagnostic e2e test.
