### ISSUE TITLE
Unmanaged Clusters - Kapp Controller Cluster DNS issue

### ISSUE THREAD

**Issue by vrabbi** [vmware-tanzu/community-edition#4163]
## Bug Report
Kapp Controller is run on host network in TCE. there is an issue with Kapp Controller config that doesnt allow an app or package to reference a cluster DNS name (eg. http://source-controller-manager-artifact-service.source-system.svc.cluster.local./imagerepository/demo01/tanzu-java-web-app-delivery/c72f8fee9ed3d9d5af40d807fc8e47617af1d8ba42357d1da84bae2a9e4a9438.tar.gz).
In [Tanzu Framework PR 1672](https://github.com/vmware-tanzu/tanzu-framework/pull/1328) it seems this was fixed however this doesnt work on TCE 0.12.rc2. i dont have an older TCE env right now but believe this used to work. i manually changed the dnsPolicy to the correct value of ClusterFirstWithHostNet from what is set by UC today (ClusterFirst) and everything works.

Is this indeed a regression in the Kapp Controller installation?

While i have tested this with TAP 1.1 I'm pretty sure the same issues will occur with app toolkit as it happens when the cartographer deliverable stamps out the Carvel App CR to apply the manifests of the knative service which which are supplied via a flux source controller blob URL using the in cluster DNS name

## Expected Behavior
for Kapp Controller to be able to resolve cluster DNS records

## Steps to Reproduce the Bug
1. install an unmanaged-cluster using 0.12.rc2
2. get the current dnsPolicy setting
```
kubectl get pod -n tkg-system -l app=kapp-controller -o json | jq .items[0].spec.dnsPolicy
```
3.  view the resolv.conf in the pod
```
kubectl exec -it $(kubectl get po -n tkg-system -l app=kapp-controller -o name --no-headers) -n tkg-system -- cat /etc/resolv.conf
```
5. Create an app that uses a local source such as fluxcd source controller

## Environment Details

* Build version (`tanzu version`): 
* Deployment (Managed/Unmanaged cluster): 
* Infrastructure Provider (Docker/AWS/Azure/vSphere): 
* Operating System (client):

**Comment by seemiller** [comment]
We'll take a look into this issue and determine what's up!
