### ISSUE TITLE
Unmanaged-cluster delete does not ask for confirmation

### ISSUE THREAD

**Issue by vrabbi** [vmware-tanzu/community-edition#4164]
## Feature Request
it would be great if tanzu unmanaged cluster was similar to managed clusters where deletion asks for confirmation.

## Describe alternatives you've considered
be careful when deleting the cluster

**Comment by vkorbes** [comment]
I believe a simple `This will delete the current working cluster and possibly cause loss of data. Confirm: [y/n]` or similar wouldn't hurt. Alternatively a `-y` (or similar) argument could be passed to avoid the check in case this is being run by a script.

What are the arguments against, @seemiller?

**Comment by stmcginnis** [comment]
One argument against doing this is backwards compatibility. Now that unmanaged cluster support has been out for a couple releases, it's safe to assume at least a few people are using it in scripts and automation for CI or other purposes.

It would be a simple change to add a `-y` switch to the CLI for someone to allow this automation to still work without hanging on waiting for input. But it's that transition from the currently released versions to this new version that would support the `-y` that would be the problem.

If someone were to add `-y` to their existing automation, the current releases of TCE would fail with "Error: unknown shorthand flag: 'y' in -y". So if their automation automatically picked up the new version it would hang on waiting for that confirmation. If they tried to be proactive by adding the `-y` to their scripts and it was using the old version it would fail on unknown input.

You could argue that the person would just need to control the upgrade and make sure the proper updates are done at the right time, which is very fair. But I do know of at least two instances now where this is being done in systems where that's not as straightforward as it sounds.

Just a data point to consider.
