### ISSUE TITLE
Fix linter workflow

### ISSUE THREAD

**Issue by karuppiah7890** [vmware-tanzu/community-edition#4215]
There have been lot of failures in the pipeline - https://github.com/vmware-tanzu/community-edition/actions/workflows/check-all.yaml - `Check - All linters, etc`

https://github.com/vmware-tanzu/community-edition/actions/runs/2228697052

https://github.com/vmware-tanzu/community-edition/actions/runs/2228888729 (not `main` but [`̦release-kpack-0.5.3`](https://github.com/vmware-tanzu/community-edition/tree/release-kpack-0.5.3)

https://github.com/vmware-tanzu/community-edition/actions/runs/2228988316

https://github.com/vmware-tanzu/community-edition/actions/runs/2228991724

https://github.com/vmware-tanzu/community-edition/actions/runs/2229113941

https://github.com/vmware-tanzu/community-edition/actions/runs/2229271375

https://github.com/vmware-tanzu/community-edition/actions/runs/2229520943

This is also reflected in the badge in our readme - 

[![Check - All linters, etc](https://github.com/vmware-tanzu/community-edition/actions/workflows/check-all.yaml/badge.svg)](https://github.com/vmware-tanzu/community-edition/actions/workflows/check-all.yaml)

**Comment by stmcginnis** [comment]
The one failure I looked at looks the same as: https://github.com/vmware-tanzu/community-edition/issues/4184

That failure went away after I upgraded to the latest Carvel binaries. We may need to add this to the workflow definition: https://github.com/vmware-tanzu/community-edition/blob/main/.github/workflows/check-packages.yaml#L27-L31

**Comment by dvonthenen** [comment]
You can also use `make ensure-deps` or just individually call the script in the `hack/ensure-deps` folder

**Comment by stmcginnis** [comment]
Odd... `ensure-deps` is already being called twice in that workflow:

https://github.com/vmware-tanzu/community-edition/blob/main/.github/workflows/check-all.yaml#L54
https://github.com/vmware-tanzu/community-edition/blob/main/.github/workflows/check-all.yaml#L63

Both time before we call the `make test-packages` where we get the failure that was presumably from an old or missing ytt:

https://github.com/vmware-tanzu/community-edition/blob/main/.github/workflows/check-all.yaml#L72

**Comment by stmcginnis** [comment]
Looks like it is because we are pinned to an older version of `ytt` there that has an issue. Will need to bump that.

https://github.com/vmware-tanzu/community-edition/blob/main/hack/ensure-deps/ensure-ytt.sh#L15
