### ISSUE TITLE
Application Toolkit Version 0.1.0 - Contour Version

### ISSUE THREAD

**Issue by dashaun** [vmware-tanzu/community-edition#4280]
When I install the app toolkit package I am getting Contour v1.19.1 instead of v1.20.1 which is the latest version and the one that is listed in the [documentation](https://tanzucommunityedition.io/docs/v0.11/package-readme-app-toolkit-0.1.0/)

**Comment by jpmcb** [comment]
cc @vmware-tanzu/pkg-app-toolkit-owners 👀 

Maybe there's an issue with what image is being cached?

**Comment by seemiller** [comment]
@kartiklunkad26 Just confirmed that the `0.1.0` version of app-toolkit does indeed have Contour 1.19.1. At this point, it is probably easiest to update the documentation to match.

**Comment by kartiklunkad26** [comment]
@ryankilroy would it be possible for you to update the docs? Its really surprising though that this is the case..
