### ISSUE TITLE
Diagnostics plugin - upgrade to a new `tanzu-framework` (or completely decouple)

### ISSUE THREAD

**Issue by jpmcb** [vmware-tanzu/community-edition#4284]
## Feature Request

The diagnostics plugin is pulling in `tanzu-framework` for it's `config` capabilities:

https://github.com/vmware-tanzu/community-edition/blob/b95dc158da781bfadbabcd7b77967c7abe6ce1d5/cli/cmd/plugin/diagnostics/pkg/support.go#L39

Diagnostics is still on `0.11.4` of tanzu-framework. We should consider bumping this version of `tanzu-framework` in diagnostics or possibly completely decouple this dependency in this plugin.

**Comment by jpmcb** [comment]
cc @vladimirvivien - Curious your thoughts on this? Can we rip out those APIs so we don't consume TF?

**Comment by vladimirvivien** [comment]
@jpmcb Yes, this code is used to figure out if a cluster is of type management cluster or workload. There is probably a way to break off the direct dependency and get that info directly.
