### ISSUE TITLE
UI Plugin: WC Add REST API for creating workload cluster

### ISSUE THREAD

**Issue by miclettej** [vmware-tanzu/community-edition#4288]
##Feature Request
Add a REST API to create workload cluster using cluster class.

Should use endpoint defined in swagger doc POST `/api/management/{id}/cluster`

##Additional Context

Should also output logs and status of workload cluster creation to a websocket connection as done in the management cluster.

**Comment by stmcginnis** [comment]
Didn't get closed by linked PR, closing now...
