### ISSUE TITLE
Automate packaging and verification of Carvel packages as part of the PR actions

### ISSUE THREAD

**Issue by beltran-rubo** [vmware-tanzu/community-edition#4318]
VMware Image Builder is a collection of services that allow the user to create customized and secure content for any platform and cloud. All these services are API-first and although designed to interact with each other, each of them can be used independently providing tools to the user for completely controlling its content lifecycle from their own software supply chains but at the same time adhering to industry standards and best practices.

[Bitnami community](https://github.com/bitnami/charts/actions/runs/2246663689) is actively using as part of the PR workflow (for Helm charts), improving the contributor's experience and getting feedback quickly about the changes. It is easy to add functional tests for web applications based on Cypress, reliability tests (scaling up & down) the number of pods, verification actions to execute into the pods and more.

## Feature Request

Enable [VMware Image Builder](https://github.com/marketplace/actions/vmware-image-builder) GitHub action to verify Carvel packages PR automatically. For this specific case the `packaging` phase create the OCI bundle and deploy it into a TKG platform (TCE can be also added in the future) setting the options to be deployed for different scenarios.

Using this workflow, we created several Carvel native packages available in GitLab internally (Apache, MariaDB, MySQL, MinIO, Tomcat, …) and we would like to contribute more automatically verified to the 'add-ons' catalog.

**Comment by jorgemoralespou** [comment]
@seemiller this is also interesting to you, since it adds to the validation of contributions to packages.

**Comment by beltran-rubo** [comment]
Update: The VMware Image Builder already supports TCE v0.12.0. That would be pretty useful to verify automatically any Carvel packages in this repo in TCE or any other platforms if required.

**Comment by dvonthenen** [comment]
I'm not sure the image builder is actually required in order to pull off testing. Please unmanaged cluster implementation for TCE.

**Comment by beltran-rubo** [comment]
It is provisioned from scratch through TMC for each verification, it is not a persistent cluster to maintain. Is that what you mean?
