### ISSUE TITLE
Package Repository Automation

### ISSUE THREAD

**Issue by seemiller** [vmware-tanzu/community-edition#4321]
## Summary

Package workflows for Tanzu Community Edition (TCE) are currently a manual process. As more and more packages are added to the TCE source repository and package repository, it becomes more and more difficult to maintain a clean and consistent set of OCI Registry based images, bundles, and projects. This proposal outlines the existing package repository workflows and possible means of automation.

## Package Repository Workflow

The package repository for TCE is currently generated by a manual process. This process is ad-hoc and inconsistent with respect to its tagging convention. This proposal outlines steps to automate this process and eliminate the inconsistencies and toil.

### Manual Workflow

Today, package repositories for TCE are built by the TCE Engineering team. The file `addons/repos/main.yaml` is modified to include a package addition or removal. The Make task `generate-package-repo` is then run by an engineer to create the new repository.

Here is an example workflow.

1. Create or modify a "repo" Yaml file in the `addons/repos/` directory
    ```shell
    cat > addons/repos/test-repo.yaml <<EOF
    ---
    packages:
    - name: foo
      versions:
      - 1.0.0
      - 1.1.0
      - 1.1.1
    - name: bar
      versions:
      - 3.2.1
    EOF
    ```

2. Run the make task to generate a new package repository bundle.

    ```shell
    make generate-package-repo CHANNEL=test-repo TAG=v1.2.3
    ```

This is a relatively straightforward workflow. It involves updating a single file, and running a single make task. This workflow is run manually by a TCE Engineer in response to a few triggers:

- The addition of a new package
- The addition of a new version for an existing package
- The removal of an existing package
- The removal of a version for an existing package
- An update to an existing package

The addition and removal of packages to the repo are performed by updates to the repository file itself. This is either performed manually, or via merging in a pull request that contains an update to the file. Updates to an existing package that is already in the repository do not require a change to the repository file. For these updates, a TCE Engineer "just knows" to run the workflow to create a new package repository bundle.

When pushing a package or package repository, it should be tagged appropriately and consistently. At current, this is a manual process and the tag is up to the person who is issuing the command. This has led to inconsistencies in the format and content of the tag. These inconsistencies are confusing to the public and end users. 

### Automated Workflow

This workflow is ripe for automation. By automatically generating a package repository with the proper triggers, we can eliminate developer toil and create a consistent experience for our contributors and maintainers.

#### Triggers

There are a number of triggers that cause the need for the package repository to be updated:

1. Modify the `addons/repos/main.yaml` file
   - Add package
   - Remove package

2. Modification of any user-managed package's `package.yaml` file

    The `package.yaml` for a package can change for 2 reasons
    - Change to the metadata for the package contained with the file 
    - Any significant change to a package will require a new bundle to be created and pushed to an OCI Registry. This will result in a new bundle SHA/Digest which will have to be updated in the `package.yaml` file.

5. Modification of any user-managed package's `metadata.yaml` file. If the metadata for a package is updated, that also requires the creation and publication of a new package repository

#### Automation

A GitHub Workflow/Action can be crafted that can create and push a new package repository in response to these triggers. The workflow would work as follows.

1. Pull Request is merged into the `main` branch.
2. Workflow starts, check for updates to relevant files
   - `addons/packages/**/*/package.yaml`
   - `addons/packages/**/*/metadata.yaml`
   - `addons/repos/main.yaml`
4. Use the commit SHA for the merge into the `main` branch as the tag of the new package repository
5. Run the make task `make generate-package-repository CHANNEL=main TAG=${COMMIT_SHA}` to push to the OCI Registry.
    > This will use the credentials for a robot account stored in the GitHub secrets.
6. Update the PR with the URL to the newly created package repository.

It is proposed to use the first 8 characters of the commit SHA as the tag for the package repository. This will provide a consistent tag format and provide traceability back to the change that caused this package repository to be created. If a package repository needs to be tagged with another version or identifier, that can be performed manually or as part of another release workflow.

**Comment by joshrosso** [comment]
Thoughts to address in this proposal:

* Along with the SHA, I'd like to see a tag be put on. This tag should be the current working release with build meta, so `v0.13.0-3`, where `3` is the current iteration of the build.

    ![image](https://user-images.githubusercontent.com/6200057/168159903-c822d5f6-6833-4da3-b972-efcd7a7767f5.png)


* It'd be nice if the action could run and tell the developer in the PR that a repo was generated for them and give them the link
* I'd like to see mention of pushing to the staging repository, rather than prod.
* I'd like to understand how we're going to deal with promotion in this new model. Now that we'll be pushing consistently to staging, we should think through what it means to "promote" an asset to prod for a release. Additionally how we had this off the releng.

**Comment by jpmcb** [comment]
Will there be a process (at some latter point probably) where we reap older repos?

**Comment by joshrosso** [comment]
> Will there be a process (at some latter point probably) where we reap older repos?

Talked about this in design review. Interesting question, going to let it fly for a bit to see if the frequency of pushes becomes at all problematic.

**Comment by joshrosso** [comment]
Approved; Let's do it!
