### ISSUE TITLE
Docker Desktop "feedback" button should go to issue type choice page

### ISSUE THREAD

**Issue by stmcginnis** [vmware-tanzu/community-edition#4381]
## Bug Report

We have a few issue templates to guide the user and help categorize new issues. By default when opening an issue in GitHub, the user is brought to https://github.com/vmware-tanzu/community-edition/issues/new/choose where they can choose which issue type to open.

The "Feedback" button inside the Docker Desktop extension UI goes directly to https://github.com/vmware-tanzu/community-edition/issues/new so the user is given a blank issue page to fill out without any template to help guide them. We should have this link go to the same "choose" link that they would get if they were opening an issue through GitHub.

**Comment by jorgemoralespou** [comment]
Is there a way to create a specific issue or to automagically create a template so that issues get triaged as coming from Docker Desktop?
