### ISSUE TITLE
Use shortcode variables on a per release branch basis

### ISSUE THREAD

**Issue by kcoriordan** [vmware-tanzu/community-edition#4399]
## Description

Currently the shortcodes (`docs/site/layouts/shortcodes`) called out in the config file (`docs/site/config.yaml`) are global, so changing them changes for all branches.
So the following PRs have to change them back to hardcoded values:  https://github.com/vmware-tanzu/community-edition/pull/4397, https://github.com/vmware-tanzu/community-edition/pull/3769

 Investigate a way to use shortcode variables on a per release branch basis.

```
  55  release_latest: v0.11.0
  56  release_latest_no_v: 0.11.0
  57  pkg_repo_latest: 0.11.0
```

**Comment by joshrosso** [comment]
@kcoriordan makes sense.

We'll put this in the icebox. Feel free to self-assign and move into a milestone if you want to tackle it for a specific release.

Thanks!
