### ISSUE TITLE
Add tanzu CLI install info to Docker Desktop UI

### ISSUE THREAD

**Issue by stmcginnis** [vmware-tanzu/community-edition#4475]
## Feature Request

Somewhere in the Docker Desktop extension UI we should point out that the user should install the tanzu CLI to be able to fully utilize the TCE cluster provided by the extension.

![image](https://user-images.githubusercontent.com/3922475/167671747-a8e5589d-5282-4d76-9ee3-d4a369a4f1a8.png)

## Describe alternatives you've considered

We have a link to the main docs landing page and have details in there under quick start, but that is assuming the user will spend some time reading through docs to find that before creating a cluster.

**Comment by jorgemoralespou** [comment]
Or the kctrl CLI, which for users that don't need the whole Tanzu, can be just enough, and it's an easier/slimmer download.
