### ISSUE TITLE
Unable to view v0.12 docs from previous doc versions

### ISSUE THREAD

**Issue by garrying** [vmware-tanzu/community-edition#4481]
## Description

When a user changes docs version from the dropdown to v0.11 or v0.10, the latest version (v0.12) is not an option in the dropdown.

A user can return to the latest release (v0.12) by clicking on `Documentation` from the top navigation bar.

## Location

https://tanzucommunityedition.io/docs/v0.11/
https://tanzucommunityedition.io/docs/v0.10/

**Comment by jpmcb** [comment]
I think I've found the issue - PR incoming!
