### ISSUE TITLE
UI Plugin: Pre-MVP general community feedback

### ISSUE THREAD

**Issue by miclettej** [vmware-tanzu/community-edition#4501]
## Feature Request

This is a placeholder github issue to track any feedback from the TCE community pre-mvp. Please feel free to edit this description with feedback, or add comments to the issue.

**Comment by thefluffysysop** [comment]
The mockups looked very good.  I hope it can play a part in troubleshooting when things go wrong.  Some basic health check UI elements might be something to add early on, if only to validate the readiness of the management cluster. 
More advanced later on would to have dialogs that show up when specific errors occur, if these can be retrieved/parsed. Would much help troubleshooting, especially those of us who are not so hot on manually digging into k8s and cluster-api.
