### ISSUE TITLE
Docker Desktop Extension - Log File on 'LOGS' tab not displaying consistently

### ISSUE THREAD

**Issue by thefluffysysop** [vmware-tanzu/community-edition#4505]
## Bug Report
On suggestion of @stmcginnis raising this issue. (https://kubernetes.slack.com/archives/C02GY94A8KT/p1652296299768999)
When initiating a TCE standalone cluster in the Docker Desktop Extension, by clicking the create button, the log file does not automatically appear in the LOGS tab. 
Only by switching between the 'Kubeconfig' tab, or any other screen in the Docker Desktop app, and back to the LOGS tab, does the log then show, with a slight delay (in my case). 

## Expected Behavior
I expected the log to appear immediately while the cluster was being created. 

## Steps to Reproduce the Bug
Once having installed the TCE extension in Docker Desktop, click 'Create' button, and do not click on anything else. Expectation was that log would start to dynamically appear in the LOGS tab. The LOGS appears to be highlighted by default. 

## Screenshots or additional information and context
![image](https://user-images.githubusercontent.com/29251599/167936908-529d8c40-fa8a-41ac-89dd-dd3b99ce523c.png)
In the screenshot above, the status indicator show the cluster is running. However, no logs show. 

## Environment Details

* Build version (`tanzu version`):  0.12
* Deployment (Managed/Unmanaged cluster): Standalone Cluster / Docker Desktop 4.8.1
* Infrastructure Provider (Docker/AWS/Azure/vSphere):  Docker
* Operating System (client): Windows 11, 21H1 19043

## Diagnostics and log bundle
N/A

**Comment by alexbarbato** [comment]
I'm seeing this issue but from a different perspective - I go to create a cluster and it looks like it'll start creating, but ultimately fails out and says no cluster created.

<img width="1069" alt="image" src="https://user-images.githubusercontent.com/23562192/167980840-c2a033ae-c683-4c06-a497-ee8c5a8f6595.png">

If the logs rendered, I'm guessing I'd be able to troubleshoot what's going wrong in my env

Mac 12.3.1, Docker desktop 4.8.1

**Comment by jorgemoralespou** [comment]
@alexbarbato your issue is "somehow" known, although will be fixed soon, and probably is related to the fact that a pre-flight check for ports 80 and 443 detected those can't be used on your machine, but a following status check got rid of the message (https://github.com/vmware-tanzu/community-edition/issues/4529).

@thefluffysysop thanks for raising this issue. We've noticed this as well, and we'll see how we can fix it in the next release.
