### ISSUE TITLE
nit: markdown linter image has no `arm64` build

### ISSUE THREAD

**Issue by jpmcb** [vmware-tanzu/community-edition#4507]
## Bug Report

When running the `make mdlint` target from an `arm64` machine, I see the following:

```
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
```

I am able to reproduce this by running the `cluster-api-provider-vsphere/extra/mdlint` image by itself

```
❯ docker run gcr.io/cluster-api-provider-vsphere/extra/mdlint:0.23.2
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested

  Usage: lint [options] <files|directories|globs>

  MarkdownLint Command Line Interface

  Options:

    -h, --help                                  output usage information
    -V, --version                               output the version number
    -f, --fix                                   fix basic errors (does not work with STDIN)
    -s, --stdin                                 read from STDIN (does not work with files)
    -o, --output [outputFile]                   write issues to file (no console)
    -c, --config [configFile]                   configuration file (JSON, JSONC, JS, or YAML)
    -i, --ignore [file|directory|glob]          file(s) to ignore/exclude
    -p, --ignore-path [file]                    path to file with ignore pattern(s)
    -r, --rules  [file|directory|glob|package]  custom rule files
```

**_Although, weirdly enough,_** as we can see from the output above, the utility still runs and reports markdown lint errors.

This issue is to surface this error/warning message and also maybe touch base and see if we want to use a different markdown linter image? Is the `cluster-api-provider-vsphere/extra/mdlint` one being maintained? It hasn't had a new tag in quite some time.

## Expected Behavior

Able to run `make mdlint` on arm64 without warning or error

## Steps to Reproduce the Bug

Run `make mdlint` from a arm64 (M1 macbook) machine

**Comment by stmcginnis** [comment]
The mdlint-ci tool that is run inside the container is Node.js code, so I don't think the tool itself is restricted to a given platform. I think it's more due to the fact that the `cluster-api-provider-vsphere` project we borrow that container image from is only publishing amd64 images. We may want to check with that team if they would be interested in building multiple platform images.

Another option would be to just create our own container. We basically just need to use a base nodejs image and add in the mdlint source.
