### ISSUE TITLE
Windows Docker Installation Fails

### ISSUE THREAD

**Issue by vincentvc168** [vmware-tanzu/community-edition#4533]
## Bug Report
I search the Github but the response cannot solve my problem.

## Expected Behavior

Unable to connect to the server: dial tcp 172.18.0.3:6443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

## Screenshots or additional information and context

<img width="660" alt="image" src="https://user-images.githubusercontent.com/61619999/168457047-bb8aad6c-c3b8-427c-891f-3e076c0a1639.png">

## Environment Details

* Build version (`tanzu version`): v0.11.4
* Deployment (Managed/Unmanaged cluster):  Managed
* Infrastructure Provider (Docker/AWS/Azure/vSphere): Docker
* Operating System (client): Windows 11

**Comment by stmcginnis** [comment]
Going to close this one in favor of tracking in https://github.com/vmware-tanzu/community-edition/issues/4535
