### ISSUE TITLE
The latest version of TCE fails in installation of Windows, Mac and Ubuntu with Docker.

### ISSUE THREAD

**Issue by vincentvc168** [vmware-tanzu/community-edition#4535]
## Bug Report

I tried to install the latest version of TCE in Windows, Mac and Ubuntu by following the official documentation. All fails!

## Steps to Reproduce the Bug

Just follow the official documentation with Docker as deployment target.

## Environment Details

* Build version (`tanzu version`): v0.11.2
* Deployment (Managed/Unmanaged cluster): Managed
* Infrastructure Provider (Docker/AWS/Azure/vSphere): Docker
* Operating System (client): Windows, Mac and Ubuntu

**Comment by vincentvc168** [comment]
I need to downgrade to v0.9.2 and using the manual command "tanzu management-cluster create -i docker --name mtce -v 10 --plan dev --ceip-participation=false" to setup management cluster.

**Comment by vincentvc168** [comment]
Detail (All cases are using Docker):
Linux - failed after "Starting control-plane", error is "Exit 1"
Mac - failed in "waiting for cert-manager to be available"
Windows - failed
I know TCE for Docker is experiment only but one of TCE purpose is facilitating Developer by leveraging local workstation. Hope it will be fixed soon. Thank you!
I spent my weekend in getting above result! :)

**Comment by stmcginnis** [comment]
This is known to work successfully on all platforms, so there must be something in your environment causing problems. Maybe a proxy or firewall interfering with network connectivity?

I would recommend going through the bootstrap troubleshooting steps to see what errors the looks contain: https://tanzucommunityedition.io/docs/v0.12/ts-manually/

You may also want to just use unmanaged clusters for local workstation development as there are a lot less resource requirements.

**Comment by vincentvc168** [comment]
> This is known to work successfully on all platforms, so there must be something in your environment causing problems. Maybe a proxy or firewall interfering with network connectivity?
> 
> I would recommend going through the bootstrap troubleshooting steps to see what errors the looks contain: https://tanzucommunityedition.io/docs/v0.12/ts-manually/
> 
> You may also want to just use unmanaged clusters for local workstation development as there are a lot less resource requirements.

I am using home broadband which is simple and does not have any firewall or proxy. I can install unmanaged cluster successfully, very smooth. Only management-cluster fails in Windows, Mac and Linux(Ubuntu). In my case, I am using Docker which is experiment for TCE (TCE supports Docker in experimental way).
Hope TCE can support Docker and provide a smooth installation experience, like UiPath Community Edition (In the past), it can attract a lot of developers and promote this product.
Looking forward to see a new TCE soon!
Thank you!

**Comment by stmcginnis** [comment]
Hey @vincentvc168 - we have some newer releases since this was opened. Could you try with the v0.12.1 release?

**Comment by dvonthenen** [comment]
Also, are you running these different platforms under virtualization like Fusion or Workstation?
