### ISSUE TITLE
Revise Installation Survey in Getting Started Docs

### ISSUE THREAD

**Issue by garrying** [vmware-tanzu/community-edition#4548]
## Description

This issue is to capture intent on revising the current TypeForm installation survey given that the response rate has been minimal. Some possible next steps include "closing" the survey, updating the questions being asked to reflect current initiatives, or changing its placement for better visibility. Looking for additional thoughts! cc @vkorbes @joshrosso

## Location
- https://tanzucommunityedition.io/docs/v0.12/getting-started/
- Linked instance in a blog post: https://tanzucommunityedition.io/posts/tanzu-community-edition-0.10-available/
- TypeForm survey: https://tb3xduryx4x.typeform.com/to/RVmhMHwR

## Additional Context
- In-progress Guided UI project: https://github.com/vmware-tanzu/community-edition/issues/3235

**Comment by stmcginnis** [comment]
@vkorbes or @microwavables - is this needed? Can one of you take this on and decide what to do with it?
