### ISSUE TITLE
Configuration options for the cert-manager package

### ISSUE THREAD

**Issue by seemiller** [vmware-tanzu/community-edition#4553]
## Feature Request

The cert-manager package only allows configuration of the namespace at the moment. The [Helm Chart for cert-manager](https://artifacthub.io/packages/helm/cert-manager/cert-manager#configuration) exposes numerous configuration options. To maintain feature parity with the Helm Chart, many of these options should be made available through the package install.

A `schema.yaml` should also be added to follow Carvel packaging best practices.

**Comment by jorgemoralespou** [comment]
From looking at the chart options there's a lot of configuration that is something really rare humans will change (e.g. `erviceAccount.automountServiceAccountToken`). For these, I would recommend the documentation of "overlays" so anything in the package can be customized.

There's though, a few configuration options that are more prone to be changed by users (e.g. `clusterResourceNamespace`) and I would agree adding them to the schema and package.

One of the tradeoffs of Helm is that they expose so much configurability that make maintaining the packages a PITA. Luckily, Carvel and the packaging API provide an easy way to provide additional overlays to packages, so we should favour that mechanism for the less common configuration, IMHO.

There's though, a problem still to be solved by Carvel, which is how to properly provide overlays to subpackages in a meta-package.

**Comment by jorgemoralespou** [comment]
Also, this issue could exist for every single package, as helm charts do expose more configurability than their corresponding TCE package.

**Comment by jorgemoralespou** [comment]
@seemiller no doubt you can learn a ton with the process/experience. But I think TCE (team) should define what they want for packages, a helm replicate of "configure every single line" or a "simple and useful configuration OOTB and everything else via overlays" model. I think this is a big decission.
