### ISSUE TITLE
External-dns YTT template support for DNS provider secret

### ISSUE THREAD

**Issue by coreydinkens** [vmware-tanzu/community-edition#4572]
## Feature Request

I am requesting the addition/updating of external-dns package YTT templating to be able to ingest and create the needed DNS account credentials secret as referenced in [this step](https://github.com/vmware-tanzu/community-edition/tree/main/addons/packages/external-dns/0.11.0#4-create-a-kubernetes-secret). [Here is a reference](https://github.com/vmware-tanzu/community-edition/blob/main/addons/packages/harbor/2.4.2/bundle/config/overlay/add-certificates.yaml) to how the Harbor package achieves this functionality with custom TLS certificates.

The end result is that a user will be able to provide the necessary DNS account credentials as part of the data-values.yaml, and the secret will automatically be created and referenced in the resolved deployment manifest. This will negate the need for the manual step of creating the secret prior to deploying the external-dns package.

I would like to keep the scope of this request to the AWS Route 53 and Azure DNS providers, as those will be commonly used.

## Describe alternatives you've considered

There are none that I am aware of

## Additional context

Adding support for the needed secret for external-dns will provide good quality-of-life improvements for the package install experience, and would make documentation more concise.

**Comment by christianang** [comment]
Thanks for the feature request @coreydinkens. Seems like a reasonable ask and I agree that it would be nice to remove any manual steps required to deploy the package. However, the package has been pretty general in its data value configuration so far (i.e nothing is particularly geared towards a specific provider). This is not to suggest we shouldn't add anything specific to a provider in the data values, but understanding if this can be general purpose may be something the team may want to explore when we go about implementing this feature.

cc @vmware-tanzu/pkg-external-dns-owners, so we can prioritize exploring how we may want to introduce this feature.

**Comment by coreydinkens** [comment]
@christianang My suggestion is rooted in the desire to have the Carvel data-values.yaml behave in a similar fashion to a Helm values.yaml.  

Helm [achieves this](https://github.com/bitnami/charts/tree/master/bitnami/external-dns/#installing-the-chart) by using the following KV prefix for each provider and the needed values:
aws.credentials.accessKey
aws.credentials.secretKey

I see no reason that we cannot offer similar support for the provider config options in our Carvel packages.

**Comment by coreydinkens** [comment]
@jorgemoralespou so you are saying this is already possible and we just need to provide the correct values as defined in the template? That would be great if so...

**Comment by jorgemoralespou** [comment]
@coreydinkens no. I'm saying I have a package that does provide this functionality, so that the @vmware-tanzu/pkg-external-dns-owners can take a look into what you're asking and a bare implementation, so they can properly productize it and support it.
