### ISSUE TITLE
How to remove failure domains from cluster

### ISSUE THREAD

**Issue by vipamadi** [vmware-tanzu/community-edition#4603]
Hi!

We have some problems after deleting some control planes nodes at our TKG cluster.
Previously we tested failure domains so we created kind objects VSphereDeploymentZone and VSphereFailureDomain but we deleted them after some tests.
But now, every time we remove a control plane node the new control plane node is created with the old spec.failureDomain value at the machines.cluster.x-k8s.io object.

Please, how could we remove all the references to this removed failure domain.

This is our cluster status:

# kubectl get cluster -n guadix-workload-cluster -o yaml
apiVersion: v1
items:
- apiVersion: cluster.x-k8s.io/v1beta1
  kind: Cluster
  ...
  status:
	...
    controlPlaneReady: true
    failureDomains:
      failure-domain-a:
        controlPlane: true
      failure-domain-b:
        controlPlane: true
    ...

**Comment by stmcginnis** [comment]
> We have some problems after deleting some control planes nodes at our TKG cluster

Hi @vipamadi  - is this with the TKG product and not TCE? If so, please contact support for help with it.
