### ISSUE TITLE
add Contour v1.21.1 package

### ISSUE THREAD

**Issue by skriss** [vmware-tanzu/community-edition#4605]
## Feature Request

Contour v1.21.1 has been released, we need to add packaging for it.

https://github.com/projectcontour/contour/releases/tag/v1.21.1

cc @vmware-tanzu/pkg-contour-owners

**Comment by sunjayBhatia** [comment]
I can take this one!

**Comment by seemiller** [comment]
Hey Contour! For this version of the package, how would y'all feel about implementing a [schema.yaml](https://carvel.dev/ytt/docs/v0.40.0/how-to-write-schema/) file?

The schema has a number of benefits:
- Provides documentation for parameters
- ytt can be used to generate an OpenAPI schema from it (useful for inclusion in package.yaml)
- replaces the values.yaml in the package, as you can specify default values within the schema

I'm happy to help out creating it if you'd like!

**Comment by skriss** [comment]
@seemiller I think that's a good idea; the one thing we need to make sure is that it works well with downstream consumers of this package. i started playing with this awhile ago and I seem to remember running into some issues around using the package with a schema.yaml as a library in downstream usage, but I can't recall specifics.

**Comment by sunjayBhatia** [comment]
@seemiller @skriss had a crack at adding a schema.yaml for contour 1.21.0 (version not yet merged to TCE)

haven't tried to use in downstream yet, but so far so good it seems, added some testing and all units pass

**Comment by sunjayBhatia** [comment]
update description to v1.21.1 that we just released
