### ISSUE TITLE
Unable to find how to change the SSL thumbprint of vCenter

### ISSUE THREAD

**Issue by MasterWayZ** [vmware-tanzu/community-edition#4628]
## Description

Unable to find how to change the SSL thumbprint of vCenter

## Location

N/A

## Additional Context

As per above, I can't find how I can set up the new SSL thumbprint of vCenter. Its cert got renewed, but everything fails now as the SSL thumbprint changed.

**Comment by dvonthenen** [comment]
Hello @MasterWayZ 

are you trying to change the SSL Thumbprint on an already deployed Kubernetes cluster?
