### ISSUE TITLE
Envoy IP not ping-able anymore after some time

### ISSUE THREAD

**Issue by romrom38** [vmware-tanzu/community-edition#4644]
Hello,

I'm using tanzu community 0.12 on vSphere without NSX, with kubevip (0.3.9) and contour (1.20.1) to publish ingress to my nodes.

I'm using the envoy LoadBalancer IP to get external access to my nodes requiering both internal and external access.
- External access is achieved with NAT-ing to envoy IP
- Internal access is obtained with a DNS wildcard record for my base subdomain used by my pods to this envoy IP

kubectl get services -A | grep LoadBalancer
projectcontour   envoy                           LoadBalancer   100.68.129.120   A.B.C.D

I use A.B.C.D IPv4 address to access my pods.

After installing contour package it work fine, and A.B.C.D address is pingable.

> ------ contour-config.yaml ------
> certificates:
>   useCertManager: true
> envoy:
>   service:
>     type: LoadBalancer
> ------------------------------------

And it works for about a week...
Then I can't ping anymore envoy IP : A.B.C.D

If I re-install contour :

> tanzu package install contour --package-name contour.community.tanzu.vmware.com --version 1.20.1 --values-file .\contour-config.yaml

I get a new IP, and services get back to normal (after I actualize my DNS).
But it works for a limited number of days ;(

I'm not sure what could be helpfull for debuging...

Kube VIP is installed with customizations : https://github.com/vrabbi/tkgm-customizations.git

> kubectl apply -n tanzu-package-repo-global -f tkgm-customizations/carvel-packages/kube-vip-package/metadata.yml
> kubectl apply -n tanzu-package-repo-global -f tkgm-customizations/carvel-packages/kube-vip-package/package.yaml
> tanzu package install kubevip -p kubevip.terasky.com -v 0.3.9 -f kube-vip-config.yaml

I am the only one to get envoy networking issues ?

**Comment by romrom38** [comment]
Hello @stmcginnis, thanks for your help.

I'm using vsphere without NSX using a managed cluster.  

I'm trying to get more accustomed to debugging in order to provide usefull data for debbuging/understanding what's happening there.

Here are the pods that might log clues regarding this problem :
kubectl get pods -A | grep contour
projectcontour   contour-67b4694845-dv44q                                       1/1     Running   0               3d23h
projectcontour   contour-67b4694845-zbh4f                                       1/1     Running   0               3d23h
projectcontour   envoy-l5xhb                                                    2/2     Running   0               3d23h
projectcontour   envoy-pljcb                                                    2/2     Running   0               3d23h
projectcontour   envoy-qgk4x                                                    2/2     Running   0               3d23h

kubectl get services -A | grep LoadBalancer
projectcontour   envoy                           LoadBalancer   100.67.77.135    10.20.94.22   80:31965/TCP,443:32536/TCP   3d23h

Currently if I search for log :
kubectl logs -n projectcontour contour-67b4694845-dv44q
time="2022-05-30T19:14:33Z" level=info msg="received a new address for status.loadBalancer" context=loadBalancerStatusWriter loadbalancer-address=10.20.94.22
...
time="2022-06-01T14:28:05Z" level=info msg="received a new address for status.loadBalancer" 
...
time="2022-06-02T22:53:13Z" level=info msg="received a new address for status.loadBalancer" context=loadBalancerStatusWriter loadbalancer-address=10.20.94.22

So upon package re-installation : address discovery and service seems to be working fine (it's pingable and "routing" trafic to pods as I expect)

I don't know how to get deleted pods logs to know more about what went wrong before...
But since it's been running for more than 3 days since last crash... it should occur soon and I will hope I'll get usefull logs this time :)

**Comment by vrabbi** [comment]
I havrnt seen this issue before but the logs the really matter here ir that could indicate the ussue are not contour but rather kubevip pods. More specifically the kubevip daemonset. This is what publishes the ip so thats where you should look for logs. Contour simply rides on the ip privided via kubevip. If you cant ping the lb ip then its a l4 issue and not l7

**Comment by romrom38** [comment]
From what I understand...

# before crash => kube-vip is broadcasting correctly the IP : 10.20.94.22
kubectl logs -n kube-system kube-vip-ds-wlc7w
time="2022-06-03T18:07:59Z" level=info msg="Broadcasting ARP update for 10.20.94.22 (00:50:56:9d:56:c1) via eth0"
time="2022-06-03T18:08:02Z" level=info msg="Broadcasting ARP update for 10.20.94.22 (00:50:56:9d:56:c1) via eth0"
time="2022-06-03T18:08:05Z" level=info msg="Broadcasting ARP update for 10.20.94.22 (00:50:56:9d:56:c1) via eth0"
time="2022-06-03T18:08:08Z" level=info msg="Broadcasting ARP update for 10.20.94.22 (00:50:56:9d:56:c1) via eth0"
time="2022-06-03T18:08:11Z" level=info msg="Broadcasting ARP update for 10.20.94.22 (00:50:56:9d:56:c1) via eth0"
time="2022-06-03T18:08:14Z" level=info msg="Broadcasting ARP update for 10.20.94.22 (00:50:56:9d:56:c1) via eth0"

# since crash => kube-vip does not broadcast anymore the IP : 10.20.94.22
kubectl logs -n kube-system kube-vip-ds-wlc7w
time="2022-06-07T19:13:12Z" level=info msg="server started"
time="2022-06-07T19:13:12Z" level=info msg="Starting Kube-vip Manager with the ARP engine"
time="2022-06-07T19:13:12Z" level=info msg="Namespace [kube-system], Hybrid mode [false]"
time="2022-06-07T19:13:12Z" level=info msg="Beginning cluster membership, namespace [kube-system], lock name [plndr-svcs-lock], id [digital-kub-work-md-2-58b9998c64-mmrd7]"
I0607 19:13:12.605408       1 leaderelection.go:243] attempting to acquire leader lease kube-system/plndr-svcs-lock...
I0607 19:13:12.620572       1 leaderelection.go:253] successfully acquired lease kube-system/plndr-svcs-lock
time="2022-06-07T19:13:12Z" level=info msg="Beginning watching services for type: LoadBalancer in all namespaces"
time="2022-06-07T19:13:12Z" level=info msg="Service [cert-manager] has been addded/modified, it has no assigned external addresses"
time="2022-06-07T19:13:12Z" level=info msg="Service [harbor-trivy] has been addded/modified, it has no assigned external addresses"
time="2022-06-07T19:13:12Z" level=info msg="Service [prometheus-pushgateway] has been addded/modified, it has no assigned external addresses"
time="2022-06-07T19:13:12Z" level=info msg="Service [harbor-notary-server] has been addded/modified, it has no assigned external addresses"
time="2022-06-07T19:13:12Z" level=info msg="Service [contour] has been addded/modified, it has no assigned external addresses"
time="2022-06-07T19:13:12Z" level=info msg="Service [harbor-jobservice] has been addded/modified, it has no assigned external addresses"
time="2022-06-07T19:13:12Z" level=info msg="Service [harbor-notary-signer] has been addded/modified, it has no assigned external addresses"
time="2022-06-07T19:13:12Z" level=info msg="Service [harbor-redis] has been addded/modified, it has no assigned external addresses"
time="2022-06-07T19:13:12Z" level=info msg="Service [harbor-core] has been addded/modified, it has no assigned external addresses"
time="2022-06-07T19:13:12Z" level=info msg="Service [kube-dns] has been addded/modified, it has no assigned external addresses"
time="2022-06-07T19:13:12Z" level=info msg="Service [metrics-server] has been addded/modified, it has no assigned external addresses"
time="2022-06-07T19:13:12Z" level=info msg="Service [prometheus-kube-state-metrics] has been addded/modified, it has no assigned external addresses"
time="2022-06-07T19:13:12Z" level=info msg="Service [cert-manager-webhook] has been addded/modified, it has no assigned external addresses"
time="2022-06-07T19:13:12Z" level=info msg="Service [harbor-database] has been addded/modified, it has no assigned external addresses"
time="2022-06-07T19:13:12Z" level=info msg="Service [antrea] has been addded/modified, it has no assigned external addresses"
time="2022-06-07T19:13:12Z" level=info msg="Service [harbor-portal] has been addded/modified, it has no assigned external addresses"
time="2022-06-07T19:13:12Z" level=info msg="Service [vsphere-csi-controller] has been addded/modified, it has no assigned external addresses"
time="2022-06-07T19:13:12Z" level=info msg="Service [prometheus-server] has been addded/modified, it has no assigned external addresses"
time="2022-06-07T19:13:12Z" level=info msg="Service [packaging-api] has been addded/modified, it has no assigned external addresses"
time="2022-06-07T19:13:12Z" level=info msg="Service [kubernetes] has been addded/modified, it has no assigned external addresses"
time="2022-06-07T19:13:12Z" level=info msg="Service [grafana] has been addded/modified, it has no assigned external addresses"
time="2022-06-07T19:13:12Z" level=info msg="Service [harbor-registry] has been addded/modified, it has no assigned external addresses"
time="2022-06-07T19:13:12Z" level=info msg="Service [envoy] has been addded/modified, it has no assigned external addresses"
time="2022-06-07T19:13:12Z" level=info msg="Service [alertmanager] has been addded/modified, it has no assigned external addresses"
time="2022-06-07T19:13:12Z" level=info msg="Service [prometheus-node-exporter] has been addded/modified, it has no assigned external addresses

And I keep getting "Service X has been added/modified, it has no assigned external addresses" messages...
But no broadcast message anymore in this log

Other daemon sets instances logs say nothing more : 
kubectl logs -n kube-system kube-vip-ds-g5zjs
time="2022-05-30T08:22:26Z" level=info msg="server started"
time="2022-05-30T08:22:26Z" level=info msg="Starting Kube-vip Manager with the ARP engine"
time="2022-05-30T08:22:26Z" level=info msg="Namespace [kube-system], Hybrid mode [false]"
time="2022-05-30T08:22:26Z" level=info msg="Beginning cluster membership, namespace [kube-system], lock name [plndr-svcs-lock], id [digital-kub-work-md-1-64d4f847f8-zrsgs]"
I0530 08:22:26.168314       1 leaderelection.go:243] attempting to acquire leader lease kube-system/plndr-svcs-lock...
time="2022-05-30T08:22:26Z" level=info msg="new leader elected: digital-kub-work-md-2-58b9998c64-mmrd7"
E0530 16:39:01.508286       1 leaderelection.go:325] error retrieving resource lock kube-system/plndr-svcs-lock: etcdserver: leader changed
+ only addition :
**E0607 19:13:10.513017       1 leaderelection.go:325] error retrieving resource lock kube-system/plndr-svcs-lock: etcdserver: leader changed**

kubectl logs -n kube-system kube-vip-ds-jjvcw
time="2022-05-30T08:22:26Z" level=info msg="server started"
time="2022-05-30T08:22:26Z" level=info msg="Starting Kube-vip Manager with the ARP engine"
time="2022-05-30T08:22:26Z" level=info msg="Namespace [kube-system], Hybrid mode [false]"
time="2022-05-30T08:22:26Z" level=info msg="Beginning cluster membership, namespace [kube-system], lock name [plndr-svcs-lock], id [digital-kub-work-md-0-69fcdc4f94-8wl7v]"
I0530 08:22:26.429676       1 leaderelection.go:243] attempting to acquire leader lease kube-system/plndr-svcs-lock...
time="2022-05-30T08:22:26Z" level=info msg="new leader elected: digital-kub-work-md-2-58b9998c64-mmrd7"

I don't understand the message : 
time="2022-06-07T19:13:12Z" level=info msg="server started"

Could it be related to vcenter DRS migrating control plane VMs from one node to other one ? (I didn't notice anything wrong on the cluster except this specific issue)
![image](https://user-images.githubusercontent.com/16734565/172854439-15c8e0ad-1702-4494-8f31-a4e85a13ea77.png)
