### ISSUE TITLE
Supported Kubernetes Versions should be updated

### ISSUE THREAD

**Issue by hidekazuna** [vmware-tanzu/community-edition#4647]
## Description

Supported Kubernetes Versions in documentation are 1.21.2, 1.20.8, 1.19.12, but actually 1.22.8,1.21.11,1.20.15.

## Location

- https://tanzucommunityedition.io/docs/v0.12/support-matrix/#supported-kubernetes-versions
- https://tanzucommunityedition.io/docs/edge/support-matrix/#supported-kubernetes-versions

**Comment by stmcginnis** [comment]
Thanks @hidekazuna - we're going to track this in #4088
