### ISSUE TITLE
UI Plugin: Add vSphere Resources step

### ISSUE THREAD

**Issue by miclettej** [vmware-tanzu/community-edition#4661]
## Feature Request

Add resources step for vSphere management cluster create wizard. Includes the following inputs:

- VM folder
- Datastore
- Network Name
- Resource pool/hosts selection tree

## Additional context

See mockup screen shot:
<img width="1003" alt="Screen Shot 2022-05-31 at 4 34 38 PM" src="https://user-images.githubusercontent.com/13439013/171300541-38525c1f-2117-40e5-be51-dcbaaa40b15d.png">

**Comment by mpanchajanya** [comment]
@miclettej @swalner-vmware  What should be the dropdown values be ?
