### ISSUE TITLE
DDE: Add unit test coverage

### ISSUE THREAD

**Issue by stmcginnis** [vmware-tanzu/community-edition#4698]
## Feature Request

This is to track adding unit tests to cover the Docker Desktop Extension code.

The expectation is not to have 100% code coverage, nor any predetermined coverage level. The code should be reviewed to determine what is testable - or can be made testable - and close out this issue when it's decided that a reasonable level has been reached.

**Comment by harshanarayana** [comment]
@stmcginnis  I was going through some of the code in the DDE Extension for the `clustermgr` and some bit of it gets really hard to mock for UT'ing. Would it be acceptable to refactor some of that to start with? I can start with a draft PR to track testing some of the testable bits and we can discuss what do we do with other bits

**Comment by stmcginnis** [comment]
Thanks, for checking it out. Yeah, I hadn't done much analysis, but my assumption was there was likely to be a lot of it that would be too difficult to make it worthwhile to test. If you wanted to see what could be covered without too much extra effort, that would be fantastic!

**Comment by harshanarayana** [comment]
@stmcginnis  I opened up a PR with some tests that needed no refactoring and `docker.go` with minor refactoring and tests for couple of the functions. PTAL when time permits
