### ISSUE TITLE
Sharing AWS VPC and NAT GW issue

### ISSUE THREAD

**Issue by AndyTauber** [vmware-tanzu/community-edition#4708]
## Bug Report

I want to share the existing AWS VPC that was created for the management cluster as is described in: https://docs.vmware.com/en/VMware-Tanzu-Kubernetes-Grid/1.5/vmware-tanzu-kubernetes-grid-15/GUID-tanzu-k8s-clusters-aws.html - the "Deploy a Cluster that Shares a VPC and NAT Gateway(s) with the Management Cluster" section.

When I follow the instructions and update the config yaml with the existing VPC and subnet info and then do a "tanzu create cluster workcluster1 -f test-config.yaml", the new workload cluster is deployed using a NEW VPC and then the creation fails due to reaching Elastic IP limits.

When I ran the create command with the --dry-run flag, I found that VPC info had not made it to the yaml but subnet info had.  So there is a rendering problem with reading the input config file and then adding VPC info to the output yaml file used to build the new workload cluster.

I edited the output of the --dry-run command with the existing AWS_VPC_ID and applied it to the management cluster and the new workload cluster built correctly and re-used the existing management VPC and subnets.

## Expected Behavior

tanzu create cluster should read the AWS_VPC_ID from the input config yaml and build the workload cluster on the shared (management) VPC.

## Steps to Reproduce the Bug

Create a new workload cluster with a config file that specifies the management cluster's AWS_VPC_ID and public and private subnets.  Do not specify an AWS_VPC_CIDR as it seems this may be a switch to determine if to build a new VPC or not.

## Environment Details

* Build version (`tanzu version`):  v0.11.4
* Deployment (Managed/Unmanaged cluster): Managed
* Infrastructure Provider (Docker/AWS/Azure/vSphere): AWS
* Operating System (client): Darwin

## Diagnostics and log bundle
This is the config file I input into the "tanzu cluster create prow-temp -f test-config.yaml" command.  AWS_VPC_ID and public and private subnet IDs came from my existing management cluster.

```
AWS_AMI_ID: ami-03714b1bf6617a560
AWS_NODE_AZ: us-east-1a
AWS_NODE_AZ_1: us-east-1b
AWS_NODE_AZ_2: us-east-1c
AWS_PRIVATE_NODE_CIDR: ""
AWS_PRIVATE_NODE_CIDR_1: ""
AWS_PRIVATE_NODE_CIDR_2: ""
AWS_PRIVATE_SUBNET_ID: subnet-0a5ee2cc286212a87
AWS_PRIVATE_SUBNET_ID_1: subnet-0444d1dc6e40269e1
AWS_PRIVATE_SUBNET_ID_2: subnet-0cd599591047cb9cf
AWS_PUBLIC_NODE_CIDR: ""
AWS_PUBLIC_NODE_CIDR_1: ""
AWS_PUBLIC_NODE_CIDR_2: ""
AWS_PUBLIC_SUBNET_ID: subnet-03a6bffe9779fc158
AWS_PUBLIC_SUBNET_ID_1: subnet-04553bfd1da51d58b
AWS_PUBLIC_SUBNET_ID_2: subnet-03d7c318c9bb19fc6
AWS_REGION: us-east-1
AWS_SSH_KEY_NAME: default-aws
AWS_VPC_CIDR: ""
AWS_VPC_ID: vpc-06b3d0152fade8b31
BASTION_HOST_ENABLED: "true"
CLUSTER_CIDR: 100.96.0.0/11
CLUSTER_NAME: prow-temp
CLUSTER_PLAN: prod
CONTROL_PLANE_MACHINE_TYPE: m5.large
ENABLE_AUDIT_LOGGING: ""
ENABLE_CEIP_PARTICIPATION: "false"
ENABLE_MHC: "true"
IDENTITY_MANAGEMENT_TYPE: none
INFRASTRUCTURE_PROVIDER: aws
LDAP_BIND_DN: ""
LDAP_BIND_PASSWORD: ""
LDAP_GROUP_SEARCH_BASE_DN: ""
LDAP_GROUP_SEARCH_FILTER: ""
LDAP_GROUP_SEARCH_GROUP_ATTRIBUTE: ""
LDAP_GROUP_SEARCH_NAME_ATTRIBUTE: cn
LDAP_GROUP_SEARCH_USER_ATTRIBUTE: DN
LDAP_HOST: ""
LDAP_ROOT_CA_DATA_B64: ""
LDAP_USER_SEARCH_BASE_DN: ""
LDAP_USER_SEARCH_FILTER: ""
LDAP_USER_SEARCH_NAME_ATTRIBUTE: ""
LDAP_USER_SEARCH_USERNAME: userPrincipalName
NODE_MACHINE_TYPE: m5.large
NODE_MACHINE_TYPE_1: m5.large
NODE_MACHINE_TYPE_2: m5.large
OIDC_IDENTITY_PROVIDER_CLIENT_ID: ""
OIDC_IDENTITY_PROVIDER_CLIENT_SECRET: ""
OIDC_IDENTITY_PROVIDER_GROUPS_CLAIM: ""
OIDC_IDENTITY_PROVIDER_ISSUER_URL: ""
OIDC_IDENTITY_PROVIDER_NAME: ""
OIDC_IDENTITY_PROVIDER_SCOPES: ""
OIDC_IDENTITY_PROVIDER_USERNAME_CLAIM: ""
OS_ARCH: amd64
OS_NAME: ubuntu
OS_VERSION: "20.04"
SERVICE_CIDR: 100.64.0.0/13
TKG_HTTP_PROXY_ENABLED: "false"
```

**Comment by stmcginnis** [comment]
Thanks for getting this issue filed and tracking down the cause Andy! Looks like this is something that will need to be fixed in the `tanzu-framework` repo. I'm going to duplicate it over there but keep this open here for now so we can track the fixes inclusion in a TCE release.

**Comment by stmcginnis** [comment]
Commented in the t-f issue, but just for visibility, this may be related to https://github.com/vmware-tanzu/tanzu-framework/pull/2528

So we either need that backported to the v0.11.x version of tanzu-framework that we use or we need to move up to a newer t-f release that includes it.
