### ISSUE TITLE
Add schema.yaml to Knative Serving package.

### ISSUE THREAD

**Issue by seemiller** [vmware-tanzu/community-edition#4723]
## Feature Request

Carvel packaging recommends the use of a schema.yaml file to document configurable parameters for packages. TCE also has a make task, `generate-openapischema-package`, that will generate the `valuesSchema` stanza for the package.yaml file.

## Describe alternatives you've considered

Continue using a values.yaml file and manually generating the schema for the package.yaml file.

**Comment by jorgemoralespou** [comment]
One caveat to using schemas is that some users might use the same file for having in a single location all the configuration for all the applied packages to the cluster. When schemas are introduced, no longer one can use this mechanism, as deployment of a package with a values file with entries not in the schema will fail.
More so, schemas might make updates of a package fail, as if a value is removed from the schema and the applied values are not updated, the update will fail, leaving the functionality in a non-working state.
