### ISSUE TITLE
Unmanaged-cluster: write logs to `io.Writer` instead of hard coded stdout

### ISSUE THREAD

**Issue by jpmcb** [vmware-tanzu/community-edition#4729]
## Feature Request

Currently, stdout is hard coded as the default loging location for the unmanaged-cluster writer.

https://github.com/vmware-tanzu/community-edition/blob/aba53f70df579a69e5e56e93793fae55be8f5a59/cli/cmd/plugin/unmanaged-cluster/log/log.go#L114-L125

We should evaluate and attempt to implement using some `io.Writer` so that consumers of the `unmanaged-cluster` packages as code aren't forced to log to stdout. This would also enable passing `ioutil.Discard` to throw away logs if desired.

## Additional context

This would be useful for the Docker Desktop extension consumer of `unmanaged-cluster`

**Comment by harshanarayana** [comment]
/assign

@jpmcb  Mind if I take this up as my first contrib to this repo ?

What is the expectation for the change ? Do we retain the existing `NewLogger` and provide a new `NewLoggerWithWriter`  or provide a function in the `CMDLogger` that can be used to set the `output` after the logger is generated ?

**Comment by harshanarayana** [comment]
@jpmcb Thanks. I've opened a PR taking care of both the items I mentioned above. PTAL when time permits and we can discuss which one to retain or if both of them can be retained.
