### ISSUE TITLE
Docker Desktop Extension: Add guidance on development

### ISSUE THREAD

**Issue by garrying** [vmware-tanzu/community-edition#4736]
## Feature Request

Extend the README in `extensions/docker-desktop` to include guidance on how to work on the extension and the React application. I believe the Prerequisites is a good starting point; include links to relevant Extensions SDK docs, `make` commands, etc.

**Comment by stmcginnis** [comment]
Thanks Garry. What is missing from the current README? The items you mention are already there.

**Comment by garrying** [comment]
I think it'd be helpful to mention a few points around UI development. Happy to close if this is covered:
- node version requirement (I'm guessing 16.x.x, LTS)
- from the `extensions/docker-desktop/ui` folder
  - `npm install` 
  - `npm run  start`
- Hot reload in Docker Desktop: `docker extension dev ui-source vmware/vmware-tanzu-community-edition-extension-for-docker-desktop:dev http://localhost:3000`
- Reset: `docker extension dev reset vmware/vmware-tanzu-community-edition-extension-for-docker-desktop:dev`
