### ISSUE TITLE
Escape Command Missing to Uninstall Tanzu CLI in MacOS

### ISSUE THREAD

**Issue by LaTonia-Mertica** [vmware-tanzu/community-edition#4737]
## Description

On the Tanzu uninstall page for the MacOS, the escape is required to execute the uninstall cli command.

## Location

The issue is seen on the uninstall Tanzu page https://tanzucommunityedition.io/docs/v0.12/cli-uninstall/ in the MacOS section.

## Additional Context

`~/Library/Application Support/tce/uninstall.sh`

The above command should appear as follows:

`~/Library/Application\ Support/tce/uninstall.sh`

**Comment by stmcginnis** [comment]
Good catch @LaTonia-Mertica! Is this something you wanted to submit a PR to update? Or pointing out to have someone address it? Good either way, I just don't want to submit an update if it's something you wanted to tackle.

Thanks!
