### ISSUE TITLE
Upgrade Knative Serving to 1.5

### ISSUE THREAD

**Issue by ThomasVitale** [vmware-tanzu/community-edition#4746]
## Feature Request

The latest Knative Serving package available in TCE is version 1.0. The Knative Serving project has a release cadence of 6 weeks. The latest release is version 1.5. It would be great if TCE would provide an updated version of the package.

## Describe alternatives you've considered

Stay with the current, old version.

**Comment by jpmcb** [comment]
cc @vmware-tanzu/knative-owners

**Comment by jorgemoralespou** [comment]
Version 1.4.0 was merged recently (https://github.com/vmware-tanzu/community-edition/tree/main/addons/packages/knative-serving/1.4.0) but won't show up by default until there's a new TCE release. One can use an unreleased package repository though to get access to the package until that happens.

Is 1.4.0 good for you, or is there a need for 1.5.0?

**Comment by ThomasVitale** [comment]
@jorgemoralespou that's great, I had missed the recent merge. Thank you!

**Comment by evankanderson** [comment]
Nader's going to take a look at this to see if we can roll it into our standard processes.

**Comment by evankanderson** [comment]
We should add 1.5 as well. @naderziada

**Comment by nader-ziada** [comment]
@evankanderson 1.5 is merged in, should we update to newer?
