### ISSUE TITLE
Windows Worker nodes: Observability  Recipes

### ISSUE THREAD

**Issue by jayunit100** [vmware-tanzu/community-edition#4756]
## Feature Request

Windows observability - prometheus, grafana, fluent, and so on.  This would require making custom YAMLs for windows nodes and publishing these images to harbor.

Also i think a fair amount of exploration of what metrics we should scrape, should we run windows node agents (and how - in a host-process pod ?) and so on.

## Describe alternatives you've considered

Not having metrics :)

## Additional context

Incoming from our terasky friends !

**Comment by jpmcb** [comment]
cc @vmware-tanzu/pkg-prometheus-owners @vmware-tanzu/pkg-grafana-owners

**Comment by vrabbi** [comment]
This is still relevant
