### ISSUE TITLE
DDE: Errors returned from extension are not bubbled up to user

### ISSUE THREAD

**Issue by stmcginnis** [vmware-tanzu/community-edition#4757]
## Bug Report

Seen while testing failure cases with resources configured too low to create a cluster.

When we create a cluster, we run some preflight checks first to make sure the environment looks suitable for running a TCE cluster. If these checks do not pass, we return an error that gets passed back from the backend as a JSON structure containing error information:

https://github.com/vmware-tanzu/community-edition/blob/187be8c9ccdbb4c296f8ac81e6bee0c6e5fa9bab/extensions/docker-desktop/apps/clustermgr/pkg/cluster/cluster.go#L88-L92

On the UI side, this error information is not shown to the end user, making this failure case confusing. The extension UI goes from "Creating cluster" to "Cluster does not exist", with nothing letting the user know that there is an issue preventing cluster creation.

## Expected Behavior

When errors are returned from the backend processes, the UI should read those errors and display them to the end user so they are aware of what has happened.

## Steps to Reproduce the Bug

Go in to the Docker Desktop resources settings and change the allocated memory to 1GB. This will cause our check for a minimum of 2GB to fail and cluster will not be able to be created. Attempt to create cluster to observe behavior.

**Comment by jorgemoralespou** [comment]
Related to #4529
