### ISSUE TITLE
cannot create management cluster on vsphere

### ISSUE THREAD

**Issue by EthanWilkinson** [vmware-tanzu/community-edition#4810]
follwing the guide to setup a cluster it just fails,  either gets stuck on waiting for kubeadmininit if its single dev env or waiting for scale up if a 3 node prod.

ESXI 6.7 
VCSA 

Bootstrap is docker desktop 

Tried Photon and Ubuntu images same thing. the nodes have internet and i can SSH into them. 

PS C:\WINDOWS\system32> kubectl get po,deploy,cluster,kubeadmcontrolplane,machine,machinedeployment -A --kubeconfig C:\Users\ethan\.kube-tkg\tmp\config_Zqi5WerA
NAMESPACE                           NAME                                                                      READY   STATUS    RESTARTS   AGE
capi-kubeadm-bootstrap-system       pod/capi-kubeadm-bootstrap-controller-manager-79b888f8b9-mprnc            1/1     Running   0          19m
capi-kubeadm-control-plane-system   pod/capi-kubeadm-control-plane-controller-manager-84b9bd7564-chp44        1/1     Running   0          19m
capi-system                         pod/capi-controller-manager-69d6d968ff-ssgch                              1/1     Running   0          19m
capv-system                         pod/capv-controller-manager-65dfc6d76c-fvx4c                              1/1     Running   0          19m
cert-manager                        pod/cert-manager-84bb9684d6-ww5wl                                         1/1     Running   0          19m
cert-manager                        pod/cert-manager-cainjector-6767468f75-9pzdm                              1/1     Running   0          19m
cert-manager                        pod/cert-manager-webhook-588bb4546d-m6sbf                                 1/1     Running   0          19m
kube-system                         pod/coredns-67c8559bb6-bjpcq                                              1/1     Running   0          19m
kube-system                         pod/coredns-67c8559bb6-qqnch                                              1/1     Running   0          19m
kube-system                         pod/etcd-tkg-kind-caljet8m55s9j37ip400-control-plane                      1/1     Running   0          19m
kube-system                         pod/kindnet-tvb92                                                         1/1     Running   0          19m
kube-system                         pod/kube-apiserver-tkg-kind-caljet8m55s9j37ip400-control-plane            1/1     Running   0          19m
kube-system                         pod/kube-controller-manager-tkg-kind-caljet8m55s9j37ip400-control-plane   1/1     Running   0          19m
kube-system                         pod/kube-proxy-cx6g7                                                      1/1     Running   0          19m
kube-system                         pod/kube-scheduler-tkg-kind-caljet8m55s9j37ip400-control-plane            1/1     Running   0          19m
local-path-storage                  pod/local-path-provisioner-547f784dff-fxnzn                               1/1     Running   0          19m

NAMESPACE                           NAME                                                            READY   UP-TO-DATE   AVAILABLE   AGE
capi-kubeadm-bootstrap-system       deployment.apps/capi-kubeadm-bootstrap-controller-manager       1/1     1            1           19m
capi-kubeadm-control-plane-system   deployment.apps/capi-kubeadm-control-plane-controller-manager   1/1     1            1           19m
capi-system                         deployment.apps/capi-controller-manager                         1/1     1            1           19m
capv-system                         deployment.apps/capv-controller-manager                         1/1     1            1           19m
cert-manager                        deployment.apps/cert-manager                                    1/1     1            1           19m
cert-manager                        deployment.apps/cert-manager-cainjector                         1/1     1            1           19m
cert-manager                        deployment.apps/cert-manager-webhook                            1/1     1            1           19m
kube-system                         deployment.apps/coredns                                         2/2     2            2           19m
local-path-storage                  deployment.apps/local-path-provisioner                          1/1     1            1           19m

NAMESPACE    NAME                                 PHASE         AGE   VERSION
tkg-system   cluster.cluster.x-k8s.io/tanmgmt-1   Provisioned   18m

NAMESPACE    NAME                                                                        CLUSTER     INITIALIZED   API SERVER AVAILABLE   REPLICAS   READY   UPDATED   UNAVAILABLE   AGE   VERSION
tkg-system   kubeadmcontrolplane.controlplane.cluster.x-k8s.io/tanmgmt-1-control-plane   tanmgmt-1                                        1                  1         1             18m   v1.22.8+vmware.1

NAMESPACE    NAME                                                       CLUSTER     NODENAME   PROVIDERID                                       PHASE         AGE   VERSION
tkg-system   machine.cluster.x-k8s.io/tanmgmt-1-control-plane-zmzfn     tanmgmt-1              vsphere://423fe592-9a03-dfc9-6044-7a85e4bfd4b2   Provisioned   18m   v1.22.8+vmware.1
tkg-system   machine.cluster.x-k8s.io/tanmgmt-1-md-0-85d4c458fd-m9gqb   tanmgmt-1                                                               Pending       18m   v1.22.8+vmware.1
tkg-system   machine.cluster.x-k8s.io/tanmgmt-1-md-1-6c477854b4-ct8zw   tanmgmt-1                                                               Pending       18m   v1.22.8+vmware.1
tkg-system   machine.cluster.x-k8s.io/tanmgmt-1-md-2-f69495d84-zpwxn    tanmgmt-1                                                               Pending       18m   v1.22.8+vmware.1

NAMESPACE    NAME                                                CLUSTER     REPLICAS   READY   UPDATED   UNAVAILABLE   PHASE       AGE   VERSION
tkg-system   machinedeployment.cluster.x-k8s.io/tanmgmt-1-md-0   tanmgmt-1   1                  1         1             ScalingUp   18m   v1.22.8+vmware.1
tkg-system   machinedeployment.cluster.x-k8s.io/tanmgmt-1-md-1   tanmgmt-1   1                  1         1             ScalingUp   18m   v1.22.8+vmware.1
tkg-system   machinedeployment.cluster.x-k8s.io/tanmgmt-1-md-2   tanmgmt-1   1                  1         1             ScalingUp   18m   v1.22.8+vmware.1
PS C:\WINDOWS\system32>

tanzu version
version: v0.11.4
buildDate: 2022-05-17
sha: a9b8f3a

**Comment by EthanWilkinson** [comment]
<img width="1158" alt="image" src="https://user-images.githubusercontent.com/42363281/174095102-71e93dd0-b8a6-44fa-bf53-8a24a88d78db.png">

**Comment by jpmcb** [comment]
Thanks for providing some info here! Sorry you're having trouble bootstrapping.

Here's the doc for troubleshooting a cluster manually: https://tanzucommunityedition.io/docs/v0.12/ts-manually/#troubleshooting-a-bootstrap-cluster-manually

We could also provide some synchronous support on slack: https://kubernetes.slack.com/archives/C02GY94A8KT
