### ISSUE TITLE
[Docs] [](/docs/v0.12/ref-vsphere/)

### ISSUE THREAD

**Issue by Virtualinux** [vmware-tanzu/community-edition#4840]
## Description

Why not just provide the powerCLI command for this - would be much more user friendly

## Location

[](https://tanzucommunityedition.io/docs/v0.12/ref-vsphere/)

## Additional Context

New-VIRole -Name “<Role_Name>” -Privilege (Get-VIPrivilege -Id <Privilege A>,<Privilege B>…<Privilege X>)

so not only do I have to go and create the command to create the role, for each permission I've got to work out the dot notation for it.   If I complete that before I get fed up and just run it as administrator i'll post it

New-VIRole -Name “XYZ” -Privilege (Get-VIPrivilege -Id VirtualMachine.Interact.PowerOn,VirtualMachine.Interact.PowerOff,VirtualMachine.Config.AddNewDisk,VirtualMachine.Config.AdvancedConfig)

**Comment by stmcginnis** [comment]
We don't want to assume the user has PowerCLI installed, but it could be useful to add another section giving this option in case they do. If you have the specific commands - or if you want to propose a PR adding a new section with those commands - that would be great.

**Comment by Virtualinux** [comment]
Hiya, 

This should do it:)  (assuming my phone hasn't messed with mine breaks too much) 

Guy

$tceprivs=@(
'Global.Licenses',
'Global.DisableMethods',
'Global.EnableMethods',
'Datastore.Browse',
'Datastore.FileManagement',
'Datastore.AllocateSpace',
'Network.Assign',
'VirtualMachine.Inventory.CreateFromExisting',
'VirtualMachine.Inventory.Delete',
'VirtualMachine.Interact.PowerOn',
'VirtualMachine.Interact.PowerOff',
'VirtualMachine.Config.AddExistingDisk',
'VirtualMachine.Config.AddNewDisk',
'VirtualMachine.Config.RemoveDisk',
'VirtualMachine.Config.RawDevice',
'VirtualMachine.Config.CPUCount',
'VirtualMachine.Config.Memory',
'VirtualMachine.Config.AddRemoveDevice',
'VirtualMachine.Config.EditDevice',
'VirtualMachine.Config.Settings',
'VirtualMachine.Config.AdvancedConfig',
'VirtualMachine.Config.DiskExtend',
'VirtualMachine.Config.ChangeTracking',
'VirtualMachine.State.CreateSnapshot',
'VirtualMachine.State.RemoveSnapshot',
'VirtualMachine.Provisioning.DeployTemplate',
'VirtualMachine.Provisioning.DiskRandomRead',
'VirtualMachine.Provisioning.GetVmFiles',
'Resource.AssignVMToPool',
'Sessions.ValidateSession',
'Sessions.GlobalMessage',
'VApp.Import',
'Cns.Searchable',
'StorageProfile.View')

 

New-VIRole -name tce-account-role -Privilege (Get-VIPrivilege -id $tceprivs)




Sent from MailDroid

-----Original Message-----

**Comment by stmcginnis** [comment]
Maybe something we want to also consider for this - here is a gist another user put together for using `govc` to set permissions.

https://gist.github.com/dominikzorgnotti/cf2264945c9316eaa25f196d41eda308

**Comment by dominikzorgnotti** [comment]
@stmcginnis By suggestion of @dvonthenen I added a doc PR: https://github.com/vmware-tanzu/community-edition/issues/4950

**Comment by dominikzorgnotti** [comment]
Since the contributing docs mention "talk first, then do a PR" I am trying my luck here, hoping that this is the right place (forgive my ignorance if I am wrong).
To address this issue (#4840) as well as #4950 and #4951 I created a proposal for an update documentation page:
https://github.com/vmware-tanzu/community-edition/commit/590558a87e717b2825bed7b5f407b6a31aba21c4

Let me know if that is useful and if so, what are the next steps.

**Comment by Virtualinux** [comment]
First time I've contributed code before so not sure of the process or your seeking feedback from me but the proposal seems comprehensive and offers different labour saving options so all good from me

Sent from MailDroid

-----Original Message-----

**Comment by stmcginnis** [comment]
👍 from me as well. That would be useful having the various examples. Please do open a PR to add that to the docs. Thanks!

**Comment by stmcginnis** [comment]
Addressed by https://github.com/vmware-tanzu/community-edition/pull/4971
