### ISSUE TITLE
Remove use of `pkg/errors` - it has been deprecated and archived

### ISSUE THREAD

**Issue by stmcginnis** [vmware-tanzu/community-edition#4850]
## Feature Request

Found out today the `pkg/errors` project had been looking for maintainers for some time and had finally decided to archive the project. We should move away from using it.

https://github.com/pkg/errors/issues/245

## Describe alternatives you've considered

A few alternatives:

- Continue using until things break
- Wait to see if a new fork becomes maintained and switch references to that
- Use native things like `fmt.Error` instead

**Comment by harshanarayana** [comment]
/assign

Mind if I take a look at this ?

**Comment by harshanarayana** [comment]
With new native `errors` library most of what is provided by the `pkg/errors` is nearly available. I think it will be a safe bet to use that in place of this. However, while looking around the code base, I also found that we have a few different ways of handling the errors across the board in the TCE repo. Should we take this opportunity and create a standard errors package that can be re-used across the board in the TCE ? xref: https://github.com/kubernetes/apimachinery/tree/master/pkg/api/errors

**Comment by stmcginnis** [comment]
That's a good idea to take the time to get something consistent across the board Harsha.

It would be more work, but I wonder if we should get that common error handling into `tanzu-framework`, then pick it up in `community-edition`. Though we're pinned to an older version of t-f for awhile yet, so maybe that's a good long term plan that isn't actually feasible at this point. So maybe both?

Either way, I like the idea of taking the opportunity to review our error handling and seeing if we can do something more consistent and better overall.

**Comment by harshanarayana** [comment]
```bash
❯ rg pkg/errors -g "*.go"
extensions/docker-desktop/apps/clustermgr/pkg/kubeconfig/internal/kubeconfig/helpers.go
7:	"sigs.k8s.io/kind/pkg/errors"

extensions/docker-desktop/apps/clustermgr/pkg/kubeconfig/internal/kubeconfig/write.go
10:	"sigs.k8s.io/kind/pkg/errors"

extensions/docker-desktop/apps/clustermgr/pkg/kubeconfig/internal/kubeconfig/read.go
11:	"sigs.k8s.io/kind/pkg/errors"

extensions/docker-desktop/apps/clustermgr/pkg/kubeconfig/internal/kubeconfig/encode.go
10:	"sigs.k8s.io/kind/pkg/errors"

extensions/docker-desktop/apps/clustermgr/pkg/kubeconfig/internal/kubeconfig/merge.go
9:	"sigs.k8s.io/kind/pkg/errors"

extensions/docker-desktop/apps/clustermgr/pkg/utils/lock.go
12:	"github.com/pkg/errors"

extensions/docker-desktop/apps/clustermgr/pkg/kubeconfig/internal/kubeconfig/remove.go
9:	"sigs.k8s.io/kind/pkg/errors"
```

This is not too many. I see we are using a few [`sigs.k8s.io/kind/pkg/errors`](https://github.com/kubernetes-sigs/kind/blob/main/pkg/errors/errors.go) which internally wraps the `pkg/errors`. 

Should be pretty straight forward to get us going. I will open a DRAFT PR with proposed changes and we can get it reviewed.

**Comment by harshanarayana** [comment]
```golang
package errors

import "fmt"

type Reason string

const (
	ReasonUnknown     Reason = "Unknown"
	ReasonLockFailed  Reason = "LockFailed"
	ReasonMergeFailed Reason = "MergeFailed"
)

type TanzuError struct {
	ErrorDetails ErrorDetails `json:"errorDetails"`
}

type ErrorDetails struct {
	Message string `json:"message,omitempty"`
	Reason  Reason `json:"reason,omitempty"`
	Err     error  `json:"err"`
}

func (t *TanzuError) Error() string {
	return fmt.Sprintf("%s: %s (%s)", t.ErrorDetails.Reason, t.ErrorDetails.Message, t.ErrorDetails.Err)
}

func NewLockFailed(err error, configPath string) *TanzuError {
	return &TanzuError{
		ErrorDetails: ErrorDetails{
			Reason:  ReasonLockFailed,
			Message: fmt.Sprintf("failed to lock config file %s", configPath),
			Err:     err,
		},
	}
}

func NewMergeFailed(err error, configPath string) *TanzuError {
	return &TanzuError{
		ErrorDetails: ErrorDetails{
			Reason:  ReasonMergeFailed,
			Message: fmt.Sprintf("failed to get kubeconfig (%s) to merge", configPath),
			Err:     err,
		},
	}
}

```
@stmcginnis @jpmcb  Here is an example of the error package I am thinking. Is this inline with what you have in mind or do I need to tune some bits of it ?

**Comment by stmcginnis** [comment]
Looks great Harsha!

**Comment by harshanarayana** [comment]
@stmcginnis @jpmcb I came across https://github.com/zchee/go-analyzer/tree/main/pkgerrors in the k8s Kind slack group.

**Comment by harshanarayana** [comment]
Works for me. I will re-open the PR with the suggested changes.

**Comment by harshanarayana** [comment]
@jpmcb @stmcginnis  PTAL at the #4914  I have opened a new one based on comment from @jpmcb
