### ISSUE TITLE
Add Knative Eventing as a TCE package

### ISSUE THREAD

**Issue by ThomasVitale** [vmware-tanzu/community-edition#4859]
## Feature Request

Knative Serving is a great project and it's really convenient to have it part of the TCE repository. It would be nice to also provide a package for [Knative Eventing](https://knative.dev/docs/eventing/) to make it more convenient working with event-driven applications on TCE.

## Describe alternatives you've considered

I could install it manually from YAML manifests or via the official Operator.

## Additional context

I have implemented a [basic version of a Knative Eventing package](https://github.com/arktonix/package-for-knative-eventing) that could be used to define a foundation for a TCE package.

**Comment by salaboy** [comment]
@ThomasVitale thanks a lot Thomas, having an initial version for the Knative Eventing package is awesome!
