### ISSUE TITLE
Add Harbor version to 2.5.x

### ISSUE THREAD

**Issue by jgalvin98** [vmware-tanzu/community-edition#4881]
## Feature Request
Requesting that the set of packaged versions of Harbor to be updated to include version 2.5.x (latest if possible) 

1.) As of 2.5.0 of Harbor, support for Cosign has been added.  This is our image signing direction and would be useful to have it this capability available. 
2.) a fixed for a bug whereby uploaded files are not purged properly.  This can (as does for me) result in filling up the designated storage filesystem very quickly, causing subsequent new uploads to fail. Harbor feature added in 2.5.0: "Activated distribution upload purging to remove orphaned files from the upload directories."

**Comment by MinerYang** [comment]
@jgalvin98 ,
Thanks and It have already bump up harbor package to latest version v2.5.3. You could check it on the latest TCE repo and could be used in the TKG 1.6 release soon I suppose.
