### ISSUE TITLE
UI plugin: [BUG] progress page is not getting the last status correctly

### ISSUE THREAD

**Issue by raymondz1** [vmware-tanzu/community-edition#4906]
The management cluster for the docker workflow created successfully. But the status in the progress page is not right. 

![Image](https://user-images.githubusercontent.com/70610112/176045020-d3008b93-a563-4179-a716-5bf94cec7a7b.png)

**Comment by swalner-vmware** [comment]
This is the same for AWS. Likely there is a change to some wording on a backend message (that we're using to recognize the last step).
