### ISSUE TITLE
UI Plugin: Deployment progress - missed last two stages

### ISSUE THREAD

**Issue by swalner-vmware** [vmware-tanzu/community-edition#4927]
During end-to-end testing (with Sean) the (AWS) management cluster was successfully deployed. However, the UI did not recognize the last two steps (so looking only at the UI's step display, the cluster looked like it wasn't completely created).
This may be due to some wording changes on the backend messages (that we're trying to recognize in a fragile way).

**Comment by stmcginnis** [comment]
I did a little digging on the progress updates that are sent.

The different steps that we have in the UI are based on status sent from the backend (Go) code. The values are defined here:

https://github.com/vmware-tanzu/tanzu-framework/blob/v0.11.4/pkg/v1/tkg/client/init.go#L46-L53

The steps are defined as part of the management cluster creation progression here:

https://github.com/vmware-tanzu/tanzu-framework/blob/v0.11.4/pkg/v1/tkg/client/init.go#L62-L70

One of the things we noticed during our testing was the last two steps of `StepInstallProvidersOnRegionalCluster` and `StepMoveClusterAPIObjects` were never marked as completed. I think the completion of the step is performed once the update for the following step is sent, notifying the next step is now running. The final step gets the update sent on start here:

https://github.com/vmware-tanzu/tanzu-framework/blob/v0.11.4/pkg/v1/tkg/client/init.go#L292

And we did see the following console log message being sent from:

https://github.com/vmware-tanzu/tanzu-framework/blob/v0.11.4/pkg/v1/tkg/client/init.go#L293

That makes me wonder if it's possible that we're dropping some of those notifications.

**Comment by stmcginnis** [comment]
The `SendProgressUpdates` call is here:

https://github.com/vmware-tanzu/tanzu-framework/blob/a9b8f3a7fc2ea45863a46a077be784e79ead0110/pkg/v1/tkg/log/writer.go#L122

That checks for our channel and sends the JSON update. Since we are receiving the other step updates, I would assume this data flow is working, but maybe possible something is getting messed up with our channel.

**Comment by stmcginnis** [comment]
Note, this is likely a duplicate of https://github.com/vmware-tanzu/community-edition/issues/4906
