### ISSUE TITLE
prevent naming collisions between clusters owned by the docker extension and by the tanzu unmanaged-cluster plugin

### ISSUE THREAD

**Issue by joefitzgerald** [vmware-tanzu/community-edition#4955]
## Bug Report

1. Create a cluster using `tanzu unmanaged-cluster create tanzu-community-edition`
1. Install the Tanzu Community Edition Docker extension
1. Click `Create` in the Docker extension's user interface
1. Observe that the creation seems to succeed, but no log output is emitted
1. Click `Delete` in the Docker extension's user interface
1. Observe that the operation is in progress (`cluster is being deleted`), and then receive an error:  `Cluster can not be created. fslock is already locked`
1. Observe that the cluster has actually been deleted, despite it being an `unmanaged-cluster` owned cluster
1. Observe that `~/.kube/config` has not been cleaned up, despite the cluster now being deleted

## Expected Behavior

* Document that there is a reserved name for clusters created by the docker extension. Warn the user that they should not make use of this name when using the `unmanaged-cluster` plugin directly.
* Reserve a name for docker-created clusters (e.g. `docker-tanzu-community-edition`). If `tanzu unmanaged-cluster create docker-tanzu-community-edition` is run, return an error indicating that this cluster name is reserved for the docker extension.
* Make the `unmanaged-cluster` plugin and the docker extension aware of each other via filesystem inspection or some other mechanism, so that they can see clusters created by each plugin and avoid naming conflicts.

## Steps to Reproduce the Bug

See above.

## Environment Details

* Build version (`tanzu version`): v0.11.4
* Deployment (Managed/Unmanaged cluster): Unmanaged cluster
* Infrastructure Provider (Docker/AWS/Azure/vSphere): Docker
* Operating System (client): macOS Monterey 12.5 Beta (21G5056b) / Apple M1 Max
* Docker Desktop: 4.9.1 (81317)
* Docker TCE Extension: v0.1.1

**Comment by stmcginnis** [comment]
@jorgemoralespou any thoughts on this one?
