### ISSUE TITLE
Publish Tanzu CLI as an ASDF plugin

### ISSUE THREAD

**Issue by vrabbi** [vmware-tanzu/community-edition#5025]
## Feature Request

Currently Tanzu CLI is built for each specific distro: TCE, TKG etc. this causes issues for running and managing TKG and TCE from the same machine.
Also having 2 versions of TCE or TKG installed on the same machine is also problematic as the CLI version is coupled with the release version.
ASDF is a great mechanism to allow for installing multiple versions of a CLI and making them interchangeable in a very simple way.
Releasing an ASDF plugin for Tanzu CLI could be a very elegant solution to solve these issues mentioned above.
## Describe alternatives you've considered
Having separate machines for managing each platform/version.

**Comment by stmcginnis** [comment]
Since I had to Google it - here's a link explaining what ASDF is: https://asdf-vm.com/

**Comment by vrabbi** [comment]
also just for reference, the Carvel team have experience with ASDF as they release all of the carvel tools via ASDF as well.
for carvel tools its also very useful as asdf allows you to set a different version of the CLI on a per folder basis with a single command.
its similar to nvm for those in the node world but is generic and works alot better :)
