### ISSUE TITLE
Ability to change VSPHERE settings after initial deployment

### ISSUE THREAD

**Issue by alexnaris** [vmware-tanzu/community-edition#5026]
Once a workload cluster is deployed, there is no known way to change VSPHERE settings like VSPHERE_DATASTORE..

So if vsphere LUN naming changes at the moment a cluster will need to destroyed and recreated to make changes.

Now these settings seem to be in a base64 encoded string in config-values secret.  

`data:
  value: longbase64string..`

I tried decoding -> changing setting -> encoding back -> replace in config-values secret.  However it does not work

So what is the proper way to make this change?  
By now we have 9 workload clusters and redeploying just because of LUN change  would be very inconvenient 

Hoping for a quick answer!

Thanks,

**Comment by stmcginnis** [comment]
@vijaykatam is this something you can help answer?

**Comment by alexnaris** [comment]
Any updates?  We really need to be able to change those settings.  For example, what do we do if VCenter password changes?  Redeploying a workload cluster does not make any sense in this case

**Comment by kashak88** [comment]
We're facing the same issue here, cluster nodes are being created on slower storage instead being created on newly acquired nvme. Redeploying from scratch seems very impractical.
