### ISSUE TITLE
unable to set up management cluster, : unable to create

### ISSUE THREAD

**Issue by prbjrgac** [vmware-tanzu/community-edition#5039]
Posted this previously and I wasn't able to find any responses so apologize for the repeat question

Having problems with the final phase getting the management cluster to install via the gui install... Keep getting the following messages below within the screenshot... Any suggestions would be greatly appreciated.  Running ubuntu 20.04

![Screenshot 2022-07-13 132153](https://user-images.githubusercontent.com/37939115/178814701-5228f2bf-fb10-49db-b381-794423925896.png)

**Comment by fferencik** [comment]
Hi, same here. Ubuntu 22.04 used for bootstrap machine, photon-3-kube-v1.22.8+vmware.1 for TCE K8s nodes, vCenter 7 U2 Build: 17920168 and VMware ESXi, 7.0.2, 17630552. Any guidance?
![071822-tce-mgmt-deploy-error](https://user-images.githubusercontent.com/29311605/179507931-c30a6a90-fecd-41ef-9ab3-07c0627c187e.jpg)

**Comment by prbjrgac** [comment]
Why it has not installed current latest 0.12 
        Downloaded the latest version of Tanzu

Trying to determine if it is a issue with Tanzu it's self or one of the pre-requisites?

**Comment by vrabbi** [comment]
the version of the CLI is correct. its the Tanzu Framework version you see there not the TCE version

**Comment by vrabbi** [comment]
are you using AVI/NSX-ALB or Kube-Vip for the K8s API Load Balancer?

**Comment by vrabbi** [comment]
also can you send the output of the commands as suggested in the yellow output of the command? that logs you shared has no real details which is hy it gives the debug command suggestion

**Comment by prbjrgac** [comment]
Sorry as this is all new to me, using the default VIP function.....

How would I send the output of the commands?

**Comment by vrabbi** [comment]
either paste here in a comment or preferably use pastebin.org and send the link here

**Comment by vrabbi** [comment]
also do you see VMs being created in vSphere?

**Comment by prbjrgac** [comment]
NO vm's are being created

**Comment by prbjrgac** [comment]
Do you mean the picture that I posted in the original question?

**Comment by vrabbi** [comment]
no i mean the output of the command it suggests to run in the output you sent a photo of

**Comment by prbjrgac** [comment]
that is the only section I took a screen shot, want me to attempt again and provide a screenshot of everything?

**Comment by vrabbi** [comment]
not a screenshot. the command in the failure message "kubectl get ....." should be run and the output shared

**Comment by prbjrgac** [comment]
going back in and will get that for you

**Comment by vrabbi** [comment]
Also make sure your dhcp server on the network passes on ntp settings to the vms as if not you may very well encounter other issues down the road

**Comment by prbjrgac** [comment]
That is my mistake, went through to fast to get you the capture.. Will run it again when I get a chance and put  it on a vLan with DHCP

**Comment by vrabbi** [comment]
Kubectl not kubetcl

**Comment by vrabbi** [comment]
the FULL command

**Comment by vrabbi** [comment]
thats the output not the command

**Comment by prbjrgac** [comment]
unable to copy from the server for some reason.... running what is in this screen shot

ran first line

![image](https://user-images.githubusercontent.com/37939115/179611792-5b864bb1-ca33-4d90-8f5f-eae9cf672991.png)

**Comment by prbjrgac** [comment]
thinking kubectl is not installed?

![image](https://user-images.githubusercontent.com/37939115/179612399-78b51234-e3b4-46b9-adf7-cc2f1ef16cf9.png)

**Comment by vrabbi** [comment]
if that doesnt work then fix your kubectl installation as kubectl is broken.

**Comment by prbjrgac** [comment]
can you shoot me exact commands for installing kubectl? Had all kinds of problems and will run through it again

**Comment by prbjrgac** [comment]
will do, thank you for all the help...

**Comment by fferencik** [comment]
Ok in my case issue is network communication between VLANs. When I have tried to deploy management cluster to different VLAN backed vDS portgroup it was failed. As I have deployed to same L2 network where vCenter lives its working just fine.
By the way vrabbi Scott Rosenberg how to check TCE version installed?

**Comment by prbjrgac** [comment]
We don't have DHCP enabled on the vLan where vCenter lives so don't think that would work

**Comment by prbjrgac** [comment]
DHCP is a requirement for the cluster to be built?

**Comment by vrabbi** [comment]
Yes you need dhcp for it to work

**Comment by prbjrgac** [comment]
Does the management cluster need to live on the same vLan as vCenter?

**Comment by vrabbi** [comment]
no

**Comment by prbjrgac** [comment]
believe it is a problem with kubectl so still digging into this further
