### ISSUE TITLE
UI Plugin: add vSphere defaults service

### ISSUE THREAD

**Issue by miclettej** [vmware-tanzu/community-edition#5219]
## Feature Request

Include a new service that is responsible for calculating vSphere management cluster default values based on:
 - discovery data (IE multiple OS Images are retrieved ===> set first as selected by default)
 - user interaction (IE user selects a node profile ==> control plane flavor, management cluster instance type and workload cluster instance type should be set)
 - fixed constant values (IE CNI provider, Cluster Service CIDR, Cluster Pod CIDR)

**Comment by jdumars** [comment]
Hi, VMware Tanzu Community Edition is no longer an actively maintained project. Please see tanzucommunityedition.io for further information.
