### ISSUE TITLE
UI Plugin: address feedback after review with UX team

### ISSUE THREAD

**Issue by miclettej** [vmware-tanzu/community-edition#5290]
## Feature Request

Welcome:

Light - Cyan color should be a darker blue

Getting Started - Cyan should be darker blue
- background images, grey outline doesn’t pop

Management clusters provider select - needs back button, title should be “create management cluster”
*titles should be leading caps

Docker - Title should say Docker prerequisites, tab font sizes larger, maybe helper text a little larger

AWS - credentials - links are washed out a bit - also need external link addresses

 - AWS region - can we add placeholder text to say select region, select ec2 key pair
 - ec2 key pair validation happening prior to connecting
 - success notification - make it obvious it’s not a button, expend right side width/padding

Management Cluster settings
 - cluster name - remove default cluster name, should be placeholder
 - title has inconsistent capitalization
 - fields have inconsistent font usage
 - helper text is small 
 - fields are misaligned
 - set default selection for node profile
 - selected node profile icon should be darker blue
 - make screen more responsive - cols 4, 4, 4
 - OS image can roll title and label into one

Review configuration - remove HR between and after tables
 - Title - should conceptualize the entire page - needs formatting
 - Tweak descriptive text for each table

vSphere - connected/connecting alert -> move closer to the connect button, make width consistent with AWS
 - IP family and SSL thumbprint - can we try to see what it looks like having them closer to login fields
 - no images use case = make error message an alert banner - also too far from field
 - try to tie the error title into the field validation but keep standalone description and refresh os image button - remediation text doesn’t need to be red anymore
 - REFRESH THE OS IMAGE CHECK = change text to VALIDATE or CHECK FOR OS IMAGES

BUG - if page has validation errors, user cannot currently go back a step - should be able to go back but not forward

SSH key - need descriptive text (SSH public key) = use a tooltip

Step 3 Load Balancer - simplified workflow - add some educational text to right
 - Control Plane Endpoint Provider - add a tooltip
 - Consider changing dropdown to static text for basic - work through with the team

Step 4 - remove Resources title
 - VMware in description, caps incorrect

Azure - need proper link for description. Color too light, should end with a period
Step 1: SSH public key field too small - issue with validation error css 
 - SSH public key ‘begins with’ instructional text should be part of tooltip or outside of field - make same for sphere
Login field placeholders - change to example values
Connected alert should have more padding on right

Step 2 - same feedback as AWS

Management cluster inventory - icon color is too light, title color inconsistent

Move ‘Delete’ action to upper right corner using action menu

**Comment by jdumars** [comment]
Hi, VMware Tanzu Community Edition is no longer an actively maintained project. Please see tanzucommunityedition.io for further information.
