### ISSUE TITLE
UI Plugin: Azure - create defaults service and orchestrator

### ISSUE THREAD

**Issue by miclettej** [vmware-tanzu/community-edition#5291]
## Feature Request

Azure management cluster create workflow should include:

Defaults service which includes utility methods for selecting a default value out of a given set of resources

Orchestrator service which retrieves resources and orchestrates calls to defaults service

**Comment by jdumars** [comment]
Hi, VMware Tanzu Community Edition is no longer an actively maintained project. Please see tanzucommunityedition.io for further information.
