### ISSUE TITLE
UI Plugin: Enhance discovery API error handling

### ISSUE THREAD

**Issue by miclettej** [vmware-tanzu/community-edition#5322]
## Feature Request

The UI should include a uniform and friendly standard error message to display when discovery APIs fail

The alert should include a "more info" action or other means to show the user the specific error details if they choose

The alert should be dismissable

**Comment by jdumars** [comment]
Hi, VMware Tanzu Community Edition is no longer an actively maintained project. Please see tanzucommunityedition.io for further information.
