### ISSUE TITLE
Installing the mgmt-cluster -> secret "tanzu-featuregates-webhook-server-cert" not found

### ISSUE THREAD

**Issue by Anganthier** [vmware-tanzu/community-edition#5329]
## Bug Report

The pod won't start due to a missing secret
tkg-system                          tanzu-featuregates-controller-manager-5d7c7f6bd4-fvrbw           0/1     ContainerCreating   0          10m

Warning  FailedMount  71s (x12 over 9m25s)  kubelet            MountVolume.SetUp failed for volume "cert" : secret "tanzu-featuregates-webhook-server-cert" not found

## Expected Behavior

The pod should just run and certificate should have been created before

## Steps to Reproduce the Bug

Not sure yet

## Screenshots or additional information and context
![image](https://user-images.githubusercontent.com/15246122/187856928-d28b703e-ccd8-45c0-a3e7-04694e338873.png)

## Environment Details

* Build version (`tanzu version`): v0.11.4
* Deployment (Managed/Unmanaged cluster): 
* Infrastructure Provider (Docker/AWS/Azure/vSphere): Docker Version 20.10.17-rd
* Operating System (client): Linux Mint 20.3

## Diagnostics and log bundle

Which service is responsible for creating the secrets? I can get the log there.

**Comment by Anganthier** [comment]
[management-cluster.my-first-tanzu.diagnostics.tar.gz](https://github.com/vmware-tanzu/community-edition/files/9467933/management-cluster.my-first-tanzu.diagnostics.tar.gz)

I collected the diagnostic information

**Comment by Anganthier** [comment]
Clicked the wrong button

**Comment by jdumars** [comment]
Hi, VMware Tanzu Community Edition is no longer an actively maintained project. Please see tanzucommunityedition.io for further information.
