### ISSUE TITLE
UI Plugin: Implement GET providers API for compatible TKR

### ISSUE THREAD

**Issue by miclettej** [vmware-tanzu/community-edition#5334]
## Feature Request

A GET `providers` API endpoint is available on the TKG kickstart UI which retrieves the compatible TKR version for the UI. We should copy this API implementation over to the guided UI and leverage it to:

1. Surface the TKR recommended version to users preemptively in vSphere mgmt cluster create so that they have early signal for which OS image to install
2. If no OS images are found, provide a useful message to the user recommending this TKR version

**Comment by jdumars** [comment]
Hi, VMware Tanzu Community Edition is no longer an actively maintained project. Please see tanzucommunityedition.io for further information.
