### ISSUE TITLE
Unable to create management cluster on AWS EC2

### ISSUE THREAD

**Issue by iensu** [vmware-tanzu/community-edition#5359]
## Bug Report
Hi! We are having some issues deploying a development tanzu setup on AWS EC2. 

The management cluster cannot be successfully provisioned using the UI since it fails to instantiate the AWSMachine resources. We get the following error message when looking at the `capa-controller-manager` logs:

```console
E0915 14:59:01.321203       1 awsmachine_controller.go:521]  "msg"="unable to create instance" "error"="failed to create AWSMachine instance: failed to run instance: InvalidParameterValue: Invalid value 'size' for InstanceType.\n\tstatus code: 400, request id: a0024ccd-a5ae-4b29-96e1-042e782dcafa"
```

When we check the resource manifest (`kubectl get awsmachines -n tkg-system mgmt-control-plane-v6h5l -o yaml`) the `instanceType` property is indeed set to `size` and not `t2.large` which we expect. 

## Expected Behavior

The management cluster is successfully provisioned.

## Steps to Reproduce the Bug

Run `tanzu management-cluster create --ui` and select AWS EC2 and follow the configuration wizard and hit deploy. 

## Screenshots or additional information and context

Here are the contents of the generated configuration file: 

```yaml
AWS_AMI_ID: ami-048b944e3ae94537b
AWS_B64ENCODED_CREDENTIALS: <REDACTED>
AWS_NODE_AZ: eu-west-1a
AWS_NODE_AZ_1: ""
AWS_NODE_AZ_2: ""
AWS_PRIVATE_NODE_CIDR: 10.0.16.0/20
AWS_PRIVATE_NODE_CIDR_1: ""
AWS_PRIVATE_NODE_CIDR_2: ""
AWS_PRIVATE_SUBNET_ID: ""
AWS_PRIVATE_SUBNET_ID_1: ""
AWS_PRIVATE_SUBNET_ID_2: ""
AWS_PROFILE: tanzu-ec2
AWS_PUBLIC_NODE_CIDR: 10.0.0.0/20
AWS_PUBLIC_NODE_CIDR_1: ""
AWS_PUBLIC_NODE_CIDR_2: ""
AWS_PUBLIC_SUBNET_ID: ""
AWS_PUBLIC_SUBNET_ID_1: ""
AWS_PUBLIC_SUBNET_ID_2: ""
AWS_REGION: eu-west-1
AWS_SSH_KEY_NAME: tanzu-eu-west-1
AWS_VPC_CIDR: 10.0.0.0/16
AWS_VPC_ID: ""
BASTION_HOST_ENABLED: "true"
CLUSTER_CIDR: 100.96.0.0/11
CLUSTER_NAME: mgmt
CLUSTER_PLAN: dev
CONTROL_PLANE_MACHINE_TYPE: t2.large
ENABLE_AUDIT_LOGGING: ""
ENABLE_CEIP_PARTICIPATION: "false"
ENABLE_MHC: "true"
IDENTITY_MANAGEMENT_TYPE: none
INFRASTRUCTURE_PROVIDER: aws
LDAP_BIND_DN: ""
LDAP_BIND_PASSWORD: ""
LDAP_GROUP_SEARCH_BASE_DN: ""
LDAP_GROUP_SEARCH_FILTER: ""
LDAP_GROUP_SEARCH_GROUP_ATTRIBUTE: ""
LDAP_GROUP_SEARCH_NAME_ATTRIBUTE: cn
LDAP_GROUP_SEARCH_USER_ATTRIBUTE: DN
LDAP_HOST: ""
LDAP_ROOT_CA_DATA_B64: ""
LDAP_USER_SEARCH_BASE_DN: ""
LDAP_USER_SEARCH_FILTER: ""
LDAP_USER_SEARCH_NAME_ATTRIBUTE: ""
LDAP_USER_SEARCH_USERNAME: userPrincipalName
NODE_MACHINE_TYPE: t2.large
OIDC_IDENTITY_PROVIDER_CLIENT_ID: ""
OIDC_IDENTITY_PROVIDER_CLIENT_SECRET: ""
OIDC_IDENTITY_PROVIDER_GROUPS_CLAIM: ""
OIDC_IDENTITY_PROVIDER_ISSUER_URL: ""
OIDC_IDENTITY_PROVIDER_NAME: ""
OIDC_IDENTITY_PROVIDER_SCOPES: ""
OIDC_IDENTITY_PROVIDER_USERNAME_CLAIM: ""
OS_ARCH: amd64
OS_NAME: ubuntu
OS_VERSION: "20.04"
SERVICE_CIDR: 100.64.0.0/13
TKG_HTTP_PROXY_ENABLED: "false"
```

## Environment Details

* Build version (`tanzu version`):  version: v0.11.4, buildDate: 2022-05-17, sha: a9b8f3a
* Deployment (Managed/Unmanaged cluster): Managed
* Infrastructure Provider (Docker/AWS/Azure/vSphere): AWS
* Operating System (client): MacOS (Intel)

**Comment by iensu** [comment]
We also did try to create the management cluster from the configuration file directly.

**Comment by jdumars** [comment]
Hi, VMware Tanzu Community Edition is no longer an actively maintained project. Please see tanzucommunityedition.io for further information.
