### ISSUE TITLE
Matrix compatibility WSO2 <> Tanzu v7

### ISSUE THREAD

**Issue by Montana** [vmware-tanzu/community-edition#5390]
I am not able to find a Matrix compatibility between VMWare Tanzu and WSO2. Do you know where I can find a Matrix compatibility of Tanzu and WSO2 products?

Cheers,
Montana Mendy

**Comment by jdumars** [comment]
Hi, VMware Tanzu Community Edition is no longer an actively maintained project. Please see tanzucommunityedition.io for further information.
