### ISSUE TITLE
TCE 0.12.1 fails with tier1 not configured

### ISSUE THREAD

**Issue by rolfbartels** [vmware-tanzu/community-edition#5404]
Deploying : TCE 0.12.1 with intergration to 
AVI 22.1.1-9052, 
NSX-T  3.1.3.7.4.19762317, 
vShpere 7.0.3.00500, 
VCF 4.4.1

When deploying via the UI we get the error in AVI under evnets "tier1 not confgiured", we have to then edit the tce manager cluster yalm file and add the folloing line
AVI_NSXT_T1LR:
and set that to the segment of the VIP's netowk in AVI.

We are having the same error with TGKm 1.15-1.16

`Config tkg-system-ioavcf-tce-mgt--tkg-system-tkg-system-ioavcf-tce-mgt-control-plane create status is failure (performed by user admin)

config_create_details
path: /api/vsvip
user: admin
status: Failure
resource_type: VsVip
resource_name: tkg-system-ioavcf-tce-mgt--tkg-system-tkg-system-ioavcf-tce-mgt-control-plane
request_data: {"cloud_ref": "/api/cloud/cloud-1e09ebf7-81cb-4cc8-b7ba-e0bd4aa8d340", "east_west_placement": false, "markers": [{"key": "clustername", "values": ["tkg-system-ioavcf-tce-mgt"]}], "name": "tkg-system-ioavcf-tce-mgt--tkg-system-tkg-system-ioavcf-tce-mgt-control-plane", "tenant_ref": "/api/tenant/admin", "vip": [{"auto_allocate_ip": true, "ipam_network_subnet": {"subnet": {"ip_addr": {"addr": "10.74.217.0", "type": "V4"}, "mask": 24}}, "vip_id": "0"}], "vrf_context_ref": "/api/vrfcontext?name=global", "vsvip_cloud_config_cksum": "1764558892"}
error_message: "tier1_lr not configured"
resource_data
cloud_ref: /api/cloud/cloud-1e09ebf7-81cb-4cc8-b7ba-e0bd4aa8d340
east_west_placement: false
markers
0
key: clustername
values
0: tkg-system-ioavcf-tce-mgt
name: tkg-system-ioavcf-tce-mgt--tkg-system-tkg-system-ioavcf-tce-mgt-control-plane
tenant_ref: /api/tenant/admin
vip
0
auto_allocate_ip: true
ipam_network_subnet
subnet
ip_addr
addr: 10.74.217.0
type: V4
mask: 24
vip_id: 0
vrf_context_ref: /api/vrfcontext?name=global
vsvip_cloud_config_cksum: 1764558892`

**Comment by jdumars** [comment]
Hi, VMware Tanzu Community Edition is no longer an actively maintained project. Please see tanzucommunityedition.io for further information.
