### ISSUE TITLE
Install Management Cluster vSphere 8

### ISSUE THREAD

**Issue by NixGi** [vmware-tanzu/community-edition#5453]
Hello,
i am new to tanzu and wan´t to create a management cluster like it is described in the documentation. But i am getting the following error message on the ui screen.

ℹ [1014 11:27:01.45816]: init.go:169] Using infrastructure provider vsphere:v1.0.3
ℹ [1014 11:27:01.45833]: init.go:171] Generating cluster configuration...
ℹ [1014 11:27:01.45846]: utils.go:356] Using default value for CONTROL_PLANE_MACHINE_COUNT = 3. Reason: CONTROL_PLANE_MACHINE_COUNT variable is not set
ℹ [1014 11:27:01.45849]: utils.go:361] Using default value for WORKER_MACHINE_COUNT = 3. Reason: WORKER_MACHINE_COUNT variable is not set

On the linux management server, where i wan´t to deploy the cluster i saw the following:

Validating the pre-requisites...
Serving kickstart UI at http://10.0.7.53:8080
web socket connection established
sending pending 0 logs to UI
Identity Provider not configured. Some authentication features won't work.
Using default value for CONTROL_PLANE_MACHINE_COUNT = 3. Reason: CONTROL_PLANE_MACHINE_COUNT variable is not set
Using default value for WORKER_MACHINE_COUNT = 3. Reason: WORKER_MACHINE_COUNT variable is not set
Validating configuration...
web socket connection established
sending pending 0 logs to UI
Using infrastructure provider vsphere:v1.0.3
Generating cluster configuration...
Using default value for CONTROL_PLANE_MACHINE_COUNT = 3. Reason: CONTROL_PLANE_MACHINE_COUNT variable is not set
Using default value for WORKER_MACHINE_COUNT = 3. Reason: WORKER_MACHINE_COUNT variable is not set
panic: Lines are 1 based

goroutine 237 [running]:
github.com/k14s/ytt/pkg/filepos.NewPosition(...)
        /go/pkg/mod/github.com/k14s/ytt@v0.32.1-0.20210511155130-214258be2519/pkg/filepos/position.go:19
github.com/k14s/ytt/pkg/yamlmeta.(*Parser).newPosition(...)
        /go/pkg/mod/github.com/k14s/ytt@v0.32.1-0.20210511155130-214258be2519/pkg/yamlmeta/parser.go:279
github.com/k14s/ytt/pkg/yamlmeta.(*Parser).correctLineNumInErr(0xc0006dd028, {0x350b1e0, 0xc0015e1d70}, 0xffffffffffffffff)
        /go/pkg/mod/github.com/k14s/ytt@v0.32.1-0.20210511155130-214258be2519/pkg/yamlmeta/parser.go:268 +0x2ab
github.com/k14s/ytt/pkg/yamlmeta.(*Parser).ParseBytes(0xc0006dd028, {0xc001913788, 0x16, 0x18}, {0x0, 0x0})
        /go/pkg/mod/github.com/k14s/ytt@v0.32.1-0.20210511155130-214258be2519/pkg/yamlmeta/parser.go:61 +0x2fd
github.com/k14s/ytt/pkg/cmd/template.(*DataValuesFlags).parseYAML(0x0, {0xc000bd56c1, 0x2}, 0x27)
        /go/pkg/mod/github.com/k14s/ytt@v0.32.1-0.20210511155130-214258be2519/pkg/cmd/template/data_values_flags.go:182 +0x5d
github.com/k14s/ytt/pkg/cmd/template.(*DataValuesFlags).AsOverlays.func2({0xc000bd56c1, 0x27})
        /go/pkg/mod/github.com/k14s/ytt@v0.32.1-0.20210511155130-214258be2519/pkg/cmd/template/data_values_flags.go:61 +0x33
github.com/k14s/ytt/pkg/cmd/template.(*DataValuesFlags).kv(0xc000a72cf0, {0xc000bd56b0, 0x40cf54}, 0xc0006dd340)
        /go/pkg/mod/github.com/k14s/ytt@v0.32.1-0.20210511155130-214258be2519/pkg/cmd/template/data_values_flags.go:166 +0x8f
github.com/k14s/ytt/pkg/cmd/template.(*DataValuesFlags).AsOverlays(0xc000a72cf0, 0x5)
        /go/pkg/mod/github.com/k14s/ytt@v0.32.1-0.20210511155130-214258be2519/pkg/cmd/template/data_values_flags.go:83 +0x51b
github.com/vmware-tanzu/tanzu-framework/pkg/v1/tkg/yamlprocessor.(*YTTProcessor).Process(0x7f9acdaf2d08, {0xc000f3a000, 0x130, 0x200}, 0xc0013048e8)
        /tmp/tce-scratch-space/tanzu-framework/pkg/v1/tkg/yamlprocessor/ytt.go:188 +0x14d
sigs.k8s.io/cluster-api/cmd/clusterctl/client/repository.NewTemplate({{0xc000f3a000, 0x130, 0x200}, {0x353bfd0, 0xc000ceff30}, {0x7f9acda937d0, 0xc000c11b60}, {0x2fb322a, 0xa}, 0x0})
        /go/pkg/mod/sigs.k8s.io/cluster-api@v1.0.1/cmd/clusterctl/client/repository/template.go:113 +0x1da
sigs.k8s.io/cluster-api/cmd/clusterctl/client/repository.(*templateClient).Get(0xc000099770, {0xc00058b440, 0x6}, {0x2fb322a, 0x14}, 0x0)
        /go/pkg/mod/sigs.k8s.io/cluster-api@v1.0.1/cmd/clusterctl/client/repository/template_client.go:99 +0x718
sigs.k8s.io/cluster-api/cmd/clusterctl/client.(*clusterctlClient).getTemplateFromRepository(0xc000c10c00, {0x35a39a8, 0xc00116b8c0}, {{{0x0, 0x0}, {0x0, 0x0}}, 0xc000de5b60, 0x0, 0x0, ...})
        /go/pkg/mod/sigs.k8s.io/cluster-api@v1.0.1/cmd/clusterctl/client/config.go:330 +0x3a2
sigs.k8s.io/cluster-api/cmd/clusterctl/client.(*clusterctlClient).GetClusterTemplate(0xc000c10c00, {{{0x0, 0x0}, {0x0, 0x0}}, 0xc000de5b60, 0x0, 0x0, {0x2fb322a, 0xa}, ...})
        /go/pkg/mod/sigs.k8s.io/cluster-api@v1.0.1/cmd/clusterctl/client/config.go:253 +0x2b3
github.com/vmware-tanzu/tanzu-framework/pkg/v1/tkg/client.(*TkgClient).getClusterConfiguration(0xc001876f70, 0xc00158fb30, 0x60, {0xc000c6d2b0, 0xe}, 0x7d)
        /tmp/tce-scratch-space/tanzu-framework/pkg/v1/tkg/client/config.go:123 +0x215
github.com/vmware-tanzu/tanzu-framework/pkg/v1/tkg/client.(*TkgClient).BuildRegionalClusterConfiguration(0xc001876f70, 0xc0001201e0)
        /tmp/tce-scratch-space/tanzu-framework/pkg/v1/tkg/client/init.go:584 +0x27f
github.com/vmware-tanzu/tanzu-framework/pkg/v1/tkg/client.(*TkgClient).InitRegion(0xc001876f70, 0xc0001201e0)
        /tmp/tce-scratch-space/tanzu-framework/pkg/v1/tkg/client/init.go:174 +0x53b
github.com/vmware-tanzu/tanzu-framework/pkg/v1/tkg/web/server/handlers.(*App).CreateVSphereRegionalCluster.func1()
        /tmp/tce-scratch-space/tanzu-framework/pkg/v1/tkg/web/server/handlers/init.go:88 +0x27
created by github.com/vmware-tanzu/tanzu-framework/pkg/v1/tkg/web/server/handlers.(*App).CreateVSphereRegionalCluster
        /tmp/tce-scratch-space/tanzu-framework/pkg/v1/tkg/web/server/handlers/init.go:87 +0xc0f
Error: exit status 2

Am i doing something wrong? Any help will be apreciated.

Frank

**Comment by NixGi** [comment]
Same on Windows Client. What am i missing? Is there a possibility to set those variables by hand?
Thanks
Frank

**Comment by jdumars** [comment]
Hi, VMware Tanzu Community Edition is no longer an actively maintained project. Please see tanzucommunityedition.io for further information.
