### ISSUE TITLE
Are we going to have 1.9.x velero helm chart?

### ISSUE THREAD

**Issue by jhuisss** [vmware-tanzu/community-edition#5459]
https://github.com/vmware-tanzu/community-edition/tree/main/addons/packages/velero
The newest version is still 1.8.0, but velero 1.9.2 is ready, are we going to have it?

**Comment by jdumars** [comment]
Hi, VMware Tanzu Community Edition is no longer an actively maintained project. Please see tanzucommunityedition.io for further information.
