### ISSUE TITLE
Carvelizing Cluster Autoscaler image

### ISSUE THREAD

**Issue by abhijit-dev82** [vmware-tanzu/community-edition#5460]
## Feature Request
 Cluster Autoscaler needs to be carvelized. For every k8s release a corresponding cluster autoscaler image is released. 
https://github.com/kubernetes/autoscaler/tree/master/cluster-autoscaler#releases
Hence we will need carvelizing of the autoscaler image.

## Describe alternatives you've considered

None

**Comment by jdumars** [comment]
Hi, VMware Tanzu Community Edition is no longer an actively maintained project. Please see tanzucommunityedition.io for further information.
