### ISSUE TITLE
Containers don't restart after CAPD install

### ISSUE THREAD

**Issue by thesteve0** [vmware-tanzu/community-edition#832]
## Bug Report
After a local standalone install, if the computer is shutdown or restarted - the containers for the kube cluster don't come back up.

## Expected Behavior
By default the TCE containers in the standalone Kube cluster should start every time the docker engine starts. 
There should be a command or flag to turn off that default behavior

## Steps to Reproduce the Bug

Install TCE standalone, turn off the computer, start it again, wait for docker to boot. There will be no cluster

## Environment Details

* Build version (`tanzu version`):  
* Operating System (client):

**Comment by bradwinfield** [comment]
Just to note, I restarted the docker containers (TCE management cluster) in the order that leaves the IP addresses for each container the same as before docker shutdown. I had to create a dummy container to take the .2 address that kind used during the build. This solves the certificate issue but the cluster still does not respond to tanzu nor kubectl commands.

**Comment by randomvariable** [comment]
Yeah, I'm pretty certain this is the etcd issues. Given the work being done on local clusters, I'm not sure how important this is anymore from a TCE perspective.

**Comment by jpmcb** [comment]
Leaving this open regardless of the standalone cluster overhaul: we should investigate how this works for the new standalone cluster model, adjust our kind provider as needed, and gather community feedback

For reference, here is the new [standalone-cluster proposal](https://github.com/vmware-tanzu/community-edition/issues/2266) that uses a different model with a much liter weight methodology. Please look at the proposal, try it out, and give your feedback there!

**Comment by grtrout** [comment]
I take it this is still an issue? I spent the last hour trying to figure out why my newly-created TCE cluster seems to be completely broken after I restarted my laptop. I get the reasons why this happens (sort of), but I thought one of the primary motivations behind TCE was to provide an experience akin to kind or minikube for local environments?

**Comment by stmcginnis** [comment]
> I thought one of the primary motivations behind TCE was to provide an experience akin to kind or minikube for local environments?

Well, yes and no. With our `standalone-cluster` and `unmanaged-cluster` implementations, we are targeting the ability to deploy local clusters for development. But TCE as a whole, no.

@grtrout were you using the `standalone-cluster` command, or the new `unmanaged-cluster` command in the v0.10.0 release candidate?

There are issues with the way `standalone-cluster` works, so there is not a solution there. That command is being deprecated and replaced by `unamanged-cluster`s.

If you use the `unmanaged-cluster` command, this can work but there are a couple gotchas. When deploying the cluster you will need to specify calico for the cni. The version of antrea we use by default is not able to handle the restart. On restart, the containers usually get assigned new IP addresses that cause problems there.

So the command `tanzu unmanaged-cluster create --cni=calico foo` _should_ get a working cluster that (in most cases) should be able to survive a reboot. There may be some other conditions that cause problems with this, but so far in my experience it has been working fine.

**Comment by grtrout** [comment]
Hey @stmcginnis, thanks for the quick reply. I've used Tanzu/TKG at a previous job and since I want to continue keeping up with the Tanzu ecosystem at my new job, I thought using TCE in my local environment might be smart. I'm also thinking about using it in a homelab, but that's a different thing...

In any case, yes, I just followed along the "getting started" docs I created a standalone cluster. I had to hack a few things to get it working (e.g., toggling the _deprecatedCgroupv1_ value to true, restarting the process 3 or 4 times, etc.), but ultimately it was up and running and functional...until I restarted my laptop.

It looks like I should check out the unmanaged-cluster, but until now I was not aware of that. I would rather use Calico over Antrea anyway, so I'm good with that. I'll try this out later today. Thanks again!

**Comment by butch7903** [comment]
> > I thought one of the primary motivations behind TCE was to provide an experience akin to kind or minikube for local environments?
> 
> Well, yes and no. With our `standalone-cluster` and `unmanaged-cluster` implementations, we are targeting the ability to deploy local clusters for development. But TCE as a whole, no.
> 
> @grtrout were you using the `standalone-cluster` command, or the new `unmanaged-cluster` command in the v0.10.0 release candidate?
> 
> There are issues with the way `standalone-cluster` works, so there is not a solution there. That command is being deprecated and replaced by `unamanged-cluster`s.
> 
> If you use the `unmanaged-cluster` command, this can work but there are a couple gotchas. When deploying the cluster you will need to specify calico for the cni. The version of antrea we use by default is not able to handle the restart. On restart, the containers usually get assigned new IP addresses that cause problems there.
> 
> So the command `tanzu unmanaged-cluster create --cni=calico foo` _should_ get a working cluster that (in most cases) should be able to survive a reboot. There may be some other conditions that cause problems with this, but so far in my experience it has been working fine.

Looks like the `tanzu unmanaged-cluster create --cni=calico foo`  is the fix. My issue I am seeing now is that the kapp-controller is crashing every so often post reboot. Any ideas why that would be or how we could troubleshoot it further?

**Comment by stmcginnis** [comment]
@seemiller any tips on troubleshooting kapp-controller? Or someone we can pull in from the carvel project to take a look?

**Comment by joshrosso** [comment]
@butch7903 when you say it's crashing, can you help us understand:

* what symptoms are you observing? 
    * For example, are you seeing the pod go in `CrashLoopBackOff`? 
    * Does this only occur shortly after the cluster reboots. or is it something that occurs hours after the cluster has been running healthily?
    * If you `kubectl describe ...` the `kapp-controller` pod, are any crash *events* displayed?

**Comment by butch7903** [comment]
Yes, having CrashLoopBackOff. The crashes begin right after reboot and continue infinitely. So far at 210 restarts.
![image](https://user-images.githubusercontent.com/31591018/157254875-436926f3-01c8-4bf5-933c-dbae38cc2a1c.png)

**Comment by joshrosso** [comment]
Looks like the events are cut off, as I don't see the Error in here.

![image](https://user-images.githubusercontent.com/6200057/157259498-4312da6f-0710-4b8d-b894-b83215d19391.png)

* Can you copy and paste the output of the `describe` command?
* Can you copy and paste the output of `kubectl logs -n tkg-system $KAPP_CONTROLLER_POD_NAME -p`

Also, if you want to join us in Slack, we can probably help you troubleshoot there.

Thanks!

**Comment by thesteve0** [comment]
Since this is referring to standalone rather than unmanaged perhaps we should close this one.

**Comment by jpmcb** [comment]
> Since this is referring to standalone rather than unmanaged perhaps we should close this one.

Yes. `unmanaged-cluster` doesn't suffer from this original issue. If users are using `antrea` CNI at the time of this writing, they may still experience issues when restarting their clusters.

Reference https://github.com/vmware-tanzu/community-edition/issues/3564 for further details

**Comment by jorgemoralespou** [comment]
@jpmcb This issue is still relevant as it affects managed-clusters with CAPD. https://kubernetes.slack.com/archives/C02GY94A8KT/p1648732902925359

**Comment by joshrosso** [comment]
> @jpmcb This issue is still relevant as it affects managed-clusters with CAPD. https://kubernetes.slack.com/archives/C02GY94A8KT/p1648732902925359

Agreed. Reopening.

To be entirely transparent, I don’t foresee CAPD-based restart support being in our near-term future.

**Comment by jorgemoralespou** [comment]
Then I would make it more prominent at the top of the doc page and not at the very bottom https://tanzucommunityedition.io/docs/v0.11/docker-install-mgmt/

**Comment by RussellHamker** [comment]
It appears that this issue with a management cluster reboot is that when docker comes back up, the containers do not start in the same order or do not get the same IP addresses. 

My Build Process for a management cluster today in Docker:
`cat <<EOF > tce-mgmt.yaml
CLUSTER_CIDR: 100.96.0.0/11
CLUSTER_NAME: tce-mgmt
CLUSTER_PLAN: dev
ENABLE_MHC: "false"
IDENTITY_MANAGEMENT_TYPE: none
INFRASTRUCTURE_PROVIDER: docker
LDAP_BIND_DN: ""
LDAP_BIND_PASSWORD: ""
LDAP_GROUP_SEARCH_BASE_DN: ""
LDAP_GROUP_SEARCH_FILTER: ""
LDAP_GROUP_SEARCH_GROUP_ATTRIBUTE: ""
LDAP_GROUP_SEARCH_NAME_ATTRIBUTE: cn
LDAP_GROUP_SEARCH_USER_ATTRIBUTE: DN
LDAP_HOST: ""
LDAP_ROOT_CA_DATA_B64: ""
LDAP_USER_SEARCH_BASE_DN: ""
LDAP_USER_SEARCH_FILTER: ""
LDAP_USER_SEARCH_NAME_ATTRIBUTE: ""
LDAP_USER_SEARCH_USERNAME: userPrincipalName
OIDC_IDENTITY_PROVIDER_CLIENT_ID: ""
OIDC_IDENTITY_PROVIDER_CLIENT_SECRET: ""
OIDC_IDENTITY_PROVIDER_GROUPS_CLAIM: ""
OIDC_IDENTITY_PROVIDER_ISSUER_URL: ""
OIDC_IDENTITY_PROVIDER_NAME: ""
OIDC_IDENTITY_PROVIDER_SCOPES: ""
OIDC_IDENTITY_PROVIDER_USERNAME_CLAIM: ""
OS_ARCH: ""
OS_NAME: ""
OS_VERSION: ""
SERVICE_CIDR: 100.64.0.0/13
TKG_HTTP_PROXY_ENABLED: "false"
EOF

tanzu management-cluster create -f tce-mgmt.yaml --cni=calico

tanzu management-cluster kubeconfig get tce-mgmt --admin

docker network inspect kind

kubectl config use-context tce-mgmt-admin@tce-mgmt

kubectl get nodes

kubectl get po -A`

Prior to Reboot: 
![image](https://user-images.githubusercontent.com/102260516/161129338-4e35f3f5-0569-4469-aa9b-ec548329df9c.png)
Post Reboot:
![image](https://user-images.githubusercontent.com/102260516/161129450-e1a1f002-b184-4fc2-b695-4cc5fe27cf6d.png)

Is there a way we could force the tanzu mgmt docker containers to retain their IPs possibly? If so, this might be an easy fix.

**Comment by stmcginnis** [comment]
> the containers do not start in the same order or do not get the same IP addresses

If I remember right, this was the case when I looked closer and what I've heard from other upstream projects like `kind`. There really needs to be some sort of IPAM integration in docker that would allow for assigning persistent IP addresses to containers for multi-node clusters to reliable survive docker engine restarts. Without that, it's possible you can restart and get your full cluster back, but it's not very likely.

**Comment by RussellHamker** [comment]
Looks like they already have that...
https://www.cloudsavvyit.com/14508/how-to-assign-a-static-ip-to-a-docker-container/

**Comment by stmcginnis** [comment]
> Looks like they already have that...

Yeah, the capability exists to set an address. The missing piece is an IPAM to manage what to set.

**Comment by RussellHamker** [comment]
I dont think IPAM is needed, you just need to set the IPs and network during the build process somehow. Where is the tanzu management yaml file stored after cluster creation?

**Comment by opsline-jvarelas** [comment]
> 
Hi @RussellHamker 
I've been trying to execute your workaround without success, do you remember the exact order for all containers?, because i had a management and workloads clusters running .... but after the reboot are not working......


or

 is there another way to run tanzu mgm and workload clusters within a linux server?, because i found the Docker option only in the TCE version.... thanks in advance.
