### ISSUE TITLE
Error when no identity provider configured can be misleading

### ISSUE THREAD

**Issue by stmcginnis** [vmware-tanzu/community-edition#847]
## Feedback

Reported by @cormachogan in #846. When an identity provider is not configured, the deployment output emits a confusing failure message:

```
Failed to configure Pinniped configuration for workload cluster. 
Please refer to the documentation to check if you can configure pinniped on workload cluster manually
```

## Suggested Changes

Since this is a normal expected condition, the output should not state their was a failure. It should be aware that identity services have not been requested and silently ignore the pinniped configuration.

**Comment by kcoriordan** [comment]
This is the warning I see:
`Warning: Pinniped configuration not found. Skipping pinniped configuration in workload cluster. Please refer to the documentation to check if you can configure pinniped on workload cluster manually`

**Comment by stmcginnis** [comment]
That is an improvement. At least it states it is just a warning and not a failure. I do think it would be better to not output anything at all, but the main concern of this issue has been addressed. Any follow up should probably be done in `tanzu-framework` anyway, so closing this one.
