### ISSUE TITLE
Doc: Deploy in an internet restricted environment 

### ISSUE THREAD

**Issue by kcoriordan** [vmware-tanzu/community-edition#862]
Add documentation to the website that describes how to deploy in an internet restricted environment

his doc/process will need to be replicated in TCE docs once kapp-contoller is upped to 0.20
https://carvel.dev/kapp-controller/docs/latest/air-gapped-workflow/

**Comment by alexbarbato** [comment]
Can I propose we re-open this please?

It's actually not necessarily a duplicate as #460 talks about things that don't work well in an airgapped deployment, but doesn't preclude us from documenting how you could at the moment.

Please holler at me if I'm off!

**Comment by alexbarbato** [comment]
Do you know if anyone on the TCE core team would maybe want to pair on this? 

I'm happy to write the docs and do as much heavy lifting as possible!

**Comment by kcoriordan** [comment]
Hi @alexbarbato 
I can import the TKG content from link above and get a draft in a PR for review

**Comment by alexbarbato** [comment]
Thanks @kcoriordan - this actually just popped to the top of my personal backlog to take a look at.

Full disclosure I haven't actually tested the documentation for TKG and if it just works here. Maybe it's useful for me to give that a poke and then we can port the docs over? (Unless there is someone internal to the team that might have a desire to take this on?)
