### ISSUE TITLE
Introduce versioning of documentation site to TCE

### ISSUE THREAD

**Issue by carlisia** [vmware-tanzu/community-edition#882]
Some of what's involved for how Velero does it:
https://velero.io/docs/v1.6/release-instructions/#changelog-and-docs-pr
https://github.com/vmware-tanzu/velero/blob/main/Makefile#L351-L361
https://github.com/vmware-tanzu/velero/blob/main/hack/release-tools/gen-docs.sh#L48

**Comment by kcoriordan** [comment]
moved this to 0,11,0 as we are not introducing doc versioning for 010.0

**Comment by joshrosso** [comment]
@kcoriordan is investigating existing models for versioning.

If the project needs to figure this out, we'll switch ownership from Kay to engineering resources.

**Comment by kcoriordan** [comment]
1. In `config.yaml ` added v`0.10.0 `under `doc versions` and `release_versions` and changed `doc_latest` to `v0.10.0 `
