### ISSUE TITLE
Packages for trial/free editions of Tanzu SaaS products. 

### ISSUE THREAD

**Issue by thesteve0** [vmware-tanzu/community-edition#888]
## Feature Request
As a developer I would love if there were also packages for that would put trial/free editions of our SaaS products onto a cluster/namespace.  I know this is usually more of a configuration change, but some might require a daemonset or such. Even if it is just configuration, I would like to set it up by just giving the usersname and password (and URL if needed) to the SaaS Package and it wires it all up for me.

## Describe alternatives you've considered

The alternative is a user finding the documentation or product page, reading through the docs, and then applying YAML to their cluster. This seems more complicated and more prone to error. An application developer does not really care about the YAML and such, the whole point of the SaaS is it should be the least amount of work possible for them.

**Comment by qnetter** [comment]
We can pass it along but it is in no way in our control. That said, TMC Starter is in the works.

**Comment by qnetter** [comment]
@joshrosso has any work for the core team been identified on the road to TMC Starter?
