### ISSUE TITLE
The Getting Started guide could more explicitly help users make decisions

### ISSUE THREAD

**Issue by zjs** [vmware-tanzu/community-edition#912]
## Feedback

There are a few points in the Getting Started guide that require users to make a decision: do I want a managed cluster or a standalone cluster? do I want to use AWS, Docker, or vSphere?

Little guidance is provided to help users decide which path to go down.

## Suggested Changes

Explicitly address these decision points in the documentation. Help users understand the trade-offs they should be considering.

I think this is a bit of a balancing act, since you don't want the Getting Started guide to be overly complex, but I think it's also an opportunity to teach users a little bit about the project (e.g., that TCE supports a variety of infrastructure platforms) and guide them to the option you think is the safest starting point for most users.

## Environment Details

N/A

**Comment by dvonthenen** [comment]
I believe this is resolved with the new doc structure. If there is additional asks, please re-open and/or file a new issue.
